### ISSUE TITLE
viewer and sync issue

### ISSUE THREAD

**Issue by xlong88** [SublimeText/LaTeXTools#1003]
After upgrading to the latest version, the pdf viewer stopped working. My OS is Ubuntu 16.04, ST3 is the latest version. More precisely, evince did not open automatically after finishing compilation. However, from the console, I found the following information:

<class '_latextools_evince_viewer.EvinceViewer'>
Running "ps xv"
Running "sh /home/longgong/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_sync /usr/bin/python /usr/bin/subl /home/longgong/Dropbox/light-weight-switches/Serenade-draft/main.pdf"
Running "/usr/bin/python /home/longgong/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_forward_search /home/longgong/Dropbox/light-weight-switches/Serenade-draft/main.pdf 9 /home/longgong/Dropbox/light-weight-switches/Serenade-draft/sections/related_work.tex"
Running "/usr/bin/subl"

And when I enter the above commands in the terminal, it worked! So, how to fix it?

Thanks!
- Long

**Comment by ig0774** [comment]
If Evince isn't appearing at all, then the culprit is the `evince_sync` script.

You could try to run something like this from the console:

```
from LaTeXTools.latextools_utils.external_command import check_output
check_output(['sh', '/home/longgong/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_sync', '/usr/bin/python', '/usr/bin/subl', '/home/longgong/Dropbox/light-weight-switches/Serenade-draft/main.pdf'], cwd='/home/longgong/.config/sublime-text-3/Packages/LaTeXTools/evince', use_texpath=False)
```

If this launches Evince, you'll have to close it to see the output. If it doesn't launch Evince, it may provide some insight as to why.
