### ISSUE TITLE
build with basic builder is broken (bibtex log parser?)

### ISSUE THREAD

**Issue by renatyv** [SublimeText/LaTeXTools#1004]
Output in the ST console:
<class '_latextools_basicBuilder.BasicBuilder'>
2
Welcome to thread Thread-8
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'sshges']
Running "pdflatex -interaction=nonstopmode -synctex=1 sshges"
Finished normally
0
Running "bibtex sshges"
Traceback (most recent call last):
  File "/Users/renatyv/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 317, in run
    self.caller.builder.set_output(out.decode(self.caller.encoding,"ignore"))
AttributeError: 'NoneType' object has no attribute 'decode'
indexing [job 5]: no files were indexed out of the 6 queued, abandoning crawl

I get the following output if I run bibtex in the terminal:
[bibtex.txt](https://github.com/SublimeText/LaTeXTools/files/696226/bibtex.txt)

**Comment by ig0774** [comment]
Thanks for opening this issue. It's already been fixed in 28d87f8, which will be in the next release. If you want, you can grab [the latest version of basicBuilder.py](https://raw.githubusercontent.com/SublimeText/LaTeXTools/master/builders/basicBuilder.py) and overwrite your local version.

**Comment by r-stein** [comment]
Since the builders are core elements I have released a new version v3.12.14 to fix this.
