### ISSUE TITLE
Evince backwards search stopped working

### ISSUE THREAD

**Issue by darthoctopus** [SublimeText/LaTeXTools#1006]
This was working as recently as Christmas, not sure what happened exactly.

I'm on Fedora 25 using the latest version of latextools and sublime.

**Comment by r-stein** [comment]
Just do check to vocabulary: Backward search is clicking into evince and jumping to Sublime Text?

You have the python-dbus bindings installed?

**Comment by darthoctopus** [comment]
Yep

Issue went away with restart, not exactly sure what happened. Am now unable to reproduce.

**Comment by r-stein** [comment]
Sometimes after an update the import dependencies of the files are not reloaded, so you need to restart ST before everything works fine again. I will close this issue then =)
