### ISSUE TITLE
shift+enter does not producd new \item. LatexTools Version 3.12.15 with Sublime Text 3

### ISSUE THREAD

**Issue by shabermalz** [SublimeText/LaTeXTools#1009]

**Comment by r-stein** [comment]
Would you mind to elaborate?
- Does it work in any list environment?
- Is your Sublime Text version newer than v3119?

You could
- Open the ST console ``ctrl+` `` and type `sublime.log_commands(True)` to log the executed commands. Then press `shift+enter` inside a a list environment and look the the executed command.
- Install the [FindKeyConflicts](https://packagecontrol.io/packages/FindKeyConflicts) packages and search for conflicts of `shift+enter`

**Comment by shabermalz** [comment]
Doesn't work in either enum or item
it's version 3126

When I log the executed commands it shows me
command: insert {"characters": "\n"}

**Comment by r-stein** [comment]
You mean `enumerate` and `itemize`?

**Comment by shabermalz** [comment]
yes.

**Comment by r-stein** [comment]
Can you use [ScopeHunter](https://packagecontrol.io/packages/ScopeHunter) and copy the scope inside the `itemize` environment?

**Comment by shabermalz** [comment]
From within a itemize environment I get this with Scopehunter

Scope:                    text.tex.latex
                               meta.group.brace.latex
                               meta.environment.math.block.be.latex

**Comment by r-stein** [comment]
This issue is similar to https://github.com/sublimehq/Packages/issues/685. You most likely have a definition, which uses `$` above in the file and the math mode is not terminated.

I don't know a good solution for this, but you could put those definitions into a different file and `\input` that file to avoid the highlighting problems.

**Comment by shabermalz** [comment]
Yep, that was it. I had the following

\newcommand {\be} {\begin{equation}}
 \newcommand {\ee} {\end{equation}}
 \newcommand {\bea} {\begin{eqnarray}}
 \newcommand {\eea} {\end{eqnarray}}
\newcommand {\beas} {\begin{eqnarray*}}
 \newcommand {\eeas} {\end{eqnarray*}}
 \newcommand{\bi}{\begin{itemize}}
 \newcommand{\ei}{\end{itemize}}

For some reason this always worked. When I eliminate it (I stopped using it
long ago) erverything works again. Now the scope under the cursor inside
the itemize environment comes out correctly as:

text.tex.latex
                               meta.environment.frame.latex
                               meta.environment.list.itemize.latex

Thank you very much for the quick help and greet Marciano from me.

Steffen Habermalz

**Comment by r-stein** [comment]
That's in fact a bug in the syntax definition regarding the white spaces.
If you change this to 
``` tex
\newcommand{\be}{\begin{equation}} 
\newcommand{\ee}{\end{equation}} 
\newcommand{\bea}{\begin{eqnarray}} 
\newcommand{\eea}{\end{eqnarray}} 
\newcommand{\beas}{\begin{eqnarray*}} 
\newcommand{\eeas}{\end{eqnarray*}} 
\newcommand{\bi}{\begin{itemize}} 
\newcommand{\ei}{\end{itemize}}
```

it should work.

**Comment by shabermalz** [comment]
That's funny. It does work with itemize but not with enumerate (even if I
delete the code)

**Comment by r-stein** [comment]
What is the scope inside enumerate and description?

**Comment by shabermalz** [comment]
It works in the description environment and has the right scope in the
enumerate environment.

Scope:                         text.tex.latex
                               meta.environment.list.enumerate.latex

However, there is no LatexTools keybinding for the enumerate environment I
noticed. Just for itemize and description. I changed the LatexTools
keybinding to  (removed the itemize.latex at the end)

{ "keys": ["shift+enter"], "command": "insert_snippet", "args":
{"contents": "\n\\item $0"}, "context":
        [
            {"key": "selector", "operator": "equal", "operand":
"meta.environment.list"},
            { "key": "selection_empty", "operator": "equal", "operand":
true, "match_all": true }
        ]
    },

after finding this.

http://stackoverflow.com/questions/39678835/sublime-latexing-cant-disable-tabularnewline-key-binding-since-latest-update

 Works fine now.

**Comment by r-stein** [comment]
The keybinding is [here](https://github.com/SublimeText/LaTeXTools/blob/v3.12.15/Default%20(Windows).sublime-keymap#L422) so I don't know why it is not working at your machine. However fine, that you have solved the problem.

**Comment by shabermalz** [comment]
It's weird. My keybindings look different. Maybe I should just reinstall
LatexTools.... Thanks for your help
