### ISSUE TITLE
Incorrect dates given in Package Control Messages?

### ISSUE THREAD

**Issue by ChipmunkMath** [SublimeText/LaTeXTools#1010]
Not sure if this is really the right place to point this out, but it looks like the updates being pushed through Package Control are having the wrong dates attached to them. For example, I saw this on opening ST today: "LaTeXTools Plugin version 3.12.15 (2016-01-14) changelog" although the ReadMe says "v3.12.15 (2017-01-14)".

Here's an image of what I'm seeing in the Package Control Messages. Can provide more info if needed.
<img width="926" alt="baddates" src="https://cloud.githubusercontent.com/assets/12464874/22123493/a6350cca-de40-11e6-9f4a-1adf56e88c9e.png">

I'm guessing that this is being manually entered and the person doing that just forgot it was a new year. Minor thing, but figured it should be ironed out.

**Comment by r-stein** [comment]
Thanks I will update that.
