### ISSUE TITLE
LaTeXTools: Delete temporary files misses .xdv files

### ISSUE THREAD

**Issue by flipphillips** [SublimeText/LaTeXTools#1012]
I recently updated both my TeXLive and Sublime LaTeXTools. I use `xelatex` a lot. I *thought* in the past the temporary `xdv` files either weren't created in the same folder or at least Delete temporary files would get rid of them.

Now, for whatever reason, most up-to-date TeXLive/`latexmk`, Sublime, etc, they remain after a cmd-L backspace.

**Comment by ig0774** [comment]
This can be fixed by adding `".xdv"` to the list of extensions in the `"temp_files_exts"` setting. Make sure you do this in your "User" settings file (**Preferences** > **Package Settings** > **LaTeXTools** > **Settings – User**), so that the change persists across updates.

**Comment by flipphillips** [comment]
Ah! Excellent- thanks. I wonder if I had done this in the past and just recently re-configured something. Regardless- thank you.


On Jan 19, 2017, at 10:52 PM, ig0774 <notifications@github.com<mailto:notifications@github.com>> wrote:


This can be fixed by adding ".xdv" to the list of extensions in the "temp_files_exts" setting. Make sure you do this in your "User" settings file (Preferences > Package Settings > LaTeXTools > Settings – User), so that the change persists across updates.
