### ISSUE TITLE
Can't find math preview settings

### ISSUE THREAD

**Issue by RaAdAT** [SublimeText/LaTeXTools#1014]
I have installed LatexTools and I know that "Math Preview Settings" should be right after "General Settings" on "Settings - User" file, but it doesn't shows up on mine.

Anyways, the math preview works, but I need to change size settings.

Any clues?

For the record:

Packages for equation preview  Status
-----------------------------  ------
standalone                     available
preview                        available
xcolor                         available
amsmath                        available
amssymb                        available
latexsym                       available
mathtools                      available

**Comment by r-stein** [comment]
You can either reset the user settings or open the default settings and copy the corresponding entries.
