### ISSUE TITLE
ST 3 with latextools could not complie tex file 

### ISSUE THREAD

**Issue by L0S0Dragon** [SublimeText/LaTeXTools#1018]
At first, I setup the latex environment successfully and could complie the tex file. However, the tex file could not be complied through the ST 3 someday. I installed the MIKTEX on my computer. 
This is the output  in the latextools thingy:
`

> [Compiling D:\quantum_information_and_quantum_computation\note\notes.tex]
> 
> TraditionalBuilder: Engine: pdflatex. Invoking texify... 
> 
>  COULD NOT COMPILE!
> 
> Attempted command:texify -b -p --engine=pdftex --tex-option="--synctex=1" notes.tex
> Build engine: Traditional Builder`

This is the output the sublime console
`

> Welcome to thread Thread-6
> ['texify', '-b', '-p', '--engine=pdftex', '--tex-option="--synctex=1"', 'notes.tex']
> Running "texify -b -p --engine=pdftex '--tex-option="--synctex=1"' notes.tex"
> Traceback (most recent call last):
>   File "./python3.3/subprocess.py", line 1104, in _execute_child
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\suyunlong\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\makePDF.py", line 295, in run
>     cwd=self.caller.tex_dir
>   File "C:\Users\suyunlong\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 221, in external_command
>     cwd=cwd
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1110, in _execute_child
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> Unable to open clipboard
> Package Control: No updated packages

`

**Comment by r-stein** [comment]
Are you able to compile other documents?

**Comment by L0S0Dragon** [comment]
I haven't try. I just installed sublime text for compiling tex

**Comment by ig0774** [comment]
You need to install a TeX distribution such as [MiKTeX](https://miktex.org) as well as LaTeXTools. LaTeXTools can't compile documents on its own.

**Comment by L0S0Dragon** [comment]
I do install the miktex and i could compile tex file at first

**Comment by ig0774** [comment]
Is MiKTeX added to your system PATH? You can check the PATH LaTeXTools uses by running the **LaTeXTools: Check System** command from the command palette.

**Comment by L0S0Dragon** [comment]
@ig0774 ：After adding it to the PATH, i could compile the tex again. Thanks you a lot！But why does it work well at first and i didn't add the miktex to the PATH

**Comment by ig0774** [comment]
The MiKTeX installer normally add MiKTeX to the PATH. Maybe it was there before but somehow got eliminated?

**Comment by r-stein** [comment]
Maybe you had Sublime Text open while it was added to the path and you needed to restart it.

**Comment by L0S0Dragon** [comment]
@ig0774 That really makes senses @r-stein @ig0774 Thanks for your help！(^_^)
