### ISSUE TITLE
Does LaTeXTools support for automatically installing missing packages?

### ISSUE THREAD

**Issue by xlong88** [SublimeText/LaTeXTools#1021]
Does (or will) LaTeXTools support for automatically installing missing packages, like winedit?

**Comment by r-stein** [comment]
This depends on the tex distribution. Are you using Miktex or texlive?

**Comment by xlong88** [comment]
I use both of them, Miktex on Windows machine and texlive on Mac and Linux machine. Do you 
have any solution?

**Comment by ig0774** [comment]
MiKTeX [has a built-in feature](https://docs.miktex.org/manual/autoinstall.html) to install packages in the fly. On TeXLive, you could use [this script](http://www.ctan.org/tex-archive/support/texliveonfly), which should at least work on Linux and could probably be adapted for Mac. LaTeXTools could easily be configured to run that script by changing the `command` builder setting to something like `["texliveonfly.py", "--engine=%E"]` (untested).

I don't see this as a feature we'd necessarily want to add to LaTeXTools.

**Comment by xlong88** [comment]
Thanks!
