### ISSUE TITLE
Automatically build when document is saved?

### ISSUE THREAD

**Issue by iliyang** [SublimeText/LaTeXTools#1022]
I'm moving to LaTeXTools from LaTeXing, and the one feature I miss is the ability to automatically invoke a build in the background when the document is saved. I know that pressing Ctrl+b (to save the file and invoke the build) is almost as simple as Ctrl+s (to save the file only), but is there an option in LaTeXTools to invoke the build upon save?

**Comment by r-stein** [comment]
Do you want to build with ctrl+s or want to auto trigger the build also on autosave?

**Comment by iliyang** [comment]
I want the latter – trigger the build on save.

**Comment by r-stein** [comment]
That's currently not supported. You could try a package like [SublimeOnSaveBuild](https://packagecontrol.io/packages/SublimeOnSaveBuild).

**Comment by iliyang** [comment]
Thanks, I'll have a look and report here!

**Comment by iliyang** [comment]
Just tried [SublimeOnSaveBuild](https://packagecontrol.io/packages/SublimeOnSaveBuild), works like a charm! Just had to add `tex` to the file extensions for which to trigger the build.

Thanks again for the suggestion, @r-stein! Issue can be closed now.
