### ISSUE TITLE
Changing size of math preview

### ISSUE THREAD

**Issue by nadnaps** [SublimeText/LaTeXTools#1026]
How do you change the size of the preview of the math equation. Right now its too big and can barely fit more than 3 characters on screen

**Comment by nadnaps** [comment]
Solve by changing preview_math_density to a lower value

**Comment by r-stein** [comment]
Duplicate of #999

**Comment by r-stein** [comment]
I have released a new version to fix this. Just remove `preview_math_scale_quotient` after the update.
