### ISSUE TITLE
User settings file override all other settings even "TEX root"

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#1032]
I had a Project settings file that the master was set to ``master.tex`` in the main folder. Then all the separate chapters were in sub-folders. Now, I need to have a separate folder inside that in which it compiles separately and doesn't compile master.tex when you run the build command.

I tried excluding the folder from the project but this will still compile ``master.tex``. Then, in find all files it won't come up. Ideally, I would want it to come up in find all files but have a way to compile it separately and not compile ``master.tex``.

I know I can add TEX root individually into each file and then remove the master from the project settings file. I was wondering if there is any other way around this. I tried setting ``!TEX root`` of the file I want to compile separately as the name of that file but seems the project setting must override the ``!TEX root`` setting.

**Comment by r-stein** [comment]
The TEX directive has the precedence, *except* if it is the same file. You can open the ST console ``ctrl+` `` and write `view.settings().set('TEXroot', None)` to temporary overwrite the project settings.
I am not sure which is be the best way to solve this.

**Comment by excetara2** [comment]
That's good enough for me as this is the only time I've needed this. I guess you just have to set the TEXroot in every file if you need this feature instead of in the project settings. 

What is the reason for not letting the TEX directive have precedence when it is the same file? Is there some feature that uses that?

I tried naming another file ``input.tex`` and just have ``\input{compileseperately.tex}`` in the ``input.tex`` file but that didn't seem to work. Then setting ``input.tex`` as the TEX root.

**Comment by r-stein** [comment]
> What is the reason for not letting the TEX directive have precedence when it is the same file? Is there some feature that uses that?

There is no particular reason it is just an implementation detail, which we may classify as bug and change.

> I tried naming another file ``input.tex`` and just have ``\input{compileseperately.tex}`` in the ``input.tex`` file but that didn't seem to work. Then setting ``input.tex`` as the TEX root. 

This works for me. I don't know why it does not work for you.

**Comment by excetara2** [comment]
Maybe I needed to restart as was trying a bunch of different things. Anyways, I'll just use the ``view.settings`` command for now.

I don't see why you wouldn't change it because if it was the same file why would you set the TEXroot directive? Maybe I'm not seeing something but either way thanks for the help.

**Comment by ig0774** [comment]
> … it is just an implementation detail, which we may classify as bug and change.

I'm inclined to do just that. Tbh, prior to this issue it seemed as though this were an either / or thing, i.e.,  people using the project setting were doing so to *not* use the `%!TEX root` stuff.

**Comment by excetara2** [comment]
Okay sounds good 👍
