### ISSUE TITLE
Command Setting

### ISSUE THREAD

**Issue by P-Chao** [SublimeText/LaTeXTools#1034]
When I compile(press *Ctrl+B*), the sublime will post a messagebox
**you must set a command in your latextools.sublime-settings file before launching the script builder!**
What can I do?

**Comment by r-stein** [comment]
Have you setup to use the command builder? Otherwise press ctrl+shift+b und select LaTeX.

**Comment by P-Chao** [comment]
I have solve the problem.
the error happens when I choose the **Script Builder**, now, I choose **Traditional Builder,
Thank you very much
