### ISSUE TITLE
How to make a scope for graying out in-line comments?

### ISSUE THREAD

**Issue by sethblumberg** [SublimeText/LaTeXTools#1035]
LaTeX doesn't have a native way to do in-line commenting (just `%` and the `comment` environment), but it's not hard to create your own, with a command that will ignore its argument.  [For instance](http://tex.stackexchange.com/a/276698/30594):

    \newcommand{\cmmnt}[1]{\ignorespaces}

I would like the argument of `\cmmnt` to be shown in gray (like the line following a `%` and the lines inside a `comment` environment are) just as the argument of `\section` is shown in bright pink (at least with the [Monokai Extended](https://packagecontrol.io/packages/Monokai%20Extended) package).

To do this, I believe I just need to tell Sublime that the inside of `\cmmnt{…}` is a scope that should be treated like a comment.  Ideally I would find code for an existing scope (or syntax?) within the LaTeXTools package files, and modify that with a new regex.  But I can't find any.  What should I do instead?

With the Sublime action *Show Scope Name* (`shift+ctrl+P`) I can see the scope of existing text.  These two scopes are the ones I searched for in the LaTeXTools files:

* A commented-out line, following a `%`:
    - text.tex.latex
    - comment.line.percentage.tex
* A commented-out section, in between `\begin{comment}` and  `\end{comment}`:
    - text.tex.latex
    - meta.environment.comment.latex
    - comment.block.environment.comment.latex

Where does LaTeXTools keep its definitions of different scopes?  And how can I add a new one?

**Comment by r-stein** [comment]
This is defined in the LaTeX syntax file, which ships with Sublime Text. You can edit it with [PackageResourceViewer][]. The default comment package can be found [here](https://github.com/sublimehq/Packages/blob/v3126/LaTeX/LaTeX.sublime-syntax#L1596).
You can add something like (did not test it):

``` yaml
    - match: '^(\\)cmmnt\s*\{([^\})*\}'
      captures:
        0: comment.command.cmmnt.latex
        1: punctuation.definition.backslash.latex
```

[PackageResourceViewer]: https://github.com/skuroda/PackageResourceViewer
