### ISSUE TITLE
Why `convert.exe' is unavailable?

### ISSUE THREAD

**Issue by ssqqqqqqq** [SublimeText/LaTeXTools#1038]
When checking system, I'm told that `convert.exe' is missing and unavailable. How could this happen?
![9259a5cc7cd98d10bac8ccbd283fb80e7aec90a7](https://cloud.githubusercontent.com/assets/26253417/23693013/0b70170a-040d-11e7-9d3e-c62ce1498203.jpg)

**Comment by ig0774** [comment]
Briefly: that `convert.exe` is the wrong `convert.exe`. Very wrong. The `convert.exe` we're looking for is [the one associated with ImageMagick](https://imagemagick.org/script/convert.php). The `convert.exe` in C:\WINDOWS\System32 is a utility for converting disks to FAT32 format. It's reported as `missing` because when we try to run the version check, the utility returns an error.

Thanks for pointing this out, however. We probably need to add a check to ensure *that* `convert.exe` is never executed, since it could have destructive consequences.

**Comment by r-stein** [comment]
Also convert is not really necessary for the features anymore. We used it to convert pdfs to preview thumbnails to preview included graphics and equations. However we directly use ghostscript (which ships with LaTeX) now.
So as far a I know it is only used to preview svg images. So just ignore, that it is missing. We may inform the user better for what the programs are necessary, but giving good feedback is not that easy.

**Comment by ssqqqqqqq** [comment]
Thanks very much! @ig0774 @r-stein

**Comment by ig0774** [comment]
Fixed in v3.13.0

**Comment by eric-wieser** [comment]
I'm still seeing this behaviour in v3.14.0:

```
Program      Location                                                    Status            Version
-------      --------                                                    ------            -------
sublime      C:\Program Files\Sublime Text 3\sublime_text.exe            available         Sublime Text Build 3126
texify       C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\texify.exe     available         MiKTeX Compiler Driver 2.9.5700 (MiKTeX 2.9)
pdflatex     C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\pdflatex.exe   available         MiKTeX-pdfTeX 2.9.5700 (1.40.16) (MiKTeX 2.9)
xelatex      C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\xelatex.exe    available         MiKTeX-XeTeX 2.9.5700 (0.99992) (MiKTeX 2.9)
lualatex     C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\lualatex.exe   available         This is LuaTeX, Version beta-0.80.0 (MiKTeX 2.9) (rev 5238)
biber        C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\biber.exe      available         biber version: 2.1
bibtex       C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\bibtex.exe     available         MiKTeX-BibTeX 2.9.5700 (0.99d) (MiKTeX 2.9)
bibtex8      C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\bibtex8.exe    available         This is 8-bit Big BibTeX version 0.99d
kpsewhich    C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\kpsewhich.exe  available         MiKTeX 2.9
convert      C:\Windows\system32\convert.exe                             restart required  Invalid drive specification.
ghostscript  C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\mgs.exe        available         9.05   
```

**Comment by hijeffery** [comment]
@eric-wieser  install imagemagick, recheck ''latextools -> check system'', restart sublime, and you are done.

**Comment by med95** [comment]
install imagemagick and Ghostscript， then add the gs path(some likes "c:\program files\gs\gs9.09\bin") to your environment path. It works. Maybe don't need the imagemagick.
