### ISSUE TITLE
Possibility to comment out multiple lines at once

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [SublimeText/LaTeXTools#1046]
Is there a way to comment out a block of text/more than one line at once, i.e. add `%` to the first column of each line selected?

TeXnicCenter for instance has this feature via `ctrl+q`, Kile with `ctrl+d`.

**Comment by r-stein** [comment]
Yes, just press `ctrl+/` you can also map it to an other keybinding. This works in Sublime Text for any language.

**Comment by AlfonsoMuskedunder** [comment]
Thanks, stupid me. I should have figured out what the German version of `ctrl+/` is before asking here. (I now know it's `ctrl+#`.)

**Comment by jamesnotjim** [comment]
Noting for OS X/macOS it's command+/

**Comment by dtieber** [comment]
It's `CMD` + `/` on OS X
