### ISSUE TITLE
Line spacing/padding

### ISSUE THREAD

**Issue by ppau1** [SublimeText/LaTeXTools#1049]
Is there a way to increase line spacing in the editor?
For other Sublime files, I can increase it by adding the following lines to the General Settings:
```json
	"line_padding_bottom": 1,
	"line_padding_top": 1,
```

**Comment by r-stein** [comment]
This works for me. You can try to open the syntax specific settings and add it there.

**Comment by ppau1** [comment]
Great! That solved the issue.
