### ISSUE TITLE
Add .ltx extension

### ISSUE THREAD

**Issue by ghost** [SublimeText/LaTeXTools#105]
Currently `LaTeXTools` didn't support the building of files with other that `.tex` extension:

    cv.ltx is not a TeX source file: cannot compile.

Anyway, the `.ltx` is a correct and widely used extension for LaTeX documents (`.tex` used mostly for plain TeX).

**Comment by ig0774** [comment]
In case anyone else stumbles on this, we have a setting, `tex_file_exts`, which can be use to make LaTeXTools recognise `.ltx` files.
