### ISSUE TITLE
Feature Request: Allow fill all quick panel to use user-entered text

### ISSUE THREAD

**Issue by diego898** [SublimeText/LaTeXTools#1051]
When I type `\include` and then `{` a helpful popup appears listing all the files in the directory. However, I sometimes want to include a file I **haven't** created yet - In this case, the popup will be empty.

I think a good default behavior, is to allow repeated enter pressing to exit the popup, and place the text you've typed in the include brackets. Currently, I'm just stuck until I press escape, loose the text I've typed, and have to retype it.

Note: This exact same thing also happens to me with `\cite{`.

**Comment by ig0774** [comment]
The behaviour you describe is desirable, but, unfortunately, impossible without changes to the Sublime API. Basically, plugins have no way of accessing the text entered into the quickpanel. The best I can suggest is to use the toggle (`C-l`, `t`, `?`) to temporarily disable the fill-all completions.

**Comment by diego898** [comment]
Thanks @ig0774 - I've made [the following post](https://forum.sublimetext.com/t/feature-request-plugins-access-quickpanel-text/26804) on sublime's forums asking for sublime to make this available.

**Comment by diego898** [comment]
User kingkeith over on the sublime forums said it is possible, just not as easy as it should be. He provided the following code:

```
import sublime
import sublime_plugin


def get_view_content(view_id):
    view = sublime.View(view_id)
    return view.substr(sublime.Region(0, view.size()))

quick_panel_view_id = 0
capture_quick_panel = False
last_known_quick_panel_text = ''

class ExampleQuickPanelCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        global capture_quick_panel
        capture_quick_panel = True
        show_text = lambda index: sublime.message_dialog(get_view_content(quick_panel_view_id) or last_known_quick_panel_text)
        self.view.window().show_quick_panel(['item1', 'item2'], show_text)

class ExampleQuickPanelListener(sublime_plugin.EventListener):
    def on_activated(self, view):
        global capture_quick_panel
        global quick_panel_view_id
        if capture_quick_panel:
            quick_panel_view_id = view.id()
            capture_quick_panel = False
    def on_deactivated(self, view):
        if view.id() == quick_panel_view_id:
            global last_known_quick_panel_text
            last_known_quick_panel_text = get_view_content(quick_panel_view_id)
```

and gif:

![](https://forum.sublimetext.com/uploads/default/optimized/3X/0/1/010248ece8aacb1b749a3b7b10558040f0f60b09_1_473x500.gif)

**Comment by ig0774** [comment]
Notes on this: In addition to storing text, we need to add a `on_query_context` handler so we can, e.g., bind `Enter` when the quick panel is visible to enter the text (that way `Esc` can still be used to cancel, ideally).

**Comment by r-stein** [comment]
I have played around with this and it seems that `enter` is the only key we can't remap in an overlay. Hence it will be something like `tab`/`ctrl+m` to insert the text as it is in the overlay and `enter` to insert the selected entry.

**Comment by ig0774** [comment]
I'm guessing the same thing applies to `esc`?

**Comment by r-stein** [comment]
Yes

**Comment by r-stein** [comment]
I have added this to the prerelease `st3-4.0.0-alpha.1`. You can press `tab` to insert the text, `enter` to select the entry, and `escape` to hide the overlay. This is not optimal, but the best I could do.
