### ISSUE TITLE
No module named multiprocessing

### ISSUE THREAD

**Issue by jyuu** [SublimeText/LaTeXTools#1054]
Just updated to 3.13.1 today and haven't been able to compile any .tex file: 

Traceback (most recent call last):
  File "./01_reload_submodules.py", line 101, in <module>
    __import__(mod)
  File "./latextools_utils/__init__.py", line 17, in <module>
    from .settings import get_setting
  File "./latextools_utils/settings.py", line 10, in <module>
    from latextools_utils.utils import run_on_main_thread
  File "./latextools_utils/utils.py", line 11, in <module>
    from multiprocessing import cpu_count
  File ".\multiprocessing\__init__.py", line 83, in <module>
ImportError: No module named _multiprocessing

**Comment by r-stein** [comment]
You are on Sublime Text 2?

**Comment by jyuu** [comment]
Yeah on sublime text 2

**Comment by jyuu** [comment]
Works on sublime 3 though! Thanks

**Comment by r-stein** [comment]
I made a quickfix to at least let in run on ST2. Could you please have a look at it @ig0774

**Comment by ig0774** [comment]
Technically, the number of CPU cores isn't that important. However, it's relatively easily done in Python, as [the default implementation shows](https://github.com/python/cpython/blob/2.6/Lib/multiprocessing/__init__.py#L108), which could remove the dependency on `multiprocessing` which is broken on ST2 on Windows and Linux. Probably should roll this into a future release, but for now, the quickfix is fine.
