### ISSUE TITLE
Bug: error message when opening and saving .tex documents

### ISSUE THREAD

**Issue by Kiluvp** [SublimeText/LaTeXTools#1057]
Since the latest update, I always get the following error message whenever I open or save a .tex document:

An error occurred while trying to run kpsewhich. Files in your TEXINPUTS could not be accessed.

The same message never occurred for the same documents before and does not appear to occur with documents of other types.

**Comment by r-stein** [comment]
Apparently LaTeXTools cannot some files and is way to verbose with its error messages. Try to disable all settings all cache settings [here](https://github.com/SublimeText/LaTeXTools/blob/v3.13.2/LaTeXTools.sublime-settings#L595). I am going to release a fix for that.

**Comment by r-stein** [comment]
Should be better in `v3.13.3`
