### ISSUE TITLE
LaTexTools not detecting texlive binaries in path (ubuntu)

### ISSUE THREAD

**Issue by z3ppj1g5aw** [SublimeText/LaTeXTools#1064]
Hi, 
I'm running Ubuntu 16.04 and I installed texlive using the install-tl script from the texlive website. All my tex binaries are in '/usr/local/texlive/2016/bin/x86-64' and that folder is also in the $PATH variable.

I've edited the User LaTeXTools.sublime-settings file to add the folder to the path. 

Now, when I try LatexTools -> Check System, I can see the folder displayed in the path but all the binaries are shown missing/unavailable.

How do I fix this?

Thanks

**Comment by ig0774** [comment]
Can you paste the **Check System** output here?

**Comment by z3ppj1g5aw** [comment]
I just fixed the problem myself. I had to create symlinks in system directories and now it detects all the binaries.
