### ISSUE TITLE
Feature Request:after compilation the skim pdf window should jump to the front automatically

### ISSUE THREAD

**Issue by SteinsWesley** [SublimeText/LaTeXTools#1066]
On OS X El Capitan, after compilation in sublime, the skim pdf viewer just only show in the Dock, not jump to the front.
I think setting the pdf viewer jumping to the front will make the process more convenient

**Comment by ig0774** [comment]
Are you looking for something other than what happens if you set `keep_focus` to `false`?

**Comment by SteinsWesley** [comment]
Thank you very much!  If I used the keyword 'popup', maybe I could have gotten the answer, blame my poor english @ig0774

**Comment by r-stein** [comment]
Is the issue solved by the answer?

**Comment by SteinsWesley** [comment]
Yes @r-stein
