### ISSUE TITLE
update will roll back LaTeX.sublime-build 

### ISSUE THREAD

**Issue by bluebaycal** [SublimeText/LaTeXTools#1067]
Issue 1: I put %!TEX program = xelatex at the beginning of tex file to force it is compiled by xelatex, however, it does not work. It always compile tex by calling TraditionalBuilder.   
p.s. This approach worked previously. After upgrading, does not work any more. 
  
Issue 2: To solve Issue 1, I manually modify the configure file LaTex.sublime-build. However, the updates of LatexPlugin will roll back my modification to the default status. 

Anybody could be of help? Thanks!

Version 3.14159265 (TeX Live 2016)
Mac OS
The LatexTools is up to date.

**Comment by r-stein** [comment]
Do you
- have that line on top of your root document?
- have choosen traditional builder in your LaTeXTool settings?
- use the top `LaTeX` option to build? (C-shift-b)

**Comment by bluebaycal** [comment]
I found I put a comment before %!TEX program = xelatex. After removing it, problem solved!
Thanks, dude:-)
