### ISSUE TITLE
%!TEX program option being ignored

### ISSUE THREAD

**Issue by python152** [SublimeText/LaTeXTools#1068]
This is on Mac, ST3, latest LatexTools.

It appears "%!TEX program = pdflatex" at the beginning of main.tex is being ignored - the only way I can set the build engine to effect through "Build with ..." menu.

Am I misconfiguring it?

**Comment by r-stein** [comment]
Which builder are you using?

**Comment by python152** [comment]
I didn't fiddle with any settings changes, the "check system" show that I am using "traditional" builder.

Builder      Status
-------      ------
traditional  available

Builder Setting  Value
---------------  -----
display_log      False
linux            {}   
osx              {}   
windows          {}

**Comment by r-stein** [comment]
Aside `pdflatex` is the default engine, which is used if you don't set an engine. Which engine is it using then?

**Comment by ig0774** [comment]
From the **Build with...** menu, make sure you are selecting the **LaTeX** option.

I'm starting to regret adding the variant builds....

**Comment by python152** [comment]
@r-stein From Tools/Build System, this is set to "Latex". 
I frequently juggle in between "pdflatex" and "lualatex" for different paper/projects. What I am hoping to achieve is by using "!TEX program = " macro to set it ... it doesn't work for me.

What worked for me is, I have to go through menu "Tools/Build With ..." and set it manually.

I am not sure what you are asking and where will it lead to.

**Comment by r-stein** [comment]
You should use build with C-shift-b and just select `LaTeX`. Then the tex directives will be used for the program. If you select an other entry that takes precedence.

**Comment by python152** [comment]
I see, it works. thx
