### ISSUE TITLE
Quickfix: README PackageControl Badge

### ISSUE THREAD

**Issue by diego898** [SublimeText/LaTeXTools#1073]
The package control badge in `README.md` currently 404s. I think it should be changed

FROM: `[![Package Control](https://img.shields.io/packagecontrol/dm/LaTeXTools.svg?maxAge=2592000)]()`

TO: `[![Package Control](https://img.shields.io/packagecontrol/dm/LaTeXTools.svg?maxAge=2592000)](https://packagecontrol.io/packages/LaTeXTools)`

**Comment by r-stein** [comment]
Sounds reasonable
