### ISSUE TITLE
c-r Problem

### ISSUE THREAD

**Issue by AdsonBatista** [SublimeText/LaTeXTools#1075]
Hello I have a problem with c-r. The items do not appear correctly.
![c-r](https://cloud.githubusercontent.com/assets/18144363/24840200/3dd35b62-1d3f-11e7-8ba4-4600828735c1.PNG)

I use Windows 10 x64.

**Comment by r-stein** [comment]
Does it work in no document? Can you provide an (minimal) example document, where it doesn't work?

**Comment by AdsonBatista** [comment]
Hello! Seeing that another \ begin {document} or \ end {document} causes problems if present in the document.
```TeX
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}

	\section{section1}
	\subsection{subsetion1}
		\begin{verbatim}
			%Preâmbulo
			\begin{document}
			%documento
			\end{document}
		\end{verbatim}
	\section{section2}
		Text
	\section{section3}
		Text
 `\end{document}
```

I can not fix it.

**Comment by r-stein** [comment]
Yes, we stop the document analysis if we reach `\end{document}`.

You can delete [this line](https://github.com/SublimeText/LaTeXTools/blob/v3.13.5/latextools_utils/analysis.py#L431) to change this behavior.

**Comment by AdsonBatista** [comment]
Sorry but, I delete this line C-r stop totally.

**Comment by r-stein** [comment]
You need to restart Sublime Text

**Comment by r-stein** [comment]
May be worth to add, that you can also disable that and use the default C-r via the [settings](https://github.com/SublimeText/LaTeXTools/blob/v3.13.5/LaTeXTools.sublime-settings#L57)

**Comment by AdsonBatista** [comment]
Doing what you said was like this. 
![capturar](https://cloud.githubusercontent.com/assets/18144363/24883754/b2f36486-1e1c-11e7-9068-abfbfa6a8266.PNG)
That's right?

**Comment by r-stein** [comment]
Yes, that's right. That is the built-in goto-overlay, which lists sections and labels. You also have a C-shift-r for the whole project (in our version it is goto the whole *document* instead of only file).
We made our own panel, because the default one doesn't seem to fit the LaTeX document structure very well. Especially for multi-file documents.

**Comment by AdsonBatista** [comment]
Interesting and very good! A physical side panel (as in other editors) is a project?

**Comment by r-stein** [comment]
Yes, you see the project files in the side panel. These files are searched with C-shift-r.
