### ISSUE TITLE
Add `-shell-escape` to build commands?

### ISSUE THREAD

**Issue by nickeubank** [SublimeText/LaTeXTools#1082]
I'm trying to compile a doc with the `minted` package (for code syntax highlighting), and I'm getting the error: 

    Package minted Error: You must invoke LaTeX with the -shell-escape flag. []

At the moment my builder is set to `simple`. 

Is there any easy way to add this flag?

Sublime Text 3, Mac OSX

**Comment by r-stein** [comment]
The easiest way is to add `% !TEX options=--shell-escape` at the top of your root document and switch the builder to `basic` or `traditional` (the simple builder is just a demonstration and `basic` is a better alternative).

**Comment by nickeubank** [comment]
@r-stein thanks!

**Comment by TaylanT** [comment]
hi @r-stein maybe you can help me again, 

I have added  `% !TEX options=--shell-escape` at the top of my root document but in the log file it still gives me `runsystem(inkscape -z -D --file=gfx/Versuchsstand/test.svg --export-pdf=gfx/Ver
suchsstand/test.pdf --export-latex)...disabled (restricted)`.

When i run `pdflatex -shell-escape my-thesis.tex ` in a normal terminal (Debian) everything works just fine. 

Do you know how to fix that problem?

**Comment by ig0774** [comment]
@taylant: what builder are you using?

**Comment by TaylanT** [comment]
I am using the TraditionalBuilder, but I tried different builders. None of them working regarding my problem. Seems like there is a problem with \write18 which gives me `restricted \write18 enabled.` in my logfile. Compiling from terminal just gives `\write18 enabled.` I have solved the issue with adding `"options": ["--shell-escape"],` to my settings file.

**Comment by assombrance** [comment]
hi, I have the same problem, where did you add that option ?

**Comment by r-stein** [comment]
@assombrance If adding `% !TEX options=--shell-escape` to the top of the root file does not work you can add that line (`"options": ["--shell-escape"],`) in the LaTeXTools settings inside `builder_settings`.
