### ISSUE TITLE
Relative path problem (\input, \include)

### ISSUE THREAD

**Issue by xGabba** [SublimeText/LaTeXTools#1083]
I'm trying to Include/Input some .tex files.
If I'm trying to do this the error message that the file wasn't found occurs. When I'm using the absolute path, to the file, it works.
After I wrote for example "\input{" then sublime text suggests me possible files which are deeper in hierarchy. But there still occurs the error.

Example:
- main.tex
- context/
-- tables.tex
-- tables/
--- table1.tex
--- table2.tex

Now I like to input files table1.tex and table2.tex into tables.tex.

**Comment by r-stein** [comment]
The paths in `\input` are relative to the texroot, hence you need to use `\input{context/tables/table1.tex}` inside `tables.tex`.

---

If you want to use relative paths you can use the [import package](https://www.ctan.org/pkg/import) (for which LaTeXTools also provides completions in the newest version).
Then you write in your `main.tex`
``` latex
% ...
\usepackage{import}
% ...
\begin{document}
% ...
\subimport{context/}{tables.tex} % attention the / musst be present
```

And in `tables.tex`
``` latex
\input{tables/table1.tex}
```

**Comment by r-stein** [comment]
If you have no further questions I will close this issue.
