### ISSUE TITLE
No Bib files found - Tex file path contains symlinks

### ISSUE THREAD

**Issue by MattDiesel** [SublimeText/LaTeXTools#1089]
Was having a problem with LaTexTools not finding the bibliography in the same directory. Turns out the issue was caused by the path containing symbolic links. This is on linux, no idea whether the same can happen on Windows.

To reproduce, start with an existing (working) document with a bibliography, then `ln -s` to the parent directory from somewhere else and open the file from there.

Reopening the file using the true path fixed the issue. 

Regards,

Matt

**Comment by r-stein** [comment]
If I understand you right the tex file is the same, but they way you open it is different?

**Comment by MattDiesel** [comment]
@r-stein correct. The paths will look different. 

Symbolic links are probably best described as being files that link to a new directory in a similar vein to shortcuts on Windows. For example running stat in these two subtly different ways produce different results:

```
$ stat somelink
  File: somelink -> ./somefolder/
  Size: 13              Blocks: 0          IO Block: 4096   symbolic link
Device: 803h/2051d      Inode: 1838792     Links: 1
[matt@matt-arch ~]$ stat somelink/
  File: somelink/
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 803h/2051d      Inode: 3697434     Links: 2
```

The second also has an equivalent `$ stat -L somelink`.

It is possible to open sublime in both the `somelink/` and `somefolder/` directories and they both work. LaTeXTools mostly works, with the exception of not finding bib files.

**Comment by MattDiesel** [comment]
It seems it's not reproducible for the simple case I gave above. I will have to investigate further as it could be some other issue with my setup. 

The only thing I've noticed that could be relevant is the following behaviour:

```
>>> import os
>>> os.path.dirname('~/somelink')
'~'
>>> os.path.dirname('~/somelink/')
'~/somelink'
```

However, as said, I can't create a simple reproducer.

**Comment by r-stein** [comment]
Thanks, I understand the setup now. Ref completions, jump to include files(C-l, C-j) and everything else works fine?

**Comment by MattDiesel** [comment]
Closing the issue, as after more testing it appears the issue is not the presence of symlinks as previously thought. I'll open a new issue when I can figure out what it is about my setup that causes it (though it seems to be only the one project, and attempts to reproduce have been unsuccessful).
