### ISSUE TITLE
Intermittent crashes when compiling 

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#1091]
build 3131
win 10
Not sure what happened but recently, when I compile programs I frequently get intermittent segfaults that totally crashes sublime. Again sorry I don't have more info but I'm not sure how to debug since it crashes all of sublime

**Comment by r-stein** [comment]
This doesn't happen on other ST versions (you can just download the portable)? I don't think we can do something about this. You could try to disable [error phantoms](https://github.com/SublimeText/LaTeXTools/blob/v3.13.6/LaTeXTools.sublime-settings#L453).
