### ISSUE TITLE
Extra backslash added to commands when autocompleting

### ISSUE THREAD

**Issue by Mc128k** [SublimeText/LaTeXTools#1092]
Hi, using ST3 and the latest release of the plugin. It's working great.
One small issue I see is that when autocompleting an extra backslash is added at the beginning of the command, see the video for more details. I couldn't find another issue describing this behaviour.

![ezgif-2-2a00ca58fe](https://cloud.githubusercontent.com/assets/3678359/25528965/7290e1ae-2c20-11e7-8fc7-ab27bbb72821.gif)

**Comment by r-stein** [comment]
I am not sure how you come from `\[...\]` to `\begin{equation}...\end{equation}` and I don't see a autocompletion popup, but that snippets inserts an additional backslash is espected (and we can't change this with snippets).
The best to do is just to omit the `\ ` before triggering the snippet.

**Comment by Mc128k** [comment]
I use tab for autocompletion, and what most users expect is that the command is actually completed, not inserted. Pressing tab multiple times switches to other possible commands, as it should be. If I don't enter the first backslash, then the autocompletion fails

**Comment by r-stein** [comment]
Since we are speaking about [these completions](https://github.com/SublimeText/LaTeXTools/blob/c122f4ffca7f0e5f82bddd51e563e682c9982540/LaTeX.sublime-completions#L18) it should also work without the leading `\ `. Since the switching doesn't work like this for me I can't say something about that. You may just edit that file and remove the leading `\ \ ` in the contents.

**Comment by Mc128k** [comment]
Oh, I get it now. It's not like other IDEs where it completes inserted text. So this is a feature more than a bug, problem solved.

**Comment by r-stein** [comment]
If you install `LaTeX-cwl` (and restart ST) you will get an IDE like completion, which uses your self-defined command and the commands from the used packages. However that is a snippet, which is very simple.

**Comment by Mc128k** [comment]
That seems to work exactly the same way, anyway it's useful. Thanks
