### ISSUE TITLE
Not recognizing %& -job-name= on the main latex file

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1094]
If I set this on my main latex file first line, it cannot parse any files correctly due the generated files being under the name `proposta` instead of the main file name.:
```latex
%& -job-name=proposta
% ^ Sets the pdf file name
%
```

It does not compiles correctly with any build. I think this could be related to:

1. https://github.com/SublimeText/LaTeXTools/issues/104 _ "LaTeXTools cannot correctly detect file names in this LOG file"

**Comment by ig0774** [comment]
LaTeXTools doesn't support that syntax. You can use `%!TEX jobname = proposta` to do what you want using either the `basic` builder or the `traditional` builder if you are using TeXLive.

**Comment by evandrocoan** [comment]
Thanks. I am closing this issue as the problem is solved. 
But if the support can/is planned be added, this issue could be reopened.
