### ISSUE TITLE
Broken documentation search on readthedocs.io

### ISSUE THREAD

**Issue by Mc128k** [SublimeText/LaTeXTools#1095]
Hi, it seems that the search feature on the official documentation is not working. Before contacting the provider I thought it could be appropriate to post the problem here.

**Comment by ig0774** [comment]
Thanks for pointing that out. It looks like the search feature for RTD is somewhat broken when using MkDocs (as we do) (bunch of issues on this). There's a suggestion [here](https://github.com/rtfd/readthedocs.org/issues/1088#issuecomment-224715045) for how to fix it. I'll  look into applying it to our docs.

**Comment by ig0774** [comment]
Thanks for pointing this out. Searching the docs should now work.
