### ISSUE TITLE
Unicode in Math Preview

### ISSUE THREAD

**Issue by adamschoenemann** [SublimeText/LaTeXTools#1097]
First of all, thank you for making this plugin, it is very nice!
However, I'm very fond of using Unicode when writing my equations. While I have it working fine when I compile, it does not work in the math preview. I've set 
```
  "preview_math_latex_compile_program": "xelatex",
  "preview_math_template_packages": ["unicode-math", "xunicode"],
```
but so far, it does not have any effect.
How would I go about doing this?

**Comment by r-stein** [comment]
Aside: The bug report fails on unicode chars, because it uses the wrong encoding (I will fix that).

The values for `"preview_math_template_packages"` should be different, because you should use LaTeX syntax (We just join the strings and put them into a template to compile it).
Hence it should be:

```js
	// An array of the used packages, from which the file for the live preview
	// will be generated.
	// Just write \\usepackage{packagename} to include other packages.
	// (The xcolor package will be present, even if not in this list.)
	"preview_math_template_packages": [
		"\\usepackage{unicode-math}",
		"\\usepackage{xunicode}"
	],
```

**Comment by adamschoenemann** [comment]
Great, that fixed it! Perhaps it should be mentioned in the documentation (or perhaps I somehow missed it?). Thanks for the speedy reply.

**Comment by r-stein** [comment]
Yes, it only mentioned in a comment above the default settings. We should improve that.
