### ISSUE TITLE
Improve badbox log parsing code (patches)

### ISSUE THREAD

**Issue by msiniscalchi** [SublimeText/LaTeXTools#1098]
@ig0774 and @r-stein --- sorry I didn't set up a proper pull request. I am attaching patches. This is because i haven't set up my own separate tree, and I don't want to just push my own commits to master, just in case.

This is a hopefully small change to log parsing. My original code used a permissive test to detect the end of an over/undefull message. It turns out that one needs to be strict: over/underfull messages end with a single line containing exactly three characters, " []". A nasty side effect of not detecting this correctly was that, if the text in the badbox contained a ")", it led to file names being dropped. It took me a while to diagnose this.

I have tested the fix on a range of log files from both MikTeX and TeXlive, but some additional testing won't hurt. 

The patches also contain other minor fixes.

[patches.zip](https://github.com/SublimeText/LaTeXTools/files/974480/patches.zip)

**Comment by ig0774** [comment]
Closing since the patches have been merged.
