### ISSUE TITLE
Feature Request: Create a new file if \input{} dialogue has no results

### ISSUE THREAD

**Issue by RaphaelArkadyMeyer** [SublimeText/LaTeXTools#1100]
When I type `\input{}` and have the search dialogue popup, I'm not always sure if I've already created the target file, so I type my fine name in. If the file does not yet exists, I'm left with my file name typed in already, but no way to use it. That menu should allow me to make a new file with the given name.

The fastest course of action currently possible is to hit escape, type the file name in again, and hit ctrl-l-j, which I find annoyingly long since I've already typed the file name in once.

**Comment by r-stein** [comment]
We are looking forward to implement this, see #1051

**Comment by RaphaelArkadyMeyer** [comment]
Ah, my bad. My search query didn't highlight that request.
