### ISSUE TITLE
Entire Latex socument shown at bottom of editor window

### ISSUE THREAD

**Issue by michK** [SublimeText/LaTeXTools#1104]
I'm not sure if this is a bug or a feature, but the entire latex document is shown at the bottom of the editor window.

Is there a way to switch this off?

I like the feature that equations are shown like this when the cursor is placed at the end of an equation, but I find the whole document being rendered a bit too much.

**Comment by r-stein** [comment]
That is not expected I assume there is a syntax error, which opens the math mode at the wrong position and doesn't close it (you may also have the wrong syntax highlighting). Can you provide a minimal example document?

**Comment by michK** [comment]
Thank you, based on what you said I went through my document and found that these lines caused it:

```
\renewcommand{\(}{\left(}     \renewcommand{\)}{\right)}
\renewcommand{\[}{\left[}     \renewcommand{\]}{\right]}
```

**Comment by r-stein** [comment]
The easiest is to just put them in an other file and `\input{}` that (though it is usually bad to edit your files to fit the syntax highlighting, but highlighting LaTeX will always have some flaws).

**Comment by michK** [comment]
I will keep that in mind, thanks. I have a bunch of custom commands so it will actually make my main script allot more clean if I put all of that in another file!
