### ISSUE TITLE
Ctrl + b did not work to compile tex file

### ISSUE THREAD

**Issue by onion5376** [SublimeText/LaTeXTools#1112]
Now, I use sublime text 3 editor under 32-bit win 7 platform. Before update the latest LatexTools, it could use the shortcut keys "Ctrl+b" to compile tex file. Recently, it did not work for the  new version LatexTools, erros is as followings:
     Traceback (most recent call last):
  File "D:\Program Files\Sublime Text3\sublime_plugin.py", line 526, in run_
    return self.run()
  File "D:\Program Files\Sublime Text3\Data\Packages\LaTeXTools\makePDF.py", line 142, in run
    project_settings.get('build_systems', [])
AttributeError: 'NoneType' object has no attribute 'get'

However, The tex file could be compiled using sublime text menu (Tools/Build menu item). I did not know what happen to this. Could you give any tips? Thank you!

**Comment by r-stein** [comment]
Have you tried to restart ST?

**Comment by onion5376** [comment]
Yes, I have restarted sublime text, it still not work. I did not know how to solve it.

**Comment by r-stein** [comment]
Which ST3 build are you using? There seems to be a bug in the build selector, which should only be triggered in < build 3080. You can try to change [this line](https://github.com/SublimeText/LaTeXTools/blob/v3.14.0/makePDF.py#L123) to
```py
project_settings = self.window.project_data() or {}
```

**Comment by onion5376** [comment]
Thans for your reply. The sublime text is "build 3038". Accoording to your instructions, I have open the file "makePDF.py", it shows the same content as followings:
project_settings =self.window.project_data().
How to solve this problem?   to update the vesion of sublime text or to revise the script?

**Comment by r-stein** [comment]
You can just edit the line and add `or {}` to the end (we will also do this in the next patch) or update ST to a newer version.

**Comment by onion5376** [comment]
The code in makePDF.py is as followings:

I did not understand how to revise this code. Maybe I only try to update the version of st3. Thank you for your helps.
