### ISSUE TITLE
new behavior of keybinding C+l, e to create an environment

### ISSUE THREAD

**Issue by xiaoweiz** [SublimeText/LaTeXTools#1113]
The new behavior of `C+l, e` becomes 
```latex
\begin{}

\end{}
```
with two cursors appearing in the braces. Now, to add contents inside the environment, one has to first escape from the multi-cursor mode and then move the cursor to the blank line, which requires several keystrokes or using mouse.

The previous behavior was typing the name of the environment, e.g. `align`, and then typing `C+l, e` produces 
```latex
\begin{align}

\end{align}
```
with a single cursor appearing inside the environment. IMO, this is more convenient than the new behavior. 

Is there a way to restore to the old behavior of this keybinding?

**Comment by r-stein** [comment]
Do you latex zeta installed?

**Comment by xiaoweiz** [comment]
Ah, Yes. Thanks for the reminder. I copied the keybinding setup of LatexTools to  LateXYZ (this is the new package name of Latex zeta) to get what I want.

**Comment by randy3k** [comment]
@xiaoweiz 

For your information, you just need to press `<tab>` after adding the contents. I personally found that it is more intuitive then typing the environment name then `C+l, e`. Plus, I usually use it to wrap the selection by an environment. When I want to center some text, I just need to select the text and do `C+l, e` and enter the `center`.
![untitled](https://cloud.githubusercontent.com/assets/1690993/26022794/29e98a02-377c-11e7-8b75-45e199085842.gif)

**Comment by xiaoweiz** [comment]
@randy3k Thanks a lot for the tip! I didn't know a simple `tab` does the trick.

**Comment by r-stein** [comment]
I also prefer that way to insert environments (especially because you also can use autocomplete if you have LaTeX-cwl installed), but it is by default already on C-l, C-n. Hence with LaTeXTools and LaTeXZeta you have (nearly) the same behavior with C-l,C-n and C-l,e.

**Comment by randy3k** [comment]
`C+l, C+n` wraps the environment name, not the content. AFAIK, there is no such functionality exists in LaTeXTools. Not sure about LaTeX-cwl as I have never tried that...

**Comment by r-stein** [comment]
Sorry for the late reply.
LaTeXYZ uses the snippet on C-l, e: `\\begin{${1:env}}\n$SELECTION$0\n\\end{$1}`
LaTeXTools uses on C-l, C-n (with selection): `\\begin{${1:env}}\n$SELECTION\\end{$1}`
and without selection: `\\begin{${1:env}}\n$0\n\\end{$1}`

This is nearly the same behavior.

LaTeX-cwl provides data, which is used by LaTeXTools to provide auto-completion, so you can press C-l, C-n and then use the auto-completion popup or fill-all helper to insert the environment:

![cwl_example](https://cloud.githubusercontent.com/assets/12573621/26284877/3b033c96-3e45-11e7-8ac4-e390166a7ac3.gif)

**Comment by vqv** [comment]
@r-stein That's an interesting example of using auto-completion with new environment, but I can't get LaTeXTools to behave this way.  I've set `"env_auto_trigger": true`, `"command_completion": "always"`, and have a `"cwl_list":` with some cwl files, but I never get the can't get the popup after pressing C-l, C-n.  It only appears if I type a backslash, but then I have to remove the backslash after the fill-in
![out](https://user-images.githubusercontent.com/867637/29678670-7668be32-88cd-11e7-8b5a-bc7c8c3367a6.gif)

**Comment by randy3k** [comment]
Just to let everybody know that LaTeXYZ has deprecated the <kbd>C+l, c</kbd> and <kbd>C-l, e</kbd> commands to make it more consistent with LaTeXTools.

**Comment by r-stein** [comment]
@vqv You can press `C-space` to manually open the auto-completion popup and it is auto-triggered with `\ `. Using `C-l, C-f` to trigger the fill-all helper should also work.

**Comment by vqv** [comment]
@r-stein Okay, I think I've gotten it to work.  Is this the right sequence of keystrokes to reproduce your example above?

`C-l, C-n` `e` `C-space`

It seems like the completion popup won't appear until I erase the default `env` placeholder or replace it with something completable like `e`.  Is there a reason that the default placeholder is `env`?  I removed it from the `Insert environment.sublime-snippet` and this allows me to invoke the environment auto-completion popup with the keystroke sequence:

`C-l, C-n` `C-space`

**Comment by r-stein** [comment]
@vqv Yes, that is the correct sequence (I have changed the `auto_complete_selector` to be triggered more often, but that depends on personal favors). I agree that it may be better to remove the placeholder, so anyone can use `C-space`` or `C-l, C-f` directly and does not need to remove the placeholder before that.

**Comment by vqv** [comment]
@r-stein Thanks for the note about `auto_complete_selector`.  I added

`"auto_complete_selector": "source, text",`

to my `User/Preferences.sublime-settings` file.  Now I can just type 

`C-l, C-n` `e`

to create a new environment and trigger the auto-complete popup.  This also works without removing the `env` placeholder.
