### ISSUE TITLE
Feature Request: %!TEXT option to run an additional command

### ISSUE THREAD

**Issue by kill0rz** [SublimeText/LaTeXTools#1114]
Hi,

it would be nice to have an an option for running an additional command per .tex file.
Maybe something like this:
`%!TEX addcommand = ./dosomething.sh`

This command should ne run after the compilation is done.

Background: I want to export my pdf to jpg and keep the version up to date. It is annoying to always do this manually. An automation this way would be cool :)

**Comment by ig0774** [comment]
Please see the documentation on the [Script Builder](https://latextools.readthedocs.io/en/latest/available-builders/#script-builder), which enables you to run any series of commands you'd like. Note that right now it's only configurable via settings, which implies using a Sublime project to configure things on a per-project / per-document basis, but it should be as simple as:

```json
"script_commands" : [
     "latexmk -pdf -cd -interaction=nonstopmode -synctex=1 -f",
     "dosomething.sh"
]
```

In that configuration, the first argument passed to `dosomething` will be the base name of the main TeX file, but obviously the argument can be ignored if not needed.

**Comment by kill0rz** [comment]
Thank you for the quick reply!
This olution looks like a good idea!

One last question:

> [...]or of the current project file (if any):
How would be the name of this file and has it to be put in the same directory as the .tex file?
I only want to do this for onw specific tex-file. Thanks!

**Comment by ig0774** [comment]
Sublime project files can have any name you'd like, though they have the extension `.sublime-project`. They can also be saved anywhere you'd like, though its obviously convenient to keep them near the document they refer to.

To create the `.sublime-project` file, just go to the **Project** menu and select **Save Project As...***.

**Comment by kill0rz** [comment]
Ok, I see. So I have to use a sublime project and am not able to create a file only Latex Tools will use?

**Comment by ig0774** [comment]
Right

**Comment by kill0rz** [comment]
OK, thank you :)
