### ISSUE TITLE
Add support for biblatex date entry for `cite_panel_format`

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#1116]
I believe date is the recommended entry type that e.g. jabref automatically format's  year entries to. 

e.g.
```
@Article{Bryan1999,
  author       = {Bryan, Greg L.},
  title        = {Fluids in the universe: adaptive mesh refinement in cosmology},
  journaltitle = {Computing in Science \& Engineering},
  date         = {1999-03},
  volume       = {1},
  number       = {2},
  pages        = {46--53},
}
```
would be good to have the `date` entry recognized in
```
	"cite_panel_format": ["{author_short} {date   or year } - {title_short} ({keyword})","{title}"],
```

**Comment by ig0774** [comment]
`date` is properly supported if you use the `new` bibliography plugin rather than the `traditional` one.

**Comment by musm** [comment]
I guess this is a circular issue, since `new` doesn't work for me, ref https://github.com/SublimeText/LaTeXTools/issues/1115

**Comment by ig0774** [comment]
Whoops. Just caught that. Don't want to catch you in a circular issue.
