### ISSUE TITLE
Build overall pdf from any chapter.tex file

### ISSUE THREAD

**Issue by knatz-personal** [SublimeText/LaTeXTools#1121]
I find myself frequently forgetting to open the main.tex file in order to build my thesis and building from the chapter I am working on. I don't know if there is a setting to enable this but I would appreciate if someone could look into it.

**Comment by r-stein** [comment]
Multi-file documents are supported:

http://latextools.readthedocs.io/en/latest/features/#multi-file-documents

This does not only enable you to build, but also improves other features like auto-completion.

**Comment by knatz-personal** [comment]
Thank you!
