### ISSUE TITLE
Syntax support for array package with {>$}{<$} spec

### ISSUE THREAD

**Issue by CareF** [SublimeText/LaTeXTools#1124]
I noticed that for the tabular with {>$} {<$} setting (meaning math mode in the table by default), there will be problems for math mode matching as all the contents after this will be specified as in the math mode. For example the following codes: 

```
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{*{3}{>{$}c<{$}}}
	a & b & c \\\hline
	1 & 2 & 3
\end{tabular}

Here it should not be in the math mode. 
\end{document}
```

**Comment by r-stein** [comment]
Which Sublime Text build are you using?

**Comment by CareF** [comment]
@r-stein Thanks!
I am using Build 3126 on Linux

**Comment by r-stein** [comment]
The LaTeX syntax is not provided by LaTeXTools, but by Sublime Text itself. As far I know support for the array package has been added in build 3127, but without the `*{N}{string}`. I have created a PR to fix this. You can download it [here](https://github.com/r-stein/Packages/tree/latex_improve_array), then select *Preferences > Browse Packages...* in ST, and copy the `LaTeX` folder into that directory.

**Comment by CareF** [comment]
This works! Thank you!
