### ISSUE TITLE
No bib files found! 

### ISSUE THREAD

**Issue by wangdzh** [SublimeText/LaTeXTools#1125]
I'm running a Sublime 3 with LaTeXTools on macOS.
I'm kind of new to LaTeXTools. Sorry if I have asked a silly question.
Although I have my `main.tex` and `bibliography.bib` under the same folder, the `No bib files found!`  pop out when I use `\cite{}`
The console shows `error: No bib files found!
TEX root: '/Users/wangdz/Desktop/LaTeX_project/aw_essay/main.tex'
Bib files found: ()
error: No bib files found!`
I have the following code at the end of my main.tex
```
\bibliographystyle{plain}
\bibliography{bibliography}
\end{spacing}
\end{document}
```

**Comment by ig0774** [comment]
Hmmmm... I can't reproduce that from a simple test. Could you try deleting the auxiliary files (`C-l,backspace`) which will also clear the cache.

**Comment by wangdzh** [comment]
That turns out to totally fix the problem,  which I have spent hours on it! I don't know how to express my gratitude!!
