### ISSUE TITLE
Problem about preview of Math formula

### ISSUE THREAD

**Issue by Edenharder** [SublimeText/LaTeXTools#1126]
The preview of the formula after this code `\newcolumntype{C}{>{$}c<{$}}` will all be wrong. For example, the preview of `$abc$` in the picture.

![image](https://cloud.githubusercontent.com/assets/6672134/26305343/30651bba-3eef-11e7-86ed-b51042018d49.png)

**Comment by r-stein** [comment]
The LaTeX syntax is part of ST and not of LaTeXTools. Support for the array package has been added in build 3127, but you can use the latest syntax on older versions. Please see https://github.com/SublimeText/LaTeXTools/issues/1124#issuecomment-302940003
