### ISSUE TITLE
Preview not working in 3.14

### ISSUE THREAD

**Issue by wxingsheng** [SublimeText/LaTeXTools#1132]
The preview works when $$xxxx$$ is used and align, equations, etc are used. However, it's not working when $xxxx$ is used.
<img width="152" alt="bugs" src="https://cloud.githubusercontent.com/assets/22246742/26383932/d4962732-4003-11e7-9a91-ed721d8efc77.png">

**Comment by r-stein** [comment]
This is by design and can be controlled via a [setting](https://github.com/SublimeText/LaTeXTools/blob/v3.14.0/LaTeXTools.sublime-settings#L107). Just add `"preview_math_scope": "text.tex.latex meta.environment.math",` to your "LaTeXTools - User" preferences.
