### ISSUE TITLE
XeLaTeX engine seems to be slow

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1133]
Though I don't have any timing data, I found it slow to build with XeLaTeX, especially when I'm typesetting Chinese. 

However, the XeTeX engine only takes a long time to finish its job the first few times I ran it, because it has to cache a lot of font information. 

So, what would be the possible reason for this? If you need a test file, you may try `chn.tex in
[chn.zip](https://github.com/SublimeText/LaTeXTools/files/1024229/chn.zip)
`. 

  
Thank you so much.

**Comment by r-stein** [comment]
We only call XeLaTeX and have no insights into it, sou may get a better answer on tex.stackexchange.com. There is already in this direction: https://tex.stackexchange.com/a/357100/99279

**Comment by Romeoly** [comment]
@r-stein Thank you so much. And your reply really helped solve the  problem.
