### ISSUE TITLE
Percentage in verbatim is recognized as comment

### ISSUE THREAD

**Issue by schreda** [SublimeText/LaTeXTools#1135]
Please fix this. This destroys all syntax highlighting in my document

**Comment by r-stein** [comment]
I have created a PR for the syntax in the default packages. You can install [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer) and edit the file *LaTeX/LaTeX.sublime-syntax* and search for the `verb` context and add `- meta_include_prototype: false` behind the push (as in the PR).

**Comment by schreda** [comment]
Worked, thanks!
