### ISSUE TITLE
Custom cwl files are not included automatically

### ISSUE THREAD

**Issue by tobiasdiez** [SublimeText/LaTeXTools#1136]
If I understand the [documentation about the cwl feature](https://latextools.readthedocs.io/en/latest/completions/#latex-cwl-support) correctly, then completions from custom `cwl` files placed in `Packages\User\cwl` should be included automatically. This is not the case for me; only the standard completions are shown. I can fix this by manually adding my file to the `cwl_list` setting, i.e.
````
"cwl_list": [
		"tex.cwl",
		"latex-209.cwl",
		"latex-document.cwl",
		"latex-l2tabu.cwl",
		"latex-mathsymbols.cwl",
		"latex.cwl"  # <-- my file
	]
``̀ `

By the way, also the cwl-files from the `LaTeX-cwl` package are not included automatically.

System: Sublime Build 3126, LatexTools  3.14.0

**Comment by r-stein** [comment]
The cwl files are only included automatically if you use the package with the same name. I.e. if you have `\usepackage{amsmath}` in the preamble of you document it will look for a file with the name `amsmath.cwl` inside the folders `LaTeX-cwl` and `User/cwl`. If you have a file, which should be included in every document (even if you don't use a package with the same name) you can add it to that list.

**Comment by tobiasdiez** [comment]
Ok, then probably I misunderstood the sentence 
>  In addition, support will be enabled if any custom cwl files are installed in the Packages/User/cwl directory.
in the documentation. 

(The missing support for used packages is probably a result of me using the subfiles package and LatexTools does not follow `\documentclass[../../index.tex]{subfiles}` to the index to extract the packages?)
