### ISSUE TITLE
Contradictory statements in documentation re: MikTeX flag

### ISSUE THREAD

**Issue by stephenlevitt** [SublimeText/LaTeXTools#1139]
At [https://latextools.readthedocs.io/en/latest/features/#output-directory-and-auxiliary-directory](url) the docs state: 

> Note: the --aux-directory flag is only implemented by MiKTeX, so the corresponding settings will only be valid if you are using MiKTeX, as indicated by your distro setting

followed by:

> If you are using texify (i.e. the traditional builder on MiKTeX) or the simple builder, the output_directory and aux_directory settings will be ignored.

The "aux-directory" flag does work when using MikTeX.

**Comment by ig0774** [comment]
There's no contradiction, but you do need to be careful about reading those statements.

The `--aux-directory` flag works for `pdflatex` / `xelatex` / `lualatex` on MiKTeX and only on MiKTeX. It does not, however, work when using the `texify` executable (which is what is run by the `traditional` builder) and the `simple` builder does not take into account the relevant settings. Hence the text above the second quote which reads:

> **Note:** These flags can only be set when using `latexmk`, the `basic` builder or the `script` builder.

Any of the three builders listed *can* use `--aux-directory` provided you are using the MiKTeX distribution.

**Comment by r-stein** [comment]
I will close this issue. If you have proposals to improve the readability of the docs we are open to suggestions =)

**Comment by stephenlevitt** [comment]
Thanks for the clarification. I've had a go at trying to improve the wording. See below.

Replace
>Note: the --aux-directory flag is only implemented by MiKTeX, so the corresponding settings will only be valid if you are using MiKTeX, as indicated by your distro setting. To get similar behavior on TeXLive / MacTeX, you can use the copy_output_on_build setting described in the settings section with any of the output_directory settings. This will run pdflatex / xelatex / lualatex with the --output-directory flag and then copy the resulting PDF to the same directory as your main TeX document.
>
>Note: These flags can only be set when using latexmk (i.e., the traditional builder on OS X and Linux), the basic builder or the script builder (see below for documentation on using the script builder). If you are using texify (i.e. the traditional builder on MiKTeX) or the simple builder, the output_directory and aux_directory settings will be ignored.

with

>The `--aux-directory` flag works on MiKTeX and only on MiKTeX. To get similar behavior on TeXLive / MacTeX, you can use the `copy_output_on_build` setting described in the settings section with any of the `output_directory` settings. This will run `pdflatex` / `xelatex` / `lualatex` with the `--output-directory` flag and then copy the resulting PDF to the same directory as your main TeX document. 
>
>Given that you are using MiKTeX, as indicated by your `distro` setting, note the following:
>
>- The  `aux-directory` setting works with the `basic` builder (running either `pdflatex` / `xelatex` / `lualatex`) and it can work with the `script` builder  (see below for documentation on using the `script` builder).
>
>- Additionally, it works with the `traditional` builder on OS X (which runs `latexmk`). However, it does not work, and is ignored along with the `output_directory` setting, when using the `traditional` builder on Windows (which runs `texify`).
>
> - Lastly, these flags do not work when using the `simple` builder as this builder does not take them into account.
