### ISSUE TITLE
Support subfiles package in children files.

### ISSUE THREAD

**Issue by tobiasdiez** [SublimeText/LaTeXTools#1143]
The [subfiles](https://www.ctan.org/pkg/subfiles) package allows you to reuse the preamble of one document in other documents.
For example,
main.tex
````tex
\documentclass{article}
\usepackage{subfiles}
% other preamble stuff goes in here
\begin{document}
\end{document}
````
and sub.tex
````tex
\documentclass[main.tex]{subfiles}
\begin{document}
% rest of document goes in here
\end{document}
````

It would be awesome if LatexTools could provide the same preamble-related features (auto-completion of macros, bibliography, ...) also in `sub.tex`.
If I specify the `TEXroot` by hand, then these features also work in the subfile, but of course the main file is used for compilation (which is not what you want).

(I'm willing to work on this, but I need a pointer where to start since I'm completely new to the code [and actually have no experience with Python]).

**Comment by r-stein** [comment]
So if we are in the subfile we would take everything between `\documentclass{...}` and `\begin{document}` from the mainfile?

**Comment by tobiasdiez** [comment]
Yes exactly, including the `\documentclass{...}` line of course! (I think, the subfiles package also includes everything after the `\end{document}` command from the main file, but this subtle point can probably be ignored)

**Comment by r-stein** [comment]
Sounds reasonable to support this. I have created a PR for it you can clone or download it [here](https://github.com/r-stein/LaTeXTools/tree/subfiles) and try it out. However you will need to clear the document cache C-l, backspace.

**Comment by tobiasdiez** [comment]
Thanks for the quick implementation! 

I tried to test it, however I get the following error which I believe is a consequence of the changes in https://github.com/r-stein/LaTeXTools/commit/bb71cf7708cd5c35621644c5b2761117745f3eef.
How do I install the regex module?

>Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\jumpto_anywhere.py", line 8, in <module>
    from .latextools_utils import analysis, ana_utils, quickpanel, utils
  File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\analysis.py", line 4, in <module>
    import regex
ImportError: No module named 'regex'

**Comment by r-stein** [comment]
Oh yes I added that dependency. I think you just need to press ctrl+shift+p and select "Package Control: Satify Dependencies".

**Comment by tobiasdiez** [comment]
Sadly that didn't worked. It reports `Package Control: All dependencies have been satisfied` however I still get the `regex` message.
There are also a few similar warnings
>   File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_cache_listener.py", line 21, in <module>
    from latex_cite_completions import (
ImportError: No module named 'latex_cite_completions'

and
>File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_input_completions.py", line 12, in <module>
    from latex_fill_all import FillAllHelper
ImportError: No module named 'latex_fill_all'
 
(I installed the version by adding the link you posted above as a repository in package control and then used it to upgrade).

**Comment by r-stein** [comment]
Sorry it seems I wrote the dependency file the wrong way and will fix it. You can download the newest version and run the command again or install (and uninstall) [RegReplace](https://packagecontrol.io/packages/RegReplace)

**Comment by tobiasdiez** [comment]
It now works perfectly! Thank you very much.

**Comment by r-stein** [comment]
This has been added in `st3-4.0.0-alpha.0`, please enable [prereleases](https://github.com/SublimeText/LaTeXTools#prereleases) to use it.

**Comment by tobiasdiez** [comment]
It appears that this feature stopped working recently, at least I no longer get completions in subfiles. (Sadly, I'm not able to tell you since which version the problem occurs).

By the way, https://github.com/SublimeText/LaTeXTools/issues/670 seems to be a duplicate of this issue and can be closed (if the aforementioned bug is resolved).
