### ISSUE TITLE
I cannot find latextools in package control

### ISSUE THREAD

**Issue by djjowfy** [SublimeText/LaTeXTools#1146]
Sublime text 3 
MAC OS 10.12

**Comment by r-stein** [comment]
We changed something with package control #1086 and it seem to be a problem with that. I will try to fix it ASAP.
Until then you can just

1. press C-shift-p
2. write "Package Control: Add Repository"
3. paste `https://github.com/SublimeText/LaTeXTools`
4. install as usual

If it does work again just remove the repository (and maybe reinstall it)

**Comment by djjowfy** [comment]
It works.Thanks.

**Comment by r-stein** [comment]
It is online again :)
Thanks @keith-hall  and @FichteFoll for helping and @wbond for fixing it.

If I understand it correct the problem was that the github API by default returns the last 30 tags in alphanumerical order, so the `vX.X.X` tags were returned instead of the new `st3-X.X.X` tags.

**Comment by cohnt** [comment]
Had this issue randomly occur for me, and I wanted to say that manually adding this github as a repository fixed it!
