### ISSUE TITLE
Add a new command LaTeXTools: Open PDF Containing Folder

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1147]
It is useful when I use the options `"aux_directory": "<cache>",` and `"output_directory": "<cache>",` and I want to copy the PDF or see some other temp files.

Currently I see command line used to open the PDF on the command `LaTeXTools: View PDF`, and take the file path used there to open the PDF.

**Comment by ig0774** [comment]
Probably best to call this something like "Open folder containing auxiliary files", since with `aux_directory` the PDF output folder is the folder containing the main TeX file.

**Comment by r-stein** [comment]
Added in [prerelease](https://github.com/SublimeText/LaTeXTools/tree/st3-3.14.1#prereleases) `st3-4.0.0-alpha.2`
