### ISSUE TITLE
Ruler set too wide in Latex files

### ISSUE THREAD

**Issue by neilernst** [SublimeText/LaTeXTools#1150]
If I want to use a ruler (view > ruler > 80), for some reason, in my Latex files only, the ruler is about 80 characters wider than all other files (tested with .md, .bib, .java). Somehow it takes the user selected ruler and pads it +80.

I checked my user prefs and I can't see where I could have changed this. The console isn't reporting anything useful. Sublime version: 3134 osx LatexTools 3.14.1

Examples:
 <img width="471" alt="screen shot 2017-06-09 at 09 39 38" src="https://user-images.githubusercontent.com/66286/26978194-999e9b3a-4cf8-11e7-8ee0-d6f6e5adad45.png">
 ![screen shot 2017-06-09 at 09 39 29](https://user-images.githubusercontent.com/66286/26978195-9afda502-4cf8-11e7-982c-24e2d0a1e99e.png)

**Comment by r-stein** [comment]
- Can you open the ST console ``ctrl+` `` and write `view.settings().get("rulers")`. Does this print `[80]`?
- If you have a e.g. java file and change the syntax to LaTeX (and vice versa) does this change the ruler?
- Do you use tabs in the screenshot document?

**Comment by neilernst** [comment]
1. yes, all syntaxes print 80
2. yes, the ruler moves when I change the syntax 
3. Yes

**Comment by r-stein** [comment]
Have you changed the font in LaTeX files? If so you can try to use a monospace font there.

**Comment by r-stein** [comment]
It looks like you are using a monospace font in other languages, but a different (not monospace) font for LaTeX. The position of the ruler is based on the width of the character `m`, which is way bigger on the other font therefore it it is farer to the right. So you can either use a monospace font or disable the ruler (it is not usefule otherwise anyway).

**Comment by neilernst** [comment]
Ok, thanks. 

I did "Preferences > Syntax Specific" and added a monospace font there (I'm still unclear on the precedence for font-settings for "Latex.sublime-settings" vs "LatexTools.sublime-settings").

I sort of assumed that word wrap at 80 characters would mean 80 characters, regardless of character width, but clearly that is not trivial. Word Wrap really means wrap at 80 "width units".

**Comment by r-stein** [comment]
`LaTeX.sublime-settings` are the settings used by Sublime Text while you are editing a LaTeX document. These are the same settings you set in your User oder Default preferences. (Technically these settings are also used by LaTeXTools, but you should not set LaTeXTools specific settings there)
`LaTeXTools.sublime-settings` are the settings only used by the LaTeXTools package. This is not used by the core or any other package.

I think anything you specify based on character width is not useful if you don't use monospace font. I will close this issue as it is resolved (or may be unsolvable).
