### ISSUE TITLE
Math preview is not consistent

### ISSUE THREAD

**Issue by ozerone** [SublimeText/LaTeXTools#1151]
If you write a math equation like $\pi$ then the preview does not work if you write it like $$\pi$$ then you can see a preview.

![notworking](https://user-images.githubusercontent.com/25182457/26989210-764a7a0c-4d0f-11e7-8eeb-5e49755db38f.png)

![working](https://user-images.githubusercontent.com/25182457/26989218-7b46e202-4d0f-11e7-8fbb-a9e75e114e0b.png)

Thank you very much for this amazing package.

**Comment by r-stein** [comment]
This the math preview is by design only visible in block and not in inline math equation you can simply change it with [this setting](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.1/LaTeXTools.sublime-settings#L107). Just set it to `text.tex.latex meta.environment.math`.

**Comment by ozerone** [comment]
Thank you very much. It is working again.
