### ISSUE TITLE
Tab triggered snippets in math env stopped working.

### ISSUE THREAD

**Issue by Port5053** [SublimeText/LaTeXTools#1153]
Snippets for brackets like `lp`+<kbd>Tab</kbd> = `\left(  \right)`, fractions with `fr`+<kbd>Tab</kbd>=`\frac{}{}` and greek letters stopped working, while others like `\begin{env} \end{env}` still do. Custom made `.sublime-snippet`'s also don't seem to be affected.

**Comment by r-stein** [comment]
I can't reproduce this (They are working for me)
- which Sublime Text version are you using?
- Have you edited the `LaTeX/LaTeX.sublime-syntax` file?
- Have you edited the `LaTeXTools/LaTeX math.sublime-completions` file?

**Comment by Port5053** [comment]
Now it works just fine again. Sorry for the inconvinience.
