### ISSUE TITLE
A command to paste a image from clipboard to the code?

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1154]
On the question [Drag and drop image files to LyX](https://tex.stackexchange.com/questions/58673/drag-and-drop-image-files-to-lyx) they show:

> Not by drag & drop, but it is possible with copy & paste. Just put the image in the clipboard and select Edit->Paste Special. LyX will then immediately open a "Save as" dialog, where you can specify where and under which name the image will be saved. However, you can also just press Enter to choose the selected name and path.

A plugin like this for Sublime Text would help a lot when [writing latex code](https://tex.stackexchange.com/questions/19176/how-to-insert-an-image-into-latex-document).

When the command is issue, it would:

1. Take the contents of the clipboard
1. Check whether it is an image.
1. Ask the user for a folder where to save the image, already suggesting the last used path and a name based on some information it can get as the current date and time.
1. Insert the image path on the cursor current position as:
```latex
\begin{figure}
\centering
        \includegraphics[totalheight=8cm]{images/verticalcell.eps}
    \caption{used by \citet[p.~4]{XXXXX}.}
    \label{fig:verticalcell}
\end{figure}
```

Originally posted on: [$28991](https://forum.sublimetext.com/t/a-command-to-paste-a-image-from-clipboard-to-the-code/28991) 

Related issues:

1. [sublime-evernote$24](https://github.com/bordaigorl/sublime-evernote/issues/24) Insert Image?
1. [forum$1965](https://forum.sublimetext.com/t/drag-and-drop-image-to-code/1965) Drag and drop image to code

**Comment by r-stein** [comment]
To clearify this: You want to paste the url of an image, then LaTeXTools should ask for a path, download the image into that folder, and insert that snippet.

**Comment by evandrocoan** [comment]
Yes. The best way is to open a quick panel:

![image](https://user-images.githubusercontent.com/5332158/27030908-69f5e02a-4f44-11e7-978e-3c3bf8909dc0.png)

On this example, I am pointing to the window's title where the image was taken. But I am not sure if this information is available.

But if not, then it is fine just to remember the last name used, updating the date and adding a sequence number, when suggesting the path name. Example, if I my last imagem was:
```
D:\latex_project\pictures\2017-06-12_07-52_A_command_to_paste_a_image.jpg
```
My next image would be suggested as:
```
D:\latex_project\pictures\2017-06-12_08-22_A_command_to_paste_a_image2.jpg
```

**Comment by r-stein** [comment]
Added in [prerelease](https://github.com/SublimeText/LaTeXTools/tree/st3-3.14.1#prereleases) `st3-4.0.0-alpha.2`
