### ISSUE TITLE
Ability to insert project already existent images command by a quick panel

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1156]
The issue [A command to paste a image from clipboard to the code?](https://github.com/SublimeText/LaTeXTools/issues/1154), covered by the pull request:

1. https://github.com/SublimeText/LaTeXTools/pull/1155 Added a command to smart paste images

Help a lot about inserting new images on latex files. However now it is missing the ability to insert already existent images on the project on the file. 

1. It would open a quick panel listing the project's existent images and would allow allow you to choose one of them.
1. Then it would insert them like:
```latex
\begin{figure}
\centering
        \includegraphics[totalheight=8cm]{images/verticalcell.eps}
    \caption{verticalcell}
    \label{fig:verticalcell}
\end{figure}
```

This feature is already present on the closed source package `Latexing`. On this question on StackOverflow this feature is explained at [Add file location (figure) in windows ST3](https://tex.stackexchange.com/questions/147526/add-file-location-figure-in-windows-st3).

> Using the package latexing (<http://www.latexing.com/>) and `\graphicspath{dir-list}` solved the problem.

> Install the Latexing plugin and configure it so that its working according to your needs.

> Keep the `screenshots` folder in the same directory as the `.tex` file.

> In the header of the document add: `\graphicspath{{Z:/screenshots/}, {Y:/path/to/dir/having/the/tex/file}}` 

> To include a file path in the document: press `ctrl+shift+l`, `ctrl+shift+l`. 
![enter image description here][1]

> You will be presented with a few options, select: "Fill Include Graphics Anywhere"; just start typing the file name, and click the one you've got to insert: 

![enter image description here][2]

> The path (`screenshots/backAnno/Screenshot-Done-1.png`) will be inserted at the cursor, and you are done now! 

  [1]: http://i.stack.imgur.com/usEaL.png
  [2]: http://i.stack.imgur.com/Vrwih.png

**Comment by r-stein** [comment]
This is already possible via the fill-all helper. If you are inside `\includegraphics[totalheight=8cm]{|}` you can press C-l, C-f and will get a popup to insert an image. This does also support graphicspath in the prereleases.

**Comment by evandrocoan** [comment]
Thanks, but it requeres to insert this `\includegraphics[totalheight=8cm]{|}` and then it only auto complete the file name. My suggestion is to allow the user from nowhere request for the filling, then it would insert a snippet within the completion chosen. For example, if I select the image `Image.png`, it would insert:
```latex
\begin{figure}
\centering
        \includegraphics[]{Image.png}
    \caption{Image}
    \label{fig:Image}
\end{figure}
```

**Comment by r-stein** [comment]
While I see your point, I don't think we should implement the same functionality twice and first letting the user insert a figure snippet end then calling fill-all helper just seems to be a better general solution approach than adding a feature to do it in a different order. We may think about a option to hook into the auto completion and snippet mechanism and optionally call the fill-all helper in those cases.

However you can just install Chain of Command and add the following keybinding. Then write fig and press `tab`. This will insert the snippet and then call fill-all helper.

```js
    {
        "keys": ["tab"],
        "command": "chain",
        "args": {
            "commands": [
                ["delete_word", {"forward": false}],
                ["insert_snippet", {"contents": "\\begin{figure}\n\\centering\n\\includegraphics[$2]{$1}\n\\caption{Image}\n\\label{fig:$3}\n\\end{figure}"}],
                ["latex_fill_all"]
            ]
        },
        "context":
        [
            { "key": "selector", "operand": "text.tex.latex" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "\\bfig$" },
        ],
    },
```

**Comment by evandrocoan** [comment]
Thanks for the time!  

I see using Chain of Command does has the same effect, therefore there is no reason for adding it here.
