### ISSUE TITLE
no bib files founds from inclued tex file

### ISSUE THREAD

**Issue by hughhugh** [SublimeText/LaTeXTools#1172]
Hi,  I am using latextools in sublime, but I met some problems when citing references.

The `thesis.tex` is the main tex file and the bib file is inserted in using` \addbibresource{bib/thesis.bib}`. 
In `thesis.tex` file, I can using `\cite{} ` successfully with the help of the hint. The printscreen is as the following.
![image](https://user-images.githubusercontent.com/9352717/28019354-45528fea-65b3-11e7-8d7f-c2cc957b6cd4.png)
In the sub tex file inclued in thesis.tex, for example,` \include{tex/chapter05}`. When I using `\cite{}` command as I did in thesis.tex,  the info"bib files not found" occurs. 
![image](https://user-images.githubusercontent.com/9352717/28019407-6cf13a60-65b3-11e7-88b9-bc6d409e1118.png)
![image](https://user-images.githubusercontent.com/9352717/28019564-f7f0f8e4-65b3-11e7-8e66-08fe9488f8fc.png)
So, how can I deal with this issue? Thank you.

Ps: I am using Overleaf to write my thesis, too. I can cite reference in "chapter05.tex" successully. 
![image](https://user-images.githubusercontent.com/9352717/28019668-4944225c-65b4-11e7-9775-ae61bace044c.png)

**Comment by r-stein** [comment]
You need to add `% !TEX root = ../thesis.tex` at the top of you included documents. See: https://latextools.readthedocs.io/en/latest/features/#multi-file-documents

**Comment by hughhugh** [comment]
@r-stein  Thank you very much for your help. It works now. It is so great!

**Comment by macwu1992** [comment]
@r-stein it works for me too, thanks a lot!
