### ISSUE TITLE
Setting "show_errors_phantoms" doesn't work on project file.

### ISSUE THREAD

**Issue by jelther** [SublimeText/LaTeXTools#1173]
Hi,

I got one project and I'm trying to set the option "show_error_phantoms" to "none" in a project setting but I couldn't.

`"settings":
	{
		"highlight_build_panel": true,
		"hide_build_panel": "never",
		"show_error_phantoms": "none",
}`

Isn't this enough to stop the warnings inline the file ?

Thanks!

**Comment by r-stein** [comment]
The error phantoms are currently not supported per project, only in your LaTeXTools - User settings.

**Comment by jelther** [comment]
@r-stein , maybe it's a good idea to point out this in documentation. It's not clear there.

Thanks!
