### ISSUE TITLE
Equation preview in Markdown files

### ISSUE THREAD

**Issue by hsiktas** [SublimeText/LaTeXTools#1174]
There are several ways [1] to include LaTeX equations into simple Markdown files. This is great for ad-hoc math notes without the need of having a sane .tex template document at hand.
It would be great if LaTeXTools would recognize math blocks in markdown files and display its equation previews inline.

[1] https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by r-stein** [comment]
No, we are not looking forward to support markdown or add markdown features. In addition this requires a whole new syntax definition. However if someone writes/changes the markdown syntax accordingly (`text.tex.latex` in the main scope and the corresponding math scopes) it will be supported automatically.

**Comment by ig0774** [comment]
Closing as this is out of scope for this project.

**Comment by eric-wieser** [comment]
>It will be supported automatically.

That's not true without #1438. I was able to get this working locally with that in place.
