### ISSUE TITLE
Unlimited math preview cache size?

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1181]
I have looked up in ``LaTeXTools.sublime-settings'', but failed to find an entry for cache size. In fact, the cache in my case exceeds 3GB. 

So, how do I control the cache size? 

Thank you so much for your help ahead of time.

**Comment by r-stein** [comment]
There is an [entry in the advanced settings](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.1/LaTeXTools%20(Advanced).sublime-settings#L128), which limits it to 50 MB.

**Comment by r-stein** [comment]
Can you run in the LaTeXTools console (``ctrl+` ``) and check whether the files are deleted:

```py
from LaTeXTools.st_preview.preview_utils import try_delete_temp_files; from LaTeXTools.latextools_utils import cache; import os; name = "preview_math"; temp_path = os.path.join(cache._global_cache_path(), name); try_delete_temp_files(name, temp_path)
```

**Comment by r-stein** [comment]
Thanks, this will be fixed in the next release.

**Comment by Romeoly** [comment]
@r-stein Thank you so much, it works fine with me.
