### ISSUE TITLE
Reverse search with Okular does not work

### ISSUE THREAD

**Issue by danielleontiev** [SublimeText/LaTeXTools#1183]
I've configured Okular with option `subl "%f:%l"` but when I ctrl+click in it nothing happens

**Comment by JackGin** [comment]
Please add %c and try shift+click instead.

**Comment by r-stein** [comment]
Do you can start sublime text by wrinting `subl` in the shell?

**Comment by ig0774** [comment]
Another thing: if you have a `subl` script but it's in `/usr/local/bin`, you may need to use the full path, e.g. `/usr/local/bin/subl`.

**Comment by danielleontiev** [comment]
@JackGin where should I add `%c`? Instead of `%f`?

**Comment by danielleontiev** [comment]
@r-stein yes I can, `subl` is in `/usr/bin/subl`. @ig0774 `/usr/bin/subl` is the only instance of `subl`. Adding it in okular settings i.e. `/usr/bin/subl "%f:%l"` does not work

**Comment by JackGin** [comment]
I would write /usr/bin/subl "%f:%l:%c" in okular settings. Please correct me if I am wrong, but this is the string I use, and not without success. 
But the main point is to use shift+click instead of ctrl+click with okular.

**Comment by danielleontiev** [comment]
@JackGin does not work for me

**Comment by JackGin** [comment]
No idea then, sorry. It works for me in openSUSE.

**Comment by danielleontiev** [comment]
@JackGin I found it. Regardless of `%c` in command it works with Shift+click and works only with "Browse" tool, but earlier I tried "Text selection tool"

**Comment by JackGin** [comment]
Indeed, I forgot to mention the choice of the browse tool.
