### ISSUE TITLE
Why we use the different panel output.latextools instead of output.exec?

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1185]
```javascript
	// Show panel
	{ "keys": ["shift+escape"],
		"context": [
			{"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
			{"key": "panel_visible", "operator": "equal", "operand": false }],
		"command": "show_panel", "args": {"panel": "output.latextools"}},
```

Related issues:

1. https://github.com/SublimeText/LaTeXTools/issues/869 Show build results not working (grayed out in menu) with or without enabling phantoms/coloring of build panel

**Comment by r-stein** [comment]
We use a different panel, because we add syntax highlighting to the ouput. This highlight should obviously not apply to different executions.

**Comment by evandrocoan** [comment]
Thanks!
