### ISSUE TITLE
Autocomplete suggestions in list cut off with ...

### ISSUE THREAD

**Issue by Dxhs** [SublimeText/LaTeXTools#1188]
The suggestions in the list are cut off too early to see what the suggestions actually are. Is this related to latextools or sublime?

![spectacle s12818](https://user-images.githubusercontent.com/13475068/28996572-a579e21a-7a03-11e7-8633-ea9ef7cb48af.png)

![spectacle n12812](https://user-images.githubusercontent.com/13475068/28996611-607f2e26-7a04-11e7-9883-a5ef334ed71d.png)

**Comment by r-stein** [comment]
It something beween, we append whitespaces to get a minimal width [here](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.0/latex_cwl_completions.py#L528) to fix an other issue, but this is badly handled by ST. We may just remove that.

**Comment by Dxhs** [comment]
> we append whitespaces

Tried changing the theme and color scheme to Spacegray Theme and it went back to normal. Used Brogrammer Theme before, and it applied wide bold characters to the list.
