### ISSUE TITLE
Spell Check For References, Citations

### ISSUE THREAD

**Issue by allenryb** [SublimeText/LaTeXTools#1189]
When I cite theorems in some references, the following trivil code will help me do it
![cite2](https://user-images.githubusercontent.com/6965371/29000545-47ad1834-7aa1-11e7-96f4-66f23eec16a3.jpg)

But as you see, the label `kroncke2013stability` is checked and highlighted as a mistyping word. 
I want the spell-check skip it.
This problem also happens for the citations in the theorem environment.

![ref](https://user-images.githubusercontent.com/6965371/29000594-32088300-7aa2-11e7-9942-cd1c9171980e.jpg)

Is there any method to disable spell-check for these two cases? 

The previous issue #677 has discussed some similar problems by `spelling_selector`. But I still couldn't modify the code to fix my problem.

Thank you!

**Comment by r-stein** [comment]
In general the content of `\ref` and `\cite` is not spellchecked, but if you have it inside brace `[]` it is, because there is not recognized by the syntax definition.
You may add `- meta.group.brace"` to not spellcheck the content of braces, i.e. create a file `LaTeX.sublime-settings` inside the user folder (to only apply it to LaTeX files with/add the content:
```js
{
    "spelling_selector": "- meta.group.brace -(comment, source, constant, keyword, storage, support, variable, markup.underline.link, meta.tag, meta.preamble, meta.include, meta.function.citation, meta.function.reference, meta.function.label, meta.function.includegraphics)",
}
```

**Comment by allenryb** [comment]
Thank you very much! @r-stein 
Your code works for me, except that `meta.group.brace` is replaced by `meta.group.bracket`, since the scope is `text.tex.latex meta.group.bracket.latex`.

**Comment by r-stein** [comment]
Thanks, yes that's what I meant :)
