### ISSUE TITLE
Get \psfragfig to behave like \includegraphics

### ISSUE THREAD

**Issue by dfridline** [SublimeText/LaTeXTools#1190]
I mostly include images through the \psfragfig command rather than the \includegraphics command so as to include LaTeX replacements of figure tags in my EPS files.  Is there a way to get LaTeXTools to recognize this command and bring up a list of acceptable figure files in the project to insert like it does with the \includegraphics command?

**Comment by r-stein** [comment]
Yes, we have an entry for this in the [advanced settings](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.1/LaTeXTools%20(Advanced).sublime-settings#L149). You can just copy the whole setting entry and add one for psfragfig.

**Comment by dfridline** [comment]
Thanks - that worked like a charm.
