### ISSUE TITLE
show_panel on shitf+esc does not hide the current open panel

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1191]
Why would it not hide the active panel?
```javascript
	// Show panel
	{ "keys": ["shift+escape"],
		"context": [
			{"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
			{"key": "panel_visible", "operator": "equal", "operand": false }],
		"command": "show_panel", "args": {"panel": "output.latextools"}},
```

**Comment by r-stein** [comment]
You hide the panel with `escape` and can re-open it with `shift+escape`. Is you question about the context that it does not work if an other panel is visible? I think it just tries to be less aggressive.

**Comment by evandrocoan** [comment]
Well, the context also get me bothered a little, however it does make sense. As it is I can have another build panel for another language using the `shift+esc`. Though, when I am focused on the search panel, I think it would block from the panel to be called as I am not on a latex view.

But I what draw most my attention was the panel not opening when I had another panel as the search panel open. I kept trying to open it with `shitf+esc`, but it simply just don't show up, until I realize the search is open and I had to press `esc, shift+esc`.

Well, I can just use chain of command and call `hide_panel` before attempting to open the build panel.

**Comment by evandrocoan** [comment]
I end up removing it on my fork:

1. https://github.com/evandrocoan/LaTeXTools/commit/635b0c7c7ce525d861b23b21767b7adcca1718a9 Replaced the output.latextools panel by the default output.exec
1. https://github.com/evandrocoan/LaTeXTools/commit/7dc8ea5a77f4415d20a2b738f0ad9909d0a3a1e3 Make the output.latextools panel not read only
