### ISSUE TITLE
Build tries to run texify although it isn't installed

### ISSUE THREAD

**Issue by dahanbn** [SublimeText/LaTeXTools#1200]
I am new to ST3 and LaTeXTools and try to build a single tex file.

The check recognises that I use TeXLive and don't have texify from MikTeX. Despite that the build command tries to run texify. How can I change that behaviour?

I am on Windows 10 Home 64-bit, ST3 64bit, TeX Live 2017 32 bit

I guess it should be simple, but I haven't figured it out.

LaTeXTool check status provides the following output:

    Variable  Value
    --------  -----
    PATH      D:\Python36\Scripts\;D:\Python36\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS     Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA     Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine     Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine     Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program     Files\SumatraPDF\;C:\Program Files (x86)\Pandoc\;C:\Program Files\Git\cmd;D:\texlive\2017\bin\win32
    
    Program      Location                                          Status            Version
    -------      --------                                          ------            -------
    sublime      C:\Program Files\Sublime Text 3\sublime_text.exe  available         Sublime Text Build 3142
    texify                                                         missing           unavailable
    pdflatex     D:\texlive\2017\bin\win32\pdflatex.exe            available         pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX)
    xelatex      D:\texlive\2017\bin\win32\xelatex.exe             available         XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/W32TeX)
    lualatex     D:\texlive\2017\bin\win32\lualatex.exe            available         This is LuaTeX, Version 1.0.4 (TeX Live 2017/W32TeX)
    biber        D:\texlive\2017\bin\win32\biber.exe               available         biber version: 2.7
    bibtex       D:\texlive\2017\bin\win32\bibtex.exe              available         BibTeX 0.99d (TeX Live 2017/W32TeX)
    bibtex8      D:\texlive\2017\bin\win32\bibtex8.exe             available         This is 8-bit Big BibTeX version 0.99d
    kpsewhich    D:\texlive\2017\bin\win32\kpsewhich.exe           available         kpathsea version 6.2.3
    convert                                                        restart required  unavailable
    ghostscript                                                    missing           unavailable
    
    Builder  Status
    -------  ------
    basic    available
    
    Builder Setting  Value
    ---------------  -----
    display_log      False
    linux            {}   
    osx              {}   
    windows          {}   
    
    Viewer   Status     Location
    ------   ------     --------
    sumatra  available  C:\Program Files\SumatraPDF\SumatraPDF.exe

**Comment by r-stein** [comment]
There is a [setting](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.1/LaTeXTools.sublime-settings#L222) for that. Just change the `distro` to `texlive`.

**Comment by dahanbn** [comment]
Thanks, it was that easy. Sorry for bothering you.
