### ISSUE TITLE
Feature request (?) : open every relevant TeX file

### ISSUE THREAD

**Issue by skilveg** [SublimeText/LaTeXTools#1202]
In my current workflow, it would be very useful to be able to open all TeX files whose path is a substring of the TeX file I'm currently working on. For instance, if I'm working on a file, say named 'main.tex', containing lines such as

> `    \input{../../spam/egg.tex}`
> `    \input{../bacon.tex}`

I would really like to have a way to open, in new tabs of ST, both files which relative path is contained in the 'input' command.

Is there already a way to do such a thing ? If not, would it be possible to add it ?

Thanks in advance.

**Comment by r-stein** [comment]
If you have you caret inside the `\input{...}` commands and press `C-l,C-o` the file will be opened in a new tab (and also created if it does not exists already). This also works with multiple-selections, so you may select `\input` and press `alt+f3` or `C-d` a few times and then `C-l,C-o` to open several included files.

Is this your request or do you want a command to open all files, which are included to create the tex document? This is currently not supported, but I may add it if also other people consider this to be desirable.

**Comment by r-stein** [comment]
PS. You can also navigate all sections in the document via `C-shift-r`

**Comment by skilveg** [comment]
Your shortcuts don't seem to work on my version, even if I complete the file names with the  `.tex` extension, or if said files are in the current working directory. `C-o` only opens a window listing all files in the current directory. Is it normal ? (I work with ST2.)

**Comment by r-stein** [comment]
You first press `C-l` and then `C-o` this should also work in ST2 (you should switch to ST3 nonetheless, because it has more features and we won't release new versions for ST2).
Pressing `C-o` opens the file finder, that is normal.

**Comment by skilveg** [comment]
Ok, I now understand why this key combination doesn't work in my folder : the absolute path contains Unicode accented characters. More precisely, the log reads
>`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 43: ordinal not in range(128)`
>`Exception KeyError: (u'/[...]\xe9e/[...].tex',) in <bound method LocalCache.__del__ of <latextools_utils.cache.LocalCache object at 0xaea1d0c>> ignored`
I know putting accents in folder names is bad practice but my path system is old, I have several version control tools currently running on it, and correcting it on my side would be a real drag.

Would it be possible to enable Unicode characters for this particular feature ?

**Comment by r-stein** [comment]
> Would it be possible to enable Unicode characters for this particular feature ?

It should and does work on ST3. I don't we will fix such issues for ST2, because they are not so common and most people switched to ST3.

**Comment by skilveg** [comment]
Thanks for the advice, it works indeed in most cases on ST3. However, when I select a file name situated in the shebang in the first line of a TeX file (of the form `%!TEX root = blah.tex`), nothing seems to happen. Is it still normal ?

**Comment by r-stein** [comment]
Yes this commands only works for `\input` and similar (`\input`/`\import`) commands. You can also open the file in the root directive via `C-l, C-j`, but this does not work with multiple-selections.
Documentation of this feature:
https://latextools.readthedocs.io/en/latest/keybindings/#jump-to-anywhere
