### ISSUE TITLE
TEXINPUTS?

### ISSUE THREAD

**Issue by dpo** [SublimeText/LaTeXTools#121]
Sorry if this is a RTFM but I could not find an answer. I have class and style files in nonstandard locations. Those locations are collected in my `TEXINPUTS` environment variables but ST2 (and LaTeX-Tools) aren't aware of it (I checked in the console.) Is there a config option to set the paths of class and style files?

Thanks!

**Comment by 5chdn** [comment]
This would be a great feature. However, I understand that this is an upstream design issue with Latex itself. Using environment variables to tell latex where to look for additional files is just annoying in so many cases. 

It would be great to have a way to set this up in latextools user preferences somehow.

**Comment by r-stein** [comment]
You can set environment variables in the LaTeXTools settings, which will be injected before running the builder. For example:

``` js
"builder_settings" : {
    "windows" : {
        "env": {
            "TEXINPUTS": "your/tex/inputs"
        }
    },
},
```

**Comment by 5chdn** [comment]
Cool. this pretty much solves this issue.

**Comment by ig0774** [comment]
Closing as we do have a solution for this.
