### ISSUE TITLE
LatexTolls doesn't run texcount.exe 

### ISSUE THREAD

**Issue by faridcher** [SublimeText/LaTeXTools#1213]
Running the texcount on my current .tex file produce the following error in ST3 console:

> "'C:\Program Files\MiKTeX 2.9\miktex\bin\x64\texcount.EXE' -total -merge -utf8 cheetah_env.tex"
error: Error while running TeXCount: texcount.EXE: The script interpreter could not be found.
texcount.EXE: Data: scriptInterpreter="perl.exe"

I have already installed the Perl and running the above command in cmd works fine.

**Comment by faridcher** [comment]
I found the solution. Although I had perl in my `path` environmental variable, I had to also include it in the `texpath` variable in the `LatexTools` preferencee:

```
"texpath" : "C:\\Program Files\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Perl64\\bin;C:\\Program Files\\ImageMagick-7.0.6-Q16",
```

This solved the problem.

**Comment by r-stein** [comment]
You also need to restart Sublime Text or your computer to propagate the update on the path variable.
