### ISSUE TITLE
{, [ and ( not working

### ISSUE THREAD

**Issue by davidgontier** [SublimeText/LaTeXTools#1215]
Hello everyone,

I am using LatexTools almost daily (thank you for your work), and I just ran into a new problem. I can no longer open brackets... Here is what I can/cannot do.
1/ First, open a new ST3 file, check that {,(,[ works fine
2/ Save your file as anything.tex
3/ It no longer works! The touch {, ( and [ are no longer responding.
4/ Now for the fun part, put the cursor between two apostrophes, and it works again!

A friend of mine also using ST3 has the same problem (our installation is similar though). Any idea where this problem may come from?

**Comment by r-stein** [comment]
Open the ST console ``ctrl+` `` and paste `sublime.log_commands(True)` then try to insert the characters again and check the console output. You may also check your keybinding whether you have bound those keys.

**Comment by davidgontier** [comment]
Now it is working (and for my friend too), but I didn't modify anything. Clearly LatexTools was not the culprit (sorry for that). Anyway, thank you for the useful tip.
