### ISSUE TITLE
How to capitalize the first letter in new sentences

### ISSUE THREAD

**Issue by Iorent** [SublimeText/LaTeXTools#1217]
I am using Sublime + Latex. I was constantly in trouble with the upper case problem. In MS Word, the first letter of each sentence can be changed to upper case automatically. I am wondering if Sublime can do this too. Or, what kind of plug-in can do this work?

**Comment by r-stein** [comment]
You can say "If I press a character preceded by a dot it should be inserted uppercase", but I don't know whether this is such useful in the context of LaTeX, because it has a more complicated structure than just plain text. However I can provide such a solution later and if other users also want to have this integrate is as opt-in to LaTeXTools.

**Comment by r-stein** [comment]
Open *Tools > Developer > New Plugin...*, paste, and save in the (default provided) User directory:

```py
import sublime_plugin


class InsertUppercaseCommand(sublime_plugin.TextCommand):
    def run(self, edit, character=""):
        self.view.run_command("insert", {"characters": character.upper()})
```

Open your keybindings and add this keybinding (you may change the selector to also enable it in other languages):

```js
    {
        "keys": ["<character>"],
        "command": "insert_uppercase",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex" },
            { "key": "preceding_text", "operator": "regex_contains", "operand": "\\.\\s*$" },
        ],
    },
```

**Comment by Iorent** [comment]
While I am not using sublime for coding work, I am using sublime+latex for writing paper. I presume that there are many users just like me. I have to constantly shift from upper case to lower case, it is annoying. Since I am not computer master, can you just explain the steps more clearly? Thanks.

**Comment by r-stein** [comment]
In the (top) main menu you select *Tools > Developer > New Plugin...*. This will open a new unsaved file. You replace the content of that file with the quoted your code and save the file under an arbitrary name, e.g. `insert_uppercase.py` in the directory which is suggested by default.

Afterwards you select *Preferences > Key Bindings* and paste the keybinding between the brackets on the right side. If you also want to enable it in other text file you can change the selector from `text.tex.latex` to just `text`.

**Comment by Iorent** [comment]
This worked!!! Thanks, buddy. You just save me a lot of work. For someone like me who is using latex for paper or book, this is amazing.

**Comment by Iorent** [comment]
This works great, yet I found a little bug. For example, I usually use "i.e.", because there is a dot before "e", so the word automatically becomes "i.E.". Tha same thing will happen with "p.s.", and the like. I am wondering if you can specify some exceptions that the letter after the dot will not change into upper case?

**Comment by ig0774** [comment]
Maybe instead of a bunch of exceptions, it's easier to change this line (in the **Keybindings** file) from:

```json
{ "key": "preceding_text", "operator": "regex_contains", "operand": "(?:^|\\.)\\s*$" },
```

to:

```json
{ "key": "preceding_text", "operator": "regex_contains", "operand": "(?:^|\\.)\\s+$" },
```

That way it will auto-capitalise when you type `. Blah blah blah`, but not when you type `e.g.`, etc.

**Comment by Iorent** [comment]
Actually, I know some basic coding. And, I can tell there are some tiny differences in function between "s*$" and "s+$". Can you tell me more about the function of "*" and "+"?

**Comment by r-stein** [comment]
These are regular expressions (you can just google a tutorial for that):

- `(?:^|\\.)` means at the start of the line (`^`) or (`|`) behind a point (`\\.`)
- `\\s*` means zero or more spaces
- `\\s+` means one or more spaces
- `$` means the end if the string, which is the position of the caret in this case

You could alternativly add an additional context to blacklist your examples, e.g. "It should not be preceded by a single character and a point":

```js
{ "key": "preceding_text", "operator": "not_regex_contains", "operand": "\\b\\w\\.$" },
```

**Comment by Iorent** [comment]
Thanks for the advice!
