### ISSUE TITLE
Go to definition F12

### ISSUE THREAD

**Issue by faridcher** [SublimeText/LaTeXTools#1220]
Is it possible to enable the more universal <kbd>F12</kbd> as the keybiding for the "Jump/Go to definition/anywhere" which is currently set to <kbd>ctrl+l+j</kbd>. Since this keybinding is hard-coded I can't customize it throughout the ST3!

thanks

**Comment by r-stein** [comment]
You can just add this keybinding to your user keybindings:

```js
    {
        "keys": ["f12"],
        "command": "jumpto_tex_anywhere",
        "context": [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }
        ],
    },
```
