### ISSUE TITLE
$file_path in script builder missing backslashes on windows

### ISSUE THREAD

**Issue by DrBones** [SublimeText/LaTeXTools#1222]
I am trying to get a custom script builder with a make file to work and as soon as I try to pass the $file_path parameter it breaks.

It looks like it is due to the missing backslashes in the cmd execution. When I set the script builder to be a simple "echo $file_path" the following output is produced
![image](https://user-images.githubusercontent.com/212259/30508140-03f63f80-9a90-11e7-812a-49a6780c5644.png)

I tried looking into the call of the cmd but since it looks fine in the self.display() call from within script_builder.py I do not know where the backslashes get lost.

I can work around this by hardcoding my paths for now but this would be awesome if I were to move the diretory to another computer.

Thanks in advance and for this amazing package!

**Comment by ig0774** [comment]
Thanks for the report. I'll have a look into this. There probably is an escaping issue.

**Comment by ig0774** [comment]
As a work-around, it seems you can just add quotation marks around the parameter to get it passed properly, e.g.,

```
"make \"$file_path\""
```

In any case, the underlying issue will be fixed in the next release.

**Comment by DrBones** [comment]
Cool, thanks for the quick reply!

I tried some of the escaping I could think of but not escaped quotes :)
This works for me now, looks strange but I only need to do that once. That also explains why I had to use forward slashes in the absolute path to my make executable!

Have a great sunday.

**Comment by r-stein** [comment]
A [prerelease](https://github.com/SublimeText/LaTeXTools#prereleases) is out. You may enable that to get the latest features and also this bugfix.
