### ISSUE TITLE
BibTeX snippets

### ISSUE THREAD

**Issue by dpo** [SublimeText/LaTeXTools#123]
Thanks for a great project. One this I was missing is Emacs-style BibTeX snippets, complete with all optional fields in all entry types. I wrote a similar set of snippets for ST2 here: https://github.com/dpo/sublime-bibtex

It'd be great if those could be integrated into LaTeXTools.

Cheers.

**Comment by ig0774** [comment]
I realise this is a very long time coming, but we now have support for snippets and some autocompletion for additional fields.
