### ISSUE TITLE
Equation and image preview bug

### ISSUE THREAD

**Issue by myillusion3852** [SublimeText/LaTeXTools#1243]
When I install LatexTools, the equations and image can not be previewed.
The report is as the pic.
How should i deal with it?
![tim 20171007155631](https://user-images.githubusercontent.com/3262317/31305960-2e583f64-ab78-11e7-89e6-2f0d6c0b0133.png)
![tim 20171007155652](https://user-images.githubusercontent.com/3262317/31305959-2e57e334-ab78-11e7-83cc-477d6ae0dcf5.png)

**Comment by r-stein** [comment]
If you click on show report this should contain a latex file. Just create a new file, copy the content and try to compile that. That should give you more information about the problem.

**Comment by myillusion3852** [comment]
I have tried as your method, and the report is same.
![tim 20171007164919](https://user-images.githubusercontent.com/3262317/31306303-887933e8-ab7f-11e7-943e-bc5fc62a8174.png)

**Comment by r-stein** [comment]
Oh sorry I didn't read the error carefully enough. The problem is not with the compilation, but with ghostscript. This seems to have a problem with the ghostscript, which is installed by texlive on windows, so you can manually install ghostscript to fix it.

https://github.com/SublimeText/LaTeXTools/issues/1148#issuecomment-308126813

**Comment by myillusion3852** [comment]
Thank you very much! I have deal with this problem.
At the beginning, I use texlive under windows. And then, I change to miktex. The equation and image could be previewed. Although the problem is solved, i still do not know why.

**Comment by myillusion3852** [comment]
The ghostscript may be the problem.

**Comment by r-stein** [comment]
The problem is solved, because the reason for the problem was, that the ghostscript installation did not work correctly. As you can see the path and hence the used installation of ghostscript changed.
