### ISSUE TITLE
math preview stops working. 

### ISSUE THREAD

**Issue by xiaoweiz** [SublimeText/LaTeXTools#1249]
ST 3149/OSX Sierra

the error message is 
```
mdpopups: Failed to convert/retrieve scheme to CSS!
```

**Comment by r-stein** [comment]
Try press ctrl+shift+p and run *Package Control: Satisfy dependencies*.

**Comment by xiaoweiz** [comment]
```python
Package Control: The dependency 'mdpopups' is installed, but out of date; upgrading to latest release 3.0.3 from 3.0.2...
reloading settings Packages/mdpopups/Preferences.sublime-settings
Package Control: The dependency 'mdpopups' has successfully been installed or updated
Package Control: All dependencies have been satisfied
mdpopups: Failed to convert/retrieve scheme to CSS!
```

**Comment by r-stein** [comment]
Restart ST after updating the dependencies.

**Comment by xiaoweiz** [comment]
It still doesn't work, unfortunately.

**Comment by xiaoweiz** [comment]
In fact, the preview doesn't work for the inline equations. But for displays (e.g., \[\]), the preview _partially_ works: the same error message still pops up, but there is a very light image appears as shown in the following. 
<img width="345" alt="screen shot 2017-10-24 at 3 04 56 pm" src="https://user-images.githubusercontent.com/4540215/31928961-9dc4caaa-b8cc-11e7-987f-6dd2e97668f0.png">

**Comment by r-stein** [comment]
It seems that the color detections (which is based on the color scheme) does not work for some reason, but you can just manually set the [color in the settings (`"preview_math_color": "#FFFF00"`)](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.2/LaTeXTools.sublime-settings#L119).
That inline equations does not work is based in the design, but you can just change [a setting (`"preview_math_scope": "text.tex.latex meta.environment.math",`)](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.2/LaTeXTools.sublime-settings#L107) to also enable them. We had some issues to enable it and some to disable it, so it's just a personal preference.

**Comment by xiaoweiz** [comment]
Great! Thanks for the prompt reply. I haven't used the preview function for a while and wasn't aware of `preview_math_scope`.

**Comment by r-stein** [comment]
No problem.
