### ISSUE TITLE
The default builder cannot be selected as pdflatex. It always runs with xelatex.

### ISSUE THREAD

**Issue by jialunliu** [SublimeText/LaTeXTools#1250]
Hi,

I find the tex file cannot be complied with the traditional builder (pdfLaTeX) even if I have selected "builder" as "traditional" and put "%!TEX program = PdfLaTeX" in the beginning of the tex file. It always complies with xelatex. Does anyone have an idea about this? I have reinstalled LaTexTools several times.

Cheers,
Jialun

**Comment by r-stein** [comment]
Try to press ctrl+shift+b and select *LaTeX* or *LaTeX - Traditional* or *LaTeX - PdfLaTeX*

**Comment by jialunliu** [comment]
Thank you so much. The problem has been solved. Cheers.
