### ISSUE TITLE
Having trouble with first build

### ISSUE THREAD

**Issue by HenryZhou7** [SublimeText/LaTeXTools#1254]
I followed the installation guide. But when I press cmd + b, there is a window popping up and it gives me the following error. I don't have a top.tex file in my directory my desired tex file is main.tex It wouldn't build for some reason. Can someone help over here? Thanks in advance.

```
pdflatex top.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `top.tex'.
<*> top.tex
           
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
```

**Comment by r-stein** [comment]
Do you have any other LaTeX packages, because this does not look like the output from our builders?

**Comment by HenryZhou7** [comment]
Yes. I used Texshop some while ago and have just decided to switch to LatexTools. Should I just delete everything else?

**Comment by r-stein** [comment]
No I mean other Sublime packages for LaTeX not other programs. Try to press ctrl+shift+b and select *LaTeX - Traditional*.

**Comment by HenryZhou7** [comment]
Okay. I think it is working now! Thank you so much!
