### ISSUE TITLE
Entries from .bib file won't show with \addbibresource

### ISSUE THREAD

**Issue by joaocandre** [SublimeText/LaTeXTools#1260]
I have started using the **biblatex** package, specifying my .bib file with `\addbibresource{}` and printing the bibliography with `\printbibliography`, and every time I call `\cite` I no longer get the list of bib entries in the bib file, instead I get warned that 

> No bib files found! 

However, if I instead specify my bib file with `\bibliograhy{}` I do get the reference list, but I want to avoid that as it causes conflicts with the **biblatex** package.

**Comment by ig0774** [comment]
LaTeXTools definitely works with `\addbibresource`—I use it myself all the time. You may need to clear the cache (run the **LaTeXTools: Clear Document Cache** command from the command palette).

I'd also note that `\bibliography` should work perfectly fine with **biblatex** though it may give you a warning.

**Comment by joaocandre** [comment]
Then there must something wrong with my setup/config as even after clearing the cache or temp files I still get the same error message. Also, `\bibliography` does not generate a warning, but at an actual error:

> Can only be used in the preamble

I'm using XeLaTeX, not sure if that's related?

**Comment by ig0774** [comment]
Hmmm... I guess you may need to move the `\bibliography` command to the preamble. What does your `\addbibresource` command look like?

**Comment by joaocandre** [comment]
I am not using `\bibliography` anymore, I was using that before I started using **biblatex**. 

Relevant part of my preamble:

> \usepackage[style=authoryear,
            bibstyle=authoryear,
            citestyle=authoryear,
            maxcitenames=2,
            maxbibnames=5,
            natbib=true,
            hyperref=true,
            backref=true,
            abbreviate=true,
            doi=false,
            isbn=false,
            url=false,
            backend=bibtex]{biblatex}

> \addbibresource{refs}

and then at the end of my document:

> \addbibresource{refs}

**Comment by joaocandre** [comment]
The issue was the I need to use the complete .bib file name with `\addbibresource` "refs.bib" instead of just "refs". The same is not required with `\bibliography`, so I was not considering that.
