### ISSUE TITLE
Compiling .tex files

### ISSUE THREAD

**Issue by anihamde** [SublimeText/LaTeXTools#1272]
I've tried compiling the simplest .tex files via the build command, but I invariably run into a compilation error:

TraditionalBuilder: Engine: pdflatex. Invoking latexmk... 

COULD NOT COMPILE!

Attempted command:latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 xxxtent.tex
Build engine: Traditional Builder

The .tex file consisted of:

\documentclass{article}

\begin{document}
Hello!
\end{document}

Can anyone help with this?

**Comment by r-stein** [comment]
Have you installed a tex distribution? E.g. Texlive

**Comment by anihamde** [comment]
I’ve installed latexmk and miktex

**Comment by r-stein** [comment]
Press *ctrl+shift+p* and run *LaTeXTools: Check System* to check that LaTeXTools also sees everything it needs. If you use miktex it should by default use texify so you can also check your settings (*Preferences > Package Settings > LaTeXTools > Settings - User*), that you have indeed set miktex as your distro.

**Comment by anihamde** [comment]
So I'm getting latexmk as missing, but I ran sudo env PATH="$PATH" tlmgr install latexmk, and I'm getting that latexmk is already present.

**Comment by anihamde** [comment]
I think I reset my settings in preferences, and it now works; I'm guessing something to do with PATH configuration, but I'm not sure. In any case, I'm wondering how to alter the build to only compile into PDF rather than multiple file types.
