### ISSUE TITLE
A .bib-parsing problem

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1273]
When I type `\cite{', the popped-up preview for 

```bibtex
@article {MR2683777, 
    AUTHOR = {Boutet de Monvel, Anne and Kotlyarov, Vladimir P. and
              Shepelsky, Dmitry and Zheng, Chunxiong},
     TITLE = {Initial boundary value problems for integrable systems:
              towards the long time asymptotics},
   JOURNAL = {Nonlinearity},
  FJOURNAL = {Nonlinearity},
    VOLUME = {23},
      YEAR = {2010},
    NUMBER = {10},
     PAGES = {2483--2499},
      ISSN = {0951-7715},
   MRCLASS = {37K15 (35Q55 37K20 37K45 65M06)},
  MRNUMBER = {2683777},
MRREVIEWER = {Dmitry E. Pelinovsky},
       URL = {https://doi.org/10.1088/0951-7715/23/10/007},
}
````

produces a lot of `???`

I guess it is because of the trailing ":" in the TITLE line, because when I changes ":" to something else like ":a", it works fine. 

Thank you.

**Comment by ig0774** [comment]
You can try setting the `bibliography` setting to `new`, which (hopefully) addresses this. Unfortunately, we're unlike to change things for the `traditional` bibliography, as it works for most cases and performs quite a bit better.

**Comment by Romeoly** [comment]
@ig0774 Your comment helps a lot and thank you very much.
