### ISSUE TITLE
Does latextools support autocomplete images under a sibling directory?

### ISSUE THREAD

**Issue by jdhao** [SublimeText/LaTeXTools#1275]
I have project where the structure is like the following:
```
F:\paper\201712_paper
├───images
├───version1
└───version2
```
I write papers in `version*` directory, and I put all my images resources in `images` directory. In my tex files, I have used the following command:
```
\graphicspath{{../images/}}
```
But it seems that the image name auto-completion does not work after I press `ctrl+l, ctrl+f`. 

It seems that latextools now support auto-complete image files [in current directory](https://github.com/SublimeText/LaTeXTools/issues/1156) or [in a subdirectory](https://github.com/SublimeText/LaTeXTools/pull/1128). Does latextools support autocomplete images under a sibling directory or am I doing it the wrong way?

**Comment by ig0774** [comment]
As long as you’re using ST3, you can install the prerelease version that has support for `\graphicspath` by setting the PackageControl setting `install_prereleases` to `[“LaTeXTools”]`.

**Comment by jdhao** [comment]
Thanks, now it works. I make a mistake by putting the `install_prereleases` option in the sublime text user setting file instead of the Package Control user setting file.

**Comment by thethinker990** [comment]
Do you plan to put this in the stable release package?
