### ISSUE TITLE
Forward and Inverse Search Not Working

### ISSUE THREAD

**Issue by harrycheon** [SublimeText/LaTeXTools#1276]
I just installed Sublime and Skim today. I followed the instructions to install LaTeXTools. Building the PDF and launching Skim works, but the forward and inverse searches don't seem to work. Nothing happens when I Cmd+Shift+Click on the PDF to inverse search or Cmd+L, J to forward search in the TeX document. I have checked my $PATH directories and done most things that was suggested online but nothing has made the searches work. What should I do?

**Comment by jdhao** [comment]
@harch17 , please follow the [instructions here](https://tex.stackexchange.com/questions/194645/jump-to-the-last-line-of-pdf-when-compiling-text-in-sublime-text) carefully.

**Comment by krzakala** [comment]
Sorry, I have the exact same problem, I do not see how the link here (which seems to be about windows) help
