### ISSUE TITLE
Math Preview Problem with ST3 build 3143

### ISSUE THREAD

**Issue by melon-audience** [SublimeText/LaTeXTools#1279]
I met a problem similar to  #1243 . Math preview doesn't work
![default](https://user-images.githubusercontent.com/35769515/36339156-d93feb68-13f9-11e8-8564-e95491905874.png)
The report contained only one line
![default](https://user-images.githubusercontent.com/35769515/36339164-f949122c-13f9-11e8-8a4b-76878a16d136.png)
After running check system, I got a similar page in which the value of display_log is false.
![default](https://user-images.githubusercontent.com/35769515/36339138-737fbb14-13f9-11e8-8b0a-b0aa3639c8cd.png)
I referred to other issues and installed ghostscript manually, but the path of ghostscript didn't change.

**Comment by r-stein** [comment]
The display log setting is for the builder and does not affect the error output of math preview. Have you tried to restart your pc after installing ghostscript? If so you may need to adapt your system variable for path.

**Comment by melon-audience** [comment]
I added ghostscript to environment variables and solved the problem, thank you!
