### ISSUE TITLE
"Ctrl+/" and toggling comments 

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1282]
It is well-known that "Ctrl+/" toggles contents to comments by preceding %. 
Suppose he wants to comment several lines where there is a blank line, e.g.,

> `This is the first line,`
> 
> `This is the third line.`

He would obtain 

>`%This is the first line,`
>
> `%This is the third line.`

Please note that there is no preceding % in the second line. 

In ocassions, this would lead to an extra space or an extra `\par`. 

I don't know  if the behavior of  `Ctrl+/' is specified by LaTeXTools  or by Sublime Text. 
If possible, could there be a % in the front of the second line? E.g., 

> `%This is the first line,`
> `%`
> `%This is the third line.`

**Comment by r-stein** [comment]
You can press ctrl+shift+l to split the selection into lines and then press ctrl+/ to toggle comments. I don't know whether there is a way to also toggle empty lines by default.

**Comment by Romeoly** [comment]
Thank you so much. And sorry for replying so late.
