### ISSUE TITLE
Unable to install LaTexTools via PackageControl due to dependency pygments not available

### ISSUE THREAD

**Issue by Steiniche** [SublimeText/LaTeXTools#1283]
This is NOT an issue with LaTexTools but rather with PackageControl which is experiencing an error due to an github certificate update: https://github.com/wbond/package_control/issues/1334

I am opening this issue in case others hit the same issue and cannot find any information about what to do.
The error looks like this:
```
ignored packages updated to: ["LaTexTools", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' is not available
Package Control: The dependency 'pygments' could not be installed or updated
```

**Workaround**
Follow the "more hands-on approach" from https://latextools.readthedocs.io/en/latest/install/ where the complete repo is downloaded and manually put into packages.

**Comment by r-stein** [comment]
if you install it manually you should run *Package Control: Satisfy dependencies* when package control is back to normal.

**Comment by YimingLiu11** [comment]
I meet the same problem today, the dependency python-jinja2 is not available in my packagecontrol. how did you solve that?

**Comment by r-stein** [comment]
@YimingLiu11 please see my comment here: https://github.com/SublimeText/LaTeXTools/issues/1414#issuecomment-506453457

**Comment by YimingLiu11** [comment]
Thanks a lot, the LaTexTools can be installed now.
