### ISSUE TITLE
chktex doesn't like "sec" snippet

### ISSUE THREAD

**Issue by a59** [SublimeText/LaTeXTools#1288]
The "sec" (Section) snippet puts the label on a new line after the "% fold" instruction.

To keep chktex happy, I move the label to right after the section command. 

I'd like to change the snippet/completion to not have to do this manually but couldn't find where that snippet/completion is defined in the LaTeXTools code. 

Any pointers?

**Comment by r-stein** [comment]
Use PackageResourceViewer and look inside the LaTeX package.

**Comment by a59** [comment]
Thanks. I found and fixed it.
