### ISSUE TITLE
Inverse search error when jump from the last page

### ISSUE THREAD

**Issue by MOOnLyer** [SublimeText/LaTeXTools#1293]
I am doing Multi-file documents. When I do the inverse search from the last page of the pdf, it always gives me the '\end{document}' in the master file.

**Comment by ig0774** [comment]
Unfortunately, this isn’t a problem that we can do anything about in LaTeXTools. The location is determined by the synctex implementation in your PDF viewer. The only information passed to Sublime is the file that synctex determines is relevant and the corresponding line and column number.

Note that this information is heavily dependent on the content of your “last page”. If it’s just standard text, everything should work as expected (at least on all the supported viewers—at least it does for me), but synctex is sometimes inaccurate around included images, etc.

**Comment by MOOnLyer** [comment]
I think it has something to do with the multi-file documents, i.e., I use \input in the main .tex file to include all the .tex.

If I want to address to this, where should I look for help?
