### ISSUE TITLE
sublime can't compile tex 

### ISSUE THREAD

**Issue by xiyuan1223** [SublimeText/LaTeXTools#1297]
windows 10 64bit#I have installed  miktex,sublime 3 and SumatraPDF ,and I config in sublime as follows
![image](https://user-images.githubusercontent.com/14871189/37324992-db667d82-26c6-11e8-9133-e575b2b89f46.png)
then I run an ctex as
![image](https://user-images.githubusercontent.com/14871189/37325034-fef25bae-26c6-11e8-9285-98831a6b2cf2.png)
but sublime errors as
![image](https://user-images.githubusercontent.com/14871189/37325048-15c99446-26c7-11e8-9974-f174616f457e.png)
I really don't know how to solve it!

**Comment by r-stein** [comment]
This looks as if you use a different compiler. Press ctrl+shift+p and select LaTeX.

**Comment by shannonPrice** [comment]
Stop
