### ISSUE TITLE
Custom builder not running

### ISSUE THREAD

**Issue by dafrick** [SublimeText/LaTeXTools#1298]
Hi, after an update (a few weeks ago), I have issues with biber. I am running Sublime Text 3.0 on Ubuntu 16.04, and using lualatex + biber. I suspect I have the same issues as outlined here:
https://github.com/SublimeText/LaTeXTools/issues/637
https://tex.stackexchange.com/questions/286095/biber-and-sublime-text

As suggested in the above threads, I want to run a custom builder (biberBuilder, see https://github.com/SublimeText/LaTeXTools/issues/637#issuecomment-192361009). `Preferences|Browse Packages` tells me that my packages folder is at `~/.config/sublime-text-3/Packages`, so I have included` biberBuilder.py` in `~/.config/sublime-text-3/Packages/User/LaTeXTools/builders/`. When I run `window.open_file(sublime.packages_path() + "/User/LaTeXTools/builders/biberBuilder.py")` in the console the correct file `biberBuilder.py` is opened, so it seems to be in the right place.
Moreover, I have added the following to my `.sublime-project` file:
```
"builder_settings": {
            "builder": "biber",
            "builder_path": "User/LaTeXTools/builders",
            "program": "lualatex",
            "options": ["--shell-escape"]
        }
```
However, when I do Ctrl+B, the basic builder runs, not my custom biber builder. 
What could be the issue? How do I troubleshoot this problem?

**Comment by r-stein** [comment]
Press control+shift+b and select the builder you want.

**Comment by dafrick** [comment]
The custom builder does not appear in that selection, I can only select the simple,l basic and traditional builder.

**Comment by dafrick** [comment]
Small addition: When I press control+shift+b, none of the builders run my custom builder - I have tried each of them.

**Comment by ig0774** [comment]
From the `ctrl+shift+b` menu, you’ll want to select the one called “LaTeX” (i.e. with nothing else there). If that doesn’t work, it’d be helpful to see the output to the console.

**Comment by ig0774** [comment]
Honestly, though, if the goal is just to run LuaLaTeX and Biber, you should just use the `basic` builder.

**Comment by dafrick** [comment]
I originally used the basic builder, but a few weeks ago this essentially stopped running biblatex/biber (see the two issues/threads that I linked to in my first post).
Selecting just "LaTeX" still runs the basic builder. The console output is:
```
<class '_latextools_basicBuilder.BasicBuilder'>
11
Welcome to thread Thread-47
['lualatex', '-interaction=nonstopmode', '-synctex=1', '--shell-escape', 'cv']
Running "lualatex -interaction=nonstopmode -synctex=1 --shell-escape cv"
Finished normally
0
False True True
Jump to:  124 39
<class '_latextools_evince_viewer.EvinceViewer'>
Running "python -c 'import dbus'"
Running "ps xv"
Running "python /home/dafrick/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_forward_search /home/dafrick/Dropbox/documents/serious/cv/cv.pdf 125 /home/dafrick/Dropbox/documents/serious/cv/cv.tex"
```

**Comment by ig0774** [comment]
The two issues you linked are a couple of years out of date and involve the “simple” builder, which was never intended to run biber (it’s a demonstration of the builder API). I wrote the “basic” builder to provide an out-of-the-box solution for biber on MiKTeX in response to that and a few other issues.

Most likely, if biber isn’t being run, it’s because Your document isn’t using any `\cite` commands, so BibLaTeX doesn’t think it has any work to do. Since I note your document is called “cv”, I’m guessing you don’t actually need to cite things in the document, but still want a bibliography, in which case you need to include a `\nocite` command somewhere in your document. Something like `\nocite{*}` just before `\printbibliography` will tell BibLaTeX to include bibliography entries that haven’t been cited in your main document.

**Comment by dafrick** [comment]
Ok thanks, I didn't realize that the issue was already two years old.

I am using \cite commands (in fact \nocite{...}), as I have a list of publications that I want to be included in my cv. The lualatex output is:
```
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:165: LaTeX Warning: Citation 'sessa2018' undefined on input line 165.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:165: LaTeX Warning: Citation 'torrisi2018' undefined on input line 165.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:165: LaTeX Warning: Citation 'frick2017b' undefined on input line 165.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:165: LaTeX Warning: Citation 'frick2017c' undefined on input line 165.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:165: LaTeX Warning: Citation 'frick2018' undefined on input line 165.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex:169: LaTeX Warning: Empty bibliography on input line 169.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex: LaTeX Warning: There were undefined references.
/home/dafrick/Dropbox/documents/serious/cv/cv.tex: Package biblatex Warning: Please (re)run Biber on the file:(biblatex)                cv(biblatex)                and rerun LaTeX afterwards.
```
I am extremely doubtful that this issue is due to my .tex or .bib files. In fact, texmaker compiles both the bibliography and tex file without issues - I just like using sublime.

**Comment by ig0774** [comment]
Hmmmm... now that’s strange. There’s a setting under “builder_settings” called “display_log”. Could you set that to `true` and re-run the build and then copy the output here?

**Comment by dafrick** [comment]
You can find the output here: https://pastebin.com/1ZWuSTFj

After playing a bit with the options, I found my error. My setting were:
```
"builder_settings": {
            "builder": "biber",
            "builder_path": "User/LaTeXTools/builders",
            "program": "lualatex",
            "options": ["--shell-escape"]
        }
```
whereas they should have been
```
"builder": "biber",
"builder_settings": {
            "builder_path": "User/LaTeXTools/builders",
            "program": "lualatex",
            "options": ["--shell-escape"]
        }
```

@ig0774 I would be happy if just the basic builder worked. If you are interested in troubleshooting this, I can continue to answer here, or open a new issue.

**Comment by ig0774** [comment]
@dafrick: Thanks for the output. I got a handle on why this happened. Basically the "basic" builder is looking for a line like this: `LaTeX Warning: Citation 'sessa2018' on page 11 undefined on input line 165.`, but (for whatever reason) the version of LuaLaTeX you're running only outputs `LaTeX Warning: Citation 'sessa2018' undefined on input line 165.`. Fortunately, that's pretty easy to fix.

**Comment by dafrick** [comment]
Great, thanks!
