### ISSUE TITLE
builder not responding

### ISSUE THREAD

**Issue by hebertodelrio** [SublimeText/LaTeXTools#1302]
I am using LatexTools 3.14.2 in OS X. If I change the builder from traditional to basic it always shows that the building system is the traditional. If I add the program to be pdflatex it always compiles it using xelatex, what is wrong?

TraditionalBuilder: Engine: xelatex. Invoking latexmk... done.

No matter what I try

**Comment by r-stein** [comment]
Press ctrl shift b and select the default LaTeX option.

**Comment by hebertodelrio** [comment]
That does it, but why if I change any of the settings in the user settings files it does not work? not the %!TEX program = pdflatex at the top of the TeX file either

**Comment by ig0774** [comment]
At some point (probably at the first build) you selected a builder other than the default one. The settings in the selected builder override the user settings or settings in the file.

**Comment by hebertodelrio** [comment]
How can I reset it? If that is the case (most likely)

-- 
Heberto del Rio

On March 21, 2018 at 6:31:53 PM, ig0774 (notifications@github.com) wrote:

At some point (probably at the first build) you selected a builder other
than the default one. The settings in the selected builder override the
user settings or settings in the file.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SublimeText/LaTeXTools/issues/1302#issuecomment-375117464>,
or mute the thread

**Comment by ig0774** [comment]
It’s as @r-stein said: selecting the LaTeX option will fix things at least until another builder is chosen.

**Comment by r-stein** [comment]
When you press `ctrl+shift+b` (instead of `ctrl+b`) there should be a panel to select the builder. The selected builder in this panel overwrites the settings.
