### ISSUE TITLE
problem with sublime3 + texlive + win10

### ISSUE THREAD

**Issue by raminbhl** [SublimeText/LaTeXTools#1304]
Hello
I have some problem in compiling with pdfLatex. The file is actually compiled and the final PDF is built (so there is probably no problem in settings) but in the console, I see this error:

`[Compiling C:\Users\...\test.tex]
TraditionalBuilder: Engine: pdflatex. Invoking latexmk... 
COULD NOT COMPILE!
Build engine: Traditional Builder `

and the final PDF is not opened automatically.
I set "sumatra" in the user settings and the SumatraPDF.exe is included in my PATH.
Can anybody help me plz.

**Comment by ig0774** [comment]
The error you’re seeing usually happens when `latexmk` is not installed, so LaTeXTools never ran `pdflatex` etc. If you have a PDF, it’s probably an artifact of a different build.

You can check if `latexmk` is installed and on the PATH LaTeXTools can see by running the **LaTeXTools: System Check** command from the command palette (`C-shift-p`). Assuming you’ve gone with something like the “basic” texlive install, you might need to switch to using the `basic` builder in the LaTeXTools settings.

**Comment by raminbhl** [comment]
Than you so much for your response. I have already executed the command and all things seem to be OK, but the problem still exists. This is the result of executing the command: 

Variable   Value
--------   -----
PATH       C:\texlive\bin\win32;C:\ProgramData\Oracle\Java\javapath.................

Program      Location                                          Status            Version
-------      --------                                          ------            -------
sublime      C:\Program Files\Sublime Text 3\sublime_text.exe  available         Sublime Text Build 3143
latexmk      C:\texlive\bin\win32\latexmk.exe                  available         Latexmk, John Collins, 17 Jan. 2018. Version 4.55
pdflatex     C:\texlive\bin\win32\pdflatex.exe                 available         pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX)
xelatex      C:\texlive\bin\win32\xelatex.exe                  available         XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/W32TeX)
lualatex     C:\texlive\bin\win32\lualatex.exe                 available         This is LuaTeX, Version 1.0.4 (TeX Live 2017/W32TeX)
biber        C:\texlive\bin\win32\biber.exe                    available         biber version: 2.10
bibtex       C:\texlive\bin\win32\bibtex.exe                   available         BibTeX 0.99d (TeX Live 2017/W32TeX)
bibtex8      C:\texlive\bin\win32\bibtex8.exe                  available         This is 8-bit Big BibTeX version 0.99d
kpsewhich    C:\texlive\bin\win32\kpsewhich.exe                available         kpathsea version 6.2.3
convert      C:\Windows\system32\convert.exe                   restart required  Invalid drive specification.
ghostscript  C:\texlive\tlpkg\tlgs\bin\gswin32c.exe            available         GPL Ghostscript 9.22 (2017-10-04)

Packages for equation preview  Status
-----------------------------  ------
standalone                     available
preview                        available
xcolor                         available
amsmath                        available
amssymb                        available
latexsym                       available
mathtools                      available

Builder  Status
-------  ------
basic    available

Builder Setting  Value
---------------  -----
display_log      True 
linux            {}   
osx              {}   
windows          {}   

Viewer   Status     Location
------   ------     --------
sumatra  available  C:\Program Files\SumatraPDF\SumatraPDF.exe

Also the result of building with the "basic" builder is the same as the "traditional" builder with the same error message. I am also confident that the pdf is not for previous builds because I deleted it and it was created again. 
Thank you again for your attension.

**Comment by ig0774** [comment]
Could you show the output to the sublime console (**View -> Show Console**) when you run the build?

**Comment by raminbhl** [comment]
<class '_latextools_basicBuilder.BasicBuilder'>
3
Welcome to thread Thread-8
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'test']
Running "'C:\texlive\bin\win32\pdflatex.EXE' -interaction=nonstopmode -synctex=1 test"
Traceback (most recent call last):
  File "C:\Users\ramin\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\makePDF.py", line 319, in run
    self.caller.builder.set_output(out.decode(self.caller.encoding,"ignore"))
LookupError: unknown encoding: 720

**Comment by raminbhl** [comment]
I found the solution accidentally(!) in the https://github.com/SublimeText/LaTeXTools/issues/358:

"However, I temporarily changed line 318 in Sublime Text 3/Packages/LaTeXTools/makePDF.py from:
self.caller.builder.set_output(out.decode(self.caller.encoding,"ignore"))
to

try:
    self.caller.builder.set_output(out.decode(self.caller.encoding,"ignore"))
except:
    self.caller.builder.set_output(out.decode('cp'+self.caller.encoding,"ignore"))"

**Comment by ig0774** [comment]
Thanks for that! I'll try to include a fix in the next release.

**Comment by ig0774** [comment]
The fix for this was included in v3.15.0.
