### ISSUE TITLE
Can't use Ctrl+B to build

### ISSUE THREAD

**Issue by lgwangh** [SublimeText/LaTeXTools#1305]
Hello!
I use Texlive with Windows 10, and my sublime text 3 is Build 3143. When I use `Ctrl+B` to build my file, it just save my file but doesn't build it. And when I use `Ctrl+Shift+B` , sublime text tells me "no build system with variant run". However, I can use `Ctrl+Shift+P` to open the menu, and select `Build With: Latex-XeLatex` to build it.
![image](https://user-images.githubusercontent.com/19831228/38454903-703106a0-3aa2-11e8-8363-f25a7ddb79ef.png)
I tried to set build system to Auto or Latex, and tried to change the `builder`, but it still doesn't work. And there is no other plugin takes `Ctrl+B` , as I can build `.py` files with build Python build system with `Ctrl+B`.

**Comment by r-stein** [comment]
Do you have the correct latex syntax highlighting? You can try to press ctrl+shift+p and write *Set Syntax: LaTeX* and then try to build again.

**Comment by lgwangh** [comment]
It still doesn't work although I have set the syntax to LaTeX. 
This plugin is very helpful and I'm sorry that I can't provide more useful information about this problem.

**Comment by ig0774** [comment]
After changing the syntax, you will want to ensure that the build is set to Auto. Can you post a screenshot of the file your editing?

**Comment by lgwangh** [comment]
I use Chinese, so I change the language of the menu. But I'm sure that I can't use `Ctrl+B` whether the build system is Latex or Auto.
![2018_04_10-003](https://user-images.githubusercontent.com/19831228/38559192-eb6668ce-3d04-11e8-8b1f-8dc4eb8dcb4c.png)
It's possible that I changed the config of my sublime text by mistake, as I'm new to coding and I can't remember what I have done to it :(

**Comment by ig0774** [comment]
Sorry for the long delay in this. To try and debug, open the console (**View | Show Console** or equivalent) and enter the following:

```
sublime.log_input(True); sublime.log_commands(True)
```

Then return to the document and attempt to build by pressing `Ctrl+B`. If you could paste the output here it would be helpful in figuring out what's going on.

**Comment by lgwangh** [comment]
It output this: 

```
key evt: control+b
command: build
command: quick_panel {"items": [{"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": ""}, "caption": "LaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Traditional"}, "caption": "LaTeX - Traditional", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "PdfLaTeX"}, "caption": "LaTeX - PdfLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "XeLaTeX"}, "caption": "LaTeX - XeLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "LuaLaTeX"}, "caption": "LaTeX - LuaLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Basic Builder"}, "caption": "LaTeX - Basic Builder", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Basic Builder - PdfLaTeX"}, "caption": "LaTeX - Basic Builder - PdfLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Basic Builder - XeLaTeX"}, "caption": "LaTeX - Basic Builder - XeLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Basic Builder - LuaLaTeX"}, "caption": "LaTeX - Basic Builder - LuaLaTeX", "command": "build"}, {"args": {"build_system": "Packages/LaTeXTools/LaTeX.sublime-build", "choice_build_system": true, "choice_variant": true, "variant": "Script Builder"}, "caption": "LaTeX - Script Builder", "command": "build"}]}
key evt: shift+control+b
command: build {"variant": "Run"}
```

Thanks for helping me 😃

**Comment by ig0774** [comment]
That seems strange... So I assume that the quick panel appears with the list of build systems? If so, what key do you press at that point?

Regarding `shift+control+b`, you almost certainly have an override defined in your Keybindings. `shift+control+b` to run the build command with the "Run" variant is the default behaviour from ST2. Either delete the custom keybinding or add the following to your custom keybinding file (this is just the ST3 default):

```json
[
	{ "keys": ["control+shift+b"], "command": "build", "args": {"select": true} },
]
```

**Comment by lgwangh** [comment]
I have found the reason. I use Chinese, so I use a plugin to translate the menu. But it is outdated. In fact, I can't find `build with… (ctrl+shift+b)` in the menu. Now I remove it and use a new plugin, and everything is fixed.
Thanks for your help 😃
