### ISSUE TITLE
SumatraPDF window does not show in Windows in 3.15.0 (Process spawns, no display)

### ISSUE THREAD

**Issue by FacelessJ** [SublimeText/LaTeXTools#1309]
After the latest update to 3.15.0, SumatraPDF won't open after successful build. The process spawns, but nothing shows. If Sumatra is already open (either using the exact command latextools uses, but from `cmd`, or just opening manually), everything works as normal.

Reverting the change to `sumatra_viewer.py` in 951c43dba6824e6a2c1d5aa7b6b01fef05c004ca fixes the issue.

Using Windows 7, ST3 3143, LatexTools 3.15.0

**Comment by ig0774** [comment]
Thanks for the detailed report! This has been fixed in v3.15.1.
