### ISSUE TITLE
Build does not override existing PDF

### ISSUE THREAD

**Issue by H4rdB4se** [SublimeText/LaTeXTools#1314]
Hi there,

this is my first time working with LaTeX. 
I am impressed, everything looks good so far.
First build was succesful and the PDF file was created. But when I run the build a second time, the old PDF won't be overwritten. It stays the old PDF file, even if the build runs succesful.

Did I miss anything at setup?
(Windows 10, 64 bit, Sublime 3 newest BETA, Sublime runs in admin mode)

Greetings
H4rd_B4se

**Comment by H4rdB4se** [comment]
Ok, now I figured out, that there is another problem. 
When building, there are following files created (all same filename and these extensions)
.aux .bbl .blg .log .pdf .synctex.gz and .toc 
The build does not create another PDF if these files exists. 
I have to delete all these files and run the build again to create these files and at least the PDF again.

**Comment by ig0774** [comment]
It's not clear what builder you're using, but if you're using the traditional builder with TeXLive, then `latexmk` might not think there's any work to do. I'm not sure why that would be, but without knowing more about how your project is setup and what you're doing, I can only guess at the possible issues...

**Comment by H4rdB4se** [comment]
I've used TeXStudio to make an initial build and it worked. Even Sublime can now build multiple times with those created files from TeXStudio. Seems like Sublime had some problems on initial build.
