### ISSUE TITLE
Reverse search command does not work after turn off the POSIX mode in `command_viewer.py`

### ISSUE THREAD

**Issue by lrtfm** [SublimeText/LaTeXTools#1316]
After turn the POSIX mode off in [viewers/command_viewer.py](https://github.com/SublimeText/LaTeXTools/commit/10a3617c69c8f6f5bdaa14860ae2738998cdc629#diff-ac7ae831dd70e07fea19e6fa575131b5), it seems that the command is splitted in wired form. In this new version, when I setting the "viewer_settings" as follows, the reverse search command will be wrong in SumatraPDF. After I turn the POSIX mode on, it works as before.
```
{
    "viewer": "command",

    "viewer_settings": {
        // Platform-specific settings:

        "windows" : {
            // See README or third-party documentation
            "forward_sync_command":"SumatraPDF.exe -forward-search $src_file $line -inverse-search \"\\\"$sublime_binary\\\" \\\"%f:%l\\\"\" $pdf_file",
            "view_command":"SumatraPDF.exe -forward-search $src_file $line -inverse-search \"\\\"$sublime_binary\\\" \\\"%f:%l\\\"\" $pdf_file",
        },

    },
}
```

I test the following code in python to compare the output of `shlex.split` with and without POSIX mode.
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
>>> import shlex
>>> command = "\"\\\"abc\\\" def\" asdf"
>>> command
'"\\"abc\\" def" asdf'        # here \\ represent single \
>>> shlex.split(command, False, False)
['"\\"', 'abc\\"', 'def"', 'asdf']      # here, I think the first two shouldn't be splitted.
>>> shlex.split(command, False, True)
['"abc" def', 'asdf']
```
Shoud we turn off the POSIX mode? If it must be turned off, how to corrected the viewer_settings before?

**Comment by ig0774** [comment]
See the update on #1318. 

As a general usage note, I wouldn't reference `$src_file` or `$line` in the `"view_command"` portion as these are meaningless variables in the few situations where its used when a `"forward_sync_command"` is defined and may cause it to fail. Basically, your settings will result in LaTeXTools trying to run something like `SumatraPDF.exe -forward-search   -inverse-search "\"C:\path\to\sublime_text.exe\" \"%f:%l\"" "C:\path\to\pdf_file.pdf"`, which may or may not work as expected.
