### ISSUE TITLE
Problem with Traditional Builder with Tex Live 2018

### ISSUE THREAD

**Issue by thanaset** [SublimeText/LaTeXTools#1317]
Hi

I wondered if someone could help me?

I upgraded to Tex Live 2018 on my Windows 10 machine this morning. Since then, I cannot compile documents using the "traditional" builder. (I was able to do it with Tex Live 2017.) Every time I try to compile a document, I get the following error message: Could not read log file ... I can, however, compile documents using both the "basic" and the "simple" builders without any issue. 

On my other machine, a Mac running El Capitan, the same set up works fine. I can compile documents using the "traditional" builder without any problem.

Any help will be much appreciated.

Thanaset

**Comment by r-stein** [comment]
Do you have any output in the ST console ``ctrl+` ``?

**Comment by thanaset** [comment]
Thanks for responding. I reinstalled TeX Live 2018 and it works OK now.
