### ISSUE TITLE
No bib files found

### ISSUE THREAD

**Issue by randomboolean** [SublimeText/LaTeXTools#1319]
I have a working tree like this:
```
project
│   main.tex
└───chapter_one
│   │   section1.1.tex
│   │   section1.2.tex
└───chapter_two
│   │   section2.1.tex
│   │   section2.2.tex
└───others
│   │   header.tex
└───refs
│   │   ref1.bib
│   │   ref2.bib
```
The `main.tex` contains `\input` statements of other files, my bib files are declared in `header.tex`.

However, when I start writing `\cite` in any of the `sectionX.Y.tex` files, there is the error `No bib files found` that appears, unless I do it from `main.tex`.

Is there a way to tell latexTools where to find the bib files ?

**Comment by ig0774** [comment]
Well, one way of doing this is to have a comment like `%!TEX root = ../main.tex` at the start of each of your `sectionX.Y.tex` files. See [the relevant bit of the documentation](https://latextools.readthedocs.io/en/latest/features/#multi-file-documents).

**Comment by randomboolean** [comment]
Thank you
