### ISSUE TITLE
Print compile command

### ISSUE THREAD

**Issue by PascalCremer** [SublimeText/LaTeXTools#1330]
I'd like to reproduce the traditional (or any) builder settings in a continuous integration pipeline on my gitlab server. 

I have adjusted some settings in my .sublime-project file, like output_directory and would like these changes to be incorporated in the pipeline as well.

Is there a possibility to print the currently used build command from LatexTools or could that be added?

**Comment by ig0774** [comment]
The builder command run is printed to the console, so you could get it from there.

**Comment by r-stein** [comment]
It wouldn't be a bad idea to also print it in a copy-paste format to the normal output.

**Comment by r-stein** [comment]
PS. You can open the console with ``ctrl+` ``. There you can see the command (as a formatted python array), reformat it, and write it in your shell.

**Comment by PascalCremer** [comment]
Thanks for getting back. I suppose the console is not the window giving this output:

```
[Compiling /home/cremer/docs/my_doc.tex]

TraditionalBuilder: Engine: pdflatex. 
Invoking latexmk... done.

No errors. Warnings:
....
```

``crtl+` `` did not do anything for me. Can I also get the console using the command palette?

**Comment by r-stein** [comment]
You can select *View > Show Console*

**Comment by PascalCremer** [comment]
Thanks! I consider that solved for me.
