### ISSUE TITLE
Keybinding for toggeling forward sync ST3

### ISSUE THREAD

**Issue by Bjoernolav** [SublimeText/LaTeXTools#1333]
I recently upgraded to ST3 on OS X Yosemite (10.10.5) and manually installed LaTeXTools by cloning the repo. Everything seems to work well, except that the keybinding for toggling forward sync (cmd+l, t, s) does not work.

From the documentation it seems like this keybinding should be supported?

I can still disable/enable forward sync by changing the "forward_sync" setting in LaTeXTools.sublime-settings.

**Comment by r-stein** [comment]
Sorry for the late reply. We have added [dependencies](https://github.com/SublimeText/LaTeXTools/blob/master/dependencies.json), which must also be installed for many features. So the manual installation is not really longer supported. If you have package control installed run "Package Control: Satisfy dependencies" in the command panel.

**Comment by Bjoernolav** [comment]
I see, thank you for the reply! I ran the "Package Control: Satisfy dependencies" and that sorted out the problem.
