### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'skim'

### ISSUE THREAD

**Issue by jeanggi90** [SublimeText/LaTeXTools#1339]
The compile of my .tex file works well but the .pdf does not open in Skim. In the ST console I get the following error message:
`<class '_latextools_traditionalBuilder.TraditionalBuilder'>
12
Welcome to thread Thread-997
Running "latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 samplefile.tex"
Finished normally
0
False True True
Jump to:  7 14
<class '_latextools_command_viewer.CommandViewer'>
Running "skim --unique '/somePath/samplefile.pdf#src:8/somePath/samplefile.tex'"
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "/Users/User/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/jumpToPDF.py", line 168, in run
    viewer.forward_sync(pdffile, srcfile, line, col, keep_focus=keep_focus)
  File "/Users/User/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/command_viewer.py", line 144, in forward_sync
    self._run_command(command, pdf_file, tex_file, line, col)
  File "/Users/User/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/viewers/command_viewer.py", line 133, in _run_command
    if sublime.platform() == 'windows' else False
  File "/Users/User/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/latextools_utils/external_command.py", line 221, in external_command
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'skim'`

I tried to reinstall Skim without any success. Running something like `open -a Skim comp.pdf` in the cli works.

My LaTeXTools path looks as follows:
`"texpath" : "$PATH:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin"`

and $PATH in the cli: `/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/Ghostscript/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/ImageMagick/bin`

**EDIT**
Running "Check system" gives me:
`
Viewer   Status     Location
------   ------     --------
command  available  N/A`

**Comment by r-stein** [comment]
Add the path to the parent folder of skim to your `texpath`. You should get it by running `which Skim` in your shell.

**Comment by jeanggi90** [comment]
'which Skim' running in the cli gives me nothing.

But I have managed to get it running by executing `sublime.load_settings("LaTeXTools.sublime-settings").set("viewer", "skim")` in the console. IDK why that helped since I did not make any changes to the settings file beforehand.

**Comment by r-stein** [comment]
Better open preferences > Package Settings > LaTeXTools > Settings and set the viewer there the other change is not persistent over a restart unless someone saves the settings. However skim should be the default.

**Comment by jeanggi90** [comment]
For some reason my settings file was screwed up after the installation. `Reset user settings to default` fixed everything. Thanks a lot for you help!
