### ISSUE TITLE
\bibitem reference cannot be detected.

### ISSUE THREAD

**Issue by zhishiwanwan01** [SublimeText/LaTeXTools#1340]
system: windows 7
sublime version: 3.1.1, build 3176
latextools version: 3.15.1

I use reference in my latex as below, but when I use `\cite`, a window said 'No bib files found' pops up; although when I used `\cite{consist}`, the pdf still displayed the right citation. 
```latex
\begin{thebibliography}{9}
    \bibliographystyle{unsrt}
    \bibitem{consist}
	Garcia, R. R. and A. Zakhor (2012)
\end{thebibliography}
```

**Comment by r-stein** [comment]
Inline bibliography is not (yet) supported by LaTeXTools

**Comment by zhishiwanwan01** [comment]
Is it on a plan?

**Comment by r-stein** [comment]
I don't think so. Parsing the content from the tex file instead of a dedicated bib file can get quite complicated and we would also be unable to detect the author, caption, etc.
In addition most people use bib files anyway.

**Comment by zhishiwanwan01** [comment]
ok, thanks anyway.
