### ISSUE TITLE
ImageMagick custom path

### ISSUE THREAD

**Issue by ghost** [SublimeText/LaTeXTools#1343]
I use a portable version of IM and SublimeText where I cannot install or point to IM with a PATH variable.
I want to give a relative path, but find no settings option for it.

Could a custom IM path setting be added?

**Comment by r-stein** [comment]
You can customize the [`texpath`](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.7/LaTeXTools.sublime-settings#L220) variable for this. However this does not support relative paths.

Aside from this IM is currently (at least in the prereleases) only used to convert svg images, so you most likely don't need it. We also used this to convert pdf and eps files, but directly call ghostscript for this now.

**Comment by SairesArt** [comment]
Ohh, I thought it was used for creating thumbnails of the images and feed it to ST.
Could I maybe implement the relative path myself, could you point me to the .py file, where I could maybe hardcode something realtive to ${packages}?

**Comment by r-stein** [comment]
The execute commands file is here: https://github.com/SublimeText/LaTeXTools/blob/master/latextools_utils/external_command.py

It already expands environment variables, so you may just create a new plugin and set the environment variable and then just use it in the texpath variable.

```py
def plugin_loaded():
    os.environ["packages"] = sublime.packages_path()
```
