### ISSUE TITLE
preview for equations between single $s

### ISSUE THREAD

**Issue by hadisfr** [SublimeText/LaTeXTools#1347]
I cannot see preview for inline mathematical equations between single `$`s, while preview works fine for full line equations between double `$`s and equations inside `equation` environment.
```tex
This is a text with $e = m \cdot c^2$ formula.
```
does not have preview but
```tex
$$e = m \cdot c^2$$
```
and
```tex
\begin{equation}
e = m \cdot c^2
\end{equation}
```
are fine.
And there isn't any error or log in console, if it's matter.

Is it a bug or sth in plug-in or occurs only on my machine? I remember to see preview for that type before; am I wrong? Is it possible to have preview for the first type of equations, too?

**Comment by r-stein** [comment]
It's not bug it's a feature ;).

You can change this by changing the setting [`preview_math_scope`](https://github.com/SublimeText/LaTeXTools/blob/version4/LaTeXTools.sublime-settings#L112-L117) to `text.tex.latex meta.environment.math`.

**Comment by hadisfr** [comment]
Oh, of course. I've become wacky recently. 🙄 
Thank you!
