### ISSUE TITLE
How to use...?

### ISSUE THREAD

**Issue by chelseas** [SublimeText/LaTeXTools#1351]
Forgive my newness to this project, but I can't seem to find a straightforward, detailed set of instructions on how to actually compile my latex document from within sublime, using LatexTools. I've installed it, and I can get "view pdf" to work, but once I alter the document, I don't know how to compile it again!

A set of instructions as follows would be helpful, e.g. something like:
1. Enter X command in the command palette 
2. Type Y
3. Press enter

or something. I looked through the stuff on setting up a build script, but I don't know how to _execute_ it.

**Comment by ig0774** [comment]
When the view is on a LaTeX document, you can press `Ctrl-B` (Windows or Linux) or `Cmd-B` (Mac). There are several other options to invoke the build system built into Sublime itself, but hopefully that gets you going.
