### ISSUE TITLE
Arch Linux - missing packages

### ISSUE THREAD

**Issue by Hootan-Man** [SublimeText/LaTeXTools#1359]
Hi guys, I already know that you recommended using vanilla instead of the TeX live, but the problem is that I need TeX live for cmake automatic document generator. 

I managed to resolve all the dependencies needed except 2.
![screenshot from 2018-08-21 16-48-30](https://user-images.githubusercontent.com/8722716/44409632-07712100-a563-11e8-96eb-2af537bc1c60.png)
do you know which packages consists "standalone" and "preview"?
I searched AUR but I couldn't resolve these last two!

**Comment by ig0774** [comment]
Honestly, we strongly recommend TeXLive rather than whatever package manager your distro uses because 1) it’s usually more up-to-date and 2) exactly these sort of issues.

Unfortunately, I really have no idea where those packages may be bundled in Arch. Personally, I tend to use Fedora...

**Comment by godspeedfw** [comment]
having this same problem

**Comment by godspeedfw** [comment]
Okay so I figured it out, you have to install the `texlive-latexextra` package.
