### ISSUE TITLE
Unable to recognize .bib file/not generating .bbl file

### ISSUE THREAD

**Issue by sagarsxn** [SublimeText/LaTeXTools#1363]
I am running LaTexTools on ST3 on macOS Sierra.

ST3 Version 3.1.1, Build 3176
LaTeXTools v3.15.1

I have a simple tex file (taken from ShareLaTeX) that looks like this:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{csquotes}
\usepackage[english]{babel}
 
\usepackage[
backend=biber,
style=alphabetic,
citestyle=authoryear
]{biblatex}
 
\addbibresource{sample.bib} %Imports bibliography file
 
\begin{document}
\section{First section}

This document is an example, two items are cited: \textit{The \LaTeX\ Companion} book is \cite{latexcompanion}, and Einstein's journal paper is \cite{einstein}.

\medskip

\printbibliography
\end{document}
```

The sample.bib file is in the same directory and looks like this:
```
@article{einstein,
    author =       "Albert Einstein",
    title =        "{Zur Elektrodynamik bewegter K{\"o}rper}. ({German})
        [{On} the electrodynamics of moving bodies]",
    journal =      "Annalen der Physik",
    volume =       "322",
    number =       "10",
    pages =        "891--921",
    year =         "1905",
    DOI =          "http://dx.doi.org/10.1002/andp.19053221004"
}
 
@book{latexcompanion,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The \LaTeX\ Companion",
    year      = "1993",
    publisher = "Addison-Wesley",
    address   = "Reading, Massachusetts"
}
 
@misc{knuthwebsite,
    author    = "Donald Knuth",
    title     = "Knuth: Computers and Typesetting",
    url       = "http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html"
}
```

When I press cmd+shift+b, I get a PDF that "cites" sources using the keyword instead of the desired citation. I have attached the PDF.
[mytest.pdf](https://github.com/SublimeText/LaTeXTools/files/2355480/mytest.pdf)

I am also attaching my .sublime-settings file and the console output below.
[LaTeXTools.sublime-settings.txt](https://github.com/SublimeText/LaTeXTools/files/2355485/LaTeXTools.sublime-settings.txt)
[console.txt](https://github.com/SublimeText/LaTeXTools/files/2355489/console.txt)

If I run `latexmk mytest.tex` in the terminal, my PDF compiles properly with all the citations and bibliography.

I am a relatively new user of Sublime Text, and I have spent many hours on trying to fix this now. I would appreciate any and all guidance at this point. Thank you!

**Comment by lrtfm** [comment]
You may find what you need here [Biber Support](https://github.com/SublimeText/LaTeXTools/wiki/Biber-Support). I hope it will help.

**Comment by sagarsxn** [comment]
I have looked through that page and it seems to be directed towards Windows users. 

I did use the following command from that page under builder_settings in my attached .sublime-settings file: `"command": "latexmk -cd -f -%E -interaction=nonstopmode -synctex=1"` but it didn't seem to help.

**Comment by ig0774** [comment]
1. When you press `cmd+shift+b`, which option do you select?

1. Can you attach your `mytest.log` and `mytest.blg` files?

1. What is the output from running the **LaTeXTools: Check System** command in the command palette (`cmd+shift+p`)?

1. Are you using MiKTeX on macOS?

**Comment by ig0774** [comment]
Also, I just noticed you have LaTeXing installed as well as LaTeXTools. These packages conflict and its possible you're not even invoking LaTeXTools at all. You should either disable or uninstall LaTeXing to use LaTeXTools.
