### ISSUE TITLE
Use docker for compilation on Windows

### ISSUE THREAD

**Issue by paulfd** [SublimeText/LaTeXTools#1364]
This is not a bug at all, but rather a discussion!

I was procrastinating and checked out VSCode. While testing the LaTeX plugin over here, I stumbled upon options to run LaTeX within Docker on Windows, thereby harnessing the speed advantage of Unix-built LaTeX distributions compared to the windows builds (no clue why this happens, but it's true).

The idea is as follows: use a Docker image with LaTeX (e.g. https://hub.docker.com/r/tianon/latex/) and then shim the usual latex commands with CMD:

`docker run -i --rm -w /data -v "%cd%:/data" tianon/latex latexmk %*`

or PowerShell:

`docker run -i --rm -w /data -v "$(Get-Location):/data" tianon/latex latexmk $args`

You can then set LaTeXTools to `texlive` and give the location of the shims in the path through user settings. However, there's an issue with log parsing, since a lot of the parsing code requires `os.path.isfile()` to avoid false positives in matching file names within the log.

To try it out, I replaced them by calls to `bash -c "[ -f … ]"` within docker through the function.

```python
docker = True

def test_file(file_name):
	if docker:
		call_str = 'docker run tianon/latex bash -c "[ -f "{}" ]"'.format(file_name)
		print(call_str)
		popen_obj = subprocess.Popen(call_str, stderr=subprocess.PIPE)
		popen_obj.wait()
		stderr_str = popen_obj.stderr.read()
		print(stderr_str)
		return stderr_str == b''
	else:
		return os.path.isfile(file_name)
```

However, there is a small time lag when you call Docker which kinds of kills the speed gains from the compilation :) 

I don't know Docker much, maybe there's a better way to test if files are present within the container. Otherwise, I guess the only solution would be to rewrite the logic used to parse the log, but from the looks of it it is quite a complicated matter with a lot of weird cases to handle.

**Comment by ig0774** [comment]
There’s a flag at the top of `parseTeXLog.py` called `print_debug` (IIRC). In addition to dumping a bunch of information on the console, this will also use some (very imperfect) heuristics to “guess” if a string is a valid file. That may work for this situation...

I’d like to rewrite the log parsing code because it’s a real mess, but I’m really hesitant to or even to touch it much because, frankly, TeX log files are *not* easily machine-parsable.

**Comment by paulfd** [comment]
Yeah I hooked on this function, it works actually, although there are some other issues with the virtualization that make it not much faster than say precompiled headers. Too bad, it seemed like an OK idea =)

Parsing TeX logs seems like quite the nightmare for sure. If I get around it I'll check if I can improve on these heuristic to remove the `isfile()` calls.

Thanks for answering!
