### ISSUE TITLE
"output_directory" option does not work on Windows 10

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#1365]
Hi,

I want to put all the intermediate files generated during the compilation into an individual folder for each latex project. This is works for MacOS by setting these two parameters as follows:

"output_directory": "cache",
"copy_output_on_build": true,

But it does not work for Windows 10 + ST3.  While I already set these two parameters, the "cache" folder still not generated and all the intermediate files are located in the same folder as the *.tex source files.

**Comment by ig0774** [comment]
See [my comment here](https://github.com/SublimeText/LaTeXTools/issues/787#issuecomment-234788213)...

**Comment by shouwei** [comment]
@ig0774 
Thank you so much for your reply. 
Unfortunately, I still get the same issue after following your steps.  
Attachment is my user settings:

[user_settings.txt](https://github.com/SublimeText/LaTeXTools/files/2367162/user_settings.txt)

**Comment by shouwei** [comment]
@ig0774 it works like a magic.
Thank you so much! :-)
