### ISSUE TITLE
Magic comment to prevent compilation

### ISSUE THREAD

**Issue by mikedecr** [SublimeText/LaTeXTools#1368]
This is maybe a weird question, so sorry for raising any eyebrows. 

Is there any interest in a way (or does it already exist) to prevent LaTeXTools from attempting to build a file even if we hit the keybind to build, like with a magic  comment?

An explanation...there are plenty of cases when we accidentally try to build a `.tex` file that we don't actually want to build (e.g. if the file contains only a table exported from a statistical program, or a template file for an R Markdown document), but thanks to muscle memory, we hit `super+b`, the build fails, and then we have to clean all the temp files out of the directory. 

I know that it's possible to include `%!TEX root = path/to/main-document.tex` to build a "main" document instead of a modular document, and this works for the table file example. But it doesn't really work for other cases, such as a template file for R Markdown. 

So I'm wondering if anybody knows of any way, or if it seems possible/feasible to create some way, to prevent a file from building using a trick such as a magic comment.

**Comment by r-stein** [comment]
I would suggest to create a `noop` keybinding for C-b and add a context, which only matches inside LaTeX documents, which are are setup like your templates.
I added super cool context selectors for LaTeX documents #1167 so you could say "Don't build LaTeX documents, which don't have a `\documentclass`:

```js
  {
    "keys": ["ctrl+b"],
    // execute a command named noop, i.e. don't execute a command
    "command": "noop",
    "context": [
      // ensure we are inside a latex file
      { "key": "selector", "operand": "text.tex.latex" },
      // only disable the build if the documentclass is missing/empty
      { "key": "latextools.documentclass", "operand": "" },
    ]
  },
```

This option requires you to enable prereleases: https://github.com/SublimeText/LaTeXTools#prereleases

**Comment by mikedecr** [comment]
Thanks, this is clever. I will have to modify the strategy somewhat since template documents would contain a `\documentclass`, but I can devise some other critera (e.g. if the filename contains `template.tex`) and give it a whirl
