### ISSUE TITLE
Mupdf "support"

### ISSUE THREAD

**Issue by Kakashiiiiy** [SublimeText/LaTeXTools#1374]
Hello,
I wanna use Mupdf instead of Evince cause ghostscript etc. got sec vulnerabilities.
It displays the pdf but if I recompile it, another windows is opened. 
According to the man page 
`SIGHUP Sending a SIGHUP signal to the mupdf process will also cause the viewed file to be reloaded automatically, for use in
              e.g. build scripts.`
It should be possible to reload the file if a process exist, but I have no idea how to do that.

**Comment by retifrav** [comment]
I also wanted to use mupdf as the viewer, but the only thing I have achieved it simply launching it with `view_command`:

``` json
"viewer": "command",
"viewer_settings": {
    "linux": {
        // mupdf doesn't seem to support such a functionality
        //"forward_sync_command": "mupdf $pdf_file#src:$line$src_file",
        "view_command": "mupdf $pdf_file"
    }
}
```

It does open the compiled PDF, but every new build launches a new instance of mupdf, and I couldn't figure out how to use `pkill -HUP mupdf` when there is already a running mupdf instance with the document.

Moreover, if I close all of those mupdf instances (*with `q` shortcut*), there will be still "unkillable" `mupdf` process(es) running (*they terminate only when I exit Sublime Text*), which isn't the case when I launch mupdf directly from shell. So it looks like that for a proper support of mupdf via `viewer_settings` one would have to modify the LaTeXTools plugin [sources](https://github.com/SublimeText/LaTeXTools/blob/50a51700671b64b29e2d9f5ec27ed2527762a0c5/plugins/viewer/command_viewer.py#L116-L126) (*but then it makes more sense to implement a dedicated [viewer](https://github.com/SublimeText/LaTeXTools/tree/50a51700671b64b29e2d9f5ec27ed2527762a0c5/plugins/viewer)*).

**Update**: Setting `viewer` to `zathura` (*and reverting changes in `viewer_settings`*) and installing both `zathura` and `zathura-pdf-mupdf` packages worked out pretty nicely out of the box, which I guess is why there is not much sense in doing anything specifically for mupdf.
