### ISSUE TITLE
Error during installation with package control

### ISSUE THREAD

**Issue by pmico** [SublimeText/LaTeXTools#1375]
This is the error you get when you install latextools:

Package Control: Error downloading package. HTTP error 502 downloading https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-jinja2/get/2.8.0.zip.
error: Package Control

Unable to download python-jinja2. Please view the console for more details.
Package Control: The dependency 'python-jinja2' could not be installed or updated
ignored packages updated to: ["Vintage"]

I think the error is due to the dot after zip extension. (/get/2.8.0.zip. <- this final dot)

**Comment by ig0774** [comment]
Try running **Package Control: Satisfy Dependencies**. Did you check the console for any information?

**Comment by pmico** [comment]
It's not necessary ... Now it's working
