### ISSUE TITLE
Vintage mode & LaTeXTools

### ISSUE THREAD

**Issue by aaltland** [SublimeText/LaTeXTools#1379]
I am beginning to use ST3 Vintage mode. LaTeXTools and Vintage seem to get along reasonably well with each other, except that `'+a` or `` `+a`` (jump to mark 'a') don't work. In fact, both `'` and `` ` `` insert the respective characters, although I am in command mode. Other than that, nothing happens. This behavior is bound to tex files. For example, in python code the command works just fine. Any suggestions?

**Comment by r-stein** [comment]
LaTeXTools sets these keybinding to change the quote behavior. This seems to have a higher priority than Vintage. You can try to add those keybindings in your user keymap to change the priority or disable auto matching in tex files (`"auto_match_enabled": false` in the syntax specific settings):

```json
	{ "keys": ["`", "<character>"], "command": "vi_select_bookmark",
		"context": [{"key": "setting.command_mode"}]
	},

	{ "keys": ["'", "<character>"], "command": "vi_select_bookmark",
		"args": {"select_bol": true},
		"context": [{"key": "setting.command_mode"}]
	},
```

**Comment by aaltland** [comment]
The keybindings did it! Thanks, A.
