### ISSUE TITLE
"No bib files found!" if .tex filename is capitalized

### ISSUE THREAD

**Issue by andreatulimiero** [SublimeText/LaTeXTools#1383]
## TL;DR
Use only lowercase characters for your `.tex` root file
### The whole story
I was struggling with the "Non bib files found!" problem, and after trying a lot of solutions proposed to this issue, I've changed the name of my .tex file from `Report` to `report`, and it worked.    
Don't know if this is a normal behaviour, but I wasted a lot of time finding the reason behind this error
My folder structure was the following:
```
<folder>
|
|- Report.tex
|
|- bibliography.bib
```
And in my `.tex` file I used
```
\begin{document}
...
\bibliography{bibliography}
\end{document}
```

**Comment by ig0774** [comment]
This is almost certainly resolved by clearing the LaTeXTools cache rather than renaming the file.

**Comment by andreatulimiero** [comment]
> This is almost certainly resolved by clearing the LaTeXTools cache rather than renaming the file.

@ig0774 It was a while ago, so I don't quite remeber the different solutions I tried, but I'm quite sure I tried clearing LaTexTools cache and it didn't worked

**Comment by tloredo** [comment]
FWIW, I had this problem, and came across this issue looking for a solution. I, too, had .tex and .bib files that had leading caps. Clearing all my aux files (Cmd-L Delete) an re-building the file fixed the problem, so thanks, @ig0774, for the suggestion. I was using a template that originally had a different name for the .bib file, and that might have been the problem.
