### ISSUE TITLE
Unreliable autocompletion

### ISSUE THREAD

**Issue by jackendrick** [SublimeText/LaTeXTools#1385]
Hi,
I am using LatexTools with sublime text 3 on mac. The auto-completion of my labels & bibliography is super useful when it works but it does not do so reliably.

When I tab to auto-complete either \ref{key} or \cite{keylist}, I sometimes get then get a drop down list of my labels or references. This does not happen often though and I can not work out what I am doing or not doing that allows this list to pop up.

Is there something that I may be doing incorrectly? I have tried removing the cache in case this helps. I am using a multi-file document and have %!TEX root = thesis.tex at the top of my content.tex (the file I am mostly writing in and want the auto-complete to work in).
Thanks

**Comment by r-stein** [comment]
I am not sure whether I understand you correct:
Do you want to know the hotkey for the autocompletion to appear or to you have an error?
The hotkey would be super+l, super+f for the dropdown overlay and ^+space for the auto completion.
If there is an error please open the ST console (View > Show Console) and check the output when your press the hotkey.

**Comment by jackendrick** [comment]
Thanks, knowing the hotkeys helps and virtually eliminates the problem. How do I find a list of these hotkeys?

So what is happening:

I start typing to cite something "\ci"
The auto-complete dropdown appears
If I use the auto-complete suggestion (by using tab with my setup) the dropdown overlay does not appear automatically. Is this intentional? The hotkeys you have suggested do work though
If I continue to type out "\cite{" then the dropdown overlay does appear automatically.

**Comment by ig0774** [comment]
Almost all of the keybindings we provide are listed [in the documentation](https://latextools.readthedocs.io/en/latest/keybindings/), which is probably the best source.

Regarding the autocomplete thing: unfortunately, ST doesn’t really provide any notification of when an autocomplete entry is inserted, so we can’t really react to the autocompletion of `\cite{}`. In other words, it’s a limitation of ST rather than a design choice.

**Comment by jackendrick** [comment]
Ok thanks!
