### ISSUE TITLE
First install - System Check missing all programs

### ISSUE THREAD

**Issue by dwendt195** [SublimeText/LaTeXTools#1387]
I am trying to install LaTeXTools on a new laptop (Windows 10), but the System Check is unable to find any of the programs needed and I am unable to build files. I am using MiKTeX, I double checked that it was installed with all the necessary packages and it is in my PATH. When I try to build a file (which worked when I used LaTeXTools on my previous laptop), I get the following error:

```
TraditionalBuilder: Engine: pdflatex. Invoking texify... 

COULD NOT COMPILE!

Attempted command:texify -b -p --engine=pdftex --tex-option="--synctex=1" math_pset_9.tex
Build engine: Traditional Builder
```

This is the result of a System Check: 

![image](https://user-images.githubusercontent.com/42623191/50550393-385e1280-0c35-11e9-9afa-0f88b5e1b12c.png)

How can I get LaTeXTools to recognize these programs in MiKTeX and build my files?

**Comment by ig0774** [comment]
Close and restart SublimeText. You seem to have installed MiKTeX after SublimeText was opened, so ST doesn’t see the changed PATH.

**Comment by dwendt195** [comment]
I tried that, it didn't fix the problem unfortunately. I also tried uninstalling and reinstalling LaTeXTools, and then restarted my computer, and nothing has changed...

**Comment by r-stein** [comment]
You can open the ST console ``ctrl+` `` and type

```py
import os; os.environ['PATH']
```

to check the system path, which is used to execute programs. This should include the path to miktex. If it doesn't you can still add it to the [`texpath` setting](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.8/LaTeXTools.sublime-settings#L219-L220)

**Comment by dwendt195** [comment]
MiKTeX was in the path, but after looking closely I figured out that there was a quote at the end of the address that shouldn't have been there, but somehow got added the path, so I edited that and now everything works. Thanks for your suggestions!
