### ISSUE TITLE
Windows flash out during the editing of math equation

### ISSUE THREAD

**Issue by zzf-technion** [SublimeText/LaTeXTools#1388]
Hello, @kemayo @r-stein,
I have used sublime text 3176 on windows 10. Each time when I edit the equation inside $x$ or $$x$$ or equation environment, because of the math live preview, some windows(pdflatex.exe, convert.ext, etc.) would flash out very quickly, then I can continue to input. Even I disabled the math preview, still have the issue. Could you figure out how to avoid the annoying problem?  

I guess the problem lies in the process of converting the equations into png, i.e. LaTeX=>PS=>PDF => png, some settings with the GhostScript or magick image. 
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\mgs.EXE' -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dQUIET -q -sDEVICE=pngalpha -dLastPage=1

Hope to receive your reply. Thank you

**Comment by r-stein** [comment]
We actually do have some special logic to avoid that console popup in windows [here](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.8/latextools_utils/external_command.py#L148-L154).
In addition mgs.exe/gswin32c.exe/gswin64c.exe should not have their own popup. If you disable the math preview (visible_mode == "none") it should not render any images at all, so it should not trigger any command.
Is there some related output in the ST console ``ctrl+` ``?

**Comment by zzf-technion** [comment]
Hello, I solved this problem by removing the package- La​Te​X Equation Preview, thank you very much for your answer. So the popup in windows is not caused by LaTextools but Latex equation preview.
