### ISSUE TITLE
After \includegraphics, autocomplete shows the wrong folder

### ISSUE THREAD

**Issue by nickriches** [SublimeText/LaTeXTools#1390]
Hi. I love the autocomplete feature which identifies graphics files in the current folder after "autocomplete". However, this appears to be broken. It is looking for graphics files in the wrong folder (the folder of a file which was opened in another tab). Closing and opening Sublime text does not appear to make a different. Is there any way to restore the correct behaviour?

**Comment by nickriches** [comment]
P.S. setting \graphicspath does not appear to help.

**Comment by nickriches** [comment]
Okay - this is resolved. It was in fact looking in the right folder!!

**Comment by r-stein** [comment]
If it was looking into the wrong folder and it used the right folder later this might be a caching issue. For performance reasons we don't scan the whole document for `\graphicspath` on each autocomplete, but use a cached version of the document. The cache is by default invalidated after 30 Minutes.

**Comment by nickriches** [comment]
Brill. thanks.
