### ISSUE TITLE
"No bib files found!" when importing preamble with bibliography

### ISSUE THREAD

**Issue by mafw** [SublimeText/LaTeXTools#1394]
I'm having trouble getting autocompletion to work when I import my .sty file containing the bibliography. 

I'm working on a larger project and import a .sty file at the beginning of my main .tex document using `\usepackage{preamble_name.sty}`.  Unfortunately, it seems that this confuses autcompletion as it returns a message saying no bib files were found. This happens when trying to cite in the main file, or any of the subfiles.  

I'm pretty sure it is the importing of the .sty file that creates the issue as I've tried including the bibliography in the main .tex file---which after some cache clearing and deleting temp files allows me to use autocompletion as expected when using `\cite{refkey}`. This behavior is consistent across all the .tex files in the project.

Is there a way to fix this issue? It is not a major inconvenience for me to include the .bib file in the main .tex file but I would be neat to keep it in the .sty file. 

Thank you for your attention and help!

**Comment by r-stein** [comment]
LaTeXTools runs a relatively (compared to LaTeX complexity) simple [analysis](https://github.com/SublimeText/LaTeXTools/blob/st3-3.15.1/latextools_utils/analysis.py) over our tex file, which is used to retrieve information about the file.
To create the `\cite{...}` autocompletion this analysis is [used](https://github.com/SublimeText/LaTeXTools/blob/st3-3.15.1/latex_cite_completions.py#L225-L253) to search for bibliography commands. However this analysis will ignore `\usepackage{...}` links and therefore it does not know about your bibliography.
A workaround would be to use the command package and write the bibliography command inside a `\begin{comment}...\end{comment]` block or behind `\end{document}`.

**Comment by mafw** [comment]
Thank you for your quick response!

I think I'll just put the bibliography in the main file. But I'm curious about your proposed workaround, I couldn't find any reference to a LaTex package called command?

**Comment by r-stein** [comment]
Sorry I meant the [comment package](https://ctan.org/pkg/comment) not the command package. That package allows you to insert block comments..

**Comment by mafw** [comment]
I see, seems like a good alternative. Thank you for your help!

Closing this now.
