### ISSUE TITLE
Cite crashes when \bibliography ends with a comment containing an Umlaut

### ISSUE THREAD

**Issue by RobertHilbrich** [SublimeText/LaTeXTools#14]
I have the following line in my Latex code:

" \bibliography{literatur}	% Sie benötigen eine *.bib-Datei "

Cite-completion in ST2 does not work, as it crashes with the following error message:

" UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 34: ordinal not in range(128) "

Line 100 says:

"print bib_command"

Apparently, the umlaut in the comment is unexpected for bib_command. After I put a comment sign in front of this line, everything worked again...

Best regards,

Robert

**Comment by ig0774** [comment]
I think we've disabled the line in question. In any case, this error no longer happens.
