### ISSUE TITLE
How to set 'Latex - Basic Builder - XeLaTex' as default builder?

### ISSUE THREAD

**Issue by OpenWaygate** [SublimeText/LaTeXTools#1402]
I compile latex with `Latex - Basic Builder - XeLaTex` most of the time, is there a way to set it as default, or place it in the first place in the figure?

<img width="249" alt="1" src="https://user-images.githubusercontent.com/27287694/55671625-a5ccaf80-58c4-11e9-982b-c76c6a63ea53.png">

**Comment by r-stein** [comment]
You can change the settings for the default variant inside the builder block of the LaTeXTools settings: https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.8/LaTeXTools.sublime-settings#L387-L426
I.e. set `"builder": "basic"` and inside the builder settings block (**not** platform specific)`"program": "xelatex"`

**Comment by OpenWaygate** [comment]
Thank you, that's just what I need!

**Comment by r-stein** [comment]
No problem, I will then close the issue
