### ISSUE TITLE
Tab auto-complete not included in *.sublime-completions files

### ISSUE THREAD

**Issue by NeoFantom** [SublimeText/LaTeXTools#1407]
I defined a auto complete map in math environment as
```
par -> \\partial
```
But when I type `par+tab`, it completes to `paragraph`. How ever this completion is not even included in any sublime-completions file. Why this happened? How can I cancel this default completion?

**Comment by ig0774** [comment]
This shortcut is provided by the [Paragraph.sublime-snippet](https://github.com/sublimehq/Packages/blob/master/LaTeX/Snippets/Paragraph.sublime-snippet) file in the LaTeX default package included with ST. (You can see [here](http://docs.sublimetext.info/en/latest/extensibility/completions.html#sources-for-completions-and-their-priorities) for details on where ST loads completions from).

I *think*, though cannot be sure, that you can change this by using the [Package Resource Viewer](https://packagecontrol.io/packages/PackageResourceViewer) to edit the `Paragraph.sublime-snippet` file and changing the tab trigger to a blank.
