### ISSUE TITLE
Why aux_directory option doesn't work well for me?

### ISSUE THREAD

**Issue by Ice0cean** [SublimeText/LaTeXTools#1409]
I use the texlive before. By setting the option “output_directory” to temp and option  copy_output_on_build to true, all the aux files such as .log, synctex are moved to a sub folder temp, and only the pdf file is in the current folder. Now I want to use MikTeX. I have set  option aux_directory to temp. But the aux files such as .log, .synctex are still in the current folder. I expect that all the aux files are moved to the subfolder as the case of the texlive. I use traditional builder. For miktex it is texify.

How can I make all the output files except for pdf file stored in a subfolder when using MikTeX?

Thanks for your response.

**Comment by r-stein** [comment]
Output directory does not seems to work with texify:

https://github.com/SublimeText/LaTeXTools/issues/1087#issuecomment-296436177

You may try to execute it with the Basic Builder
