### ISSUE TITLE
can't install latextools in sublime text 3 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [SublimeText/LaTeXTools#1414]
Can't install latextools in sublime text 3 (Ubuntu 18.04 system).

Already installed Package Control, and during the installation, 'latextools' appeared in 'in_process_packages' but without any further responses after that.

**Comment by zhiqiangzhongddu** [comment]
update more detailed information:

Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' is not available
Package Control: The dependency 'python-jinja2' could not be installed or updated
ignored packages updated to: []

**Comment by r-stein** [comment]
I would just retry it in a few hours. jinja2 is a bitbucket dependency and there are sometimes issues with installing dependencies from bitbucket.

**Comment by r-stein** [comment]
Note you can also manually install those dependencies:
In sublime text select browse packages to get into the packages folder and add the dependencies there:
- `markupsafe` from https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-markupsafe/downloads/
- `python-jinja2` from https://bitbucket.org/teddy_beer_maniac/sublime-text-dependency-jinja2/downloads/

this should result in a directory path like `python-jinja2/all/jinja2/<python files>`

**Comment by r-stein** [comment]
related issue https://github.com/wbond/package_control/issues/1430

**Comment by zhiqiangzhongddu** [comment]
thanks, after manually installed missed packages, it works now.
