### ISSUE TITLE
No bib files found using \addbibfile{bibliography.bib}

### ISSUE THREAD

**Issue by nunocalaim** [SublimeText/LaTeXTools#1415]
I tried clearing the sublime cache, tried renaming the main file.

My chapters are inside a folder

I have the magic !Tex command in the first line

my bibliography is called like this:
\addbibfile{bibliography.bib} %in the preamble
\printbibliography % before end document

What can I do?

**Comment by ig0774** [comment]
Where is the bibliography.bib file relative to your main tex file? Is the bib file stored in the same folder as the chapter?

**Comment by nunocalaim** [comment]
The file is in the folder of the main tex file and not inside the chapters
folder

ig0774 <notifications@github.com> escreveu em ter, 2/07/2019 às 22:47 :

> Where is the bibliography.bib file relative to your main tex file? Is the
> bib file stored in the same folder as the chapter?
>

**Comment by ig0774** [comment]
How are the chapter files imported into your main file? Are you using `\input{}`, `\include{}` or something else?

**Comment by nunocalaim** [comment]
I'm using a template which inlcudes chapters as
`
\chapterfile{filename.tex}`

where in the template.cls we have
`
\newcommand{\chapterfile}[1]{\listgadd{\novathesis@chapter@list}{#1}}`

this is the template I'm using [NOVAthesis](https://github.com/joaomlourenco/novathesis)

**Comment by flaviomartins** [comment]
You need to use \addbibresource{bibliography.bib} directly to get autocomplete.

\addbibfile is a macro in the template that is defined as
`\newcommand{\addbibfile}[1]{\addbibresource{#1}}`
