### ISSUE TITLE
How to build with latex engine

### ISSUE THREAD

**Issue by jayhathaway** [SublimeText/LaTeXTools#1416]
I am using ST3 with latextools on windows and texlive 2019. I have been scouring the documentation and can't figure out how to build with the ordinary latex engine (as in, NOT pdflatex).

**Comment by ig0774** [comment]
So, just to preface this response, we don't have proper support for DVI files, so if you're using simple latex, you'll need to output to PDF if you want to use the viewer integration, etc.

The easiest thing to do would be to use the script builder to run `latex` and then, when its finished, run `dvipdfm`. To do that you'd need something like this in your LaTeXTools.sublime-settings file (or project file, etc.):

```json
"builder": "script"
"builder_settings": {
    "windows": {
        "script_commands": [
            "latex -interaction=nonstopmode -synctex=1", 
            "bibtex $jobname",
            "latex -interaction=nonstopmode -synctex=1",
            "latex -interaction=nonstopmode -synctex=1",
            "dvipdfm $jobname.dvi"
        ]
    }
}
```
