### ISSUE TITLE
Prevent unsafe settings of "temp_files_exts"

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1417]
If someone added some idiot exts (e.g., ".tex" and ".pdf") to "temp_files_exts", when he press "Ctrl+L, Delete", it would be a disaster.  Is there a mechanism (like a whitelist) to prevent such dumb settings?

Thank you so much for your reading.

**Comment by ig0774** [comment]
Not currently. While I can see there could be some value to something like this, I would be hesitant to make too many assumptions about what other peoples' projects look like.... Maybe (though this is a stretch) the source code is all in `.ltx` files and the `.tex` files are generated. In a different vein, it's pretty harmless and, in some cases, maybe even desirable to treat `.pdf` files as temporary files. They can, after all, be easily regenerated, assuming the `.tex` source is available.

**Comment by Romeoly** [comment]
Some authors prefer to include PDF-images in their tex files, rather thatn JPG or PNG, because JPG and PNG are raster images.  Such PDF files are generated with other tools (like Mathematica). If such PDF files are deleted, it would be troublesome to regenerate them.

**Comment by Romeoly** [comment]
Would "temp_files_exts_confirmed" be helpful? 

I mean, it someone wants to modify "temp_files_exts",  he must do it twice. Just like changing the password.

**Comment by ig0774** [comment]
I'd honestly think it's more worthwhile to add a confirmation prompt to the "Delete Temp Files" command that says "Are you sure?". We could even generate a list of affected files...

**Comment by Romeoly** [comment]
> 
> 
> I'd honestly think it's more worthwhile to add a confirmation prompt to the "Delete Temp Files" command that says "Are you sure?". We could even generate a list of affected files...

I think this is a good idea.
