### ISSUE TITLE
Is there an option to force building PDFs?

### ISSUE THREAD

**Issue by Romeoly** [SublimeText/LaTeXTools#1418]
When `Ctrl+B` is pressed, LT calls `latexmk` (taking TeX Live as an example) and compiles the TeX file. If the TeX file is not changed, `latexmk` will skip compiling the TeX file, and show the PDF file (if exists) directly.  

However, in some occasions, if an exterior file (e.g., a BIB, a JPG, or an `\include`ed file)  is changed, we have to rebuild the PDF file. In this case, pressing simply `Ctrl+B` won't work. 

To solve this problem, I type some space-bars  and then `Ctrl+S`. Then `Ctrl+B`. 

Is there another way to do this? 

Thank you so much for your reading.

**Comment by ig0774** [comment]
Personally, at least for small documents, I use `Ctrl+L, backspace`, which usually deletes enough to force a rebuild.

**Comment by Romeoly** [comment]
Thanks.
