### ISSUE TITLE
KeyError: 'bst' reported in latex_installed_packages.py

### ISSUE THREAD

**Issue by dnaihao** [SublimeText/LaTeXTools#1425]
Since my sublime cannot fill the bracket for usepackage automatically, I ran ```LatexTools: Build cache of LaTex packages``` manually but got
![Latextools-key-error](https://user-images.githubusercontent.com/46325823/62827947-53203e80-bba9-11e9-934e-40da6298e8c8.png)

Then I investigated into the file latex_installed_packages.py. After I changed this line
![Latextools-fix](https://user-images.githubusercontent.com/46325823/62827958-8c58ae80-bba9-11e9-910f-97a00038121b.png)
and ran ```LatexTools: Build cache of LaTex packages```, the autofill for usepackage  worked successfully:
![Latextools-fixed](https://user-images.githubusercontent.com/46325823/62827989-b0b48b00-bba9-11e9-9b9e-2ebdaaa1f875.png)

So could we change the method to
![Latextools-fix-all](https://user-images.githubusercontent.com/46325823/62828018-21f43e00-bbaa-11e9-8c5a-1b995bb49ce1.png)
in latex_installed_packages.py?

If you don't mind, could I commit to Latextools to fix this issue?

**Comment by ig0774** [comment]
The default should probably be `[]` rather than `''`. Other than that, feel free to create a PR.

**Comment by dnaihao** [comment]
Sure thing. Could you assign me the permission to this repo?
