### ISSUE TITLE
output_directory not recognized with TexLive-2019 (Mac)

### ISSUE THREAD

**Issue by mjm31** [SublimeText/LaTeXTools#1426]
Any output_directory setting other than "" does not get recognized on one of my Macs.  It works fine on the other Mac using the exact same LaTeXTools.sublime-settings file.  The only difference between the 2 Macs that I can see is that one of them is running TexLive-2018 (the one that works) and the other one is running TexLive-2019.  Is there a known problem setting output_directory with that newer version of LaTeX?

**Comment by ig0774** [comment]
`output_directory` works perfectly well on my Mac with TeXLive 2019. Is there any output to the output console or the Sublime console?

**Comment by mjm31** [comment]
Thanks for the very quick response!  The output I get is as if I just ran pdftex for the first time.  All the build files go in the local directory (with the .tex file) -- even though I've set the output_directory to something other than "".  But the builder is looking for the files in the output_directory so it doesn't find them (so all bib and counter references are missing).  If I move all the build files into the output_directory, then the pdf file is built with all the proper references (but the new build files still go in the local directory).

Sounds like it isn't a problem with the new TexLive-2019 though...

**Comment by mjm31** [comment]
I figure out the problem!   I had an old .latexmkrc configuration file in my $HOME directory.  Weird thing is that I had the identical configuration on my other Mac -- and that didn't cause any problem on that system.

**Comment by do-mart** [comment]
I have a similar problem with LatexTools 3.15.1 and TexLive 1.49.  If I set the output directory to a specific path with `"output_directory": "tempo"`, all the files are created in the same folder as the main tex file. On my other Mac running the same up-to-date software, the output directory is recognized and files are created in a new `tempo` folder. (I don't have any `.latexmkrc` or other config files in my home directory. In fact, the `-output-directory` option work if I compile the main tex file directly on the command line.)
