### ISSUE TITLE
Autocompletion not working with Sublime 3 build

### ISSUE THREAD

**Issue by weixuanzhang** [SublimeText/LaTeXTools#1429]
I noticed that the autocomplete functionality from LatexTools (autocomplete when typing \cite{ or \ref{) is not working, although "cite_auto_trigger" and "ref_auto_trigger" are set to true. My configurations:
Sublime Text Build 3126
LatexTools Plugin version: 3.14.1 (2017-06-01)
OS: Ubuntu 16.04
Thank you very much!

**Comment by r-stein** [comment]
Can you open the Sublime Text console ``ctrl+` `` and check whether errors occur? Did you overwrite the `{` keybinding in our user keybindings?

**Comment by weixuanzhang** [comment]
I reset the keybindings in LatexTools to default, and found the following definition of "{" keybinding in the general keymap. Could that be the problem?
![Screenshot from 2019-08-28 11-28-57](https://user-images.githubusercontent.com/8019238/63844128-e8804880-c987-11e9-9a48-74388c5620ce.png)

**Comment by r-stein** [comment]
Yes that is the problem. You have defined a keybinding for `{` in our user keybindings, which take precedence over the keybinding from LaTeXTools.

You may
1. Copy the `{` keybindings from LaTeXTools *below* those in our user file
2. You can add this: `{ "key": "selector", "operator": "equal", "operand": "- text.tex.latex" },` to the context in the first two keybindings. This will disable those keybindings inside latex files
3. Do something different to change the keybinding precedence

**Comment by weixuanzhang** [comment]
Works like a charm! Thank you very much! I'll close the issue.
