### ISSUE TITLE
Bibtex not working when called from a different file

### ISSUE THREAD

**Issue by shimianto** [SublimeText/LaTeXTools#1431]
I am using the LaTexTools package on Sublime 3 on my MacOS. In order to keep my latex documents organized I like to have each of my sections on a different file and I call them from the main file (the one that is being compiled) with the `\input` command. All works fine except when I call the `\bibliography` command from a file that is not the one being compiled, it does not work. If I put it back on the main file it works just fine.

**Comment by deathaxe** [comment]
The following is working in v4: cite completions and building pdf document.

### main.tex

```
\documentclass[a4paper]{book}

\begin{document}

\section{A Section}

This is intro of \cite{foobar}.

\input{ch1}
\input{appendix}

\end{document}
```

### ch1.tex

```
%!TEX root = main.tex

This is \cite{foobar}.
```

### appendix.tex

```
%!TEX root = main.tex

\bibliographystyle{amsalpha} %The style you want to use for references.
\bibliography{main}
```

### main.bib

```
@BOOK{foobar,
	author = {Author/Editor},
	title = {Title},
	year = {Year}
}
```
