### ISSUE TITLE
A window popup when typing the equation

### ISSUE THREAD

**Issue by vietanhle0101** [SublimeText/LaTeXTools#1436]
A window always pop-up when typing or editing the equation (It occurs very fast, but slow down my coding speed). The window related to pdflatex.exe. Even when I change the "preview_math_mode" to "none"
Let me know to fix it.

**Comment by r-stein** [comment]
You don't have [LaTeX Equation Preview](https://packagecontrol.io/packages/LaTeX%20Equation%20Preview) installed?

If the preview mode is set to none, no preview should appear. If it is previewing it should not slow down your writing speed, because most work is done on different threads.

**Comment by vietanhle0101** [comment]
![Untitled](https://user-images.githubusercontent.com/51708449/66947327-8d71e600-f007-11e9-88b7-f5179347d9c4.png)
here is the screenshot, this window always appears. How to prevent it.

**Comment by r-stein** [comment]
Yes thats a typical window, which appears when the pdflatex command is called from the python subprocess module. We do actually set a flag to prevent it [here](https://github.com/SublimeText/LaTeXTools/blob/master/latextools_utils/external_command.py#L175-L176).

Are you sure you don't have LaTeX Equation Preview installed? Such issues usually come from that package. Please press `ctrl+shift+p` and select `Package Control: List Packages` and search for `LaTeX Equation Preview`.

**Comment by r-stein** [comment]
You are welcome
