### ISSUE TITLE
No pdf file generated despite no error

### ISSUE THREAD

**Issue by vietanhle0101** [SublimeText/LaTeXTools#1437]
![2019-10-17_105117](https://user-images.githubusercontent.com/51708449/67034179-0fc3de00-f0cc-11e9-80b3-1c066796a5de.png)
I am struggling with this problem. Does anyone help me to fix it? Thank you.
I dont understand what does (Log parsing issues. Disregard unless something else is wrong.) mean.

**Comment by r-stein** [comment]
The message `(Log parsing issues. Disregard unless something else is wrong.)` means that LaTeXTools was not able to parse the rest of the log file.
Unfortunately there is no well defined tex-log format and LaTeXTools just heuristically tries to guess its best to detect errors and warning, which leads to a very complex [code](https://github.com/SublimeText/LaTeXTools/blob/master/parseTeXlog.py), that does not work in all cases.

I recommend to look at the full log file and try to find the issue yourself.
