### ISSUE TITLE
How to use minted package with latextools?

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/LaTeXTools#1439]
From https://github.com/gpoore/minted/issues/81 "missing pygments output", we see that minted requires to know where the `outputdirectory` is. 

Then, I can only make it work with LatexTools, by editing my latex code to this:
```latex
\usepackage[outputdir={F:\SublimeText\Data\Cache\LaTeXTools\abe5f755bb73246f4f53824425b74d3e}]{minted}
```

**Comment by r-stein** [comment]
Is your problem to enable it with the output directory option `cached` or to enable it in general?

**Comment by evandrocoan** [comment]
There is a long time I configured LatexTools, so I am not sure. But I can say that this problem only happens when using the pdflatex with some option like `--output-directory`. For example, if I call pdflatex with `--output-directory=/tmp/latex`, I must import the minted package with `\usepackage[outputdir={/tmp/latex}]{minted}`

**Comment by evandrocoan** [comment]
LatexTools could use a fixed cache directory. In my project I always import minted with a relative path to my actual project as `\usepackage[outputdir={setup/cache}]{minted}` because I always have a local directory on my project called `setup/cache`. Then, if latex tools used my project local cache directory `setup/cache`, instead of this random cache directory as `...\Data\Cache\LaTeXTools\abe5f755bb73246f4f53824425b74d3e`, then, the problem would be fixed.

**Comment by ig0774** [comment]
LaTeXTools output_directory directives support relative paths (from the root file), so you should really just need:

`%!TEX output_directory=setup/cache` (or the same value as a setting depending on your setup).

**Comment by evandrocoan** [comment]
Thanks! Problem solved. The same way I set `\usepackage[outputdir={setup/cache}]{minted}` in my latex source file, I can also set `%!TEX output_directory=setup/cache` at the top of my latex source file.
