### ISSUE TITLE
#Sublimetext #LaTeXTools not working 

### ISSUE THREAD

**Issue by marlytatiana** [SublimeText/LaTeXTools#1450]
Hi everyone, 
I've been working with LaTeXTools recently, doing basic stuff. I stopped for one or two weeks, and now nothing is running. As you can see in the image below. I haven't changed the code, nor move files. Some ideas of what can I do about it? Perhaps reinstall the whole thing?

:)
Thanks for the comments.

![errrors](https://user-images.githubusercontent.com/30057653/69007412-c0c4cf00-093d-11ea-8c5a-221c15cc9d91.png)

**Comment by r-stein** [comment]
It seems to be something wrong with you document. Did you always build with xelatex? You may just have selected the wrong builder.

**Comment by marlytatiana** [comment]
> It seems to be something wrong with you document. Did you always build with xelatex? You may just have selected the wrong builder.

Oh yes, you're right. I have both builders pdflatex and xelatex, and I didn't realize I was building with xelatex instead of pdflatex, which is the one I want working with. I still don't understand the difference between those two. 
Thank you, btw 
:)

**Comment by r-stein** [comment]
xelatex is a little bit different and its main advantage of it is the support for asian languages.
