### ISSUE TITLE
Bibliography autocompletion with multiple bib files

### ISSUE THREAD

**Issue by owendiba** [SublimeText/LaTeXTools#1452]
Using biblatex with multiple bib files, the autocomplete feature for the cite command only works for the first bib file, not the second. This is especially annoying because if I try and type the key for an entry in the second bib file it just autocompletes to the closest approximation in the first file. Is there a way to fix this other than to just merge the two bib files?

**Comment by r-stein** [comment]
Sorry for the late reply. In general the potential bib files are merged together and all bib files are parsed and used for the completion. We would need to see how the bib files are included and check what is missing in the current implementation.

**Comment by deathaxe** [comment]
It appears like a caching issue. Newly added bibliographies are not picked up by auto completions, until document cache is rebuild.

It works after calling `LaTeXTools: Clear Document cache` from command line.

**Comment by deathaxe** [comment]
Fixed by 149a357e6db8d98f060085afb1e19463f94f1bea
