### ISSUE TITLE
LatexTools adds newline at cursor on build

### ISSUE THREAD

**Issue by zsiegel92** [SublimeText/LaTeXTools#1456]
Not always, but quite frequently, LatexTools adds a newline character exactly at my cursor (not at the end of document) upon build. It clearly adds the newline *after* the build begins, because it doesn't affect the build, though it often causes a typo that interferes with my next build.

**Comment by r-stein** [comment]
That's weird and I assume it is some interferences with other settings/plugins. After the build process LaTeXTools opens the selected section in the pdf viewer. This shifts the focus to the pdf viewer. Afterwards LaTeXTools takes the focus back to sublime text. I assume somewhere in this process the insertion is triggered, but I don't see how this could be the case.

For further analysis I suggested that you open the ST console (View > Show Console) and run the command

```
sublime.log_commands(True)
```
This will log every command, and if this happens again, you can check the console again.

**Comment by zsiegel92** [comment]
@r-stein Thank you for this thoughtful response! Please mark this closed - I built a build system that opens the PDF in Chrome via Applescript, and the bug was caused by how I wrote that.

PS - if you want a description of how I use Chrome as my viewer (with forward sync to the correct line! And it finds the tab if it's already open rather than opening a new tab!) please ask!
