### ISSUE TITLE
\cite and \ref fills place {} in the wrong place

### ISSUE THREAD

**Issue by johnlb** [SublimeText/LaTeXTools#1458]
When I type ``\cite{`` and the autofill window pops up, whether or not I choose an item from the list, it places the brackets one character to the left. So, I end up with ``\cit{text}e``

If I already have a character to the right of the cursor when I call it, it will actually return the correct placement.

This is a fresh install of LaTeXTools.

**Comment by r-stein** [comment]
do you have a vim emulator in use?

**Comment by johnlb-delta-sigma** [comment]
Haha I do indeed. Using Vintageous.

**Comment by johnlb** [comment]
Haha I do indeed. I'm using Vintageous.

**Comment by r-stein** [comment]
looks like #1329, closing as duplicate. There is already a PR #1457 to solve this, which will hopefully be merged in the next days
