### ISSUE TITLE
Cannot find LaTeX-cwl folder for autocompletion

### ISSUE THREAD

**Issue by phatsp** [SublimeText/LaTeXTools#1468]
I have installed LaTexTools as well as LaTex-cwl package and they seem to work fine. However, I want to add customized autocompletion files of a package (i.e tikz package). According to the documentation, it says that I need to copy the .cwl file to "User/cwl/  folder" (or "User/LaTex-cwl/")  but I couldn't find them anywhere. Do I have to create a folder under "Sublime 3/Packages/User" then name it "cwl" to copy the .cwl files
![image](https://user-images.githubusercontent.com/43247670/76194594-0ffa7c80-6219-11ea-871d-37457861ee6c.png)
![image](https://user-images.githubusercontent.com/43247670/76194658-2f91a500-6219-11ea-8fc5-93ba4a1164d5.png)

**Comment by r-stein** [comment]
> Do I have to create a folder under "Sublime 3/Packages/User" then name it "cwl" to copy the .cwl files

Yes, you have to create the folder on your own. Afterwards you may need to restart Sublime Text to empty the cached cwl files. (See [file selection source code](https://github.com/SublimeText/LaTeXTools/blob/st3-4.0.0-alpha.9/latex_cwl_completions.py#L467-L468)).
