### ISSUE TITLE
Expand key binding Shift-Enter to add \item in paralist-environments

### ISSUE THREAD

**Issue by pjanck** [SublimeText/LaTeXTools#1471]
The current key binding "Shift-Enter" adds `\item` only inside vanilla list-like environments (itemize, enumerate etc.). 

My wish would be to expand the supported environments with those from `paralist` package ([Paralist documentation](https://ctan.org/pkg/paralist)).

I assume the correct place to code would be [here](https://github.com/SublimeText/LaTeXTools/blob/66059c66b9c68575e384ee5bd814d6448b5753a0/Default%20(Windows).sublime-keymap#L422), but I am not fluent in ST or Python syntax to correct it myself.

#1369 may be related, however introducing the following into "Key bindings - User" of LaTeXTools package did not add the functionality as expected.
```json
{  "keys": ["shift+enter"], 
   "command": "insert_snippet", 
   "args": { "contents": "\n\\item $0" }, 
   "context": [
     { "key": "selector", "operand": "text.tex.latex" },
     { "key": "latextools.env_selector", "operand": "asparaitem"},
   ]  },
```

**Comment by r-stein** [comment]
This feature is still in the prereleases (We will hopefully release the new version soon.): https://github.com/SublimeText/LaTeXTools#prereleases

Note that the syntax of the env selector is based on the usual selector syntax and works with several environments, e.g.:

```json
    {
        "keys": ["shift+enter"], 
        "command": "insert_snippet", 
        "args": { "contents": "\n\\item $0" }, 
        "context": [
            { "key": "selector", "operand": "text.tex.latex" },
            { "key": "latextools.env_selector", "operand": "asparaitem , inparaitem"},
        ]
    },
```

**Comment by pjanck** [comment]
@r-stein Nice! Allowing for prerelease version and updating the LaTeXTools package did the trick. Thank you for your fast response!
