### ISSUE TITLE
No option to build with LaTeXTools in Sublime 3 on Windows 10 with MikTeX

### ISSUE THREAD

**Issue by absconditus87** [SublimeText/LaTeXTools#1479]
Hi,

I followed the installation instructions in the documentation and installed LaTeXTools on Windows 10 for MikTeX, Sumatra, and Sublime 3.

When I run the system check everything shows as available except for the mathtools and magick.

When I try to build a LaTeX file using Ctrl+Shift+B, I don't get any options for LaTeXTools.

![image](https://user-images.githubusercontent.com/68182085/87242308-2701e300-c434-11ea-957c-7dc4576b4c73.png)

How can I get this to work?

Thank you.

**Comment by r-stein** [comment]
The build system is based on the current syntax. It seems that the selected syntax of the file is python.

Press Ctrl+shift+P and write `Set Syntax: LaTeX`, afterwards it should work

**Comment by absconditus87** [comment]
> 
> 
> The build system is based on the current syntax. It seems that the selected syntax of the file is python.
> 
> Press Ctrl+shift+P and write `Set Syntax: LaTeX`, afterwards it should work

Thanks for the suggestion. I tried it but it didn't work. I still only get the Python options.

**Comment by r-stein** [comment]
Then you may have manually selected the build system. *Tools > Build System* and then if Python is selected select *Automatic*

**Comment by absconditus87** [comment]
This did it. Thank you!

**Comment by r-stein** [comment]
No problem :)
