### ISSUE TITLE
disabling auto-pair $ in User settings not working

### ISSUE THREAD

**Issue by kiwifreak** [SublimeText/LaTeXTools#1480]
I have the same issue as described in

#282 

I have copied the file Default (OSX).sublime-keymap to my user directory (ST 3/Packages/User) and commented out the four blocks of code concerning the auto-pair $ option.

After restarting sublime text the auto-pair is not disabled however.

I am not so familiar with Sublime Text. Any ideas?

**Comment by deathaxe** [comment]
Commented out settings in `Packages/User/<name>.sublime-keymap` file are like not being present, causing corresponding rules from `Packages/<package>/<name>.sublime-keymap` to still apply.

You have to create a real override.

As of ST4, empty command can be used to clear existing bindings.

Example:

```
	{
		"keys": ["$"],
		"command": "",
		"context": [
			{ "key": "selection_empty", "match_all": true },
			{ "key": "selector", "operand": "text.tex.latex", "match_all": true },
		]
	},
```
