### ISSUE TITLE
Show images on hover when they're wrapped in a custom command

### ISSUE THREAD

**Issue by sn0wyfall** [SublimeText/LaTeXTools#1483]
I usually wrap the `\includegraphics` command inside a different command, such as `\img`, so that I can do things like centering them easily. Would it in any way be possible to show images when hovering over these custom commands that include the `\includegraphics` command? Here is an example of how I define the `\img` command:

    \newcommand{\img}[4]{
      \begin{figure}[h]
        \includegraphics[#1]{#2}
        \centering
        \caption{#3}
        \label{#4}
      \end{figure}
    }

   ...

    \img{width=5cm}{my_image}{My image}{fig:my_imae}

**Comment by ig0774** [comment]
So to generate image previews, we rely on the LaTeX syntax file for ST, in particular, on the scopes you can see [here](https://github.com/SublimeText/LaTeXTools/blob/45376f12449e32c4ad769f5baa0a75c1fa72194d/st_preview/preview_image.py#L543). While it not impossible to support a custom syntax, you'd have to create your own copy of the LaTeX syntax that sets the appropriate scopes correctly.

The other possibility would be to define a LaTeX noop command and then include the corresponding `\includegraphics` command, e.g.,

```latex
\newcommand{\nop}[1]{}

...

\img{width=5cm}{my_image}{My image}{fig:my_imae}
\nop{\includegraphics{my_image}}
```

**Comment by sn0wyfall** [comment]
Thanks for the reply! That no operation command seems to be the easiest way to get this done.
