### ISSUE TITLE
Shortcut for forward search? 

### ISSUE THREAD

**Issue by sn0wyfall** [SublimeText/LaTeXTools#1485]
I do not like the default forward search setting (`forward_sync`) which forward syncs all the time when compiling, since it messes up the way that Skim.app previews the PDF file (it scrolls randomly, for example), so I have disabled it. 

However, I'd like to use this functionality once in a while. Is there a way I can set a dedicated shortcut for forward sync to the PDF, while at the same time not having forward sync every time I build the PDF?

**Comment by ig0774** [comment]
`cmd + l, j`. Search for “forward search” in [the docs](https://latextools.readthedocs.io/en/latest/keybindings/) for more details.

**Comment by sn0wyfall** [comment]
Thanks, finally found it! I was super confused because it was called `jump_to_pdf` and I was search for "forward". Case closed!
