### ISSUE TITLE
Autocompletion for environments and stuff? 

### ISSUE THREAD

**Issue by sn0wyfall** [SublimeText/LaTeXTools#1486]
In Overleaf, when you start a new environment, such as `\begin{figure}`, you'll get a dropdown allowing you to choose from many different environments. This also happens in latex tools when including an image with include graphics or use package. 

**Question:** Is this possible with latex tools when creating environments? 

Also, in overleaf when you finish writing the `\begin{my_env}` text, after you press enter an `\end{my_env}` automatically pops up. 

**Question:** Is this behavior also supported by latextools?

**Comment by sn0wyfall** [comment]
Apparently I needed to install the `LaTeX-cwl` package

**Comment by r-stein** [comment]
Yes you need the `LaTeX-cwl` package. The completions are taken from there.
