### ISSUE TITLE
\ref autocompletion for multiple files

### ISSUE THREAD

**Issue by gawells** [SublimeText/LaTeXTools#1487]
As far as I can see `\ref` will only list labels from the open file for autocompletion. Is it possible to list from all `.tex` files in the current directory (or project), similar to overleaf?

**Comment by r-stein** [comment]
The `\ref` completion should work correctly if you have configured your tex files as a multi file document https://latextools.readthedocs.io/en/latest/features/#multi-file-documents

The underlying analysis automatically follows `\include` and `\input`

**Comment by gawells** [comment]
Hi thanks, I should've elaborated more. In this case I'm using the `xr` package for a main text and supplementary info file to refer to each other. But the two are meant to be separate documents.
