### ISSUE TITLE
-shell-escape implementation 

### ISSUE THREAD

**Issue by jakobmoenster** [SublimeText/LaTeXTools#149]
It should be possible to set the -shell-escape / write18 enable in the preference menu. 
For now I added it to the file LaTeX.sublime-build, which works as supposed.

"cmd": ["latexmk", "-cd",
				"-e", "\\$pdflatex = 'pdflatex %O -interaction=nonstopmode -synctex=1 -shell-escape %S'",
				//"-silent",
				"-f", "-pdf"],

**Comment by louwers** [comment]
Also interested in this.

**Comment by conor-byrne** [comment]
@PeterPablo Thank you! This just helped me after hours of frustration. Perhaps I just didn't use my user settings file properly but surely there's got to be a better way than editing the py files?

**Comment by juanfal** [comment]
I've added

    /Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/simpleBuilder.py:
       41:      pdflatex = ["pdflatex", "-shell-escape", "-interaction=nonstopmode", "-synctex=1"]

    /Users/me/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/traditionalBuilder.py:
       19:              "-e", "$pdflatex = '%E -shell-escape -interaction=nonstopmode -synctex=1 %S %O'",


so that `minted` package, which calls python to colour source listings, can do its job

Thanks for the help

**Comment by ig0774** [comment]
This is now more or less available by default through the `options` builder setting or by using the `%!TEX options` setting, though its up to the builder to take advantage of the feature, which only the traditional builder does.
