### ISSUE TITLE
using "\comment" on latex breaks syntax highlight editor

### ISSUE THREAD

**Issue by LMBertholdo** [SublimeText/LaTeXTools#1491]
Every time I use "\comment{ ... }"  syntax highlight stop working and all following text go as a comment (
[Screen Shot 2020-09-02 at 23.54.27.pdf](https://github.com/SublimeText/LaTeXTools/files/5165870/Screen.Shot.2020-09-02.at.23.54.27.pdf)

Any idea how to fix this? 

I am using this definition on tex
 \renewcommand\comment[1]{{\color{blue} \sffamily [xxx:  #1]}}

**Comment by r-stein** [comment]
This is the syntax highlighting for the comment package. I think it ends with \endcomment.
Unfortunately the highlighting is static and we just wanted to include often used packages. Therefore you will need to edit Tyne syntax file top change this.
