### ISSUE TITLE
[ubuntu][ST3] Unable to use pdflatex to compile document; always uses latexmk which is not found

### ISSUE THREAD

**Issue by bouncinglime** [SublimeText/LaTeXTools#1492]
I have installed and successfully used texlive. Everything works properly with TeXmaker but I don't like the syntax highlighting that it does. I found LaTeXTools for SublimeText3 and am very excited to be able to use it.

However, even after changing to ``` "builder" : "simple"``` and updating the linux ```texpath``` to include the correct ```/usr/bin``` from running ```which pdflatex```, I still get an error that it's trying to use a non-existent ```latexmk``` to compile my document.

I've run a Check System, and it shows that ```pdflatex``` is installed and is the LaTeX Engine. Why is it not using that when trying to compile my tex document?

OS : Ubuntu 20.04
SublimeText : 3.2.2
LaTeXTools : 3.15.1

Please let me know if there's any other info that's helpful for troubleshooting.

Thanks!

**Comment by deathaxe** [comment]
This indicates a "traditional" build item having been selected, which overrides any `"builder"` setting.
