### ISSUE TITLE
How to disable viewer

### ISSUE THREAD

**Issue by pgimalac** [SublimeText/LaTeXTools#1498]
I have a simple question but I can't find the answer in the doc: how do I disable the viewer ?

I usually use zathura, but it doesn't give the focus back on sublime (I just want to build, see how it looks and keep writing...) even though I have `"keep_focus": true`, so I'd like to disable it, and just open zathura myself, which works well.

When I don't specify any viewer or give an empty command it just opens evince...

**Comment by deathaxe** [comment]
```

	// OPTION: "open_pdf_on_build"
	// specifies whether LaTeXTools should open the PDF file on a
	// successful build. If set to false, the PDF file won't be opened
	// unless explicitly launched using C-l,v or C-l,j
	"open_pdf_on_build": true,
```
