### ISSUE TITLE
TEXroot: Allow path expansion

### ISSUE THREAD

**Issue by sinus-x** [SublimeText/LaTeXTools#1499]
LaTeXtools does not recognise `~` as path alias and (probably) treats it as just a character. Because of that, full path is neccesary:
```json
"settings": {
  "TEXroot": "/home/user/Projects/project/main.tex"
}
```

Would it be possible to do just
```json
"settings": {
  "TEXroot": "~/Projects/project/main.tex"
}
```

**Comment by deathaxe** [comment]
The setting doesn't exist in v4 anymore.
