### ISSUE TITLE
Issue with bibliography, don't know were to look for answer

### ISSUE THREAD

**Issue by der-theorist** [SublimeText/LaTeXTools#1509]
I am using Sublime Text 3 w/ LaTexTools on a Mac.

I am working on a tex file for several weeks and all worked fine. Today, the compiling process skipped printing the library, saying the bib entries were undefined (I am using biber).
Common issue with biber/biblatex, but I checked everywhere for answers:
1. No error indicated in blg file.
2. Deleted cache & aux files several times, did not change the outcome.
3. Did not change the path to the bib file nor the bib file's name.
4. When I upload both tex file and bib file to Overleaf, the pdf compiles without any problem---and with bibliography.
5. I could not find any error in the log file.

The bug must be somewhere in LaTexTools or in my build settings. However, I did not customize and simply use the standard pdflatex basic builder.

Any help is welcome!

**Comment by ig0774** [comment]
Would you be able to share either the build log or the build output? It’s pretty hard to be able to guess what might be wrong from this description.

**Comment by der-theorist** [comment]
Thanks for getting in touch. The problem somehow solved itself, so there might have been a temporary file somewhere that blocked the bibliography from compiling. That's why I also can't copy the log resp. output file.
