### ISSUE TITLE
Math preview can't work

### ISSUE THREAD

**Issue by CDPDisk** [SublimeText/LaTeXTools#1511]
As the picture shows, 
![image](https://user-images.githubusercontent.com/32790144/104424080-db361f00-55b9-11eb-974a-e6abe99f095a.png)
ERROR: Failed to run 'pdflatex' to create pdf to preview.
I use MiKTex. Ghostscript should be included in MiKTex. 
And the system check:
![image](https://user-images.githubusercontent.com/32790144/104424543-7af3ad00-55ba-11eb-8391-d3851d46e318.png)
The packages for equation preview preview and mathtools are missing, but I don't know how to install them.

And another problem, I have added the ImageMagick to the path, but system check still can't find it. I have tried to restart my computer.
![image](https://user-images.githubusercontent.com/32790144/104424817-d2921880-55ba-11eb-9465-39c8c6cae556.png)

**Comment by CDPDisk** [comment]
I have installed the package in MiKTex. But the math preview still can't work and have the same error. And the ImageMagick is missing as well.

**Comment by deathaxe** [comment]
System check results clearly state missing `preview` package.

That's not related with LaTeXTools
