### ISSUE TITLE
Autocompletion on Sublime 4 doesn't insert backslash

### ISSUE THREAD

**Issue by rotmaus** [SublimeText/LaTeXTools#1517]
Then using built-in autocompletion (typing backslash) backslash itself is deleted after inserting the autocompletion text.
![sublime4](https://user-images.githubusercontent.com/3464482/112967378-82ebd380-914b-11eb-9878-9227d4cda462.gif)

**Comment by octiler** [comment]
Duplicate of #1506

**Comment by maurice-schleussinger** [comment]
This issue is resolved with the ST 4 beta release, see the README on how to install it.

**Comment by deathaxe** [comment]
Fixed by v4.
