### ISSUE TITLE
Issues installing packages

### ISSUE THREAD

**Issue by Holwy** [SublimeText/LaTeXTools#1519]
Hello, probably this is a silly issue but I'm struggling installing all programs needed by Latextools.
I switched from texlive to miktex hoping for a easier process, what am I doing wrong? Thank you in advance
<img width="779" alt="3" src="https://user-images.githubusercontent.com/81386570/117541180-f3232a00-b012-11eb-834c-65262af6d324.PNG">
<img width="761" alt="2" src="https://user-images.githubusercontent.com/81386570/117541181-f3bbc080-b012-11eb-9981-09295f859ea2.PNG">
<img width="959" alt="elimina" src="https://user-images.githubusercontent.com/81386570/117541182-f4545700-b012-11eb-9964-d6c1f560b240.PNG">

**Comment by ig0774** [comment]
Probably the best thing to do would be to see if things work if you leave the `texpath` setting as “”.

**Comment by Holwy** [comment]
> Probably the best thing to do would be to see if things work if you leave the `texpath` setting as “”.

Thank you so much, it solved all the issues. Now I can also preview formulas! Before this I was having problems with texlive, with miktex all works perfectly.
