### ISSUE TITLE
cite command does not autocomplete, builds properly

### ISSUE THREAD

**Issue by rishkhare** [SublimeText/LaTeXTools#1520]
I have been using a thesis template from my university that has bib commands in a .cls file. The thesis is divided into chapters and each of the chapter files has the %!TEX root addition.

Looking at the different threads, I tried several things. For example, using the comment package in the main file. This lead to the references vanishing altogether. The citation autocomplete was working perfectly before I started writing on this custom template.

Any suggestions?

**Comment by dreistein543** [comment]
it seems that the citaion autocomplete can only detect `bib` file which has been specified in the working `tex` file.

> for example, I have such a documents structure
> parent folder contains the main.tex which specify `bib` file
> sub folder "chapters" contains several tex files like 'introduction.tex' and I use `\input{/chapters/introduction}` in main.tex to input them

 the citation autocomplete triggers only when I typing `\cite{` or `\textcite{` in main.tex. If I do it in introduction.tex, warning happens "no bib found"

**Comment by deathaxe** [comment]
Not without any more information about template structure.
