### ISSUE TITLE
another tab auto-completion issue

### ISSUE THREAD

**Issue by aaltland** [SublimeText/LaTeXTools#1528]
Hi,

I encountered a tab-completion issue after upgrading to ST4 (build 4107 on macos). Autocompletions triggered by tab-tab no longer work as they should. Say, a \rightarrow used to be generated by "-> + tab + tab". What I get now is "->\rightarrow", i.e. the triggering symbols "->" aren't deleted. Don't know if this is an LaTeXYZ issue (posted there, but no reaction (https://github.com/randy3k/LaTeXYZ/issues/26#issue-906638688), or one of LaTexTools. (Both packages appear to be abandoned :(( )

Anybody an idea?

**Comment by deathaxe** [comment]
Wrong repo
