### ISSUE TITLE
Falls back to Basic Builder

### ISSUE THREAD

**Issue by Kamik423** [SublimeText/LaTeXTools#1529]
I have the builder explicitly set to `traditional` (although that should be the default). This usually works. But sometimes after building with ⌘B a few times it will switch to the basic builder and stay that way.

**Comment by deathaxe** [comment]
For `"builder": "traditional"` setting to be taken into account, make sure to choose `"LaTeX"` build variant via <kbd>ctrl+shift+b</kbd>.

If one of the other entries (e.g.: "LaTeX - Basic Builder") is selected, `"builder"` setting is overridden, even when hitting <kbd>ctrl+b</kbd> until anything else is choosen.
