### ISSUE TITLE
Support for Sublime Text 4

### ISSUE THREAD

**Issue by sahibaulakh** [SublimeText/LaTeXTools#1531]
I just upgraded to sublime text 4 and found problems with LatexTools. 

I had to revert back to sublime text 3. While I am quite happy to stay on 3 since latex is mainly what I do with sublime, I was wondering how long I can drag out 3.

Are there plans to support ST4?

Also, I am so dependent on LatexTools that I am quite willing to pay for it. May be if you make it a licensed product, you can have a more reasonable scenario. If there is any way to contribute monetarily to the project, kindly let me know.

Thanks.

**Comment by VadokDev** [comment]
I'm also looking for a fix to this bug, but looking for a workaround, I disabled the code that opens SumatraPDF after build by commenting it to not switch into the SumatraPDF window. With this, you manually open the PDF file and let open the SumatraPDF window. SumatraPDF will update the file view after recompiling the .tex, letting you build from Sublime Text 4 without change to the SumatraPDF window.

You can try this by commenting the lines [100-103](https://github.com/SublimeText/LaTeXTools/blob/45376f12449e32c4ad769f5baa0a75c1fa72194d/viewers/sumatra_viewer.py#L110-L113) of the [sumatra_viewer.py](https://github.com/SublimeText/LaTeXTools/blob/master/viewers/sumatra_viewer.py) file:

```Python
        ...
        try:
            #external_command(
            #    [sumatra_binary] + commands,
            #    use_texpath=False, show_window=True
            #)
        except OSError:
        ...
```

Also, here is a gist that I make to focus on the Sublime Text 4 window without comment the code above. I don't know how to implement it on the LateXTools source, but I leave it here if anyone wants to give it a try.

[https://gist.github.com/VadokDev/491a68bede11dc89fb8df4a87117bccd](https://gist.github.com/VadokDev/491a68bede11dc89fb8df4a87117bccd)

By the way, here is more info about why when you execute the LateXTool command to focus the sbt4 window, it opens a new sbt4 instance: https://forum.sublimetext.com/t/4109-always-opens-a-new-windows-after-build/59133.

I hope this could help you.

**Comment by alexander-novo** [comment]
I would like to mention that in addition to the Sumatra issue as mentioned above (which the sublime text maintainers seem adamant is the correct behavior), some of the macros are also broken. For instance, expanding `begin` with tab leads to this:

![image](https://user-images.githubusercontent.com/11657716/132447988-c3c00e9b-f3ff-42fd-bb99-309453876b8d.png)

**Comment by alexander-novo** [comment]
@ankitp94 This extension is several years unsupported now. Unfortunately, I think extensions in Sublime Text 4 are, in general, dead. If you want extension support, you probably need to move to where all of the authors moved several years ago now (Visual Studio Code). I felt like in 2021 the LaTeX extension in VS Code (Latex Workshop) severely lacked compared to LatexTools, however they have caught up in the past few years.

**Comment by ankitp94** [comment]
It is really unfortunate. I always found Sublime Text + LatexTools to be much faster than VSCode (and Atom). I hope someone will get around to updating this extension.

**Comment by deathaxe** [comment]
Support for ST4 is provided by LaTeXTools v4.

For everyone interested in testing, add the following to "Package Control.sublime-settings"

```
	"install_prereleases": [
		"LaTeXTools"
	],

```
