### ISSUE TITLE
No Builder Available

### ISSUE THREAD

**Issue by amirmasoudabdol** [SublimeText/LaTeXTools#1532]
I'm seeing this error where for some reasons, LaTeXTools doesn't provide any of the builders. I can see that all the system checks are passing but the builders are not there. I saw in the documentations that I should not change the `command` option and I didn't. I even clean uninstalled and installed the package, but I still cannot get it to work! 

I'm running ST4 (4112), on macOS Big Sur 11.5.1.

**Comment by deathaxe** [comment]
Supported by v4.
