### ISSUE TITLE
Math Preview Too Far to the Left, Being Cut Off

### ISSUE THREAD

**Issue by amaiable** [SublimeText/LaTeXTools#1541]
![image](https://user-images.githubusercontent.com/58350457/135516805-fc061569-a405-4857-a9d8-7e4d9f93423f.png)
![image](https://user-images.githubusercontent.com/58350457/135517039-b99c7288-33e4-46ad-b71c-beca60e1a123.png)
![image](https://user-images.githubusercontent.com/58350457/135517064-54cbbba1-30bd-4071-b76f-81763bf22f5a.png)
(Notice the characters being cut off on the left side

Seems to happen for shorter equations, but never for the long environments / equations.

Using latest MikTex and lates LaTeXTools with latest GS. Is this happening to anyone else?

**Comment by deathaxe** [comment]
LaTeXTools 4 do longer generates previews for inline math expressions
