### ISSUE TITLE
Issue with BibLatex on ST3

### ISSUE THREAD

**Issue by p9romain** [SublimeText/LaTeXTools#1549]
Hi,
I had this comon error and I don't understand a thing to all the solutions to resolve it : when I make a .bib file and I use `\printbibliography`, the bibliography doesn't appear.
I've tested many things to solve this, like change the builder mode to basic, force to compile with pdfLatex, biber, then twice pdfLatex but nothing work.

What can I do ?

**Comment by ig0774** [comment]
Do you have any `\cite` commands in your document? `\printbibliography` only prints sources that are cited in the document. IIRC something like `\nocite{*}` before the `\printbibliography` command will load all the citations in your bib file.

**Comment by p9romain** [comment]
> Do you have any `\cite` commands in your document? `\printbibliography` only prints sources that are cited in the document. IIRC something like `\nocite{*}` before the `\printbibliography` command will load all the citations in your bib file.

I have my .bib file with 9 entries and, for test, I did this for the nine entries :
```
% nine times this as a test
Testestestestestestestestest \cite{ytb:cnrs_dalibard} Testestestestestestestestest\\

\newpage

% each keyword contains at least one entry
\printbibliography[keyword={metier},title={aTitle1}]
\printbibliography[keyword={cnrs},title={aTitle2}]
\printbibliography[keyword={ups},title={aTitle3}]
\printbibliography[keyword={other},title={aTitle4}]
```

**Comment by deathaxe** [comment]
Fixed by https://github.com/SublimeText/LaTeXTools/commit/a2aca03740c3e7deb4531d7061b5410809840603
