### ISSUE TITLE
Cannot launch skim

### ISSUE THREAD

**Issue by fewww** [SublimeText/LaTeXTools#1553]
After updating my mac to Monterey 12.1, I cannot launch Skim from the Sublime Text window. Command+L, V does not work (the same with command+l, j). I am using Sublime Text 3, Build 3211. ( Some month ago I tried Sublime Text 4, then I had other problems.)
Can somebody help me?

**Comment by chiumichael** [comment]
I have a similar issue. Forward sync no longer works for me. Not sure if it's the OS update or if it's something else.

**Comment by catch22** [comment]
The call to `/bin/sh .../LaTeXTools/skim/displayfile -r -g path/to/file.pdf` fails with the following error:

> 150:168: syntax error: Internal table overflow. (-2707)

**Comment by stanleybaran** [comment]
I also have this issue after updating to Monterey 12.1. Has anybody found a solution yet?

**Comment by lyrixderaven** [comment]
Same here, triggered by updating to Monterey 12.1. My upgrade coincided with the latest skim upgrade 1.6.6, so I went down the rabbit hole of downgrading skim until the recommended version as given in the documentation (1.4.24), to no avail.

**Comment by dgolovaty** [comment]
Same issue here after updating to Monterey 12.1, plus the packages standalone and preview are shown as missing upon the system check (while they are installed in MacTex).

**Comment by ikhanchoi** [comment]
Same for me, after Monterey 12.1, sublime text 4.

**Comment by catch22** [comment]
Skim 1.6.7 mentions "Work around scripting support bug in macOS 12.1." in the release notes, but does not work for me either.

**Comment by bipson** [comment]
Is this by any chance related to #1539?

**Comment by stanleybaran** [comment]
I tried the indentation fix in #1539, still doesn't work.

**Comment by kdzhang** [comment]
Same issue here. I tried multiple versions of Sublime Text, including rolling back to Sublime Text 3, none of them worked.

**Comment by fewww** [comment]
Installing the test version of Skim from https://skim-app.sourceforge.io/Skim.zip (following https://sourceforge.net/p/skim-app/bugs/1438/?limit=25&page=3 and) solved this for me.

**Comment by lyrixderaven** [comment]
> Installing the test version of Skim from https://skim-app.sourceforge.io/Skim.zip (following https://sourceforge.net/p/skim-app/bugs/1438/?limit=25&page=3 and) solved this for me.

Can confirm, that fixed it for me as well!

**Comment by kdzhang** [comment]
> Installing the test version of Skim from https://skim-app.sourceforge.io/Skim.zip (following https://sourceforge.net/p/skim-app/bugs/1438/?limit=25&page=3 and) solved this for me.

This also worked for me.

**Comment by dgolovaty** [comment]
Worked for me too - thanks!

**Comment by anbaccar** [comment]
Confirming it worked for me as well, thank you!!
