### ISSUE TITLE
Autocomplete does not give the correct output

### ISSUE THREAD

**Issue by marshblocker** [SublimeText/LaTeXTools#1555]
I have the following code

```Tex
\begin{document}
in
\end{document}
```

when I press `Tab`, it gives me the following completions

![image](https://user-images.githubusercontent.com/91042310/148720329-c621599c-2e0e-479d-8d94-af573478dd04.png)

Since `\in` is what I want, I pressed `Enter` to receive it but instead my `in` auto-completes into `\int` instead of `\in`. This also happens with other commands like `phi` and `theta` where it auto-completes into the _next_ suggested command (e.g. `phi` auto-completes into `\varphi` instead of the topmost suggested `\phi`). This seems to be a general behavior, not just on the commands I've listed,

**Comment by Dilemian** [comment]
I also have the same problem.

Choosing \varepsilon gives \epsilon, and vice versa.
Similarly for others: \vartheta and \theta, \varphi and \phi

<img width="322" alt="completion" src="https://user-images.githubusercontent.com/128664860/227096365-705a7bd5-13d2-484b-8bea-550ce1223dcb.png">

**Comment by deathaxe** [comment]
Those math related completions/snippets seem to be designed to behave like this in order to be able to toggle between them by pressing tab key multiple times.
