### ISSUE TITLE
Autocomplete trigger for custom commands.

### ISSUE THREAD

**Issue by otanan** [SublimeText/LaTeXTools#1556]
Currently we can toggle settings to let an autocompletion list appear whenever we run \ref or \cite. It seems to also automatically handle \nameref despite no explicit mentions of this command in the source.
I was hoping we could get some sort of way of injecting our own commands to look cause an autocomplete trigger to appear.

One example being when I want to create a special command for referencing problems, I would define it to be \probref, and would like the same list to appear.

**Comment by ig0774** [comment]
Probably not easily at the level you’re looking for. The `\ref` commands we look for are defined [starting here](https://github.com/SublimeText/LaTeXTools/blob/b27fc391b2e0c7298d7e2be2472f3642e25ed3d2/latex_ref_completions.py#L7). If you look closely, you can see how `\nameref` is supported. Citations are handled by [this](https://github.com/SublimeText/LaTeXTools/blob/b27fc391b2e0c7298d7e2be2472f3642e25ed3d2/latex_cite_completions.py#L129) horrendous regex, which really isn’t easily amenable to extension.


There is a [shortcut](https://latextools.readthedocs.io/en/latest/keybindings/#references-and-citations) you can use to insert citations or references at arbitrary places.
Alternatively, you can use a standard Sublime key binding [similar to this one](https://github.com/SublimeText/LaTeXTools/blob/b27fc391b2e0c7298d7e2be2472f3642e25ed3d2/Default%20(Linux).sublime-keymap#L92) to make any valid ST key binding add citations LaTeXTools knows about.

**Comment by otanan** [comment]
This is exactly what I was looking for! Adding "prob" to the latex_ref_completions.py script gave me the desired functionality. Thank you so much.
