### ISSUE TITLE
"synchornization file cannot be opened" error

### ISSUE THREAD

**Issue by tisquinn** [SublimeText/LaTeXTools#1560]
Hi! I am setting up latextools with sumatra pdf on a new PC for maybe the 5th time and have run into an error I cannot fix. When I compile a pdf in sublime text, it successfully opens in Sumatra PDF; but i get an error message saying "synchornization file cannot be opened," and so neither direction of search works. But if, in Sumatra, I close the file and then reopen it directly (i.e., from explorer or using file > open, not automatically upon building it in sublime text), synchronization works perfectly. The trouble is that _every_ rebuild then requires closing and reopening the pdf. Any ideas on troubleshooting? Happy to share more info as needed! Thank you!!!!

**Comment by tisquinn** [comment]
sorry for the needless post. Problem was on the Sumatra side. If anyone else has this issue, it is just a known issue with the current 64-bit version of the app. Try a 32 bit or the portable version and it works great! (https://github.com/sumatrapdfreader/sumatrapdf/issues/2642)

**Comment by zuiran** [comment]
> sorry for the needless post. Problem was on the Sumatra side. If anyone else has this issue, it is just a known issue with the current 64-bit version of the app. Try a 32 bit or the portable version and it works great! ([sumatrapdfreader/sumatrapdf#2642](https://github.com/sumatrapdfreader/sumatrapdf/issues/2642))

Thanks a lot. This issue has driven me crazy. Your answer really helps me.
