### ISSUE TITLE
Pull request #1535 (Version 4) breaks system check and auto-open of viewer on macOS

### ISSUE THREAD

**Issue by robfisc** [SublimeText/LaTeXTools#1562]
Pull request #1535 introduces two bugs for me on macOS Monterey (12.2.1) with Sublime text build 4126:
(i) The "Check System" menu item is greyed out in the LaTeXTools menu. It also disappeared from the Command Palette.
(ii) The previewer does not open anymore after building a .tex file. If previewer, i.e. Skim, is already open and showing the target PDF file, the position within the previewer is not updated (via SyncTex).

I used the same vanilla LaTeXTools.sublime-settings file.

**Comment by lxsjgzs** [comment]
See the PR #1540, switch to `Files changed` tab and located to your local `jumpToPDF.py`, then copy the green line 101 and 103 and replace it in your local file.

**Comment by robfisc** [comment]
Thanks a lot @lxsjgzs. Your suggestion fixed the viewer issues.

For reference:
`git fetch https://github.com/hadisfr/LaTeXTools.git
git cherry-pick 937c0a280f7e79e1a2340123b8fa5e5adfc8e11a`
