### ISSUE TITLE
Having trouble loading the cache

### ISSUE THREAD

**Issue by Yuxin-Deng-Tel-13540067880** [SublimeText/LaTeXTools#1566]
*My English is not very good, this article is translated by Google, if there is any inaccurate description please contact me*

# Problem loading $\LaTeX$**Tools** cache
An error message pops up when typing `\documentclass{`, the content is as follows:

> Cache files for installed packages,classes and bibliographystyles do not exist,would you like to generate it?After generating complete,please re-run this completion action!

Tried the solution from [in this issue](https://hub.nuaa.cf/SublimeText/LaTeXTools/issues/577 "issue link") but it didn't work* (several commands mentioned in the question cannot be found in found in my ST4 and tried `build cache of LaTeX packages` but nothing happened in ST4

If anyone has a solution, please contact me in GitHub, or via `3051508062@qq.com`, thank you

**Comment by Yuxin-Deng-Tel-13540067880** [comment]
# More information

If you want more contact information, you can try to call +86 13540067880 or send a text message, or you can try to add WeChat and QQ friends through your mobile phone number. Of course, it is also possible to contact me directly through [Github](https://github.com/Yuxin-Deng-Tel-13540067880 'personal homepage'). Hope the author @rensbaardman can come up with an effective solution to this problem, thanks.

**Comment by chenmaster05** [comment]
It seems that you have just installed MIKTeX. Please make sure you have checked for updates within the MiKTeX Console:

1. Open MiKTeX Console;
2. Check for updates.

Doing an update is not required, only checking for update is required. If the above does not work, please try opening MiKTeX Console with admin permissions.

If the above still does not work, please provide relevant outputs upon running "LaTeXTools: Build cache of LaTeX packages" from the control panel.

**Comment by Yuxin-Deng-Tel-13540067880** [comment]
1. In fact,I use MikTex on my computer
2. Thanks for your advice.But I found that write $\LaTeX$ via vscode is a better choice,so I give up trying to solve this problem.
3. Thank you anyway.
