### ISSUE TITLE
Autofill helper does not appear for cite, ref, input

### ISSUE THREAD

**Issue by jlsiewert** [SublimeText/LaTeXTools#1582]
The autofill helper does not appear for commands like `\cite{}`, `\ref{}`, `input{}`. 

The console only shows `Cannot determine completion type for current selection` when triggering `Ctl-l`, `Ctl-f`. Any idea on how to debug this?

System: macOS Ventura, arm64
Sublime Text: 4 (4143)
LaTexTools: v4.0.0_beta.0

**Comment by jlsiewert** [comment]
Ok, investigated that a little bit.

Looks like the regex plugin uses prebuilt binaries but [has no support for arm64](https://github.com/facelessuser/sublime-regex/issues/3).
They are waiting for Python 3.8 support in Package Control.

For now, using Rosetta is a workaround.

**Comment by deathaxe** [comment]
Fixed by 4.0.0-beta.1 which runs on python 3.8
