### ISSUE TITLE
Log parsing issue: build panel refers errors to a wrong file.

### ISSUE THREAD

**Issue by quantum-mob** [SublimeText/LaTeXTools#1590]
Here is my simple latex file:
```
\documentclass{article}
\begin{document}

\xxxx 

\end{document}
```

Obviously, it has an error at line 5 in the main latex file. However, the build panel displays as follows:

```
[Compiling /Users/Masso/Downloads/Temp.tex]

TraditionalBuilder: Engine: lualatex. Invoking latexmk... done.

Errors:

/usr/local/texlive/2023basic/texmf-dist/tex/latex/base/article.cls:4: Undefined control sequence. [\xxxx]

No warnings.

/Users/Masso/Downloads/Temp.log:1: Double-click here to open the full log.

[Done!]
```
Here is the log file:
[Temp.log](https://github.com/SublimeText/LaTeXTools/files/13904650/Temp.log)

For your information, I am using Sublime Text 4.

**Comment by deathaxe** [comment]
It can only display, what's provided by the log file
