### ISSUE TITLE
LaTeX-cwl prevents snippets from appearing in the autocompletion list

### ISSUE THREAD

**Issue by quantum-mob** [SublimeText/LaTeXTools#1591]
It seems that the LaTeX-cwl plugin prevents snippets from appearing in the autocompletion popup. If I remove LaTeX-cwl (or set "command_completion": "never" in LaTeXTools settings), then snippets appear in the autocompletion list as expected.

Is this intended with LaTeX-cwl or a bug? Or, am I missing something?

I'm using Sublime Text 4 (4169) on macOS.

**Comment by odapg** [comment]
@quantum-mob I believe this to be intended, I encountered the same behaviour.
On my side, to get the snippets back, I changed the code in `latex_cwl_completions.py` as follows: line 315, change 

`        return (
            completions,
            sublime.INHIBIT_WORD_COMPLETIONS |
            sublime.INHIBIT_EXPLICIT_COMPLETIONS
        )`

into

`        return (
            completions,
            sublime.INHIBIT_WORD_COMPLETIONS 
        )`
