### ISSUE TITLE
Disable escaped curly bracket in equation environment

### ISSUE THREAD

**Issue by ajlawren** [SublimeText/LaTeXTools#1594]
I'd like to be able to disable the keybinding that auto-pairs **escaped** curly brackets in the equation environment when text is highlighted and change it to auto-pairing **unescaped** curly brackets. I cannot figure out how to do that by modifying the regex in the keybindings file. Can someone help me?

**Comment by deathaxe** [comment]
Auto-pairing escaped braces in math blocks is restricted to empty selections in LaTeXTools v4.0.0-beta builds.
