### ISSUE TITLE
Focus does not shift to viewer after build 

### ISSUE THREAD

**Issue by joaocandre** [SublimeText/LaTeXTools#1595]
I've noticed that  the viewer windows does not grab focus on each build/update if already opened, forcing the user to close the viewer to achieve that behavior.

I'm running Sublime Text 4, in a Gnome (Wayland) environment.

**Comment by deathaxe** [comment]
LaTeXTools uses python `dbus` module to perform forward search in already running viewer after building a PDF document. Even re-invoking evince doesn't switch focus. Most likely a dbus/wayland bug.
