### ISSUE TITLE
Support for `-aux-directory`?

### ISSUE THREAD

**Issue by bordaigorl** [SublimeText/LaTeXTools#161]
Is it possible to add support for the `-aux-directory` and `-output-directory` options of `pdflatex`?
This is currently causing the log parser to fail in detecting the filenames or finding the log.

**Comment by juanfal** [comment]
Does it have LaTeXTools support for output-directory right now?

Tx

**Comment by ig0774** [comment]
Short answer: No. 

Long answer: Technically, the *builder* can work with the `-output-directory` flag, which can be set in various ways, but LaTeXTools won't find the log file or the pdf document, so you lose error reporting and PDF viewing.

**Comment by ig0774** [comment]
v3.8.0 adds this feature. Note that it's not supported through `.latexmkrc` files (though I suppose that can be added if enough people want it), but through settings or directives (as we handle the `TEXroot`).

**Comment by musmo** [comment]
I'm struggling to actually get this to work (windows, texlive2015). I put the line `"aux_directory": "<<cache>>", `` in my sublimte LaTeXTools setting. However, nothing changes and I still see all the log and aux and synctex files in my folder.

Also I'm having similar difficulties with the out_directory option

**Comment by ig0774** [comment]
`aux_directory` doesn't do anything on Texlive. It's only implemented by MiKTeX. You could get something similar by using `output_directory`, however.

**Comment by musmo** [comment]
I added the line `"output_directory": "out"` to my user file. Now when I  build a directory is created and only the `.aux` and  `.fdb_latexmk` files are copied. Is this expected behavior?

**Comment by ig0774** [comment]
I'm not entirely sure what you mean by copied. Are those the only files appearing in your output directory? You may have to clear out the previous files from your last build.

**Comment by musmo** [comment]
Yes those are the only files that appear in the output directory

```
SyncTeX written on report.synctex.gz.
Transcript written on report.log.
Failure to make 'C:\Users\mus\Dropbox \reports\blended_tails\out/report.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: (Pdf)LaTeX failed to generate the expected log file 'C:\Users\mus\Dropbox \reports\blended_tails\out/report.log'
Latexmk: Did not finish processing file 'report.tex':
   (Pdf)LaTeX failed to generate the expected log file 'C:\Users\mus\Dropbox \reports\blended_tails\out/report.log'
Latexmk: Undoing directory change
Latexmk: Errors, in force_mode: so I tried finishing targets
C:\texlive\2015\bin\win32\runscript.tlu:665: command failed with exit code 12:
perl.exe c:\texlive\2015\texmf-dist\scripts\latexmk\latexmk.pl -cd -e "$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O'" -f -pdf "--output-directory=C:\Users\mus\Dropbox \reports\blended_tails\out" report.tex
```

**Comment by ig0774** [comment]
You appear to have a custom `command` setting generating the `$pdflatex = ...` part of the command. The output directory setting won't work automatically if you override the `commad` setting unless you also explicitly include the `--output-directory` setting in your command. Your best bet would be to remove the `command` setting, as your `pdflatex` command is just the default.

**Comment by musmo** [comment]
Thank you!
