### ISSUE TITLE
OSX -output-directory option mimics -aux-directory option

### ISSUE THREAD

**Issue by lawlist** [SublimeText/LaTeXTools#163]
https://github.com/lawlist/LaTexTools-Unofficial-Modification

LaTexTools-Unofficial-Modification
==================================

As to an OSX operating system, I have created an unofficial modification of the existing LaTexTools code to permit an -output-directory option to /tmp, and then copy the *.pdf back to the working directory.

[NOTE: The '/tmp' directory option is hard-coded into all four (4) of the files mentioned below; so anyone looking to change those portions would need to look for "## BEGIN / END modification by lawlist" within the code.]

Build now triggers an automatic save of the *.tex file, and the build window closes upon successful completion (or stays open if there is an error). The *.pdf that is used by Skim is the one in the /tmp directory, which works best for anyone looking to take advantage of the LaTexTools magic of jumpToPDF.py and viewPDF.py. This modification appears to handle the log issues (as to one *.tex file being built at a time), and a few other issues encountered relating to daily operations with the files below. Because my business only involves letters and legal pleadings (rarely with tables of contents and authorities), I have not yet had any need to modify files other than those below:

LaTeX.sublime-build

jumpToPDF.py

makePDF.py

viewPDF.py

I uploaded the original code before my modifications, so anyone who is interested can see the history of changes.

For anyone seeking the -aux-directory option with TexLive on OSX, please put in a feature request to the TexLive maintainers. Until the -aux-directory option is supported by TexLive, the best workarounds will probably be using the -output-directory option and copying the *.pdf to the working directory; or, simply cleaning up with the little -c option and a .latexmkrc file (defining the scope of the cleanup). The magic of jumpToPDF.py and viewPDF.py makes cleaning up the less preferred option, as the auxiliary files are needed for the magic to function correctly.

----

I created my own ST2 plugin that saves / builds / cleans (if build was successful), but it does not have the bells and whistles of LaTexTools. Things like forward / backwards sync would of course need the auxiliary files, and an automatic cleanup makes those options unavailable. It is only designed for building one (1) *.tex file in the open tab, and some of the output is piped into the python console. It is based upon the Bash concept of: latexmk file.tex && latexmk -c file.tex

https://github.com/lawlist/ST2-plugin-latexmk-save-build-clean

----

The code by dpo and bjmorgan cleans-up after the fact with a keyboard shortcut, which may be useful to anyone wanting the auxiliary files to be stored (at least temporarily) in the working directory. For anyone wanting the little -c option, however, it is necessary to create a .latexmkrc (defining the scope of the cleanup) and also to modify the two build files created by dpo / bjmorgan. Their contribution essentially uses the big -C option to remove everything except the actual *.tex.

https://gist.github.com/bjmorgan/4349538

----

There were some additional workarounds mentioned by some of the posters in the issues that I referenced below:

**Comment by ig0774** [comment]
We now have support for `--output-directory` and `--aux-directory` natively built-in to LaTeXTools. Thanks @lawlist, however, for isolating what needed to be changed!
