### ISSUE TITLE
Log files in a different output directory

### ISSUE THREAD

**Issue by subangstrom** [SublimeText/LaTeXTools#169]
When using the $out_dir variable set in .latexmkrc  (for example: $out_dir = 'build';), the log file is not parsed by latextools. A user setting read by makePDF might be a quick fix

**Comment by ig0774** [comment]
Support for `--output-directory` and `--aux-directory` is added in v3.8.0. Note, however, that this support will not work if you specify the `$out_dir` in `.latexmkrc`. LaTeXTools needs to know about the output directory in order to find log files, the pdf, etc.

**Comment by vins31** [comment]
It does not work for me.
Instead of the `$out_dir` variable I use the `--output-directory` option, as indicated by @ig0774 .
Here is the content of my `latexmkrc` file

```latexmk
$pdf_mode = "1";
$pdflatex = "pdflatex -synctex=1 --output-directory build";
@default_files = ('test.tex');
```

I get the error `Could not read log file test.log`, using LatexTools v3.14.1 on OS X with Sublime Text 3.

**Comment by ig0774** [comment]
Sorry if this wasn’t clear, but LaTeXTools doesn’t read `.latexmkrc` files. In other words, you have to add the `output_directory` setting.
