### ISSUE TITLE
BibTeX entry with spaces between `@xxx{` and its reference key

### ISSUE THREAD

**Issue by dlimpid** [SublimeText/LaTeXTools#237]
Hi!

I have a BibTeX file which I believe is valid but I'm not sure (because it works, but I could not find any documents saying about that), each entry has spaces between `@xxx{` and entry key, for example:
```
@Article{         Murphy:2002:LDO,
  author        = "Kenneth M. Murphy and Steven L. Reiner",
  title         = "The lineage decisions of helper {T} cells",
  journal       = NatRevImmunol,
  year          = "2002",
  volume        = "2",
  number        = "12",
  pages         = "933--944",
  annote        = "reviews",
  url           = "http://www.nature.com/nri/journal/v2/n12/full/nri954.html"
}
```
(It is a default option for [BibTool](http://www.gerd-neugebauer.de/software/TeX/BibTool/bibtool.pdf)'s output, `print.align.key=18`). When I type `\cite{` and select the entry, I get
```
\cite{         Murphy:2002:LDO}
```
rather than `\cite{Murphy:2002:LDO}`. Can this be changed so that spaces can be dealt with?

Thank you so much!

**Comment by ig0774** [comment]
This should be resolved in v3.7.0
