### ISSUE TITLE
Present sections (and subsections) in sidebar

### ISSUE THREAD

**Issue by jpgamaral** [SublimeText/LaTeXTools#252]
Is it possible to show the sections (and subsections) of a particular file in the sidebar?

![screenshot](https://f.cloud.github.com/assets/842073/948761/71714de6-036f-11e3-88e6-c7edd9ea61d0.png)

**Comment by ig0774** [comment]
Closing this as I don't think its feasible to add this to ST's sidebar without ST implementing a new API. The `C-r` behaviour is probably the best we're going to be able to do.

**Comment by AdriaJ** [comment]
Hi all, I am new to ST, I hope this comment is relevant.
This discussion is some years old now, do you know if there has been changes with the recent version of ST regarding the customization of the side bar?
Indeed, displaying a clickable link to sections (and even subsections) headers would be quite handy for Latex typing.

**Comment by odapg** [comment]
Hi @AdriaJ , after seeing your message I uploaded a package that was designed for my personal use, and that could interest you. You can find it here : [LaTeXOutline](https://github.com/odapg/LaTeXOutline). 
It opens a tab on the side with a clickable table of contents on it. It is a light adaptation of another package (warmdev's [SublimeOutline](https://github.com/warmdev/SublimeOutline) ) to LaTeX, and it is pretty basic (only sections, subsections and subsubsections).   I have only tested it on my computer, I hope this works on any configuration.

**Comment by AdriaJ** [comment]
Hi @odapg , I just downloaded your package and set it up on my laptop (Ubuntu 20.04 os). Super quick to set up and it works amazingly well, thanks a lot!
Your package deserves to be the final answer to this issue :)

**Comment by odapg** [comment]
Hi @AdriaJ, I wanted to mention that I polished and improved this package quite a bit. If you are still using it, I would be much interested in your comments on this new version before possibly submitting it to packagecontrol! :)

**Comment by AdriaJ** [comment]
Hey, I have been using the package quite intensively on the past 6 months (thesis writing). Worked like a charm!
Fortunately I am done so I won't need it as intensively as before, but let me know how I should update and I can try to give feedback :)

**Comment by odapg** [comment]
Well, congrats on your thesis! I you want to try the new version, the best option is to replace the existing LaTeXOutline folder in your packages with the new one (now this is version 2.1, available [here](https://github.com/odapg/LaTeXOutline/releases/tag/2.1)).
