### ISSUE TITLE
command palette: add explicit forward search and toggle forward sync

### ISSUE THREAD

**Issue by joernhees** [SublimeText/LaTeXTools#253]
seems a couple of commands are not in the command palette (```Cmd```+```Shift```+```p```), which is especially important to search commands and learn hotkeys.

The two commands i always forget the hotkeys for are toggling forward sync and explicit forward search. Both are really useful when you notice some weird looking stuff somewhere in the middle of your pdf which is actually caused by package configs. If you fix that and just rebuild the implicit forward search will get you to the first page which is really annoying after a couple cycles...

Would be cool if this could be added.

**Comment by ig0774** [comment]
Quite late, but forward sync (**Jump to PDF**) and the various toggles are now available through the command palette.
