### ISSUE TITLE
Features requested

### ISSUE THREAD

**Issue by harishkumarholla** [SublimeText/LaTeXTools#255]
1. Is it possible to add a menu item and /or toolbar button for latextools in sublime text? Though adding toolbar seems too much, atleast a menu item for latextools underwhich main commands are listed will be a value addition. The menu may be made visible only when a tex file is open (like in vim-latex).
2. Is it possible to put a menu item that has drop down list of all available compilers for tex so that choosing an engine will be very easy. A similar feature is available in WinEdt (www.winedt.com) for windows. I am attaching a screen shot for the same.

First a dropdown menu in toolbar button:

![capture](https://f.cloud.github.com/assets/2251874/981936/f59e04a0-07a8-11e3-865a-d2e852da0d7e.PNG)

And a menu for TeX:

![capture1](https://f.cloud.github.com/assets/2251874/981937/17d3eb0c-07a9-11e3-83dc-c44007c581d4.PNG)

These features are really useful especially in customising the build commands. I know that I am asking toomuch but I didn't want the idea to slip by.

Thank you for the great work.

**Comment by r-stein** [comment]
Now (`v3.12.0`) it is possible to see a list of different build systems via `C-shift-b`.
