### ISSUE TITLE
Suggestion: add option for specific output folder and preview via native app in MacOS

### ISSUE THREAD

**Issue by DimitryDushkin** [SublimeText/LaTeXTools#256]
1. Add option for specific output folder. It's quite easy to do because mklatex already have such options. I think many of us like a little more orderliness in a folder of latex project.

2. I still cannot understand why preview in MacOS is not implemented via native Preview app. I think it wouldn't be hard to make.

I think I can implement such features. Will you add them to upstream?

**Comment by juanfal** [comment]
Is it there any way, not hacking sources, of course, to use Preview?  I would prefer to use Preview, than Skim.  I do not use sync… nor like to have those myriad of files around, nor Skim open next to Preview in Macs.

**Comment by ig0774** [comment]
Currently, no, there is no way to use Preview without modifying the Python code. Eventually, there will be.

**Comment by ig0774** [comment]
An option for using Preview.app as a viewer now exists. Output folder support will be coming.

**Comment by ig0774** [comment]
Output folder support has been added, so I'm closing this issue.
