### ISSUE TITLE
Feature suggestion: reading .bib file under ~/Library/texmf/bibtex/bib/ in OS X (and corresponding locations in other OS)

### ISSUE THREAD

**Issue by ntrolls** [SublimeText/LaTeXTools#258]
I keep a single bibtex file, which are accessed by all my TeX documents from ~/Library/texmf/bibtex/bib/ directory in OS X (well, actually, the bibtex file is symlinked from my DropBox into that directory for inter-machine synchronisation, but that is a separate matter). I find the citation completion system really indispensable, but it only looks for the .bib file from the current directory. It would be fantastic if the plugin could also look at the shared location.

I noticed that you will soon allow full customisation of the build process, so this may be doable through that, I guess. Just wanted to leave this on record.

**Comment by ig0774** [comment]
To be clear, this should be implemented since #425 was merged.
