### ISSUE TITLE
cite* errors for .Rnw files

### ISSUE THREAD

**Issue by tgouhier** [SublimeText/LaTeXTools#259]
Although the new citation system for bibtex references works great on LaTeX files with .tex extensions, it fails when a file is saved with a .Rnw extension and contains a mixture of LaTeX and Sweave/knitr R code. The error appears to stem from the fact that LaTeXTools expects the file to have a .tex extension and thus fails when the file has a .Rnw extension.

PS: Commenting out lines 42-43 in file latex_cite_completions.py solves the problem.

**Comment by ig0774** [comment]
Since #522 has been merged, this should now be possible by modifying the `tex_file_exts` setting.
