### ISSUE TITLE
Can't quickly insert multiple references within one \cref{}

### ISSUE THREAD

**Issue by xivaxy** [SublimeText/LaTeXTools#266]
Similar to the possibility to insert multiple citations in one “\cite{}” command, when the quick panel is autotriggered as soon as you enter “,”, it would be nice to have the possibility to insert multiple labels in one \cref{} or \Cref{} command (\usepackage{cleveref}). E.g. \cref{eq:pp1,fig:pf3}.

**Comment by ig0774** [comment]
This has been done in v3.10.0 (and a few other reference commands).
