### ISSUE TITLE
XeLaTeX with MiKTeX

### ISSUE THREAD

**Issue by chid** [SublimeText/LaTeXTools#294]
Is it possible to use XeLaTeX with `texify` simply by adding the option `--engine=xetex` to the `texify` command.

I modified by `sublime-build` file to contain 

```
"cmd": ["texify", "--engine=xetex",
					"-b", "-p",
					"--tex-option=\"--synctex=1\""
			],
```

This change can be added into the `makePDF.py` file in order to detect for the engine option string by appending the option `--engine=xetex` (or luatex) into `self.make_cmd`

**Comment by ig0774** [comment]
Closing as we've supported xelatex on MiKTeX for a while now.
