### ISSUE TITLE
Can I use Preview on OS X with latextools?

### ISSUE THREAD

**Issue by ernestyao** [SublimeText/LaTeXTools#304]
I read through the readme and find that I have to install Skim on OS X. Can I use native application Preview instead?

**Comment by Edenharder** [comment]
I'd like to ask that is preview supported now?

**Comment by r-stein** [comment]
Yes, you can change the viewer to `preview` in the [settings](https://github.com/SublimeText/LaTeXTools/blob/master/LaTeXTools.sublime-settings#L246). However it does not support forward search (yet?).

**Comment by Edenharder** [comment]
Could you kindly show me how to " change the viewer to preview in the settings"?

**Comment by r-stein** [comment]
Select *Preferences > Package Settings > LaTeXTools > Settings - User* and search for the viewer settings. Theres should be something like `"viewer": "",` or `"viewer": "skim",`. Just change this to `"viewer": "preview",`

**Comment by Edenharder** [comment]
Thanks, I also find it out, that's why I delete the comment. I think the comment in the setting file 
```
// Path to PDF viewer, if needed
// TODO think about it. Also, maybe configure it here!
```
should be deleted, it's somewhat misleading. Firstly, I only try change the viewer there.
