### ISSUE TITLE
suggestion for a better tex engine selection mechanism

### ISSUE THREAD

**Issue by pierodancona** [SublimeText/LaTeXTools#316]
Hi, I would like to suggest a possible solution to the problem of tex engine selection.

There is a new tool, TrY, which should become part of TeXlive in the next iteration.
This is actually a very simple python script which parses the first lines of the file
looking for a list of bash commands, then executes them. That's it.

Now my build system is just
/usr/local/bin/try

and the first line of my tex files contains
%$ latexmk $0

which tells try to run latexmk on the present file.
Do you see it? If I need to run xelatex, I just change the line to
%$ xelatex $0

or better
%$ latexmk -xelatex $0

or if I want better control
%$ xelatex -shell-escape mydoc.tex
%$ biber -min-crossref=3 mydoc.bcf
%$ xelatex -shell-escape mydoc.tex
%$ xelatex -shell-escape mydoc.tex

and so on. I have total control in the file, which by the way
is even better if I have to share the file since the information
about the typesetting rules is included.

Just a suggestion
Thank you for your work!
Piero

**Comment by ig0774** [comment]
It should be possible to make use of this (and `arara` and others) by using the Script Builder, which is described in the README. Right now, I don't think we're looking to migrate the `traditional` builder off of `latexmk` or `texify`, but if someone would like to come up with alternative builders for other build / automation systems, please feel free to [open a PR](https://help.github.com/articles/creating-a-pull-request/). Some (hopefully) helpful notes on writing builders can be found [on our Wiki here](https://github.com/SublimeText/LaTeXTools/wiki/Custom-Builders).
