### ISSUE TITLE
[suggestion] Genious-complete on \input and \includegraphics

### ISSUE THREAD

**Issue by adamal** [SublimeText/LaTeXTools#318]
`\ref`- and `\cite`-completions are freakin' awesome. It would be even awesomer to have something similar for the \input and \includegraphics.
I.e. `\input{`-`tab` gives suggestions for .tex files on the path, and `\includegraphics{`-`tab` gives suggestions for imagefiles on the `\graphicspath`.

**Comment by ig0774** [comment]
Hey! This feature has been implemented! Sorry it took so long...
