### ISSUE TITLE
Use key in bibtex popup

### ISSUE THREAD

**Issue by sirgraystar** [SublimeText/LaTeXTools#322]
NB: I'm not certain this is a LaTeXTools feature, but presumably it is not default in Sublime.

When I add a citation and the popup opens, my BibTeX citations without an `author` field show as `???? - foo`. All my references without an `author` field (like urls) have a `key` field, which makes sorting work properly. It would be nice if the `key` field was used when the author field was not found, instead of just `????`.

**Comment by ig0774** [comment]
Using the `new` bibliography, it's possible to get pretty much any arbitrary field to display in the pop-up by modifying the `"cite_panel_format"` setting.
