### ISSUE TITLE
Extend ref auto trigger to memoir's fref/tref/...

### ISSUE THREAD

**Issue by timtro** [SublimeText/LaTeXTools#324]
In the Default (Linux).sublime-keymap, I added "f" and "t" to the following line(s)

```
 {"key": "preceding_text", "operator": "regex_contains",
                 "operand": "\\\\(((eq|page|v|V|auto|name|c|C|cpage|f|t)?ref)|(cite([a-zX*]*?)(\\[.*?\\]){0,2}))$", "match_all": true}],
```

I also added "t" and "f" to the following line from latex_ref_completions.py

```
  _ref_special_commands = "|".join(["", "eq", "page", "v", "V", "auto", "name", "c", "C", "cpage", "f", "t"])[::-1]
```

My question is whether or not it was necessary to modify both files. My suspicion is that I only needed the first. Of course, I could just try it, but that would tell me nothing about what each of the two does. So, that is part of my question too.

Thanks!

**Comment by ig0774** [comment]
I've added completions for memoir's referencing functionality to v3.12.1.
