### ISSUE TITLE
No inverse search in ST2+evince (archlinux)

### ISSUE THREAD

**Issue by cosenal** [SublimeText/LaTeXTools#330]
I just switched to ArchLinux and LatexTools works as smoothly as it used to work on my ubuntu, except for the inverse search from evince. I even changed the 'python' and the 'sublime' parameters in the User config file so that they point to 'python2' and 'subl', respectively, but it didn't help.
Anyone experiencing the same issue with archlinux?

**Comment by pxdu** [comment]
I got the same issue and I just solved it. I have suse Leap 42. I first make sure that the naming is "sublime-text" not "sublime_text". Second, make sure that "sublime-text" is in the path. I then modify the first two lines of evince_sync to have the correct names of sublime-text and python. In my case, I change these two lines to

PYTHON="/usr/bin/python2.7"
SUBLIME="sublime-text" 

Also, make sure the naming of "sublime-text" in Latextools.sublime.settings is correct.

I hope this helps

**Comment by ig0774** [comment]
@pxdu: Have you tried just modifying the`sublime` and `python` settings in the `linux` section of your local copy of `LaTeXTools.sublime-settings`? The values there are what gets passed to the `evince_sync` script.

**Comment by pxdu** [comment]
ig0774: yes. The values in LaTeXTools.sublime-settings also need modified accordingly to the system, namely what sublime text and python 2 is in your linux path.

**Comment by CareF** [comment]
I got a similar problem but on ST3. When I tried @jonasmalacofilho 's way to copy files (evince_sync and evince_backward_search) and run 
    bash evince_sync python2 subl3 latextmp.pdf
Everything works fine and the inverse search works. 
But when I build from ST and try it again on the evince window that showed up, the inverse search don't work. Though in the `C+\`` panel I did see the line: 
    Running "sh /home/user/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_sync python2 /opt/sublime_text_3/sublime_text /home/user/tmp/latextmp.pdf"
And when I try to run this line in terminal outside ST, the inverse search also works fine. 

Is there anything I can try?

**Comment by r-stein** [comment]
@CareF You can get the path to python2 via `where python2`. You may try to insert the full path to the settings or ensure, that the path to python2 is in the PATH of [system check](https://github.com/SublimeText/LaTeXTools/tree/v3.12.11#system-check).

**Comment by CareF** [comment]
@r-stein 
Thank you for your advise. But it doesn't work. And I don't think the path of Python is the problem because I find python and python2 all works well in outside command. (Actually python works even better, because python2 seems to cause some bugs about mouse locate)

**Comment by ghouzenyan** [comment]
@CareF 
Hi, I find the same problem.

When I invoke the panel and see the line:
`Running "sh /home/ghou/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_sync python sublime-text-dev /home/ghou/Desktop/untitled.pdf"`
The forward search works but not focus on evince. But backword search is broken.

So I try the command in the terminal outside ST3. There are two cases:
1. In `~/.config/sublime-text-3/Packages/LaTeXTools/evince` path, both search works well  and forward search keeps focus on evince correctly
1. In others, forward search also works well, but backword search is still broken

My latextools setting is correct? How to solve it?

**Comment by lucainnocenti** [comment]
I had the same problem on Ubuntu 17.10 and solved it by setting in the LaTeXTools preferences (in the linux section) `"python": "/usr/bin/python3"` (whereas it previously contained the path to the anaconda executable) and `"sublime": "subl"` (whereas it was previously "sublime-text").

While this was already pointed out in this and similar issues, wouldn't it be useful to add a note in the [relevant doc page](https://latextools.readthedocs.io/en/latest/available-viewers/)? This would save time to many people encountering the same issue.
