### ISSUE TITLE
How to change engine to xelatex?

### ISSUE THREAD

**Issue by richard1017** [SublimeText/LaTeXTools#356]
I know it might be a dumb question, but I really found the README instructions are quite helpless.

I just want to use xelatex engine for compilation. In the README, it states:

```
program: one of pdflatex (the default), xelatex or lualatex. This selects the TeX engine.
```

So, I edit my `LaTeXTools.sublime-settings` in `User` folder as follows:

```
"builder_settings" : {

        // General settings:
        // See README or third-party documentation

        "program": "xelatex",
        "command": ["texify", "-b", "-p", "--tex-option=\"--synctex=1\""],

        // (built-ins): true shows the log of each command in the output panel
        "display_log" : false,  

        // Platform-specific settings:
        "osx" : {
            // See README or third-party documentation
        },

        "windows" : {
            // See README or third-party documentation
        },

        "linux" : {
            // See README or third-party documentation
        }
```

I also tried the to change `"builder": "traditional",` options, but with no luck.

There must be some simple trick to change the TeX engine, but I can't find in the README instructions.

Any help will be appreciated.

Thanks.

**Comment by laujeve** [comment]
Why I cannot find LaTeXTools.sublime-settings in User folder ?

**Comment by msiniscalchi** [comment]
Check the readme. There is a command to generate it.

**Comment by laujeve** [comment]
Thanks! @msiniscalchi

**Comment by msiniscalchi** [comment]
Please close the issue if it's solved.

**Comment by ZeningQu** [comment]
I had the same issue and just setting 

`"program": "xelatex"` in `LaTeXTools.sublime-settings` 

or setting
`%!TEX program = xelatex` in my `.tex` file

didn't work for me. When I `cmd+B` I still get `pdfLatex`. The following command worked for me in getting `xelatex`:

`"command" : [ "latexmk", "-cd", "-xelatex", "-f", "-pdf"]`

**Comment by r-stein** [comment]
@ZeningQu I don't know why it does not work for you, but you should at least add the options ``"-interaction=nonstopmode"` and `"-synctex=1"` to your command.
You could also try to remove that command and run the build via ctrl+shift+b and select *LaTeX - XeLaTeX*

**Comment by syrte** [comment]
"run the build via ctrl+shift+b and select LaTeX - XeLaTeX" works for me. Thanks, r-stein.
