### ISSUE TITLE
How can I manually trigger the references window?

### ISSUE THREAD

**Issue by tknuth** [SublimeText/LaTeXTools#357]
When I type `\citeauthor{`, a window pops up that reads my bibliography file. Is there a way to do this manually? I read about `C-l, x`, but that does not open it. I use commands like `\footcite[]{}`, where this would be a very useful behaviour.

Thank you in advance!

Tobias

**Comment by ig0774** [comment]
This functionality is now available in v3.10.0, using `C-l,alt-x,c` (sorry for the convoluted key-binding).
