### ISSUE TITLE
"forward_sync"-setting is ignored

### ISSUE THREAD

**Issue by fefrei** [SublimeText/LaTeXTools#369]
Since the latest upgrade (with the new settings system), after building a LaTeX file, the PDF file is always opened in SumatraPDF, although I use the setting `"forward_sync": false`.

I'm using the traditional builder. My full settings file is here: https://secure.fefrei.de/paste/?43e0e8da1cc6b919#3pfNs2GdgQddoWhFFQvXMBtY0zpi55jpoTqk64Utlvg=

How can I return to the old behaviour, where the PDF only opens when I "jump" manually?

**Comment by ig0774** [comment]
This can now be set by changing the `open_pdf_on_build` setting to `false`.
