### ISSUE TITLE
\cite key autocomplete does not work with text inside less-than/greater-than symbols

### ISSUE THREAD

**Issue by warmlogic** [SublimeText/LaTeXTools#392]
When using \cite, it is possible to add pre-citation text using text inside less-than/greater-than symbols: `\cite<e.g.,>{Smith2014}`. This ends up looking like: (e.g., Smith, 2014).

Likewise, one can add text to the end with square brackets `\cite[p.~107]{Smith2014}`. This looks like: (Smith, 2014, p. 107).

Bibtex cite key autocompletion does not work with the less-than/greater-than prefix method, though it does work with the square brackets. Is it possible to make it work for the less-than/greater-than method?

(edited to retain formatting of less-than/greater-than symbols and brackets)

**Comment by ig0774** [comment]
This functionality should now be available since #506 has been merged.
