### ISSUE TITLE
LaTeXTools on OS X 10.10

### ISSUE THREAD

**Issue by leandersabel** [SublimeText/LaTeXTools#401]
Hey there,

I just upgraded to OS X 10.10 and building LaTeX documents from Sublime Text 3 stopped working. It simply stops after invoking latexmk.

    [Compiling /Users/Me/Document.tex]
    TraditionalBuilder: Invoking latexmk... done.

Are there any more logs that might show why this is happening?

Running latexmk on a simple .tex file from the command line still works.
and building from Sublime also worked fine yesterday before the upgrade to 10.10

---
    Latexmk, John Collins, 10 Nov 2013. Version 4.39
    pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014)
    OS X 10.10
    Sublime Text Build 3059

**Comment by adrfinance** [comment]
Hey guys, I am getting the same issue now that the new Mac OS X is out.. Seems to be a bug with every new edition of Mac OS X .. Any idea how to fix it ? It doesnt compile through ST3, does compile through the terminal and texworks... Thanks

**Comment by PeterPablo** [comment]
Take a look at #531 and #560. Updating to the latest version of `LaTexTools` should suffice to solve your problem.

**Comment by adrfinance** [comment]
Thanks Pablo. Here is what I did and it now works (on a MAC) : Open SublimeText 3, press Command+Shift+P, write "install" and press enter when Package Control: Install Package appears, then exit this menu, press Command+Shift+P, select LatexTools: Reconfigure and migrate settings, press enter, then it works. cheers

**Comment by ig0774** [comment]
Closing as this should be resolved...
