### ISSUE TITLE
Recently, there's only one configuration (LaTeXTools.sublime-settings) file 

### ISSUE THREAD

**Issue by pide2000** [SublimeText/LaTeXTools#404]
In your Documentation you referenced two files (LaTeXTools.sublime-settings and LaTeX.sublime-settings) the second one is deprecated, there's only one file with all the settings in it at the User Directory

Reference: http://tex.stackexchange.com/questions/165339/latextools-you-need-to-migrate-your-preferences-see-the-readme-file-for-instru

**Comment by ig0774** [comment]
Thanks for pointing this out!
