### ISSUE TITLE
Cite completion failing to popup with incomplete second author field

### ISSUE THREAD

**Issue by ghost** [SublimeText/LaTeXTools#407]
My cite completion was not showing up, with this error:

`<authors = [a.split(" ")[-1] if a[-1] != '}' or a.find('{') == -1 else re.sub(r'{|}', '', a[len(a) - a[::-1].index('{'):-1]) for a in authors]
IndexError: string index out of range>`

I found it was working with some .bib files, but not my major one. As far as I can tell, the problem citation ended up being one that had one author with a first and last name, and a second author with just a first name.

Just a heads up!

**Comment by ig0774** [comment]
This should be resolved in the latest release (v3.7.0)
