### ISSUE TITLE
Custom builder description

### ISSUE THREAD

**Issue by petereichinger** [SublimeText/LaTeXTools#408]
Hi,

today I tried to create a custom builder and add it to the User Package directory.

I'm on Windows 7 x64
I encountered some problems that I had to fix (as far as I can see this is not documented).
* In the description it says the path on Windows to the custom builder must be separated by "\" but that is wrong. "\\" has to be used.
* When specifying the custom builder the file must be named "*Builder.py" and in the configuration the "Builder.py" part has to be omitted

**Comment by ig0774** [comment]
I added [this wiki page](https://github.com/SublimeText/LaTeXTools/wiki/Custom-Builders) on custom builders not very long ago. It may not be perfect, but at least its a start.

**Comment by ig0774** [comment]
Closing as documentation exists in the form of the aforementioned wiki page.
