### ISSUE TITLE
Porting LaTeXTools to Atom.io

### ISSUE THREAD

**Issue by yrammos** [SublimeText/LaTeXTools#411]
Just a short question to gauge the collective interest in an effort to port the truly sublime LaTeXTools to the GitHub-authored, open-source Atom.io editor, a platform that seems to be a more sustainable and long-term commitment than the possibly (but by no means certainly) defunct, proprietary SublimeText.

Does @msiniscalchi, or any other member, have any such thoughts? 

Thanks.

**Comment by msiniscalchi** [comment]
Just a head's up: it's happening. I have a prelimary repo up.
