### ISSUE TITLE
No autocompletion with \cite when bibfile contain  characters with accents

### ISSUE THREAD

**Issue by coin-au-carre** [SublimeText/LaTeXTools#418]
I have troubles when including my big bibfile coming exported from Zotero.
The bibtex file contains accent character such as à, é, ô that can be found in authors name.
It also happens for some characters such as "–" instead of "-"

I used this script but I would like to keep the accents in my references.
>#!/usr/bin/env bash
>sed -e 's/é/e/g' -e 's/è/e/g' -e 's/à/a/g' -e 's/ô/o/g' -e 's/â/a/g' -e 's/–/-/g' -e 's/ó/o/g'  -e 's/á/a/g' $1

**Comment by ig0774** [comment]
This work-around should no longer be necessary. 3.7.0 support utf-8-encoding bib files.
