### ISSUE TITLE
Cannot find builder SumatraPDF. Check your LaTeXTools preferences

### ISSUE THREAD

**Issue by gaandrey** [SublimeText/LaTeXTools#429]
Hi.
I've been trying to povide a builder path for SumatraPDF in the file
LaTeXTools.sublime-settings
located at
C:\Users\Andrey\AppData\Roaming\Sublime Text 2\Packages\User
in different kinds of ways. As follows:
"builder": "..\\..\\..\\..\\..\\..\\Program files\\SumatraPDF"
"builder": ":..\/..\/..\/..\/..\/..\/Program files\/SumatraPDF"
"builder": "..\/..\/..\/..\/..\/..\/Program^ files\/SumatraPDF"
"builder": ".\/..\/..\/..\/..\/..\/..\/Program^ files\/SumatraPDF"
All of these work(relocate from "\Packeges" to SumatraPDF folder) in command prompt.
I also tried putting absolute path:
C:\\Program files\\SumatraPDF
C:\\Program^ files\\SumatraPDF
C:\\\"Program files\"\\SumatraPDF
These work as well only in command prompt.
SumatraPDF is in the $PATH and executable in cmd from any location.
Still, when I build all I'm getting is "Cannot find builder SumatraPDF"
No errors in the display log

Also, I can compile, but only in simple mode.
Traditional gives me this:
[Compiling C:\Users\Andrey\Desktop\first.tex]

TraditionalBuilder: Invoking latexmk... 

COULD NOT COMPILE!

Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf first.tex
Build engine: Traditional Builder

My system is 32bit Windows 8,1
I would be happy if anybody gave me a clue on what's going on. Been stumped for a couple of days now.
Thanks

**Comment by ig0774** [comment]
The key error reported in the latest comment was already resolved.
