### ISSUE TITLE
@preamble in the bib file breaks the cite dropdown

### ISSUE THREAD

**Issue by ThSGM** [SublimeText/LaTeXTools#435]
Here is an example bib file: 

    @preamble{"\providecommand{\noopsort}[1]{}"}
    @article{doctors_1980,
	Author = {Smith, J.},
	Date-Added = {2014-10-11 21:04:44 +0000},
	Date-Modified = {2014-10-11 21:04:44 +0000},
	Journal = {My Journal},
	Number = {03},
	Pages = {647--672},
	Publisher = {Cambridge Univ Press},
	Title = {My title},
	Volume = {98},
	Year = {1980}
	}

The @preamble noopsort command is a recommended fix in order to properly order names. In any case, it seems that inserting these preamble commands breaks the ability to have a dropdown menu when we use the \cite{} command. Removing the first line of the above returns the feature.

Is there a way to fix this?

**Comment by ig0774** [comment]
This has been fixed.
