### ISSUE TITLE
About biber support?

### ISSUE THREAD

**Issue by krypttr** [SublimeText/LaTeXTools#436]
I use biber as the backend for biblatex. Preparing a document in my linux environment which uses  was working fine. But the same document does not compile in Windows. I guess the problem is due to the difference between latexmk and texify. But I have to keep using biber. I found some solutions but they were not really instructive and old. I am using Sublime Text 3. How can I make a builder which compiles bibliography files with biber?

Thank you.

**Comment by ig0774** [comment]
For anyone who comes across this, I've created a [wiki page](https://github.com/SublimeText/LaTeXTools/wiki/BIber-Support) documenting a few different ways of supporting `biber`.
