### ISSUE TITLE
is there a way to make sublime automatically compile, say, when i save?

### ISSUE THREAD

**Issue by jovo** [SublimeText/LaTeXTools#447]
i realize it will only save me a keystroke, but i found it really nice when i was using other editors.
thanks, j

**Comment by ig0774** [comment]
You could use the [SublimeOnSaveBuild](https://packagecontrol.io/packages/SublimeOnSaveBuild) package adding `tex` to the `filename_filter`. 

Alternatively, you can create a simple Python file and save it in your User packages directory with this code:

    import sublime_plugin

    class LaTeXBuildOnSave(sublime_plugin.EventListener):
        def on_post_save(self, view):
            if view.score_selector(view.sel()[0].b, 'text.tex.latex'):
                view.window().run_command('build')

**Comment by jovo** [comment]
thanks!!!
