### ISSUE TITLE
"Sorry, cannot select engine using a %!TEX program directive on MikTeX" in latest on ST3

### ISSUE THREAD

**Issue by damurdock** [SublimeText/LaTeXTools#452]
I'm running the latest versions of MikTeX, Sublime Text 3, and LaTeXTools. Building 

    \documentclass[a4paper,12pt]{article}
    \begin{document}
    Hello World!
    \end{document}

results in a nice "Hello World!" pdf

Adding a `%!TEX TS-program = xelatex` or `%!TEX program = xelatex` to the top brings up the error. I know this issue has been brought up before in #394 and #234 at least, but it's back in the latest Package Control build.

**Comment by msiniscalchi** [comment]
This was implemented in the latest update. Closing.
