### ISSUE TITLE
Is there a way to make latexmk coordinate with psfrag?

### ISSUE THREAD

**Issue by tuczjuer** [SublimeText/LaTeXTools#453]
First, I want to say that LatexTools is a very handy and powerful tool, thank you for developing. 

The problem I meet is that, when I try to include .eps figure (which I normally do) and use \psfrag to replance the text in figure with equations, etc. For a comparison, when I was using TexShop with MacTex , and using builder "latex" with "tex+dvi" as building chain, \psfrag works fine. However, I am not able to make it work in LatexTools. In particular, I am not sure if I set up correctly or if there is issue with it. My setting is 

"cmd": ["latex", "-cd", "-e", 
            "$dvips = '%E -interaction=nonstopmode -synctex=1 %S %D'", "-shell-escape", "-f", "-P pdf"]

**Comment by ig0774** [comment]
Here are the options I can see (I haven't tested any of these... I don't use eps figures myself)

1. As mentioned [here](http://tex.stackexchange.com/a/59056), the `auto-pst-pdf` package seems to take care of converting eps -> pdf, etc. To use it, you'd need to set the `--shell-escape` flag either by including `%!TEX option = --shell-escape` at the top of your root file or setting the `options` setting to `['--shell-escape']` in LaTeXTools.sublime-settings.

1. [This](http://tex.stackexchange.com/a/25925) answer suggests that `xelatex` can do this out of the box. You can use `xelatex` by including `%!TEX program = xelatex` or similarly setting the `program` build setting in LaTeXTools.sublime-settings.

1. You can use the ScriptBuilder (available from v3.6.2) to setup a latex -> dvipdf chain. You would need to change the `builder` setting to `script` and set the `script_commands` setting like so (see the README for where this all goes):

    ```json
"script_commands": [
        "latex --interaction=nonstopmode -shell-escape",
        "dvipdf $file_base_name.dvi"
]
```
