### ISSUE TITLE
Custom PDF viewer support in OSX

### ISSUE THREAD

**Issue by larryxiao** [SublimeText/LaTeXTools#454]
Is it possible to support custom pdf viewer (with only viewing functionality is fine), and allow user to choose? like the built-in Preview for OSX?
I'd be happy to work on it.

As a workaround, I currently modify jumpToPDF.py:

``` python
if plat == 'darwin':
    subprocess.Popen(['open'] + [pdffile])
```

**Comment by ig0774** [comment]
This will be addressed by #639, which adds a "viewer" for Preview and provides a means for adding custom viewers (if needed).
