### ISSUE TITLE
Crash with multiple bib files

### ISSUE THREAD

**Issue by vomout** [SublimeText/LaTeXTools#456]
I have \bibliography{abbrevs2,bib-bib-own} as my bibliography command. It produces the output below in the console when entering '\cite{', and the citation menu does not appear. Neither does tab-completion work. With just \bibliography{bib} the menu works, so the problem does not seem to be the complaint about the @preamble, but being unable to handle multiple bib files.

(abbrevs2.bib contains abbreviated journal names, abbrevs.bib full names, allowing me to easily change between the two depending on journal requirements. bib.bib is my general bibliography database, and bib-own.bib list of my own papers.)

The console output:

Bib files found: 
[u'/XXX/bib.bib', u'/XXX/bib-own.bib', u'/XXX/abbrevs2.bib']
Files:
[u'/XXX/bib.bib', u'/XXX/bib-own.bib', u'/XXX/cv/abbrevs2.bib']
u'/XXX/bib.bib' has 5286 lines
Found 438 total bib entries
u'/XXX/bib-own.bib' has 508 lines
Cannot process this @ line: @preamble{ " \providecommand{\homesiteprefix}{http://XXX/} " }
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./latex_cite_completions.py", line 417, in run
  File "./latex_cite_completions.py", line 287, in get_cite_completions
TypeError: cannot concatenate 'str' and 'dict' objects

**Comment by ig0774** [comment]
This should work now (actually, I think it was a while ago).
