### ISSUE TITLE
Problems with smart completion of \subsection

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#460]
There are two problems with the `\subsection` smart completion that I've run into. 

Firstly, it overrides the possibility of the `\subsubsection` command since it only allows expansion into the the following completion.

    \subsection{subsection name} % (fold)
    \label{sub:subsection_name}
    
    % subsection subsection_name (end)
Which I acknowledge has some nice properties as it lets you tab between the different fields and simultaneously edit the label and the commented out ending description. 
But it would be nice if there were some way to also allow the creation of a \subsubsection via an additional tab (or some other operation).

Secondly, if you try to expand `sub` then it expands correctly, but if you type in `\sub` then it expands to

    \\subsection{subsection name} % (fold)
    \label{sub:subsection_name}
    
    % subsection subsection_name (end)

Which is not a valid LaTeX command. 

I think the latter point can be caught with a simple addition to the regex, and I'm happy to help implement it, but I'm currently working on my dissertation and thus don't have the time to search through the code behind LaTeXTools to find what I'd need to change. 

However, if someone would point me in the right direction (e.g., where to find the file I'd need to edit to add the necessary regex for catching a leading \ for tab completion), I'll probably be able to fix this pretty quickly. 

Thanks a bunch!

**Comment by ig0774** [comment]
I'm closing this as we don't control the LaTeX package. At least someone was able to suggest a nice work-around.
