### ISSUE TITLE
How to use xelatex in simple builder on OS X 10.10

### ISSUE THREAD

**Issue by ernestyao** [SublimeText/LaTeXTools#461]
As my latex files always contain some non-English fonts, I have to use xelatex as my default builder. At least that's the only option I can get correct pdfs.
After I change 
`pdflatex = ["pdflatex", "-interaction=nonstopmode", "-synctex=1"]`
to
`pdflatex = ["xelatex", "-interaction=nonstopmode", "-synctex=1"]`
in simpleBuilder.py. My LatexTools works.
But I think merging the modification to LaTexTools.sublime_settings should be more reasonable. How should I do it?

**Comment by Cescfangs** [comment]
Hey, guys.
I changed the simpleBuilder.py just as @ernestyao did, but it didn't work at all, the first line of log file says:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=pdflatex 2015.7.29)  29 JUL 2015 22:35
```
and it failed when using `specfont`

**Comment by ernestyao** [comment]
@Cescfangs  I don't think the line you quoted means something wrong. It's just a normal log I suppose.
I've do the change in OS X 10.10.4 with MacTex Basic package 2015 and Sublime Text 3 beta. It works. If you can read in Chinese, you can see my blog here: http://www.readern.com/sublime-text-latex-chinese-under-mac.html

**Comment by ernestyao** [comment]
With your latest update, I did not have to change .py files. I modified the User settings as follow:
`"command" : ["latexmk", "-cd", "-e", "$pdflatex = 'xelatex -interaction=nonstopmode -synctex=1 %S %O'", "-f", "-pdf"],`
I can get the same PDF now with warning as follow:
```TraditionalBuilder: Your custom command does not allow the engine to be selected```
I wonder if there's something wrong still?

**Comment by ig0774** [comment]
Nothing's wrong. That's just a warning that you've supplied a custom command that doesn't support changing the engine. Incidentally, the *easiest* way to use xelatex, if you're happy using the traditional builder, is to add a directive to the start of your main tex file `%! TEX program = xelatex` or instead of using the `"command"` option, just use the `"program"` option (`"program": "xelatex"`).

**Comment by ernestyao** [comment]
Thank you, @ig0774
