### ISSUE TITLE
Support for CWL files for autocompletion

### ISSUE THREAD

**Issue by gjulianm** [SublimeText/LaTeXTools#462]
I've been trying LaTeXTools and the only thing I miss is autocompletion for commands, not only for the default packages but for custom ones too. Texstudio does it with the [cwl format](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#CWLDESCRIPTION).

Are there any plans to include some kind of support for this? If there isn't, could you give some leads on which would be the best way to do it? I could give it a look, I already made a .sty -> .cwl creator in Python so I have already half work done.

Thanks!

**Comment by ig0774** [comment]
We actually have quite good support for cwl files now thanks to @btstream.
