### ISSUE TITLE
Turn off viewer launch?

### ISSUE THREAD

**Issue by jeckstei** [SublimeText/LaTeXTools#463]
I am trying to use LatexTools in Windows (7).  Every time I perform a build, LaTeXTools opens a new SumatraPDF tab (or in older versions of SumatraPDF, a new window).  I periodically need to delete dozens of tabs.  I have determined that the problem is caused by working in a network drive directory implemented by WebDrive.  It does not happen on a local drive.

I could work around this by disabling the viewer launch, since SumatraPDF will detect the changes and update automatically. But I can't find an option for doing this.  Is there one?

Help!  (This was the only way I could discern of asking a question about LaTeXTools.)

**Comment by ig0774** [comment]
This feature has been merged and is now available.
