### ISSUE TITLE
\citeA{ does not trigger the search through the bilbiography as does \cite{

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#464]
This should be a relatively small thing (just adding another keyword trigger). I'm right now working on writing a paper, but I hope that after January to be able to dive in more and try to fix things like this directly when I find them. 

This is amazing work and I really appreciate it, even if at times I seem to complain about minor things. 

Grazie.

**Comment by ig0774** [comment]
This functionality should now be available.
