### ISSUE TITLE
Ref/Cite: Unrecognized Format

### ISSUE THREAD

**Issue by chrisruf** [SublimeText/LaTeXTools#465]
It seems that the keybinding and \ref{ invoked auto complete does not work correctly. I am on the latest version of OS X (10.10.1), ST (3065) and LaTeXTools (installed via Package Control 3). Typing \ref{ does not invoke the auto completion menu. Also c-l,x or c-l,ctrl-space result in the Ref/Cite: Unrecognized Format error message. Since ST and LT are essential to my every day workflow I am grateful for your help in fixing this issue or pointing the error out to me. Thank you for the great work you do with LT. Is there a way to financially contribute to your work?

**Comment by daneeq** [comment]
Same problem for me, with identical configuration except for OS X (10.10.2). I've always had this problem in ST2 and used workarounds, such as direct code pasting from Mendeley. The console doesn't seem to output anything helpful:

    433
    True True
    error: Ref/cite: unrecognized format.

**Comment by afedynitch** [comment]
I had the same problem on a similar configuration with a multi-file project. The solution was to go to each file and click on Save with Encoding/UTF-8. Check the console for the errors like:
```
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 56: invalid continuation byte
```
The bad file is listed a few lines above like:
```
    Searching file: u'/path/to/thetroublemakerfile.tex' 
```

So in the end it is not a ```LaTeXTools``` problem, but I agree that the error message could be clearer then just ```Ref/cite: unrecognized format```

**Comment by msiniscalchi** [comment]
Any news on this? Did changing the encoding fix the problem for the OP?

In general, UTF-8 is supported; other encodings are iffy, and iit may or
may not be feasible to 100% fix things... sorry folks.

On Fri, Apr 3, 2015 at 6:46 AM, afedynitch <notifications@github.com> wrote:

> I had the same problem on a similar configuration with a multi-file
> project. The solution was to go to each file and click on Save with
> Encoding/UTF-8. Check the console for the errors like:
>
>     UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 56: invalid continuation byte
>
> The bad file is listed a few lines above like:
>
>     Searching file: u'/path/to/thetroublemakerfile.tex'
>
> So in the end it is not a LaTeXTools problem, but I agree that the error
> message could be clearer then just Ref/cite: unrecognized format
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/465#issuecomment-89265939>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by breecummins** [comment]
Thank you, @afedynitch. Your solution fixed the same problem for me. I also have a multi-file project, and the \ref{ dropdown menu failed to appear. Resaving every file as UTF-8 worked.

**Comment by Guerki** [comment]
Resaving everything as UTF-8 did not work for me. The only error message I get in the console is:
````
True True
error: Ref/cite: unrecognized format.
````
I get the same error on OSX Yosemite and on Windows 8.1 (same file)

**Comment by msiniscalchi** [comment]
Closing, as saving as UTF-8 seems to resolve things.
