### ISSUE TITLE
suggestion: add information about the usage of the python `dbus` module for Linux users

### ISSUE THREAD

**Issue by xiaoweiz** [SublimeText/LaTeXTools#470]
I was trying to set up LaTeXTools with ST3 in an Ubuntu 14.04 environment. I followed the documentation to modify the section titled "Platform settings" of the file `LaTeX.sublime-settings`, i.e. specifying the path to `texlive` and the command executable for SublimeText. 

Since I had the Anaconda distribution of python installed (which I believe is quite common for people doing scientific computing), I also changed the path of "python2" to point to the `python` associated with Anaconda, instead of the one that comes with the Ubuntu system. 

Then, everything works except for the forward/inverse search. As I had pretty smooth experience with LaTeXTools on my Mac machine before, I didn't expect such nuisance and struggled for quite some time until I found #330 . Then I realized that the problem was caused by the fact that the `python` in Anaconda distribution doesn't have the module `dbus`. So I changed the path of `python` to point to the one shipped with Ubuntu and the problem is fixed.

So I feel it'd be quite helpful to add some comments in the documentation or the file `LaTeX.sublime-settings` to inform the Linux users about the above fact.

**Comment by ig0774** [comment]
Thanks for pointing this out. I've added a note about requiring `dbus` to the README.
