### ISSUE TITLE
Need a little help on how to fix the problem with LaTexTools in ST2/TexLive2014/Windows!

### ISSUE THREAD

**Issue by romerFin** [SublimeText/LaTeXTools#471]
I recently start to establish the environment for me to use LaTex in ST2 with TexLive 2014 on Windows.

After searching for several solutions, I still get the error message: COULD NOT COMPILE! as following:
<pre><code>
TraditionalBuilder: Invoking latexmk... 

COULD NOT COMPILE!

Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf first.tex

Build engine: Traditional Builder
</code></pre>

I've adjusted the following things and it just couldn't work.

．1.  Preferences -> Package Settings -> LaTexTools -> Settings-User

In the Platform settings, I changed the windows section as following (discarding comments):

<pre><code>
"windows": {
		"texpath" : "D:\\texlive\\2014\\bin\\win32;$PATH",
		"distro" : "texlive"
},
</code></pre>

．2.  I've added "D:\texlive\2014\bin\win32" to my environment variable.

In addition, in the "traditionalBuilder.py" file, I have the following commands:
<pre><code>
DEFAULT_COMMAND_LATEXMK = ["latexmk", "-cd",
				"-e", "$pdflatex = '%E -interaction=nonstopmode -synctex=1 %S %O'",
				"-f", "-pdf"]
</code></pre>

I think these are pretty much what I've done the past few days...

Thanks in advance hoping anyone can help me figure it out the problems.

**Comment by msiniscalchi** [comment]
Can you run latexmk from the command line?

On Fri, Jan 30, 2015 at 11:39 AM, romerFin <notifications@github.com> wrote:

> I recently start to establish the environment for me to use LaTex in ST2
> with TexLive 2014 on Windows.
>
> After searching for several solutions, I still get the error message:
> COULD NOT COMPILE! as following:
>
>
> TraditionalBuilder: Invoking latexmk...
>
> COULD NOT COMPILE!
>
> Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf first.tex
>
> Build engine: Traditional Builder
>
> I've adjusted the following things and it just couldn't work.
>
> ．1. Preferences -> Package Settings -> LaTexTools -> Settings-User
>
> In the Platform settings, I changed the windows section as following
> (discarding comments):
>
>
> "windows": {
>         "texpath" : "D:\\texlive\\2014\\bin\\win32;$PATH",
>         "distro" : "texlive"
> },
>
> ．2. I've added "D:\texlive\2014\bin\win32" to my environment variable.
>
> In addition, in the "traditionalBuilder.py" file, I have the following
> commands:
>
>
> DEFAULT_COMMAND_LATEXMK = ["latexmk", "-cd",
>                 "-e", "$pdflatex = '%E -interaction=nonstopmode -synctex=1 %S %O'",
>                 "-f", "-pdf"]
>
> I think these are pretty much what I've done the past few days...
>
> Thanks in advance hoping anyone can help me figure it out the problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/471>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by romerFin** [comment]
@msiniscalchi: I'm not quite sure how to run latexmk from the command line, but it seems when I tried to execute latexmk, it said:

command is not recognized as an internal or external command, operable program or batch file.

**Comment by msiniscalchi** [comment]
OK, so that's what i though. latexmk is not on your path. Please
double-check that you have added the correct path in the settings file. If
that fails, as a last resort, add the texlive binary path to your
environment variables. This last shouldn't be necessary though.

**Comment by romerFin** [comment]
@msiniscalchi: Could you explain it more explicitly? I don't quite understand, thanks!

Do you mean I should check this location "D:\texlive\2014\bin\win32" or the path I added in the setting file is wrong (as following)

<pre><code>
"texpath" : "D:\\texlive\\2014\\bin\\win32;$PATH"
</code></pre>

or how can I locate the real latexmk path and add it to the path accordingly?

It's a little bit confusing to me though.

**Comment by msiniscalchi** [comment]
Any progress on this? The settings you have should work... are you sure that you have actually installed latexmk? I'm not sure about Windows---I have miktex on my Windows laptop---but on OS X, you can install a basic set of texlive packages that does *not* include latexmk. Might that be the problem? Or did you install the whole texlive distro?

**Comment by romerFin** [comment]
Sorry it takes me so long to see your response. 
I've tried to set up another compiler other than ST2 and it actually worked!
It's a little be frustrating not to fully get through the ST2 installing process though.

**Comment by drasnop** [comment]
If anyone else is stuck with this, note that `latexmk` is not installed when you do a "small" installation of TexLive. To fix this after installing TexLive, open a Windows command prompt and type: `tlmgr install latexmk`
