### ISSUE TITLE
Setting path for the bib file location

### ISSUE THREAD

**Issue by nfar0032** [SublimeText/LaTeXTools#472]
Hello and first of all thank you for this amazing tool!!

I don't know if it is possible but I wanted to ask whether there is a way where I could set the path to where the bib file is located in the settings file such that when I type \cite{} it loads the references from that bib file automatically, because currently my bib file is not located in the same directory as the .tex files.

Thanks again!! :+1:

**Comment by msiniscalchi** [comment]
This would be nice to have. I'll mark it as a TODO item.

**Comment by merlinthered** [comment]
I would also find this functionality very useful, as I don't want to maintain a separate bibliography for all my different papers.

**Comment by r-stein** [comment]
It should be trivial to add a setting for that. I will have a look. However you will need to enable [prereleases](https://github.com/SublimeText/LaTeXTools#prereleases) to have that feature in the near future.

**Comment by r-stein** [comment]
Added in [prerelease](https://github.com/SublimeText/LaTeXTools/tree/st3-3.14.1#prereleases) `st3-4.0.0-alpha.2`
