### ISSUE TITLE
No cite autocompletion if bib file contains @online items

### ISSUE THREAD

**Issue by theArchonius** [SublimeText/LaTeXTools#473]
I'm using Sublime Text 3 & LaTeXTools (via Package Control) and biblatex and it seems that when I add @online items to my bib file, the auto-completion of cite commands stops working. Removing them resolves the issue, but thats actually not an option for me. I also tried moving them to a separate bib file in hope that this at least enables the auto completion for my other bib items, but it didn't help...

So am I missing something or is this a bug?

**Comment by msiniscalchi** [comment]
This is sadly one of the ways in which bib file parsing is incomplete. I have patches for a complete overhaul of the parsing code that would solve this and other issues, but it's a major change to the code, and I must find the time to evaluate it and merge it.

**Comment by ig0774** [comment]
`@online` entries should work with either of the two available bibliography plugins.
