### ISSUE TITLE
Skim backward search not working

### ISSUE THREAD

**Issue by a59** [SublimeText/LaTeXTools#474]
OS X 10.10.2
Sublime Text Build 3065
Skim 1.4.10

I have looked around and can't work out who to get the backward search function working from Skim to Sublime Text. 

This page was not much help.

http://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/#activating-backward-search-from-skim

**Comment by msiniscalchi** [comment]
Check the README: Skim now has a preset for Sublime Text! Select it (in Preferences) and you should be good to go. Closing.
