### ISSUE TITLE
Cite panel fails with UTF-8 characters in a bibtex file

### ISSUE THREAD

**Issue by pbruneau** [SublimeText/LaTeXTools#487]
Hi all,

As many, I store my bibliographic references in a .bib file, and cite them from my .tex files. I appreciate the cite panel provided by LaTexTools. I installed the latter via package control with SublimeText 2 - I expect I get an uptodate version this way. 

Assume a .tex file and a .bib file, both UTF-8 encoded, with appropriate usepackage clause in the tex. If my .bib file does not contain other character than ascii, the cite panel shows up fine. If it contains at least one non-ascii character (e.g. french accented characters in my case), it fails. I get this on the console:

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 60: ordinal not in range(128)

Traced back to the latest line of `latex_cite_completions.py`. After some research, I found a way to fix this, maybe a bit brutal for purists, but working anyway: adding:

    from __future__ import unicode_literals

At the beggining of `latex_cite_completions.py`. Works like a charm then. But as my fix gets supersed at each update of the package, maybe this should be fixed in a more durable (and maybe elegant) way?

**Comment by msiniscalchi** [comment]
The proper way is to add support for UTF-8-encoded bib files. But I'll look into what you suggest as a quick fix.

**Comment by ig0774** [comment]
This was fixed in v3.9.0.
