### ISSUE TITLE
Command (and environment) shortcuts don't work

### ISSUE THREAD

**Issue by vuwu** [SublimeText/LaTeXTools#488]
When I try to transform `color` into the corresponding latex command `\color{}` by using `⌘-L,C`, it won't work (it does sometimes, but it's unreliable). Similarly, I cannot replace `test` by the latex environment `\begin{test} ... \end{test}`, it will just remove `test` and display an empty environment `\begin{} ... \end{}` instead. I am on OSX 10.10.3.

**Comment by msiniscalchi** [comment]
I'm sorry, but I just checked once again, and everything works on my
machine (ST3, OSX 10.10.2, but I doubt the OS version makes any
difference). One thing to keep in mind is that, for the commands to work,
you must type, e.g., "test" and then immediately c-l,c or c-l,e: do not
type a space after "test."

On Sun, Apr 12, 2015 at 9:53 AM, LAC D <notifications@github.com> wrote:

> When I try to transform color into the corresponding latex command
> \color{} by using ⌘-L,C, it won't work (it does sometimes, but it's
> unreliable). Similarly, I cannot replace test by the latex environment \begin{test}
> ... \end{test}, it will just remove test and display an empty environment \begin{}
> ... \end{} instead. Something's wrong? I am on OSX 10.10.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/488>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by msiniscalchi** [comment]
Works on 10.10.3, too. Please double-check and close if all is OK.

**Comment by vuwu** [comment]
Everything works, I made the mistake to think that one has to highlight a passage in order to transform  it into a command or environment. Sorry for the confusion!
