### ISSUE TITLE
Synctex files not cleaned correctly

### ISSUE THREAD

**Issue by RomeshA** [SublimeText/LaTeXTools#492]
`delete_temp_files.py` fails to delete the `.synctex.gz` files on my system because it uses `os.path.splitext(file_name)` which returns the file extension as `.gz` rather than `.synctex.gz`. One solution may be to simply check if the file name ends with `.synctex.gz` since this is the only extension in the list that has more than one period.

**Comment by r-stein** [comment]
can be closed, fixed in https://github.com/SublimeText/LaTeXTools/pull/520

**Comment by msiniscalchi** [comment]
Closing.
