### ISSUE TITLE
reference temp file for revtex not included in delete_temp_files.py

### ISSUE THREAD

**Issue by moiraine-sedai** [SublimeText/LaTeXTools#493]
running latexmk on `foo.tex` with revtex4.1 will give a temporary file `fooNotes.bib` which should be deleted.

**Comment by msiniscalchi** [comment]
Recent versions incorporate patch #522, which allows you to configure which file *extensions* to delete. Unfortuantely I don't think that <filename>Notes.bib would be allowed. Short of special-casing RevTeX, I don't think this can be fixed. @ig0774 comments?

**Comment by ig0774** [comment]
Actually, the code in `delete_temp_files` only checks that the file ends with any of the strings in the `temp_files_exts` setting. If that setting had an entry for `'Notes.bib'` it should delete `fooNotes.bib` just as surely as `foo.bib`.

**Comment by msiniscalchi** [comment]
Fantastic. Then it's time to close this.
