### ISSUE TITLE
"Jump to PDF" loses focus (Linux, evince)

### ISSUE THREAD

**Issue by datamaan** [SublimeText/LaTeXTools#495]
Everytime I build or do a "Jump to PDF" the focus goes to evince. Settings and toggles are on "keep_focus": true.

I'm running ArchLinux with KDE5 and use evince as PDF-viewer for LaTeXTools.
Is there anything I'm doing wrong?

**Comment by HakanSiktas** [comment]
Same here on Windows and SumatraPDF.
> "keep_focus": true

does not work.

**Comment by gutierrezps** [comment]
Same here with MiKTeX and SumatraPDF on Windows 8.1 and Sublime 2. Nor toggling through the shortcut (Ctrl+L,T,F) neither by changing the setting on LaTeXTools.sublime-settings, the focus always goes to SumatraPDF.

**Comment by msiniscalchi** [comment]
This is, unfortunately, something that can't be fixed. Sumatra does not allow one to control focus via the command line, and for some reason DDE commands don't work on ST3 anymore. There's a branch on GitHub where I experimented---I tried many, many thigns, but nothing worked.
I'll document this when I get a chance. Very annoying!

Date: Sun, 14 Jun 2015 16:19:22 -0700

**Comment by gutierrezps** [comment]
Thanks for the quick response. But can't you just toggle the jumpToPDF function? I mean, if "Focus editor" is enabled, don't call jumpToPDF command. If not, why?

**Comment by r-stein** [comment]
For the Sumatra part:
``` python
# ...
# removed startupinfo argument
subprocess.Popen(startCommands)

if keep_focus:
    # the command to start ST
    # could also be "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"
    sublime_command = "subl"
    # time to await the start of Sumatra (in ms)
    wait_time = 500
    def focus_sublime():
        subprocess.Popen(sublime_command, shell=_ST3)
    sublime.set_timeout(focus_sublime, wait_time)
```
works surprisingly well.

**Comment by PeterPablo** [comment]
Thank you @r-stein, this worked great for me. Important: Be carefull to change the leasing spaces `   ` to leading tabulator! I added an additional print statement `` to confirm on the console that this part of the code is reached.

I used **PackageResourceViewer: Open Resource** to edit `jumpToPDF.py`.

@r-stein, please consider creating a pull request. Quite certainly, this would require to make the line `sublime_command` to be smart about the executable's location though.

Thanks again!

**Comment by ig0774** [comment]
@r-stein's suggestion has been merged, so this should be fixed.
