### ISSUE TITLE
How to make nomencl work?

### ISSUE THREAD

**Issue by dr424** [SublimeText/LaTeXTools#503]
Hi, 

I am trying to compile a simple example that makes use of the nomencl package to print nomenclature. I am using SublimeText and LaTeXTools with mac, and it compiles without errors, but the nomenclature is not printed. I have been inspecting the build rules of LaTeXTools, but I cannot find the way to make it work. The example is: 

\documentclass[a4paper,10pt]{article}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{nomencl}
\renewcommand{\nomname}{Nomenclature}
\makenomenclature

\title{I am trying to make nomencl work}
\author{}

\begin{document}
\maketitle
\blindtext \nomenclature{HI}{Hello} \nomenclature{BYE}{Good bye}
\printnomenclature
\end{document}

Thanks

**Comment by msiniscalchi** [comment]
What do you see in the ST console (ctrl-backtick)? Any error messages? Did
you check the TeX log file? This may be a LaTeX issue...

**Comment by dr424** [comment]
Hi, 

The ST console prints out the following:
-----------------------------
[Compiling /Users/admin/Desktop/Test/nomencl.tex]

TraditionalBuilder: Invoking latexmk... done.

No errors.


[Done!]
-----------------------------


Then, checking the log file, it seems it loads the nomencl package but it is unable to create the .nsl file:

(/usr/local/texlive/2014/texmf-dist/tex/latex/nomencl/nomencl.sty
Package: nomencl 2005/09/22 v4.2 Nomenclature package (LN)
\nomlabelwidth=\dimen104
\nom@tempdim=\dimen105
\nomitemsep=\skip43
)
\@nomenclaturefile=\write3
\openout3 = `nomencl.nlo'.


Writing nomenclature file nomencl.nlo
(./nomencl.aux)
\openout1 = `nomencl.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 12.
LaTeX Font Info:    ... okay on input line 12.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <12> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 14.

No file nomencl.nls.
[1


Checking with other programs, like TeXShop, it seems to have to create first some sort of engine for nomenclature (http://tex.stackexchange.com/questions/37567/invoking-makeindex-for-nomencl) and then modify the compilation rules to make it consider the nomenclature. I have tried to do something similar on ST, checking the build rules, but as I mentioned earlier, I have been unable to do it. 

Provided that you also use mac, are you able to replicate this problem? 

Thanks in advance.

**Comment by ig0774** [comment]
The problem here has little to do with LaTeXTools itself and more to do with the underlying build engine (`texify` on MiKTeX and LaTeXmk on basically anything else) and, more specifically, with the build tools having no knowledge of the various packages that might use the `makeindex` functionality (they DO both support generic indexes).

The [documented solution](http://mirrors.ctan.org/support/latexmk/example_rcfiles/nomenclature_latexmkrc) for LaTeXmk is to create a `.latexmkrc` file which contains the following entry:

    # Custom dependency and function for nomencl package
    add_cus_dep( 'nlo', 'nls', 0, 'makenlo2nls' );
    sub makenlo2nls {
        system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
    }

Which will correctly process the nomenclature for your test. Alternatively, or on a platform that doesn't use LaTeXmk, you can add this line to the top of your document:

    \immediate\write18{makeindex -s nomencl.ist -o "\jobname.nls" "\jobname.nlo"}

(pulled from [this](http://tex.stackexchange.com/a/198475) question)
