### ISSUE TITLE
Recursively delete temp files does not remove .synctex.gz

### ISSUE THREAD

**Issue by fredrike** [SublimeText/LaTeXTools#509]
The python function [os.path.splitext](https://docs.python.org/2/library/os.path.html#os.path.splitext): 

`Split the pathname path into a pair (root, ext) such that root + ext == path, and ext is empty or begins with a period and contains at most one period. `

Used  at line [33](https://github.com/SublimeText/LaTeXTools/blob/master/delete_temp_files.py#L33) will never match `.synctex.gz` ([L34](https://github.com/SublimeText/LaTeXTools/blob/master/delete_temp_files.py#L34)) hence it will never be removed.

**Comment by ig0774** [comment]
Just ftr, there's already an issue (#492) covering this and a patch (#494) which fixes the issue...
