### ISSUE TITLE
Citing from a bibliography with one entry

### ISSUE THREAD

**Issue by QuantumPhi** [SublimeText/LaTeXTools#518]
If "TL;DR": Single bibliography entry `->` autocomplete `\cite` command

This is more of a convenience issue.

When citing from a bibliography with `\cite{}`, the options panel shows up, allowing for selection of a source from the list in the bibliography. However, when the bibliography contains only 1 entry:
```
@book={robot,
    author={Asimov, Isaac},
    title={I, Robot},
    date=1950
}
```
having the selection show up seems redundant, as there is no other option to choose from.

In this example, using the command `\cite` then opening a brace should automatically insert the citation for `robot` from the bibliography.

**Comment by ig0774** [comment]
Since the relevant change has been merged, I'm closing this.
