### ISSUE TITLE
"latexmk" cannot be found

### ISSUE THREAD

**Issue by zhuzelong** [SublimeText/LaTeXTools#523]
OS: Mac OS X 10.10.3
Editor: SublimeText 3

I upgraded the TeX distribution to TeX Live 2015. The error `the command line tool 'latexmk' is not available on your path.`

I switched back to TeX Live 2014 and typed `which latexmk` in terminal, it returned a path. But when I switched to TeX Live 2015 and typed `which latexmk` in terminal, it returned nothing. 

I am not sure whether `latexmk` is disabled in TeX Live 2015. But could I tell LaTeXTools to use the command `pdflatex` instead of `latexmk`?

**Comment by ig0774** [comment]
You could always switch to the simpleBuilder in your LaTeXTools.sublime-preferences file (`Sublime Text` **->** `Preferences` **->** `Package Settings` **->** `LaTeXTools` **->** `Settings - User`). It sounds like you downloaded the "BasicTeX" version instead of the full TeX distro....
