### ISSUE TITLE
LatexTools hanging on Build (MacOS X)

### ISSUE THREAD

**Issue by powellb** [SublimeText/LaTeXTools#527]
I have been successfully using LatexTools for quite some time (thanks for a great package); however, it now takes 1-2 minutes to build a document. When I start the build, the beachball appears and 1-2 minutes later, it states the following and the document is built:

[Compiling /Users/powellb/test.tex]

TraditionalBuilder: Invoking latexmk... done.

No errors.

However, the document should take milliseconds to build. If I perform latexmk from the command-line, it completes nearly instantly.

Any suggestions on why it is completely blocking Sublime Text (cannot perform any other actions during Build) for 1-2 minutes?

**Comment by msiniscalchi** [comment]
@powellb any new info on this? Does the problem persist in recent versions?

**Comment by powellb** [comment]
I haven't had a problem. It seemed to be related to whether Skim.app was already open, but everything seems fine now...
