### ISSUE TITLE
xelatex and latexmk

### ISSUE THREAD

**Issue by jknaus** [SublimeText/LaTeXTools#528]
Hi,
I am using sublime text 3 and latextools (2015-4-12 under xubuntu 15.04 with vanilla texlive 2015 (not the one from the package repos).
I mostly typeset xetex/xelatex documents using latexmk, this work fine in texworks if I add 

    % !TEX TS-program = xelatexmk

to the beginning of the document and create a typeset script 

    latexmk -pdf -e '$pdflatex=q/xelatex $synctexoption %O %S/' $fullname

Where should one place this typeset script in latextools?
Right now, a build fails with the following error

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Fatal fontspec error: "cannot-use-pdftex"
    ! 
    ! The fontspec package requires either XeTeX or LuaTeX to function.
    ! 
    ! You must change your typesetting engine to, e.g., "xelatex" or "lualatex"
    ! instead of plain "latex" or "pdflatex".
    ! 
    ! See the fontspec documentation for further information.
    ! 
    ! For immediate help type H <return>.
    !...............................................  

Obviously, latextools doesn't know how to handle the xelatexmk TS-program.
Thanks for your help.

**Comment by ig0774** [comment]
The use of xelatexmk as a name for the LaTeX engine is an artifact of TeXShop from when XeTeX was new and Mac-only.

Obviously LaTeXTools doesn't support TeXworks typeset scripts out of the box, but the builders are fully customisable, so it could be done with a bit of Python.

However, for what you want to accomplish, just add a comment `% program = xelatex` before your current TS-program line (or change the TS-program line to xelatex) and it will do what you expect...
