### ISSUE TITLE
\cite autocomplete not working

### ISSUE THREAD

**Issue by MartyPye** [SublimeText/LaTeXTools#530]
Hi,

I'm on Sublime Text 3 with the latest version of LaTeXTools. Unfortunately, the \cite autocomplete isn't working, it fails with the following output in the console. Any ideas?

![screen shot 2015-07-07 at 09 45 34](https://cloud.githubusercontent.com/assets/3891674/8541242/03517980-248d-11e5-983f-38001d937287.png)

Cheers,
Marty

**Comment by ig0774** [comment]
Most likely you have a file encoded in Windows CP-1252, the default code page for English in Windows, containing the accented character "é". Support for non-ascii / utf8 encoded files is... not great. Similarly, the bibliography stuff tends to choke on non-ascii characters (e.g. #487), so your best bet, for now, is to just to use TeX-style accents, e.g., replace "é" with {\'e}.

**Comment by MartyPye** [comment]
This solution worked, thanks! I had some files with comments in both German and English, so I removed all ä,ü,ö,ß/etc.
