### ISSUE TITLE
Cannot compile on El Capitan

### ISSUE THREAD

**Issue by NathanJang** [SublimeText/LaTeXTools#533]
This is what I get when I try to build:

```
[Compiling /Users/.../Paper.tex]

TraditionalBuilder: Invoking latexmk... 

COULD NOT COMPILE!

Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf Paper.tex
Build engine: Traditional Builder
```

I understand that El Capitan doesn't symlink `/usr/texbin` so it might be a path issue; see [the section "El Capitan" here](https://www.tug.org/mactex/mactex-download.html).

**Comment by ig0774** [comment]
Yep. See #531, which is exactly the same issue.

**Comment by NathanJang** [comment]
Thanks!
