### ISSUE TITLE
How to autocomplete environments

### ISSUE THREAD

**Issue by zhuzelong** [SublimeText/LaTeXTools#540]
SublimeText 3
latest LaTeXTools

In a LaTeX file, when I typed `enum`, it would be auto completed as:

```
\begin{enumerate}
        (cursor here)
\end{enumerate}
```

But when I typed `descrip`, nothing is completed. Then I typed `\begin{descrption}` and tab it, the completion was:

```
\begin{\begin{description}
        (cursor here)
\end{description}
```

I have to delete the redundant `\begin`. This issue also happened in other environments `subsection`, `subsubsection`. 

How could I make the auto complete works right?

**Comment by mikedecr** [comment]
The LaTeX language files that come with Sublime by default contain two snippet files that might be close to what you're looking for. The first one begins and ends an environment, which is triggered by `begin + tab`, and the second is a description environment snippet, which is triggered by `desc + tab`. Are you looking for something more specific than these?

**Comment by zhuzelong** [comment]
@mikedecr I get it. Thank you very much.
