### ISSUE TITLE
Evince+sublimte text 3+LaTeXTools - evince is too slow

### ISSUE THREAD

**Issue by andradx** [SublimeText/LaTeXTools#541]
Hi all,

This might be a bit unrelated since it is due to evince, I guess, but I thought it worth giving it a shot here.

**Sublime is great** - true

**LaTeXTools is great** - true (maybe the -shell-escape feature could be activated by default, but I managed to have it working)

Evince is great - **not really**

Writing a paper is something, writing a big document is another. In particular, evince is keept open after the first time and just refreshes the document. But to some extent it seems as if evince is tracking a history of my clicking on the Index pane, and also on the number of hyperref links I click. It progressively slows down the more I click. Eventually, everytime I scroll up or down to a new page (zoom is at around 153%) it hiccoughs for a second, i.e., scrolling pauses, 1 second goes by and then loads the page.

Doesn't really work that I turn off parts of my document for compilation, I'm trying to write a thesis and I need the full thing typed from time to time to make sure every hyperref is correct, references make sense, etc... But it elevates the document size to around 10MB.

For the sake of things I'm on Arch with Evince 3.16.1, Sublime Text 3 and LaTeXTools installed from the Control Package as instructed.

Sorry if the post doesn't really fit here, but I was hoping someone could direct me towards a lighter pdf viewer supporting the synctex functions, reverse(inverse?) and forward search.

Thank you for your help.

**Comment by aleth** [comment]
Okular works well and supports synctex. I haven't tried it with Latextools though.

**Comment by andradx** [comment]
Okular will require installing a big chunk of KDE related stuff. Will try it though.

**Comment by andradx** [comment]
Okular is better, but not as fluid as I'd hope. At that zoom level, page crossing is still a bummer.

Can anyone confirm that this work for backward search?

https://github.com/cbrunet/LaTeXTools/commit/870102cd7809a317d6af96a411f8d14a58977b7a
