### ISSUE TITLE
Bug: Auto-complete for \longrightarrow places \rightarrow instead

### ISSUE THREAD

**Issue by bazzilic** [SublimeText/LaTeXTools#542]
I am not sure the problem is exactly in LaTeXTools, but it looks very probable to me.

### Steps to Reproduce
1. Type several first characters of `\longrightarrow`
2. Press ctrl+space to bring up auto-complete menu, if it did not appear on its own
3. select `longrightarrow` from the list

### Expected Results
`\longrightarrow` is inserted

### Actual Results
`\rightarrow` is inserted

**Comment by ig0774** [comment]
Btw, if you want to fix this before the pull request is made, just replace the `LaTeX math.sublime-completions` file in your `LaTeXTools` package directory with [the one found here](https://raw.githubusercontent.com/ig0774/LaTeXTools/longrightarrow/LaTeX%20math.sublime-completions).

**Comment by bazzilic** [comment]
Thanks man! That issue was annoying as heck )

**Comment by ig0774** [comment]
I'm closing this as the latest update now has the updated `LaTeX math.sublime-completions` file.
