### ISSUE TITLE
PDF build fails

### ISSUE THREAD

**Issue by mcnesium** [SublimeText/LaTeXTools#545]
After upgrading to OSX 10.10 this plugin is not building properly anymore in ST3. I saw #401 but the solution is already implemented in the current version of LatexTools. 

    \documentclass{report}
    \begin{document}
    test
    \end{document}

This might not be a very good minimal example, but it does show the following output in the ST3 console:

    <module 'simpleBuilder' from '/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/simpleBuilder.py'>
    <class 'simpleBuilder.SimpleBuilder'>
    4
    Welcome to thread Thread-58
    ['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'test']
    Finished normally
    1
    Exception in thread Thread-58:
    Traceback (most recent call last):
      File "./threading.py", line 901, in _bootstrap_inner
      File "/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 164, in run
        data = open(self.caller.tex_base + ".log", 'rb').read()
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/mcnesium/Desktop/testtex/test.log'

so I did `touch test.log` in the directory and then the console said this:

    <module 'simpleBuilder' from '/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/simpleBuilder.py'>
    <class 'simpleBuilder.SimpleBuilder'>
    3
    Welcome to thread Thread-60
    ['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'test']
    Finished normally
    1
    False True True
    !TEX root =  '/Users/mcnesium/Desktop/testtex/test.tex'
    Jump to:  6 14

Looks ok but neither a pdf has been created nor skim started. With another real project any changes to the latex files remain undetected and the PDF is not updated, but skim is started and the already existing pdf is loaded. So is this a PDF-related issue?

**Comment by msiniscalchi** [comment]
​I don't have access to El Capitan, so I can't test this. I have seen
reports from other users though. Looks like the location of the tex tree
has changed, or something like that. [I could rant about Apple screwing
with well-established Unix tradition, but I won't... yet.]

Anyway, I will certainly upgrade as soon as El Capitan is released, and I
will then implement a fix.​ [I hope at least!]

On Mon, Aug 17, 2015 at 3:19 PM, mcnesium <notifications@github.com> wrote:

> After upgrading to OSX 10.10 this plugin is not building properly anymore
> in ST3. I saw #401 <https://github.com/SublimeText/LaTeXTools/issues/401>
> but the solution is already implemented in the current version of
> LatexTools.
>
> \documentclass{report}
> \begin{document}
> test
> \end{document}
>
> This might not be a very good minimal example, but it does show the
> following output in the ST3 console:
>
> <module 'simpleBuilder' from '/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/simpleBuilder.py'>
> <class 'simpleBuilder.SimpleBuilder'>
> 4
> Welcome to thread Thread-58
> ['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'test']
> Finished normally
> 1
> Exception in thread Thread-58:
> Traceback (most recent call last):
>   File "./threading.py", line 901, in _bootstrap_inner
>   File "/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 164, in run
>     data = open(self.caller.tex_base + ".log", 'rb').read()
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/mcnesium/Desktop/testtex/test.log'
>
> so I did touch test.log in the directory and then the console said this:
>
> <module 'simpleBuilder' from '/Users/mcnesium/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/builders/simpleBuilder.py'>
> <class 'simpleBuilder.SimpleBuilder'>
> 3
> Welcome to thread Thread-60
> ['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'test']
> Finished normally
> 1
> False True True
> !TEX root =  '/Users/mcnesium/Desktop/testtex/test.tex'
> Jump to:  6 14
>
> Looks ok but neither a pdf has been created nor skim started. With another
> real project any changes to the latex files remain undetected and the PDF
> is not updated, but skim is started and the already existing pdf is loaded.
> So is this a PDF-related issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/545>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by mcnesium** [comment]
This is on Yosemite (10.10)

**Comment by msiniscalchi** [comment]
Oh, sorry. In this case I'm not sure---I'm running Yosemite on all my Macs
with no issues....

On Mon, Aug 17, 2015 at 8:45 AM, mcnesium <notifications@github.com> wrote:

> This is on Yosemite (10.10)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/545#issuecomment-131821718>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by mcnesium** [comment]
Just did a complete reinstall using `brew cask remove basictex` and `brew cask install basictex`. After reinstalling all the packages needed in my project using `sudo tlmgr install …` it looks like everything works again now.
Before that issue appeared I did a `sudo tlmgr update --self --all` – this might have crashed because the Tex Live distro upgraded to 2015 in between.
With all that done I must again state that the latex universe is still all but user friendly. But this does not belong here, so nevermind.
