### ISSUE TITLE
Disable % (fold) in auto-completions

### ISSUE THREAD

**Issue by mcnesium** [SublimeText/LaTeXTools#548]
Is there a way to disable the `% (fold)` and corresponding `% … (end)` in the headline auto-completion of chapters, sections etc? In ST3 Build 3083 they do not seem to work with code folding anyway.

**Comment by ig0774** [comment]
Those snippets have nothing to do with this plugin. They are part of the default LaTeX package bundled with Sublime Text, and, unfortunately, [there isn't really a way to override snippet files](https://sublimetext.userecho.com/topic/117895-overwrite-default-snippets/). You could create your own snippet files in your User directory, something like this:

```xml
<snippet>
    <content><![CDATA[\chapter{${1:chapter name}}
\label{cha:${2:${1/\\\w+\{(.*?)\}|\\(.)|(\w+)|([^\w\\]+)/(?4:_:\L$1$2$3)/g}}}
${0:$TM_SELECTED_TEXT}]]></content>
    <tabTrigger>chapter</tabTrigger>
    <scope>text.tex.latex</scope>
    <description>Chapter</description>
</snippet>
```

But that won't get rid of the pre-existing snippet; it will merely give you another option.

**Comment by mcnesium** [comment]
ok thx for the reply anyway

**Comment by Andi-Lo** [comment]
Here is a different approach that might fix that problem for you in a better way

1. Install the sublime package "PackageResourceViewer" via package control
2. Hit strg + shift + p and type: "PackageResourceViewer: Open Resource"
3. Search for Latex and select it
4. Then Select the snippet you want to change (e.g. Chapter)
5. Delete the %fold and hit save.

Done!

I don't know if this stays the same if the Package "Latex" gets an update but that's how it worked for me.

**Comment by ig0774** [comment]
I'm closing this because I don't see any way LaTeXTools can address this. @Andi-Lo's solution is probably the best that's aside from [a PR for the LaTeX package](https://github.com/sublimehq/Packages) itself.
