### ISSUE TITLE
.lox files are not deleted

### ISSUE THREAD

**Issue by Limro** [SublimeText/LaTeXTools#549]
I should be making a pull request for this, but the last one I did didn't get through...

As the title says, the ``.lox`` files does not get deleted. These files comes around with the ``fixMe`` package.
``Packages\LaTeXTools\delete_temp_files.py`` : Add ``,'.lox'`` to line 28/29, please.

**Comment by r-stein** [comment]
Since the extensions are now user definable (https://github.com/SublimeText/LaTeXTools/pull/520), I would assume you can close the issue

**Comment by Limro** [comment]
Sounds fair.
