### ISSUE TITLE
\cite automation fill in external .tex files

### ISSUE THREAD

**Issue by Koffieketel** [SublimeText/LaTeXTools#550]
Hi everyone, 

Working in ST2 the automated \cite bar comes up at my main file as shown: http://puu.sh/jRyMn/1fc73343bd.png
In this main file, I include several chapters by the \include command. 

However when I am typing in one of my seperate chapter .tex files, ST doesn't recognize the citations anymore and I get the following error: http://puu.sh/jRyQY/dd0020c855.jpg

Does anyone knows what is going wrong? 

Thanks

**Comment by msiniscalchi** [comment]
You need to use the "tex root" directive at the top of each included file.
Please check the README for details.

On Fri, Aug 28, 2015 at 8:30 AM, Koffieketel <notifications@github.com>
wrote:

> Hi everyone,
>
> Working in ST2 the automated \cite bar comes up at my main file as shown:
> http://puu.sh/jRyMn/1fc73343bd.png
> In this main file, I include several chapters by the \include command.
>
> However when I am typing in one of my seperate chapter .tex files, ST
> doesn't recognize the citations anymore and I get the following error:
> http://puu.sh/jRyQY/dd0020c855.jpg
>
> Does anyone knows what is going wrong?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/550>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661
