### ISSUE TITLE
Replacing PDFTex with LuaTeX

### ISSUE THREAD

**Issue by carsten-j** [SublimeText/LaTeXTools#553]
I cannot find the command option under Builder Settings in the LaTeX.sublime-settings file. Can someone please explain exactly how to replace PDFTex with LuaTeX as Tex Engine. Please post a working example of a LaTeX.sublime-settings file doing this.

**Comment by msiniscalchi** [comment]
Check the README. You can use a %!TEX directive as the first line of your
(master) tex file; you don't need to mess with the settings file.

On Wed, Sep 2, 2015 at 3:49 PM, Carsten Jørgensen <notifications@github.com>
wrote:

> I cannot find the command option under Builder Settings in the
> LaTeX.sublime-settings file. Can someone please explain exactly how to
> replace PDFTex with LuaTeX as Tex Engine. Please post a working example of
> a LaTeX.sublime-settings file doing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/553>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by carsten-j** [comment]
Thanks. But I would really like to know how it works by means of changing the LaTeX.sublime-settings file.

**Comment by ig0774** [comment]
If you just want to change the engine, something like this `builder_settings` block should do the same trick:

```json
"builder_settings": {
    "program": "lualatex"
},
```

You are almost certainly better off using the `%!TEX` directive though, since its settable on a per-file basis instead of just globally.

**Comment by carsten-j** [comment]
That did the trick. Thanks!
