### ISSUE TITLE
Setting "builder" to "script": LaTeXTools no longer builds (OS X)

### ISSUE THREAD

**Issue by louwers** [SublimeText/LaTeXTools#554]
Somehow, if I set "builder" to "script", LaTeXTools refuses to build (a blank console appears but nothing happens). This is not a path issue, I tried to open Sublime Text using the Terminal, but still the problem persists.

I tried adding a line to 'program' and also 'command' of 'builder_settings' (even though these should have default values), basically copying [this configuration](http://tex.stackexchange.com/questions/170723/custom-build-settings-in-sublime?newreg=8bb2fea5ce4c4d788f10edba577b5c28). Is there any other setting I should set for "script" to work as builder?

**Comment by ranneyd** [comment]
Did you solve this issue? I'm getting it now

**Comment by msiniscalchi** [comment]
The script builder is not implemented yet.

**Comment by ranneyd** [comment]
I think I'm having a different issue then. When I try to build I get the same result as he did (white console at the bottom, no output). Sublime text builds .cpp files and I was able to hack together a very rudimentary build system that runs pdflatex on the .tex file and it works too. I haven't done anything related to setting "builder" to "script", at least I don't think I have.

**Comment by r-stein** [comment]
@ranneyd I think you have this issue https://github.com/SublimeText/LaTeXTools/issues/589

**Comment by ranneyd** [comment]
I think you are correct
