### ISSUE TITLE
Inconsistency README / comments in settings w.r.t. build_settings

### ISSUE THREAD

**Issue by louwers** [SublimeText/LaTeXTools#555]
On the one hand the comments tell:
```
	// "script"			external script: just invokes the script
	//					specified in "builder_settings"
```
Yet on the other hand the README reads:
```
builder-settings: these are builder-specific settings. For the default/traditional builder, the following settings are useful: 
```
I finally got my custom build command to work by setting the builder to `default`, instead of `script`.

**Comment by msiniscalchi** [comment]
The script builder is still experimental and incomplete---it does nothing
right now.

On Sat, Sep 5, 2015 at 5:56 AM, Bart Louwers <notifications@github.com>
wrote:

> On the one hand the comments tell:
>
>     // "script"         external script: just invokes the script
>     //                  specified in "builder_settings"
>
> Yet on the other hand the README reads:
>
> builder-settings: these are builder-specific settings. For the default/traditional builder, the following settings are useful:
>
> I finally got my custom build command to work by setting the builder to
> default, instead of script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/555>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by louwers** [comment]
That might explain why it didn't work, haha.
Might I suggest making that more explicit? [I am not the only one](http://tex.stackexchange.com/questions/170723/custom-build-settings-in-sublime/178804) that tried using it.

Thank you.
