### ISSUE TITLE
auto pairing \[ \]

### ISSUE THREAD

**Issue by fwang2** [SublimeText/LaTeXTools#557]
## steps to reproduce (ST2):

Type the following 

     \[ ]

I was expecting:

    \[ \]

I am not sure if this should be handled within or can be handled with customization.

**Comment by iamntz** [comment]
I'm not using this package, but adding this on your keymap may help:

```
{ "keys": ["["], "command": "insert_snippet", "args": {"contents": "[$0\\]"}, "context":
  [
    { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
    { "key": "preceding_text", "operator": "regex_contains", "operand": "\\\\", "match_all": true },
  ]
},
```

**Comment by fwang2** [comment]
this snippet appears to be working its magic.
many thanks
