### ISSUE TITLE
Sublime Text reports no error, but there are.

### ISSUE THREAD

**Issue by Limro** [SublimeText/LaTeXTools#558]
I have written some bogus into my document:

```Latex
\section{Case: GPS location}

\seasdasd

\lipsum[1]
```

I'd expect the log to state something is messed up, but that is not the case. 
I get the following:

```
No errors. Warnings:

(Log parsing issues. Disregard unless something else is wrong.)
```

But if I run it through TexMaker the error is listed as 

``Error | line 12 | ! Undefned control seqeuence. \seasdasd``

Any clues to what might be wrong?

**Comment by ig0774** [comment]
Can you give an actual [MWE](http://minimalbeispiel.de/mini-en.html) or at least the log? The log parsing code is probably not perfect, but it certainly works for this

```latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\section{Case: GPS location}

\seasdasd

\lipsum[1]
\end{document}
```

Which means there is probably something else in your document that the log parser is choking on.

**Comment by Limro** [comment]
And now I can't reproduce the result my self... that was odd.
Mark as closed.
