### ISSUE TITLE
Recurring Build Problems on El Capitan

### ISSUE THREAD

**Issue by ankmathur96** [SublimeText/LaTeXTools#560]
Getting the following error message: 

COULD NOT COMPILE!

Attempted command:latexmk -cd -e $pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S %O' -f -pdf hw3.tex

I saw the thread about this from a year ago that discussed removing the space between the equal sign, but I have been unable to figure out how to fix this in the latest builds of LatexTools, where some of the advice for those files is not applicable.
Uninstalling and reinstalling the package has not helped the problem. The past couple of times this has happened, I have switched back to MacTeX for some time and then gone back, and suddenly, it works! It has reverted to a state of not working just now. Any notes on how to fix?

**Comment by msiniscalchi** [comment]
You need to add the path to your TeX distribution that is linked to in
/Library/TeX. This may be as simple as /Library/TeX/texbin, or more
complicated---I'll add info in the README.

On Wed, Sep 30, 2015 at 8:49 PM, Ankit Mathur <notifications@github.com>
wrote:

> Getting the following error message:
>
> COULD NOT COMPILE!
>
> Attempted command:latexmk -cd -e $pdflatex = 'pdflatex
> -interaction=nonstopmode -synctex=1 %S %O' -f -pdf hw3.tex
>
> I saw the thread about this from a year ago that discussed removing the
> space between the equal sign, but I have been unable to figure out how to
> fix this in the latest builds of LatexTools, where some of the advice for
> those files is not applicable.
> Uninstalling and reinstalling the package has not helped the problem. The
> past couple of times this has happened, I have switched back to MacTeX for
> some time and then gone back, and suddenly, it works! It has reverted to a
> state of not working just now. Any notes on how to fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/560>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by ankmathur96** [comment]
Thanks! Where is the file that I have to change the path in (or where is the section you've discussed this in the README?)

**Comment by rk2900** [comment]
Hi,

I've add one more line in ~/.bash_profile, the line is as below:
> export PATH="$PATH:/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin"

But the error occurs again: COULD NOT COMPILE!

How can I fix it?

Thank you!

**Comment by moiraine-sedai** [comment]
Changing path as per https://github.com/SublimeText/LaTeXTools/issues/531 works for latex doc not containing eps only as the eps figures are no longer automatically converted to pdf somehow. The same document and the same setting works fine in yosemite.

**Comment by moiraine-sedai** [comment]
Fixed for me under the newest version 2015-10-01. Thanks!

**Comment by ankmathur96** [comment]
Changing path seems to work consistently. Thanks!
