### ISSUE TITLE
Fill helper does not escape directory names

### ISSUE THREAD

**Issue by KamphuisAlex** [SublimeText/LaTeXTools#564]
I usually store images in a folder called img. In the .tex-file i would use:
\includegraphics{img/image.eps}

The fill helper does finds the images in subdirectories perfectly, but when inserting it gives
\includegraphics{img\image.eps}, (note the backslash} which is interpreted as a command rather then a path. The fill helper should provide either '/' or '\\' in stead of '\' for it to work pefectly.

**Comment by KamphuisAlex** [comment]
I have edited the latex_input_completions.py file to replace '\' with '/'.

I hardcoded it in there, because I have too little knowledge about for instance using a setting to toggle wether you want this. I think that therefore it is not a good idea to create a pull request. But if you have the same problem as i do, you can solve it (temporarily?) by editing the latex_input_completions.py file like so:

#. find the line that says 'result = [[' (it is in the *run* function in the *LatexFillInputCommand*-class)
#. goto 'filename in completions]' which should be around line 217, and append the following code afterwards

    if type(result[0]) is list:
                # list of list
                i = 0
                for r1 in result:
                    r1 = [r.replace('\\', '/') for r in r1]
                    result[i] = r1
                    i = i + 1
            else:
                # list of strings
                result = [r.replace('\\', '/') for r in result]

**Comment by r-stein** [comment]
This issue will be fixed after merging pull request https://github.com/SublimeText/LaTeXTools/pull/570 .

**Comment by msiniscalchi** [comment]
Thank you! I will pull this by the week-end.

On Wed, Oct 21, 2015 at 1:10 PM, Richard Stein <notifications@github.com>
wrote:

> This issue will be fixed after merging pull request #570
> <https://github.com/SublimeText/LaTeXTools/pull/570> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/564#issuecomment-149981244>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by r-stein** [comment]
Don't forget to pull the request @msiniscalchi.

In addition this might be an improper suggestion, but I think it would be worth considering to add @ig0774 as a collaborator. Since he seems to be very motivated, helpful, and competent in the code base. Hence it would be a win-win situation: it would take some load from your shoulder, ig0774 and other contributors could publish their features more frequently, and the users would have a lower respond time to bug reports/feature requests.

**Comment by r-stein** [comment]
This can be closed now.

**Comment by KamphuisAlex** [comment]
solved in latest update
