### ISSUE TITLE
Feature request: Auto-hide console following build

### ISSUE THREAD

**Issue by stevebarratt123** [SublimeText/LaTeXTools#566]
Apologies if this is posted in the wrong place, I couldn't find anywhere else. 

I routinely make this modification:

http://stackoverflow.com/questions/25441973/sublime-text-latextools-console-autohide

to makePDF.py whenever LaTeXTools is updated. The last few times I get something wrong when I try to re-edit the file, perhaps I'm missing some nuance of python syntax.. Anyway, I and I'm sure many others find this little mod very useful, particularly if one is very frequently building to check progress. Could this be added to the official release?

Either way, thanks for the fabulous package!

**Comment by mckennapsean** [comment]
:+1:

**Comment by r-stein** [comment]
As mentioned this is adressed by pull request https://github.com/SublimeText/LaTeXTools/pull/574.

Until the pull request is merged you might want to add this after line 177: (The stackoverflow answer is missing the caller attribut)
```python
self.caller.window.run_command("hide_panel", {"panel": "output.exec"})
```
In addition you could just checkout the git repository, locally commit your changes, and pull manually to avoid repeating the manipulations many times.

**Comment by r-stein** [comment]
This can be closed now. (adressed in https://github.com/SublimeText/LaTeXTools/pull/574)

To enable the feature you can re-migrate your setting and then change the field `hide_build_panel` or just add the attribut to your `LaTeXTools.sublime-settings`, e.g.
``` javascript
"hide_build_panel": "no_errors",
```
to hide the build panel if no errors occur.
