### ISSUE TITLE
Pdflatex doesn't work - but then does (windows)

### ISSUE THREAD

**Issue by kirbpowell** [SublimeText/LaTeXTools#567]
Sorry if this is in the wrong place. 

Just installed this add on to try out using Sublime for LaTeX. I'd previously been using TeXworks. I installed LaTeXTools, fixed up my PATH, and installed updates for MiKTeX. 

Now, whenever I compile a .tex file from Sublime, I get the "pdflatex.EXE has stopped working" prompt which stops and lets me close the program. I do, and then the build dialogue in sublime finishes and tells me that no errors have occurred, but sumatraPDF does not open. I go ahead and navigate to the folder where my .tex files are located, and sure enough, I've got all the files I would expect from a successful compilation. The PDF has generated with all my changes, and the logs look good. 

What's going on, and how can I keep pdflatex from crashing each and every time I compile from sublime?

**Comment by msiniscalchi** [comment]
You need to automatically generate a settings. Check the README.

**Comment by kirbpowell** [comment]
Thanks for responding!

I already generated a settings file when I initially installed LaTeXTools. I did try to re-generate one, just to make sure I wasn't mistaken, but it gave me the "do you want to overwrite your existing settings file" dialogue - so that's not the problem. I I did actually check out the README pretty thoroughly before posting here, I've successfully and flawlessly installed LaTeXTools on a Macbook, and two Linux machines already, so for me at least the problem seems to be isolated to Windows 10.

Any other advice, or potential solutions?

**Comment by Limro** [comment]
Can confirm - I believe the problem is in either MikTex (unlikely) or the use of MikTex.

I have the problem every time I apply a new ``\usepackage{...}`` which my computer have not seen before.

**Comment by msiniscalchi** [comment]
Oh... I see. Could it be that the issue is with on-the-fly installation of
packages? Honestly this is working for me right now (I'm on Win10 / MikTeX
with on-the-fly installation). But, you never know...

On Wed, Nov 25, 2015 at 10:52 AM, Rasmus Bækgaard <notifications@github.com>
wrote:

> Can confirm - I believe the problem is in either MikTex (unlikely) or the
> use of MikTex.
>
> I have the problem every time I apply a new \usepackage{...} which my
> computer have not seen before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/567#issuecomment-159669477>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by kirbpowell** [comment]
It could be - that's interesting though as that's my setup as well (Win10/MikTeX). 

Not quite sure where to go from here, I could post a screenshot of the error if that would help.

**Comment by Limro** [comment]
It could be (too) - I'm running W10 Pro N, Miktex 2.9 x64 with on-the-fly. But I haven't tried the x86 version.

**Comment by r-stein** [comment]
I would recommend open a cmd in the folder and execute this command and check whether it generates errors: (substitue tex_root by the name of your root file)
``` sh
texify -b -p --engine=pdftex --tex-option="--synctex=1" tex_root.tex
```
This is the default windows command. You can check the executed command in the console `View > Show Console`.

If its a package install problem, you can open the program `Settings (Admin)` for the MiKTeX Options and in the `General` tab change the the settings for *Install missing packages on-the-fly* to `Yes`.

**Comment by kirbpowell** [comment]
Alright, it looks like the problem may in fact be with pdflatex. I get the same 'non-error' when running the above command. It even tells me to check the log file for errors, but there aren't any errors in the log file. As far as the logs, and the resultant pdf are concerned, everything went fine. 

I did double check my MikTeX settings, and *install missing packages on-the-fly* is set to *yes*

**Comment by andrew-greve** [comment]
Hi kirbpowell, having the same issue as you, exactly.  Did you ever this this fixed?

**Comment by FlorianRappl** [comment]
I don't think its a Sublime / LaTeXTools plugin issue; it might be something with the latest MikTeX binary. I haven't seen `pdflatex` crashing in any of my other systems, but with a very recent distribution `pdflatex` sometimes crashes after downloading / installing new packages.

**Comment by dillonma** [comment]
I'm running into the same issue W10 / MikTeX x64. Happens with both LaTeXTools and Latexing. I realize the issue may not be a LaTeXTools issue, but it is extremely annoying. I tried putting pdflatex in compatibility mode and it did not make a difference. Any other clues or setting that might make this work?

Like @kirbpowell, the PDFs generate just fine despite Windows thinking that pdflatex "has stopped working" and I can run pdflatex at the command prompt without issue.

MiKTeX-pdfTeX 2.9.5800 (1.40.16) (MiKTeX 2.9 64-bit)

**Comment by ig0774** [comment]
The best advice I've seen on the Internet (I haven't tested this myself) is to kill any MiKTeX proceeses (texify, pdflatex, etc.) and rebuild the filename database (Rebuild FNDB). The more drastic option is to reinstall MiKTeX (which has been reported to be successful).

Unfortunately, I have yet to see any reports of steps that reliably reproduce this problem (i.e. under most circumstances install on the fly seems to work as expected), so I can't see that a bug can be opened with MiKTeX. It sounds like it may be a file-locking issue (e.g. perhaps updating the fndb is blocked by pdflatex due or something).

In any case, the command @r-stein mentioned is the actual command LaTeXTools runs. If it works from the command line it should work from Sublime. If it appears to work from the command line and not ST, it may be a concurrency issue (i.e. texify—the command we run directly—returns control to LaTeXTools before the pdf or log file are actually generated). In that case, manually running the forward sync command after the pdf file exists (ctrl + l, j) should work.

If there's any output in either the Sublime console or the build output view when this circumstance happens, it may help determine what's going on.

**Comment by dillonma** [comment]
Thanks for your response @ig0774, **rebuilding the FNDB seemed to do the trick**.

There were no errors generated from the command @r-stein recommended, nor in ST, hence my confusion and lack of figuring out where to go in the first place.

Thanks again for this.
