### ISSUE TITLE
PDF preview dose not work

### ISSUE THREAD

**Issue by Ricardo-May** [SublimeText/LaTeXTools#573]
I have already set my ST3 and latextools, and actually the pdf preview sometimes worked well but I have met some trouble as well sometimes it dose not jump to PDF and preview the file, what's going on with my settings? Please help me.

**Comment by Code-Curious** [comment]
Same thing here, I am using ST3 on Windows and I have SumatraPDF in my Path. The output PDF does get refreshed but the it doesn't switch to SumatraPDF's window even though I configured the `keep_focus` setting to `false`

**Comment by ig0774** [comment]
I'm not sure if #578 really addressed this... Can you provide any more details on what's happening? In particular, anything printed on the build panel and on the Sublime console (⌘ + ` or Ctrl + `) could be useful in working out what is going on.

**Comment by Ricardo-May** [comment]
Now, this problem has not occurred anymore. I think it is already fixed for most scenarios

**Comment by ig0774** [comment]
Ok. I'm going to close this for now, but please either re-open it or create a new issue if this returns.
