### ISSUE TITLE
latex_gen_pkg_cache seems not to work

### ISSUE THREAD

**Issue by MartinThoma** [SublimeText/LaTeXTools#577]
When I type `\usepackage{` I always get the message:

> Cache files for installed packages, classes and bibliographystyles do not exists, would you like to generate it? After generating complete, please re-run this completion action!

How can I fix that? It seems to come from https://github.com/SublimeText/LaTeXTools/blob/master/latex_input_completions.py

**Comment by ig0774** [comment]
Three options:

1. Turn off the autocomplete feature by adding a setting `fill_auto_trigger` and setting it to `false` in your `LaTeXTools.sublime-settings` file (Preferences -> LaTeXTools -> Settings - User).

1. From the command palette, select `LaTeXTools: Build cache for LaTeX packages`.

1. Click `Ok` on the message when it shows up. This will run the same command as above.

Note that the caching-building command can take a minute or two to run and should display a message to the status bar when done.

**Comment by MartinThoma** [comment]
I tried 2 and 3. It didn't work. How can I investigate why it doesn't work?

**Comment by ig0774** [comment]
Do any errors show up in the console?

**Comment by ig0774** [comment]
Basically, what the command does is to run: `kpsewhich --show-path=tex` and `kpsewhich --show-path=bst` and then walk through the returned directories find files matching specific extensions (`sty`, `cls` and `bst`).

**Comment by MartinThoma** [comment]
Yes, there is:

```bash
Exception in thread Thread-12:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/home/moose/.config/sublime-text-3/Packages/LaTeXTools/latex_installed_packages.py", line 113, in _generate_package_cache
    _get_tex_searchpath('tex'),
  File "/home/moose/.config/sublime-text-3/Packages/LaTeXTools/latex_installed_packages.py", line 44, in _get_tex_searchpath
    texpath = get_texpath() or os.environ['PATH']
  File "/home/moose/.config/sublime-text-3/Packages/LaTeXTools/latex_installed_packages.py", line 30, in get_texpath
    texpath = platform_settings['texpath']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by r-stein** [comment]
I would assume you have not configured your settings.
You might try
1. Open the command palette `ctrl+shift+p`
2. write `LaTeXTools: Reconfigure and migrate settings`
3. Try to build the cache again `LaTeXTools: Build cache for LaTeX packages`

But LaTeXTools should not be able to build the pdf either.

**Comment by MartinThoma** [comment]
Thank you! Now the `\usepackage{` autocompletion works :-)
(And it's sooo nice :-) )

**Comment by MartinThoma** [comment]
Isn't it possible to execute those two commands automatically? Or at least give a hint in the error message that this might solve the problem?

**Comment by r-stein** [comment]
The second command *is* executed automatically when pressing `{` the first time.
The first command can possible overwrite the existing settings, hence it should not always be executed.
However in my opinion there should be a default settings file, which will be used by ST if no user defined settings file exists or the command could be executed automatically after the installation if necessary/possible. You need this settings file to enable several features (build, cite-completion, ...).
Nevertheless I agree there should be a better error handling/message, as in the build dialog.
