### ISSUE TITLE
Latest update broke Okular work around

### ISSUE THREAD

**Issue by AshTex** [SublimeText/LaTeXTools#582]
Using Linux Mint with a HiDPI screen. Evince does a shocking job of rendering a PDF so I was using Okular with the work around outlined here: https://github.com/lklein/LaTeXTools/commit/b5a4e6c113cd08166572f8c81209424304a9d110

However with the recent update this fix doesn't work anymore? Even with jumpToPDF.py and ViewPDF.py changed it still opens it in Evince!?

Has a superseding script been added elsewhere?

**Comment by AshTex** [comment]
Have no idea but it just started working.

I really don't know why. Ah well. Happy days.

**Comment by AshTex** [comment]
Nope this is still broken. Not sure why it temporarily started working. I've not changed any of the files.

**Comment by ig0774** [comment]
Similarly, to make `view_pdf` work, you should just replace lines 52-58 of viewPDF.py with 

```python
viewercmd = ["okular", "--unique"]
```

And you should note, as @r-stein alluded to, that applying a "work around" like this is fragile: it may need to be redone any time you update LaTeXTools and when that happens, *where* the changes need to be applied shifts.

**Comment by AshTex** [comment]
Hi - thanks for the replies.

I had made (and remade) the changes listed above but it still doesn't work. I think I may have broken something else while I was hacking about last week. By removing all references to evince it doesn't open that anymore so if I simply open the document in Okular manually then it all proceeds to work fine. At some point I'll start from a fresh version but for now it's working well enough and I'm under a deadline! (What's new :P)

**Comment by r-stein** [comment]
Whats new:
- https://raw.githubusercontent.com/SublimeText/LaTeXTools/master/messages/21.txt
- https://raw.githubusercontent.com/SublimeText/LaTeXTools/master/messages/22.txt

If you regularly need to change stuff in the package, I would recommend to use git and pull automatically. It will save labor and no update will undo your changes in a critical moment.

**Comment by AshTex** [comment]
Thanks for the tip. I'll definitely look into that :)

**Comment by ig0774** [comment]
@AshTex: I've included an okular viewer in the latest release. See the README / settings file for how to use it. Much simpler than this hack.
