### ISSUE TITLE
Again after an update: "You must invoke LaTeX with the -shell-escape flag." 

### ISSUE THREAD

**Issue by andradx** [SublimeText/LaTeXTools#583]
I had solved this in the past, but it reverts to the original with package control updates it seems.

I frequently use minted on my documents and so -shell-escape must be passed on to the latexmk command. I had reworked on the traditional builder such that it read:

```
DEFAULT_COMMAND_LATEXMK = ["latexmk", "-cd",
				"-e", "$pdflatex = '%E -shell-escape -interaction=nonstopmode -synctex=1 %S %O'",
				"-f", "-pdf"]
```
on the traditionalBuilder.py

and also on the LaTeXTools.sublime-settings:

```
		"linux" : {
			"command" :  ["latexmk", "-cd", "-e", "$pdflatex = '%E -shell-escape -interaction=nonstopmode -synctex=1 %S %O'", "-f", "-pdf"]
}
```
which I guess is kind of redundant. However, disabling and re-enabling, and then restarting sublime doesn't make it run the latexmk with the -shell-escape flag.

* How can I solve this right now?

* How can this be solved permanently? 

    * I guess that it's not a good default option to allow for shell escaping from latexmk, but if the package minted is loaded, you have no choice but to allow shell escaping to generate the data associated with said package. So, it would be a good thing to have a parser for certain packages and depending on that latexmk w/ or w/o shell-escaping is called. (My humble two cents, I don't know how difficult it is to implement this.)

**Comment by ig0774** [comment]
Have you tried trashing the aux files and rebuilding (ctrl + l, backspace)? Latexmk won't see the changed command as requiring recompilation, which will look like nothing's changed.

This is precisely the situation that #576 is intended to address on a more permanent basis, by providing several ways of supplying options to latexmk/ texify.

**Comment by andradx** [comment]
I guess I must upgrade my search skills. Solution #576 is just about perfect, thanks.

**Comment by msiniscalchi** [comment]
Closing.
