### ISSUE TITLE
jumpto_tex_file is unresponsive

### ISSUE THREAD

**Issue by sethblumberg** [SublimeText/LaTeXTools#586]
The new feature (mapped to C-l,C-o) to open a tex file specified with an \include or \input line doesn't work.

When such a line is selected and the keybinding pressed, there is no response at all.  And when I added the following line to LaTex.sublime-comands, the command doesn't appear on the Command Palette:
>    { "caption": "LaTeXTools: Jump to TeX file", "command": "jumpto_tex_file"}

This makes me think Sublime doesn't realize the command jumpto_tex_file is supposed to be a command.

My setup: Sublime 2.0.2, newest (11-14-15) LaTeXTools, OSX 10.9.5 Mavericks, TexLive-2014

**Comment by ig0774** [comment]
It sounds like LaTeXTools either isn't properly installed or you don't, in fact have the latest version. 

Some things to check:
1) Do you, in fact, have a file named `jumpto_tex_file.py` in your local LaTeXTools package?
2) Do any errors occur related to loading that module in your console (Cmd + `)?

If you don't have the file, please try reinstalling LaTeXTools. If there's an error in the console, please copy and paste it into this issue so it can be resolved.

**Comment by sethblumberg** [comment]
You were right.  Here's the error from the console:

```
Reloading plugin /Users/seth/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/jumpto_tex_file.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./jumpto_tex_file.py", line 9, in <module>
    from .getTeXRoot import get_tex_root
ValueError: Attempted relative import in non-package
```

**Comment by ig0774** [comment]
Ah... Yes. Lines 8-11 of `jumpto_tex_file.py` are:

```python
try:
    from .getTeXRoot import get_tex_root
except ImportError:
    from getTeXRoot import get_tex_root
```

These need to be changed to this:

```python
try:
    from getTeXRoot import get_tex_root
except ImportError:
    from .getTeXRoot import get_tex_root
```

You can make this change to your local copy and I'll submit a pull request that will hopefully get merged soon.

**Comment by sethblumberg** [comment]
Your correction made the console error at launch go away.  And it also made the jump to tex file appear in the command palete (because of the extra line I added to `< LaTex.sublime-comands>`).

But now when I press C-l,C-o (on a line with \input), I get this no response, and this console error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 356, in run_
  File "./jumpto_tex_file.py", line 69, in run
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

```

**Comment by r-stein** [comment]
Sorry I underestimated the difference between ST2 and ST3 and didn't install ST2 to test ist. Now I have ST2 and will fix it as soon as possible.
