### ISSUE TITLE
Update 11-22 Broke Building

### ISSUE THREAD

**Issue by blahblah57** [SublimeText/LaTeXTools#589]
Hello,

On both my laptop and desktop LatexTools updated today and now I can no longer build my files. I tried running the migrate and reconfigure settings option and  uninstalling and reinstalling the plugin, but I can not get it to build anymore.

My console shows I am continuing to get the following error:
```
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "C:\USB\PortableApps\Sublime Text 3\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "C:\USB\PortableApps\Sublime Text 3\Data\Packages\LaTeXTools\makePDF.py", line 337, in run
    builder_module = __import__(builder_name + 'Builder')
  File "C:\USB\PortableApps\Sublime Text 3\Data\Packages\LaTeXTools\builders\traditionalBuilder.py", line 133
    cmd[i] = c.replace("%E", engine)
```

**Comment by r-stein** [comment]
in the file `builders/traditionalBuilder.py` line `133` you need to change the indendation from spaces to tabs.

**Comment by Gabriel-p** [comment]
Will this fix be released soon or should I manually fix it as shown above?

**Comment by jayzrnr** [comment]
This did the trick!

**Comment by louwers** [comment]
Didn't work for me. Somehow, LaTeXTools tries to run
```
Running 'pdf -shell-escape -interaction=nonstopmode -synctex=1 "filename.tex"  -recorder '
``
