### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by Limro** [SublimeText/LaTeXTools#591]
To compare to #589 , I don't see any console output.

I can clean my folder, but when I rebuild, ``Ctrl + B`` *nothing* happens!
There are nothing in the output console, and no files are being generated.

I take all suggestions to get this fixed. 
I don't want to write my master thesis in TexStudio or TexMaker!

**Comment by KevinGUOgit** [comment]
I meet the same sequence as you. I don't know how to fix it.
About he PDF setting path is not useful.

**Comment by r-stein** [comment]
The occur is visible in `View > Show Console` not in the ouput (the same bug as in https://github.com/SublimeText/LaTeXTools/issues/589)

To quick fix it open `Preferences > Browse Packages` then open the `LaTeXTools` folder then in the file `builders/traditionalBuilder.py` line 133 you need to change the indendation from spaces to tabs.

**Comment by Limro** [comment]
Dat work-around, @r-stein ! Much love. 

I hope your #590 gets through soon :)

**Comment by KevinGUOgit** [comment]
Thank you very much. It works. Thank goodness!!!

**Comment by neok-m4700** [comment]
makePDF.py also needs to be fixed

**Comment by Limro** [comment]
@neok-m4700, I get no errors, but I see the spaces from 35-39, 255, 365-370, and 430-434.
