### ISSUE TITLE
Complete from CWL does not call fill helper

### ISSUE THREAD

**Issue by KamphuisAlex** [SublimeText/LaTeXTools#593]
Typing  \include{ calls the fill helper that provides you with some suggestions that you can include.

When inserting a command such as \include{} via the cwl completions, eg. type \inclu and then press tab to complete to \include{} (where it puts the cursor in between the brackets for you to name a file to include), the fill helper is not called.

**Comment by msiniscalchi** [comment]
I don't think that can be fixed easily. LaTeX-cwl is a separate plugin, and
so doesn't know about the fill helper functionality. However, you can still
invoke the fill helper via the usual keybinding- C-l,C-f (delete the
placeholder "file" first).

If this is satisfactory, please close.

On Mon, Nov 23, 2015 at 5:56 AM, KamphuisAlex <notifications@github.com>
wrote:

> Typing \include{ calls the fill helper that provides you with some
> suggestions that you can include.
>
> When inserting a command such as \include{} via the cwl completions, eg.
> type \inclu and then press tab to complete to \include{} (where it puts the
> cursor in between the brackets for you to name a file to include), the fill
> helper is not called.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/593>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by KamphuisAlex** [comment]
Considering this is difficult to implement and the shortkey offers a workaround I would suggest not spending time on this. Thanks for the help!

**Comment by r-stein** [comment]
I just wanted to add, that the fill helper also inserts entries to the autocompletion. Hence if you use the cwl-autocompletion to insert `\include{}` and then write a part of your filename. The file will show up in the autocompletion menu.

To establish your intended behavior one would have to hook into the autocompletion `commit_completion`-command, because cwl only creates a completion list. I don't think sublime offers an API for that. Therefore one would have to rebind the tab-key to a new writen command, which encapsulates the completion and may trigger the fill-help.

**Comment by KamphuisAlex** [comment]
Thanks for you swift reply. Although what you are saying essentially works for me bear in mind that inserting a completion like \include{} using for instance the tab key will close the auto complete window. Merely typing a filename will not open it again. Typing part of a filename and then using Ctrl+Space (or whatever other keymapping you use) or Ctrl-l + Ctlr-f will open either the autocomplete window or the fill helper.

Thanks again for the explanation.

**Comment by r-stein** [comment]
Just in case you don't know:
You can setup Sublime Text to always popup the autocomplete panel when typing. Just add
``` javascript
// Controls what scopes auto complete will be triggered in
"auto_complete_selector": "source, text",
```
to your user settings file.

**Comment by KamphuisAlex** [comment]
Thank you, i Just do not want it to trigger for every single word, only for commands.

Alex Kamphuis
±316 1020 1776


-------- Oorspronkelijk bericht --------
Onderwerp: Re: [LaTeXTools] Complete from CWL does not call fill helper (#593)
Van: Richard Stein <notifications@github.com>
Aan: SublimeText/LaTeXTools <LaTeXTools@noreply.github.com>
Cc: KamphuisAlex <kamphuis.alex@gmail.com>
