### ISSUE TITLE
Select Line Hotkey Changed Globally

### ISSUE THREAD

**Issue by NJBS** [SublimeText/LaTeXTools#595]
The latest update has broken the default Sublime Text select line hotkey. LaTeXTools has globally overwritten the default Ctrl+l hotkey used to select a line with its double Ctrl+l style line selection normally used in Latex files. This behavior occurs across all opened files, regardless of what syntax style is being used to view them.

**Comment by r-stein** [comment]
Fixed in https://github.com/SublimeText/LaTeXTools/pull/596

**Comment by msiniscalchi** [comment]
Patch merged.
