### ISSUE TITLE
Update broke custom completions

### ISSUE THREAD

**Issue by daftscience** [SublimeText/LaTeXTools#598]
The new update seems to be interfering with my custom completion files. I'm not sure I'm doing something wrong, or what exactly is causing the issue.

Here is an example completions file.

```
{
        "scope": "text.tex.latex",
        "completions":
        [
                { "trigger": "pi",  "contents":  "\\prettyimage{width=$1\\textwidth}{graphics/$2}$0"},
        ]
}
```

Right now uninstalling LatexTools will make my configuration work. Re-installing it breaks it again.

Thanks in advance for the help

**Comment by r-stein** [comment]
Do you use cwl-autocompletion?

**Comment by msiniscalchi** [comment]
I haven't seen any follow-up here. Closing, but feel free to reopen if necessary.
