### ISSUE TITLE
Cannot auto-complete citations using a bib file in the texmf tree

### ISSUE THREAD

**Issue by tpoisot** [SublimeText/LaTeXTools#60]
Hi,

I have a file called library.bib in my local texf tree, so that I can use is in all my documents. When I try to use `cite_` in LaTeX tools, it fails because it looks for the file in the local directory, which obviously fails.

Having bib files in the texmf tree is standard practice in LaTeX, any way the plugin can conform to it?

**Comment by ig0774** [comment]
This was fixed quite a while ago now.
