### ISSUE TITLE
can we have a release?

### ISSUE THREAD

**Issue by floswald** [SublimeText/LaTeXTools#600]
It would be great if you could tag your commits once in a while. This way, whenever the current build breaks something, we can just go back to the previous release.

thanks for the good work!

**Comment by msiniscalchi** [comment]
I've added tags, actually going back a couple years. Not perfect, but at
least it can serve as a fallback option. If this is what you had in mind,
please close.

On Tue, Nov 24, 2015 at 2:33 AM, Florian Oswald <notifications@github.com>
wrote:

> It would be great if you could tag your releases once in a while. This
> way, whenever the current build breaks something, we can just go back to
> the previous release.
>
> thanks for the good work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/600>.
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by msiniscalchi** [comment]
I'll close.
