### ISSUE TITLE
Bug: Stoping compilation process does not terminate the pdflatex process

### ISSUE THREAD

**Issue by dlavoieb** [SublimeText/LaTeXTools#603]
When manually stopping the compilation process which hangs due to a bad file, the `pdflatex` process keeps running in the background and never terminates.

This file is an example of file that does not compile and hangs.
[example.tex](https://files.zenhub.io/5657b1d57177c2365afba1c1)

To reproduce simply start the compilation with LatexTools and stop (press CMD+B during compile).

In terminal: `$ ps -ef | grep pdf` still show the process running and the ressource usage is quite significant (100% cpu).

**Comment by ig0774** [comment]
Thanks for the report. I've make some changes to makePDF.py which should fix the issue. You can grab the modified file [here](https://raw.githubusercontent.com/ig0774/LaTeXTools/kill_child_processes/makePDF.py).

**Comment by msiniscalchi** [comment]
Patch merged.
