### ISSUE TITLE
No warnings about overfull/underfull boxes

### ISSUE THREAD

**Issue by atmo** [SublimeText/LaTeXTools#61]
I built my LaTeX project, and didn't see any warnings about overfull hboxes, which actually were in log. Is this functionality supported? The thing is that my project consist of several files, but adding extra comment at a first line as you recommended, anyway, didn't help. However, everyrhing else works as expected.

**Comment by SGL483** [comment]
It seems that overfull and underfull hboxes are not implemented yet. Please see this thread on Stackexchange. There you'll find a fork of LatexTools which has this feature.

https://tex.stackexchange.com/questions/142040/sublimetext-latextools-overfull-hbox-warnings

**Comment by ig0774** [comment]
Warnings of hboxes and vboxes have been implemented in v3.7.0.
