### ISSUE TITLE
Not rebuilding unless I delete temp files

### ISSUE THREAD

**Issue by jeremyvoltz** [SublimeText/LaTeXTools#612]
When I build (C-b) in ST, It outputs the usual build notes (very quickly), but the pdf and temp files are unchanged.  It will only truly rebuild if I delete the temp files (either the .aux or the .fdb_latexmk).  Deleting the pdf won't even trigger a fresh build.

This started in the last week.

**Comment by ig0774** [comment]
The build result appearing very quickly is usually a sign that `latexmk` exited unexpectedly but the (old) log file was still there.

The problem you are describing sounds like it may be an issue with `latexmk` and something about your document. Could you try running: `latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 [YOUR_DOC]` from the terminal / command line in the folder that contains your TeX document and report the output?

To troubleshoot, it would help to have the output from the Sublime console and a MWE of a document that causes the issue. Right now there isn't much to go on

**Comment by jeremyvoltz** [comment]
**Here's the output in the terminal:**
Latexmk: This is Latexmk, John Collins, 30 March 2012, version: 4.31.
**** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
Latexmk: Changing directory to './'
Latexmk: applying rule 'bibtex IntermediateCLT'...
Rule 'bibtex IntermediateCLT': File changes, etc:
   Non-existent destination files:
      'IntermediateCLT.bbl'
Latexmk: I WON'T RUN 'bibtex IntermediateCLT' because I don't find the following files:
  'thesis.bib'
Latexmk: Errors, so I did not complete making targets
Latexmk: Undoing directory change
Latexmk: Use the -f option to force complete processing.


**Here's the output of the build in sublime text:**
Compiling /Users/jeremyvoltz/Documents/thesis/IntermediateCLT.tex]

TraditionalBuilder: Engine: pdflatex -> pdf. Invoking latexmk... done.

No errors. Warnings:
(a bunch of warnings...)

[Done!]


**And here's the output of sublime text console:**
<module 'traditionalBuilder' from '/Users/jeremyvoltz/Library/Application Support/Sublime Text 2/Packages/LaTeXTools/builders/traditionalBuilder.py'>
<class 'traditionalBuilder.TraditionalBuilder'>
Welcome to thread Thread-62
2
['latexmk', '-cd', '-e', '-f', '-pdf', '-latexoption="-interaction=nonstopmode"', '-latexoption="-synctex=1"', u'IntermediateCLT.tex']
Finished normally
12
False True True
!TEX root =  u'/Users/jeremyvoltz/Documents/thesis/IntermediateCLT.tex'
Jump to:  489 0

**Comment by r-stein** [comment]
I would assume you have written in your document `\bibliography{thesis}`, but the bibliography file is missing.
Nevertheless latexmk should build a new pdf. Can you try to run the following command in a shell/cmd in the tex root file directory:
``` sh
latexmk -cd -e -f -pdf -latexoption="-interaction=nonstopmode" -latexoption="-synctex=1" IntermediateCLT.tex
```

**Comment by jeremyvoltz** [comment]
jeremyvoltz (master *) thesis $ latexmk -cd -e -f -pdf -latexoption="-interaction=nonstopmode" -latexoption="-synctex=1" IntermediateCLT.tex
Latexmk: This is Latexmk, John Collins, 30 March 2012, version: 4.31.
**** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
Latexmk: Changing directory to './'
Latexmk: applying rule 'bibtex IntermediateCLT'...
Rule 'bibtex IntermediateCLT': File changes, etc:
   Non-existent destination files:
      'IntermediateCLT.bbl'
Latexmk: I WON'T RUN 'bibtex IntermediateCLT' because I don't find the following files:
  'thesis.bib'
Latexmk: Errors, so I did not complete making targets
Latexmk: Undoing directory change
Latexmk: Use the -f option to force complete processing.

**Comment by ig0774** [comment]
Probably the simplest thing to do is to create an empty file called `thesis.bib` in the same directory as your IntermediateCLT.tex file.

**Comment by jeremyvoltz** [comment]
That's the thing, my bibliography call is hard coded:
\bibliography{/Users/jeremyvoltz/Dropbox/EclipseWorkspace/Bibtex/ThesisBibManual,/Users/jeremyvoltz/Dropbox/EclipseWorkspace/Bibtex/thesis} 

The file thesis.bib has never changed location, and i've been using this identical bibliography line in two other tex documents for a year without incident.  It ought to be finding the thesis.bib file.

**Comment by jeremyvoltz** [comment]
And now interestingly, after it built successfully and created 'IntermediateCLT.bbl', I removed thesis.bib from the working directory, keeping it only in the linked location, and building still works.  It's almost like it just needed to build that '.bbl' file one time, and then it was ok with the linked location.  Strange.

**Comment by ig0774** [comment]
Ah! I wasn't quite sure if you had a bib file at all. Two suggestions that might be more productive (but you only need to do one or the other): 1. You could try using the LaTeXTools `simple` builder or 2. You could try creating a `.latexmkrc` in the same folder as IntermediateCLT.tex with a line `$bibtex_use = 2`, which tells latexmk to always try to to rebuild the bib file.

**Comment by ig0774** [comment]
I'm closing this as this seems to be a bug in latexmk rather than LaTeXTools. In addition to my suggestions above, you could try updating latexmk and see if that fixes the issue for you.
