### ISSUE TITLE
[Bug]reference for section

### ISSUE THREAD

**Issue by Ricardo-May** [SublimeText/LaTeXTools#614]
Hey, Guys!
I am glad to inform you that there is a bug occurring for the section reference. When I use the reference for section, I find that the words following after the reference are changed into **bold** format as well, and a brace is needed to prevent it.
Of course, it does not affect my using LaTeXTools, but I beg for the xelatex for simple builder for my non-English writing, actually I always modify the simplebuilder.py in order to invoke xelatex instead of pdflatex. Maybe something can be done for simple builder using `%!TEX program = xelatex`.

Let me give a simple example for this below.
```LaTeX
\documentclass{article}
\begin{document}
When I write this article, I may need to refer to some sections, like \ref{sec:test}, but the words just after this reference become bold. 

However, if I include this reference \ref{sec:test} in a pair of braces, this problem would not occur, like {\ref{sec:test}} blabla...
\section{test}\label{sec:test}
\end{document}
```
I am not sure if I have explanded this problem clearly, actually I mean the words in this example like
> but the words just after this reference become bold. 

would become bold like

**but the words just after this reference become bold**.

if I include the reference in a pair of braces, like `{\ref{sec:test}}` this reference won't affect the words following the reference into bold format.

Of course, I mean this occur after compiled.

*I am sorry if I didn't introduce this issue exactly due to my poor English.*

Thanks for LaTeXTools, and hope it become better in the future!

**Comment by ig0774** [comment]
I'm a little confused what you're talking about. Can you provide a screenshot or a document that exhibits the behaviour you're seeing?

The nearest thing that occurs to me is this:

<img width="258" alt="highlighting" src="https://cloud.githubusercontent.com/assets/212893/11591673/80b40fb2-9a91-11e5-8af4-f047dd4f6bcc.png">

Which isn't exactly an error, its more of a way of highlighting an issue (i.e., that the `\ref{}` command is not closed). But I suspect that this isn't what you mean?

**Comment by Ricardo-May** [comment]
Let me give a simple example for this below.
```LaTeX
\documentclass{article}
\begin{document}
When I write this article, I may need to refer to some sections, like \ref{sec:test}, but the words just after this reference become bold. 

However, if I include this reference \ref{sec:test} in a pair of braces, this problem would not occur, like {\ref{sec:test}} blabla...
\section{test}\label{sec:test}
\end{document}
```
I am not sure if I have explanded this problem clearly, actually I mean the words like 
> but the words just after this reference become bold. 

this words would become bold like

**but the words just after this reference become bold**.

if I include the reference in a pair of braces, like `{\ref{sec:test}}` this reference won't affect the words following the reference into bold format.

*I am sorry if I didn't introduce this issue exactly due to my poor English.*

**Comment by msiniscalchi** [comment]
That's a problem with syntax highlighting, I believe. Try a different color scheme maybe. Anyway, it should not be related to LaTeXTools, as we don't alter syntax highlight.

**Comment by Ricardo-May** [comment]
Sorry, I mean after I compiling the tex file, the PDF file shows this phenomenon rather than the source codes.

**Comment by Ricardo-May** [comment]
OK, I think you are right, it should not be related to LaTeXTools, maybe it is just a bug for something else...

Sorry for wrong bug submit...
