### ISSUE TITLE
Multi-file root definition doesn't work is there's a space between % and !

### ISSUE THREAD

**Issue by alrekr** [SublimeText/LaTeXTools#619]
If the first line of a document is `% !TeX root = <master>.tex` multi-file support is broken, meaning you can't build the document using `C-b` unless you're in the root file. Removing the space so the line reads `%!TeX root = <master>.tex` makes multi-file support work again.

This appear to be unnecessarily strict and incompatible with the magic comments in e.g. TexStudio. 

Addendum: As @r-stein correctly points out below, the problem isn't the whitespace, but rather that TEX is assumed uppercase. I erroneously identified the wrong error. Whitespace introduces no error.

**Comment by r-stein** [comment]
The mistake might, be that `TeX` is assumed to be upper case, i.e. `% !TEX root = <master>.tex`. This might also be to strict, but the number of whitespaces is ignored to determine the tex root.

**Comment by ig0774** [comment]
Hmmmm... I just realised that my latest commit accidentally fixes the issue @r-stein pointed out by ensuring that the `IGNORE_CASE` flag is set.

**Comment by alrekr** [comment]
The issue has already been resolved. Closing the issue.
