### ISSUE TITLE
After successful building, hiding of process output

### ISSUE THREAD

**Issue by juanfal** [SublimeText/LaTeXTools#620]
It would be great to have a clean .tex source after ⌘-B (^B) on your document, not needing to Escape to hide the leftovers at the bottom of your source.tex.

Is it there any way to have this by default?

**Comment by ig0774** [comment]
Are you talking about the panel with the build results? Because if so, thanks to @r-stein, we already have this feature! See the section on `hide_build_panel` In the README for the details.

**Comment by msiniscalchi** [comment]
@juanfal please close if this is what you meant.

**Comment by juanfal** [comment]
YES!  my apologies for not having found it, my fault, I tried, I promise.  Closing 😀

**Comment by r-stein** [comment]
In the hindsight it might be a good idea to change the default value to `no_warnings`. I used `never` to not change the existing behavior, but hiding the panel might a behavior the majority of users want.
