### ISSUE TITLE
Sorry, but texify did not succeed.

### ISSUE THREAD

**Issue by wojoeraf** [SublimeText/LaTeXTools#627]
Since updating my miktex packages I get for (even for very Simple files, see MWE) the error message:
```
Sorry, but texify did not succeed.
The log file hopefully contains the information to get MiKTeX going again:
C:/Users/Username/AppData/Local/MiKTeX/2.9/miktex/log/texify.log
You may want to visit the MiKTeX project page, if you need help.
```
The texify.log tells:
```
2015-12-14 19:03:34,635+0100 FATAL texify - MiKTeX encountered an internal error.
2015-12-14 19:03:34,635+0100 FATAL texify - Info: 
2015-12-14 19:03:34,635+0100 FATAL texify - Source: Programs\MiKTeX\texify\mcd.cpp
2015-12-14 19:03:34,635+0100 FATAL texify - Line: 1168
```

#### MWE
```latex
\documentclass{article}
\begin{document}
test file
\end{document}
```
When compiling with e.g. texworks, everything is fine.

**Comment by msiniscalchi** [comment]
This is not a LaTeXTools error message. Are you sure you aren't using another LaTeX plugin? Or perhaps you want to use LaTeXTools, but some other plugin is somehow hijacking the build command. In any case, please uninstall any other LaTeX plugin you might have and try again---what you see is most definitely *not* coming from LaTeXTools.

Closing.

**Comment by wojoeraf** [comment]
Just wana add:
I reinstalled miktex and the got the `Could not compile` message.
After reading the hint to use the `reconfigure LaTeXTools...` functionality I used it and now it works.

If this was somewhere hinted in one of the changelogs, so my fail. But if not, consider writing this hint in the changelogs, thanks.

**Comment by msiniscalchi** [comment]
As I said, the original message you posted here is *not* a LaTeXTools message. There are a couple other plugins for LaTeX, so maybe you installed those, too, and you were having issues with conflicts. That said, the README states clearly that you should run the Reconfigure laTeXTools command, or many things won't work.
