### ISSUE TITLE
"View PDF" doesn't find PDF viewer

### ISSUE THREAD

**Issue by Doggie52** [SublimeText/LaTeXTools#632]
The *View PDF* command doesn't find the PDF viewer and asks to find it on the PATH.
![image](https://cloud.githubusercontent.com/assets/4928988/12003771/a8e743de-aaf2-11e5-8753-e4b95ae2e1bc.png)

Building, jumping and other commands work, however, since I have correctly defined the path under `windows: sumatra` in the settings. My guess is that the path searched by *View PDF* is simply not fetched from the right place.

I'm on Windows 10 x64 running latest Sublime 3 x64 beta.

**Comment by r-stein** [comment]
Fixed in commit https://github.com/SublimeText/LaTeXTools/commit/b2dcbde8dc9c77e9a4836c9fc03cd7d411ea3845. However this commit is not yet in the package control (not in a tagged version).
Hence this will be fixed soon =)

**Comment by Doggie52** [comment]
Thank you for bringing this up! Did not see this.
