### ISSUE TITLE
hep me please ! Latex Tools not working ,I have tested many ways,problem is solved

### ISSUE THREAD

**Issue by licheng6095** [SublimeText/LaTeXTools#634]
1. system: win 8.1 64
2. latex: Mixtec    c:\CTEX\MiKTeX\miktex\bin\
3. sublime 3
4. sumatrapdf 2.0
default installation path

question:   press Ctrl+b 
                             [Compiling C:\Users\LI\Desktop\test.tex]
It seems to have been so, no movement
I have tried many solutions have failed,Your answer may be very useful for me, thank you
![qq 20151231151429](https://cloud.githubusercontent.com/assets/16497907/12062100/356bfdf8-afd1-11e5-822f-70e4b13aeb52.png)

after I reinstall Mixtec

![qq 20151231162717](https://cloud.githubusercontent.com/assets/16497907/12062654/61d74e74-afdb-11e5-9de6-8163566d6220.png)

**Comment by r-stein** [comment]
You should add the sumatra path into your User-settings:
```js
// ...
		// Command to invoke Sumatra. If blank, "SumatraPDF.exe" is used (it has to be on your PATH)
		"sumatra": "C:\\Program Files (x86)\\SumatraPDF\\SumatraPDF.exe",
// ...
```
The other thing seems to be a miktex problem.
You could try to restart your computer and try to compile it manually using the `texify` command in a cmd. (`shift+rightclick` in the folder, then "Open command window here." and then write `texify test.tex` to execute the compilation)

**Comment by licheng6095** [comment]
@r-stein  happy new year ,thank you for help, reinstall Mixtec and smartra the problem is solved,
