### ISSUE TITLE
Biber and Sublime text

### ISSUE THREAD

**Issue by grosdode** [SublimeText/LaTeXTools#637]
I use Sublime since two years and also biber but after an update of Latextools biber do not run. I get the two warnings below (and many more because of the undefined cites):
```
LaTeX Warning: There were undefined references.

Package biblatex Warning: Please (re)run Biber on the file:(biblatex)                Signalerzeugung(biblatex)                and rerun LaTeX afterwards.
```
The console show me this:
```
<module 'simpleBuilder' from 'C:\\Users\\Dominik\\AppData\\Roaming\\Sublime Text 3\\Packages\\LaTeXTools\\builders\\simpleBuilder.py'>
<class 'simpleBuilder.SimpleBuilder'>
2
Welcome to thread Thread-9
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'Signalerzeugung']
Finished normally
0
False True True
!TEX root = 'D:\\Dropbox\\Masterarbeit\\dokumentation\\signalerzeugung\\Signalerzeugung.tex'
Jump to:  191 24
Windows, Calling Sumatra
```
I reinstalled the latextools and Miktex but the Problem still exist :-(

**Comment by r-stein** [comment]
The simple builder uses `pdflatex` + `bibtex`. Hence you could try to switch to the traditional builder in the options, which uses `texify`. You can change the bibtex command of texify by changing the environment variable `BIBTEX` to biber ([texify doc](http://docs.miktex.org/manual/texify.html)). *biber must be in the PATH*.

You could also invoke biber manually, by opening a cmd in the directory (`shift+right-click` on the folder background -> "Open command window here." / "Eingabeaufforderung hier öffnen") and run `biber Signalerzeugung`. Afterwards the bbl and blg files exists and further compilations should succeed. However this does not solve the problem.

**Comment by grosdode** [comment]
thanks for the fast answer.
The second part with the command line works fine but it would be nice if this could be automatically done. Hence I changed the builder but don't understand "You can change the bibtex command of texify by changing the environment variable BIBTEX to biber (texify doc). biber must be in the PATH."
An answer in german would be nice if you are from germany too. :-)

**Comment by r-stein** [comment]
Since it is an international forum I would dislike to write german only =).

You can easily change the environment variable by opening the start menu and then type and open "Change environment varibles" / "Umgebungsvariablen für dieses Konto bearbeiten". Then click on "New..." / "Neu..." and add variable with the name `BIBTEX` and the value either `biber` or the full path to the biber executable. Afterwards restart Sublime Text.

**Comment by ig0774** [comment]
Another option would be to use the traditional builder, install MiKTeX's version of latexmk and change your "distro" setting in the LaTeXTools setting to "texlive". Unlike texify, latexmk actually uses the build output to determine it should use biber.

**Comment by grosdode** [comment]
I fixed it :-)
I'd used the simpleBuilder from [here](https://github.com/raimund-schluessler/LaTeXTools/commit/300d56737a444d8ef477ce526f7c489443fc0839?diff=unified) and added the System Variable

Thanks to you guys

**Comment by r-stein** [comment]
@grosdode keep in mind, that LaTeXTools updates might overwrite the SimpleBuilder. In addition the environment variable has no effect on the simple builder, because it does not use the `texify` command

**Comment by grosdode** [comment]
@r-stein Yes I know, I tried to put a copy to the User folder and use this but I don't know how to use this copy instead of the original.
I tried to change the builder path
```
"builder_path": "User/LaTeXToolsUser/builders",
```
but what have I wirte instead of
```
"builder": "simple",
```
are there other files I have to modify?

I needed a environment variable for the simpeBuilder (biber, path to biber)

**Comment by r-stein** [comment]
I made a small adaption of your posted example to rename it from `SimpleBuilder` to `BiberBuilder`:
[biberBuilder.py.txt](https://github.com/SublimeText/LaTeXTools/files/79581/biberBuilder.py.txt)

I changed the extension to txt, because I cannot upload py files. Hence just rename it from `biberBuilder.py.txt` to `biberBuilder.py` and put it into the directory `Packages/User/LaTeXToolsUser/builders`. Afterwards use

``` js
"builder": "biber",
```

**Comment by grosdode** [comment]
Thanks but I still get the same error:
```
Cannot find builder biber.
Check your LaTeXTools Preferences
```
The console show the same:
```
error: Cannot find builder biber.
Check your LaTeXTools Preferences
```

**Comment by r-stein** [comment]
have you tried to restart ST?

**Comment by grosdode** [comment]
several times :-(

**Comment by r-stein** [comment]
If you open the console `View > Show Console` and paste
``` py
window.open_file(sublime.packages_path() + "/User/LaTeXToolsUser/builders/biberBuilder.py")
```
it should open the file, otherwise review your path. Do you use ST2 oder ST3?

**Comment by grosdode** [comment]
Yes it open the file
I use ST3 and the lates version of Latextools

**Comment by r-stein** [comment]
and your settings are:
```py
	"builder": "biber",
	"builder_path": "User/LaTeXToolsUser/builders",
```

**Comment by grosdode** [comment]
Now it works
I used Packages/User/LaTeXToolsUser/builders as you posted before

Thank you very much

**Comment by r-stein** [comment]
ok thats nice

**Comment by jaejunlee0538** [comment]
Mine is not working...

Any body who got this message?


```
SimpleBuilder:
pdflatex run 1;
biber run 1;


COULD NOT COMPILE!

Attempted command:biber test
Build engine: Simple Builder
```

**Comment by r-stein** [comment]
Can you paste the console output from `View > Show Console`?
Do you have biber installed and in your path?

**Comment by jaejunlee0538** [comment]
Sorry, now I cannot reproduce the error because my LaTeXTools seems totally broken...
It's not working with these message in console.

```
TraditionalBuilder: Engine: pdflatex -> pdftex. Invoking texify... done.

Output from compilation:


Sorry, but texify did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/Users/jaejunlee/AppData/Local/MiKTeX/2.9/miktex/log/texify.log

You may want to visit the MiKTeX project page, if you need help.
```

But this was the console output at that time.

```
SimpleBuilder:
pdflatex run 1;
biber run 1;


COULD NOT COMPILE!

Attempted command:biber test
Build engine: Simple Builder
```

**Comment by r-stein** [comment]
This is the output from the output panel, which automatically shows up. Not from the console, which prints the error itself.

The new problem is a Miktex problem and you should look into the log file for further informations. I would assume you will find the solution to this problem, if you google the error in the log file.

**Comment by grosdode** [comment]
Nach dem letzten Update hat sich nen bisschen was geändert hier der Code der wieder funktioniert falls jemand über google auf den Post stößt :-)


`
# ST2/ST3 compat
from __future__ import print_function
import sublime
if sublime.version() < '3000':
    # we are on ST2 and Python 2.X
	_ST3 = False
else:
	_ST3 = True

import os.path
import re
# This will work because makePDF.py puts the appropriate
# builders directory in sys.path
from pdfBuilder import PdfBuilder

DEBUG = False




#----------------------------------------------------------------
# BiberBuilder class
#
# Just add the biber bibtex engine to the SimpleBuilder



class BiberBuilder(PdfBuilder):

	def __init__(self, tex_root, output, engine, options,
				 tex_directives, builder_settings, platform_settings):
		# Sets the file name parts, plus internal stuff
		super(BiberBuilder, self).__init__(tex_root, output, engine, options,
			tex_directives, builder_settings, platform_settings)

		# Now do our own initialization: set our name, see if we want to display output
		self.name = "Biber Builder"
		self.display_log = builder_settings.get("display_log", False)

	def commands(self):
		# Print greeting
		self.display("\n\nBiberBuilder:\n")

		pdflatex = ["pdflatex", "-interaction=nonstopmode", "-synctex=1"]
		bibtex = ["bibtex"]
		biber = ["biber"]
		# Regex to look for missing citations
		# This works for plain latex; apparently natbib requires special handling
		# TODO: does it work with biblatex?
		citations_rx = re.compile(r"Warning: Citation `.+' on page \d+ undefined")
		citations_biber = re.compile(r"Please \(re\)run Biber")
		# We have commands in our PATH, and are in the same dir as the master file

		# This is for debugging purposes
		def display_results(n):
			if self.display_log:
				self.display("Command results, run %d:\n" % (n,) )
				self.display(self.out)
				self.display("\n")

		run = 1
		brun = 0
		yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
		display_results(run)

		# Check for citations
		# Use search, not match: match looks at the beginning of the string
		# We need to run pdflatex twice after bibtex
		if citations_rx.search(self.out):
			brun = brun + 1
			yield (bibtex + [self.base_name], "bibtex run %d;\n" % (brun,))
			display_results(1)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Check if biber wants to be rerun
		if citations_biber.search(self.out):
			brun = brun + 1
			yield (biber + [self.base_name], "biber run %d;\n" % (brun,))
			display_results(1)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Apparently natbib needs separate processing
		if "Package natbib Warning: There were undefined citations." in self.out:
			brun = brun + 1
			yield (bibtex + [self.base_name], "bibtex run %d;\n" % (brun,))
			display_results(2)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Check for changed labels
		# Do this at the end, so if there are also citations to resolve,
		# we may save one pdflatex run
		if "Rerun to get cross-references right." in self.out:
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d; " % (run, ))
			display_results(run)

		self.display("done.\n")









`

**Comment by grosdode** [comment]
Sorry I wrote the last Post in german.
Since the last update the code from above doesn't work. In the *.txt file is the working code  (but you have to save it as *.py)
[biberBuilder.txt](https://github.com/SublimeText/LaTeXTools/files/156323/biberBuilder.txt)

**Comment by ig0774** [comment]
Here's an updated version that should work.

```python
import os.path
import re

# This will work because makePDF.py puts the appropriate
# builders directory in sys.path
from pdfBuilder import PdfBuilder

#----------------------------------------------------------------
# BiberBuilder class
#
# Just add the biber bibtex engine to the SimpleBuilder

class BiberBuilder(PdfBuilder):

	def __init__(self, *args):
		# Sets the file name parts, plus internal stuff
		super(BiberBuilder, self).__init__(*args)

		# Now do our own initialization: set our name, see if we want to display output
		self.name = "Biber Builder"
		self.display_log = builder_settings.get("display_log", False)

	def commands(self):
		# Print greeting
		self.display("\n\nBiberBuilder:\n")

		pdflatex = ["pdflatex", "-interaction=nonstopmode", "-synctex=1"]
		bibtex = ["bibtex"]
		biber = ["biber"]
		# Regex to look for missing citations
		# This works for plain latex; apparently natbib requires special handling
		citations_rx = re.compile(r"Warning: Citation `.+' on page \d+ undefined")
		citations_biber = re.compile(r"Please \(re\)run Biber")
		# We have commands in our PATH, and are in the same dir as the master file

		# This is for debugging purposes
		def display_results(n):
			if self.display_log:
				self.display("Command results, run %d:\n" % (n,) )
				self.display(self.out)
				self.display("\n")

		run = 1
		brun = 0
		yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
		display_results(run)

		# Check for citations
		# Use search, not match: match looks at the beginning of the string
		# We need to run pdflatex twice after bibtex
		if citations_rx.search(self.out):
			brun = brun + 1
			yield (bibtex + [self.base_name], "bibtex run %d;\n" % (brun,))
			display_results(1)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Check if biber wants to be rerun
		if citations_biber.search(self.out):
			brun = brun + 1
			yield (biber + [self.base_name], "biber run %d;\n" % (brun,))
			display_results(1)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Apparently natbib needs separate processing
		if "Package natbib Warning: There were undefined citations." in self.out:
			brun = brun + 1
			yield (bibtex + [self.base_name], "bibtex run %d;\n" % (brun,))
			display_results(2)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d;\n" % (run, ))
			display_results(run)

		# Check for changed labels
		# Do this at the end, so if there are also citations to resolve,
		# we may save one pdflatex run
		if "Rerun to get cross-references right." in self.out:
			run = run + 1
			yield (pdflatex + [self.base_name], "pdflatex run %d; " % (run, ))
			display_results(run)

		self.display("done.\n")
```

**Comment by bjentsch** [comment]
Did anyone encounter this console message?

    <module 'biberBuilder' from 'C:\\Users\\Public\\Programme\\Sublime Text Build 3103\\Data\\Packages\\User\\LaTeXToolsUser\\builders\\biberBuilder.py'>
    <class 'biberBuilder.BiberBuilder'>
    Traceback (most recent call last):
      File "C:\Users\Public\Programme\Sublime Text Build 3103\sublime_plugin.py", line 551, in run_
          return self.run(**args)
      File "C:\Users\Public\Programme\Sublime Text Build 3103\Data\Packages\LaTeXTools\makePDF.py", line 474, in run
          platform_settings
    TypeError: __init__() takes 5 positional arguments but 8 were given

I tried your updated biberBuilder solutions, but sadly they won't work for me.

**Comment by ig0774** [comment]
@bjentsch: I amended the above. It should work now.

On biber support more generally (for now), see [the wiki](https://github.com/SublimeText/LaTeXTools/wiki/BIber-Support), which outlines the ways biber can be used in LaTeXTools.

**Comment by bjentsch** [comment]
Sorry, but the same error persists :-/

**Comment by ig0774** [comment]
You have to restart ST...

**Comment by bjentsch** [comment]
Great - thanks! :-)

**Comment by babesyoung** [comment]
I use MacTex + latextools, and I met this problem too. And I used this script, but it doesn't work. I don't know what hanppend? here is the console message.
Welcome to thread Thread-3
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'shortsample']
Finished normally
0
['biber', 'shortsample']
Finished normally
2
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'shortsample']
Finished normally
0
['pdflatex', '-interaction=nonstopmode', '-synctex=1', 'shortsample']
Finished normally
0
False True True
!TEX root =  '/Users/yyh-nuaa/Downloads/apa6/samples/shortsample.tex'
Jump to:  15 42
<class '_latextools_skim_viewer.SkimViewer'>
Package Control: No updated packages

**Comment by ig0774** [comment]
Looks like `biber` exit with an exit status of 2, indicating an error. Check the `blg` file.

**Comment by ig0774** [comment]
Also, that builder doesn't support xelatex. On MacTeX, I'd just use the `traditional` builder which supports binder natively.

**Comment by babesyoung** [comment]
sorry to trouble you, but can you compile the "shortsample.tex" in "apa6" successfully using mactex+latextool?

**Comment by ig0774** [comment]
Yes. Did you download the corresponding `.bib` file as well as the `.tex` file? Otherwise the citations won't show up, but it should work (i.e. compile a pdf).

**Comment by babesyoung** [comment]
thx for help anyway.

**Comment by timothoms** [comment]
This problem reappeared for me on MacTex/OSX since the most recent changes to LaTexTools in the last few days. Biber was working before a couple of days ago with the "traditional" build; now all citations are not defined when using the "traditional" or "basic" builds with biber. Switching to bibtex works with the same setup (but, of course, introduces problems with biblatex). Any advice?

**Comment by JFrisc** [comment]
hey all

i scrolled several times through this thread to get a solution but seems that i m a fool haha^
sublime shows the following after pressing crtl+B



TraditionalBuilder: Engine: pdflatex. Invoking texify... done.

Could not read log file test.log

Output from compilation:


Sorry, but pdflatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\jonat\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log

Sorry, but "MiKTeX Compiler Driver" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:



dont have a clue how i could fix it:( installed everything again and again but still it s not working
maybe someone of you could help, who knows
