### ISSUE TITLE
Close completion panel if "\\" is inserted

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/LaTeXTools#640]
Coming from LaTeXing (which was unusable due to https://github.com/LaTeXing/LaTeXing/issues/198), I was really used to the auto-complete panel automatically getting closed once I inserted the second backslash and I missed it immediately.

**Comment by r-stein** [comment]
Done in https://github.com/SublimeText/LaTeXTools/pull/641

**Comment by FichteFoll** [comment]
:+1:
