### ISSUE TITLE
xelatex + bibtex compiling problem

### ISSUE THREAD

**Issue by Koffieketel** [SublimeText/LaTeXTools#645]
Hi! 
First of all, I love LaTeXTools already for years now! (together with sublimetext2)

At the moment I have got a LaTeX template which has to be compiled with xelatex together with bibtex for my bibliography from mendeley. 
(Actually I would like to use the normal compiling sequence, using xelatex instead of the default .tex  compiler).

For this, I put %!TEX program = <xelatex> on top of my main file, however it doesn't do anything different unfortunately (I also copied the original LaTeXTools.sublime-settings file to be sure I had no custom one). 

I also tried to change the LaTeXTools.sublime-settings to change it from "traditional" to my preferred sequence, however without any succes.

Can you help me please? 
Thanks!

**Comment by ig0774** [comment]
Glad you love the package.

For what you want to accomplish, it should be sufficient to use the traditional builder and set a `%!TEX program` directive.

The line should be this:

```
%!TEX program = xelatex
```

Note that, in particular, you don't need to tell the traditional builder what build sequence to use. For the most part, it will just do the right thing.

If that doesn't work, it would be helpful to see the build output as well as any output to the console (ctrl + ` or cmd + `) that occurs when you try to build.

**Comment by Koffieketel** [comment]
Oke I will check that

**Comment by Koffieketel** [comment]
It looks like it is working now! 

`%!TEX program = xelatex` compared to `%!TEX program = <xelatex>`. 
I had the latter in my code which didn't work. 

Thanks!
