### ISSUE TITLE
Set spellchecking language in the document

### ISSUE THREAD

**Issue by fph** [SublimeText/LaTeXTools#647]
Feature request: it would be cool if Latextools honored Texstudio's `% !TEX spellcheck = it-IT` directives to set the spellchecking language.

**Comment by r-stein** [comment]
I think this is a nice idea and I am preparing a PR. Just a few points:
- Do you know if the `spellcheck` directive only holds for the current document or should also extracted from the root document?
- I am not sure on which events the function should be triggered. E.g. on every save would directly react on changes, but slow down ST.
- It seems only to be useful if the [Dictionaries](https://packagecontrol.io/packages/Dictionaries) package is installed. (In addition translation locales to the dictionary language names cannot be done in a generic way and requires a full mapping.)

**Comment by fph** [comment]
Thanks for the enthusiastic support!

1. No, I don't know. It would make sense to me if it held only for the current document, though. Also because I can imagine use cases where different `\include`d files use different languages.

2. Good point. AFAIK it is common for this kind of directives to work only if they are in the first 10 lines of the file (the only reference online I could find, though, is [here](http://tex.stackexchange.com/a/46218/1371). Would it be acceptable to scan on every save only the first 10 lines to see if they start with `% !TEX`? (Incidentally, I see that LaTeXTools currently handles the `%!TEX root=...` directive in `getTeXRoot.py` by scanning only up to the first non-comment line.)

3. I agree with you that it seems necessary to have Dictionaries installed, and that a manual locale-to-language-name mapping seems necessary.

4. Incidentally, [this tex.stackexchange answer](http://tex.stackexchange.com/a/84687/1371) claims that Sublime Text already supports spellcheck directives, but I couldn't find it confirmed anywhere else. I have tried it with `it_IT` and it doesn't work, so I assume it is a mistake in the answer.

**Comment by r-stein** [comment]
- I think it would be nice to first check the current file and if it is not defined in the root
- My current implementations checks whether the dictionary packages is installed and creates a mapping from the locales to the names. In addition the user can define his own mappings in his settings (He might have own dictionaries or other dict packages). If someone is interested, the implementation is available [here](https://github.com/r-stein/LaTeXTools/blob/autodetect_spell_check/detect_spellcheck.py).
- The answers states it understands `root` and `program` but not `spellcheck`, which is truee

**Comment by ig0774** [comment]
@r-stein: Is there anything apart from #636 that prevents this from being a PR? This looks like a nice feature to add.

**Comment by r-stein** [comment]
@ig0774 No, that is the only reason.

Besides I am still thinking whether it should be triggered only `on_load` or `on_load` and `on_save`.

**Comment by ig0774** [comment]
FWIW, I think it's worth using the `on_post_save` event, if only because without it, the file would need to be closed an re-opened for changes to the `%!TEX spellcheck...` to be detected.

It may be a good idea (and I should probably do this in `texSyntaxListener` too) to use `on_post_save_async` so that on ST3 (at any rate) it doesn't interfere as much with ST's responsiveness.

**Comment by ig0774** [comment]
@r-stein's changes have been merged and will be available in the next release. As he noted, this functionality is (more or less) basically dependent on having the [`Dictionaries`](https://packagecontrol.io/packages/Dictionaries) package installed. This also means that we may be missing some mappings available in Texstudio and elsewhere (though not Italian), in addition to having some mappings not available in Texstudio, etc.

If you find even with the `Dictionaries` package you are missing a language you need, see [`Dictionaries` instructions for converting existing languages](https://github.com/titoBouzout/Dictionaries#adding-a-new-language) and add a mapping to the newly created file in the `tex_spellcheck_paths` setting.

**Comment by fph** [comment]
Thanks for implementing this; I am closing the issue.
