### ISSUE TITLE
Project File is read only every 2nd compilation attempt

### ISSUE THREAD

**Issue by shaaati** [SublimeText/LaTeXTools#651]
Currently, I encounter quite a strange problem.
Whenever I compile my tex document from another than the master file, it succeeds only every second time.
My `projectname.sublime-project` looks as follows:
```
{
  "folders":[...],
  "settings": {
      "TEXroot": "../main.tex"
  }
}
```
The project directory has a separate folder for the chapter files, hence the `../` in the TEXroot.
When I press `super+b` in a chapter file, it first tries to compile that file alone. I am not able to use autocompletion for references or citations as well.
After the compilation attempt has failed, autocompletion suddenly works and another press of `super+b` leads to the compilation of my master file `main.tex`.

Somehow, every second time LatexTools seems to remember what my project settings are.

I am running Sublime Text 3, Build 3083 on OS X 10.9.5.

**Comment by r-stein** [comment]
The TEXroot must be an absolute path, e.g. `/Users/shaati/latex/master/main.tex`.

To explain why it works *every second time*:
The relative path is not (yet) treated directly and hence relative to the directory from which you call the build command. This directory is/can be different if you have focus on the file or on the output panel. Hence it starts from the wrong directory if you call it in the file and in the correct directory if you call it from the output panel.

**Comment by ig0774** [comment]
This does sound like this is a duplicate of #152. Out of curiosity though, does it only work every second time (i.e., build fails, build succeeds, build fails, build succeeds) or does it work on the second and subsequent attempts (i.e., build fails, build succeeds, build succeeds...)?

It may be worth using the comment form to specify the root file, i.e., by placing `%! TEX root = ../main.tex` at the start of each of your chapters. This manner of specifying the tex root doesn't suffer from the same issue.

**Comment by shaaati** [comment]
It works in only half of all cases, that is **every** second time.
Changing the option to an absolute path fixed the problem, thanks for the help. At the same time, it brought back PDF sync, which didn't work either.

I knew of the comment option, but as I like to keep editor-specific stuff out of my files I switched over to the newer project-based settings approach.
