### ISSUE TITLE
Python exception: IndexError('string index out of range',) with tufte-handout document class

### ISSUE THREAD

**Issue by alecshaw** [SublimeText/LaTeXTools#654]
I seem to be receiving this error with this document class (tufte-handout):

LaTeXtools could not parse the TeX log file
Python exception: IndexError('string index out of range',)

The document compiles and produces a PDF.

I have included a log file below:
[islenskmalfraedi.txt](https://github.com/SublimeText/LaTeXTools/files/126960/islenskmalfraedi.txt)

**Comment by ig0774** [comment]
Thanks for reporting this bug. It's been fixed in the latest version.
