### ISSUE TITLE
LaTeXTools can't find installed pygmentize package

### ISSUE THREAD

**Issue by 2016rshah** [SublimeText/LaTeXTools#657]
When compiling a LaTeX file with the package minted, LaTeXTools fails and says `Package minted Error: You must have 'pygmentize' installed to use this package. []`. I have installed it, and everything works fine if I try compiling from the command line (with `pdflatex --shell-escape FILENAME.tex`). I'm guessing LaTeXTools is looking for the package in the wrong place, but I am not sure how to fix that, does anyone have any suggestions?

As of right now, `Pygments version 2.1.1` is installed at `/Library/Frameworks/Python.framework/Versions/3.4/bin/pygmentize`. I am on Mac OSX Yosemite using Sublime Text 3. I can provide further information about my setup as needed if that would help. 

(To be clear, I have specified `--shell-escape` in the configuration file for LaTeXTools, so that is not the issue as far as I know)

**Comment by r-stein** [comment]
The traditional builder uses latexmk. I would recommend to open the Sublime Text console with `View>Show Console`. This prints the executed command, which should be:

``` py
['latexmk', '-cd', '-e', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '-latexoption="--shell-escape"', 'your_file.tex']
```

Hence you could try run to this command in your shell:
``` py
'latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 -latexoption="--shell-escape" your_file.tex'
```

Remember that the `shell-escape` option is not platform specific, hence *not* inside `osx`.

**Comment by ig0774** [comment]
This more or less falls under the warnings about the `$PATH` on OS X. You need to ensure that your `texpath` setting includes not just `pdflatex` and friends but any other executables that they might need to launch. So you not only need to set `--shell-escape` you need to ensure that `pygmantize` is available on the `$PATH`, which in your case looks like you need `/Library/Frameworks/Python.framework/Versions/3.4/bin` included.

As an alternative, you can redefine the `\MintedPygmentize` command in your document to the full path to the pygmantize executable, e.g.,

 ```latex
\renewcommand{\MintedPygmentize}{/Library/Frameworks/Python.framework/Versions/3.4/bin/pygmantize}
```

**Comment by 2016rshah** [comment]
@r-stein hmm, I had no idea about `latexmk` versus `pdflatex`, so I tried using the command you provided (it matched with what my ST console showed me) and the compilation succeeded even though it didn't work from ST.

@ig0774 you were spot on about adding `/Library/Frameworks/Python.framework/Versions/3.4/bin` to my texpath. In my LaTeXTools configuration file, I changed 

    "texpath" : "$PATH:/usr/texbin:/usr/local/bin:/opt/local/bin"
to 

    "texpath" : "$PATH:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin" 

and everything started working like a charm, thank you so much. 

Also, just for the record, I tried the other solution first, but it did not work for me and gave me the following errors:

    LaTeX Error: \MintedPygmentize undefined. [\renewcommand{\MintedPygmentize}]
    LaTeX Error: Command \MintedPygmentize already defined. [\newcommand{\MintedPygmentize}{pygmentize}]

but since changing my `texpath` fixed the problem, we're all good. Thank you all so much!

**Comment by guilgautier** [comment]
Hi there, thank for these great answers!
I had the same issues but still struggled a bit. That's why I wish to share a more detailed answer.

Like @2016rshah I wanted to use the [minted](https://ctan.org/pkg/minted) package to highlight some Python code in a LaTeX file.
If you only add the `\usepackage{minted}` in the preamble and then build the `.tex` file then you would _a priori_ get 2 errors:
1. `Package minted Error: You must invoke LaTeX with the -shell-escape flag.`
2. `Package minted Error: You must have 'pygmentize' installed to use this package.`

First, you need to have the Python package [Pygments](https://pypi.org/project/Pygments/) installed
  ``` 
  $ pip install Pygments
  ```

Then you can update the `LaTeXTools.sublime-settings` file accordingly

- ```Sublime Text -> Preferences -> Package Settings -> LaTexTools -> Settings - User```

- To solve 1. add the `--shell-escape` option in the `"builder_settings"` field
  ```
  "builder_settings" : {

   // General settings:
   // See README or third-party documentation

   // SHELL ESCAPE OTPTION
   "options" : "--shell-escape",
   
   // (built-ins): true shows the log of each command in the output panel
   "display_log" : false,

   // Platform-specific settings:
   "osx" : {
    // See README or third-party documentation
   },

  ...
  }
  ```


- To solve 2.

  - locate the folder where `pygmentize` is saved

  ```
  $ which pygmentize
  /Users/ggautier/anaconda/bin/pygmentize
  ```

  - add the path i.e. `/Users/ggautier/anaconda/bin` in the `"texpath"` field

  ```
  // ------------------------------------------------------------------
  // Platform settings: adapt as needed for your machine
  // ------------------------------------------------------------------

   "osx":  {
    // Path used when invoking tex & friends; MUST include $PATH
    "texpath" : "$PATH:/Users/ggautier/anaconda/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:"
    // Path to PDF viewer, if needed
    // TODO think about it. Also, maybe configure it here!
   }
  ```

Hopefully, you should be fine!
