### ISSUE TITLE
Okular support not working

### ISSUE THREAD

**Issue by andradx** [SublimeText/LaTeXTools#658]
I applied the 639 patch to version 3103 in the hope that Okular support would work, but evince is still being launched.

How can I troubleshoot this?

Evince is not the best/fastest/smoothest viewer for large documents, hence my thing for Okular...

Patch here https://patch-diff.githubusercontent.com/raw/SublimeText/LaTeXTools/pull/639.patch

**Comment by r-stein** [comment]
Have you changed your settings to use okular?

``` js
"viewer": "command"

"viewer_settings": {
    "linux": {
        "forward_sync_command": "okular --unique $pdf_file#src:$line$src_file"
        "view_command": "okular --unique"
    }
}
```

**Comment by andradx** [comment]
That goes into LaTeXTools.sublime-settings, correct? To anywhere within the outermost enclosing brackets or to a particular line/section within?

**Comment by r-stein** [comment]
Yes anywhere in the outermost brackets.

It would be useful to look at the ST console output `View>Show Console`, this should contain something like `CommandViewer` and *not* `EvinceViewer`. Afterwards the command should also be printed.

**Comment by andradx** [comment]
This the console output after patching w/ 639 and including your snippet onto LaTeXTools.sublime-settings.

```
Welcome to thread Thread-10
['latexmk', '-cd', '-e', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', '-latexoption="--shell-escape"', 'tpds-jandrade.tex']
Finished normally
0
False True True
!TEX root =  '/home/andrade/Documents/TPDS/TPDS15/tpds-jandrade.tex'
Jump to:  33 20
Linux!
(Re)launching evince
launched evince_sync

```

Should I just include the options you mention in the LaTeXTools.sublime-settings file and never mind about the patch? I've noticed I complained before in the issues about Okular. That time I managed to get it to work, but not this time.

**Comment by r-stein** [comment]
That outputs matches the output in the main branch, but not the one on the `ig0774:pluggable_viewers`.
You could open the packages directory delete the LaTeXTools folder and run the following command in a shell to be sure you have checked out the correct branch:
``` sh
git clone -b pluggable_viewers --single-branch https://github.com/ig0774/LaTeXTools
```

**Comment by andradx** [comment]
That's just perfect, I now have okular support again.
