### ISSUE TITLE
Delete temporary minitoc files

### ISSUE THREAD

**Issue by jayzrnr** [SublimeText/LaTeXTools#661]
Could you add the .mtc and .mtc0 file extensions to the list of file types that can be deleted automatically?

**Comment by ig0774** [comment]
The extensions deleted are all controlled by the `temp_files_exts` setting in your LaTeXTools.sublime-settings file.

If you don't have that entry, you can either run the **LaTeXTools: Reset user settings to default** (which will overwrite your existing settings) or go to **Preferences | Package Settings | LaTeXTools | Settings - Default (read-only)** and copy the `temp_files_exts` block to your local settings.

**Comment by jayzrnr** [comment]
Thx for the simple solution! It wasn't in my settings file so I wasn't aware of this variable.
