### ISSUE TITLE
Build in ST2 not working after update

### ISSUE THREAD

**Issue by lewaszek** [SublimeText/LaTeXTools#663]
As of  LaTeXTools Plugin version 3.6.3 (2016-02-25) build is not working for me in ST2 on Ubuntu 15.10. I'm still able to do things like run bibtex and clean up LaTeX auxiliary files, just 'build' with the build system 'LaTeX' does not give me any feedback except a blank console window.

From View > Show console after [ctrl+b]:
```
<module 'traditionalBuilder' [...]/builders/traditionalBuilder.py'>
<class 'traditionalBuilder.TraditionalBuilder'>
Traceback (most recent call last):
  File "./sublime_plugin.py", line 337, in run_
  File "./makePDF.py", line 474, in run
TypeError: __init__() takes exactly 5 arguments (8 given)
```
Any hints appreciated, can't rule out, that I messed something up. Shell command `latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 file.tex` still works.

**Comment by ig0774** [comment]
Thanks for all the detail on this. Have you tried simply restarting Sublime Text? That should fix the issue...

**Comment by lewaszek** [comment]
Thanks for the response. Restart of Sublime Text or system restart did not help, unfortunately.

**Comment by ig0774** [comment]
That's what I was worried about. Somehow after the upgrade you seem to have been left with an old version of `traditionalBuilder.py` in your package folder, hence the error.

Probably the easiest thing to do is to remove and reinstall the package. If you use Package Control, its as easy as running `Package Control: Remove Package`, selecting LaTeXTools and then running `Package Control: Install Package`, again selecting LaTeXTools. Note that removing and reinstalling LaTeXTools **won't** touch your LaTeXTools.sublime-settings file, so everything *should* work after its reinstalled, but please let me know if it doesn't.

**Comment by lewaszek** [comment]
This. I checked the file permissions after first remove/install did not work. For some reason, the owner of the folder 'builders' and all the files inside was 'root' since somewhen in 2014. Changed, repeated, worked. Thanks a lot for Your help!
