### ISSUE TITLE
completion for includegraphics: other directory and macros ? 

### ISSUE THREAD

**Issue by pierremomo** [SublimeText/LaTeXTools#665]
Hello,

I just discovered the new feature: completion for input/includegraphics .. it's terrific ! I have some questions: does it work only for images in the current directory ? or is there a way to specify some other subdirectory for example ? 

Moreover, I usually work with some macro, such as
 \newcommand{\image}[2]{\includegraphics[width=#1\linewidth]{./media/#2}}

is there a way to make the completion work also for this macro \image ? 

thanks a lot for your help and congrats again for your incredible work with this package...

Pierre

**Comment by r-stein** [comment]
To address your questions and try to provide workarounds:

1. Currently it is not possible to add additional directories for image (or tex or bib) files. However all subdirectories of the tex root are scanned and you might create the desired behavior using symbolic links. This is not perfect, but might be an okayish workaround.
2. The completion selection is currently hard coded in the source code. Hence there is no option in LaTeXTools to use our macro. In addition other commands like "open included graphics" (`C-l,C-o`) also rely on the command being named `includegraphics`. In general I would say supporting newcommand definitions is hard to establish. However you could add your own keybinding to change the text and toggle between `image` and `includegraphics`:

  ``` js
  {
      "keys": ["{"],
      "command": "chain",
      "args": {
          "commands": [
              ["delete_word", {"forward": false}],
              ["insert", {"characters": "includegraphics"}],
              ["latex_fill_input", {"insert_char": "{"}]
          ]
      },
      "context":
      [
          {"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
          {"key": "selection_empty", "operator": "equal", "operand": true, "match_all": true},
          {"key": "preceding_text", "operator": "regex_contains", "operand": "\\\\image$", "match_all": true}
      ]
  },
  {
      "keys": ["}"],
      "command": "chain",
      "args": {
          "commands": [
              ["move_to", {"forward": true, "to": "brackets"}],
              ["delete_word", {"forward": false}],
              ["insert", {"characters": "image"}],
              ["move_to", {"forward": true, "to": "brackets"}]
          ]
      },
      "context":
      [
          {"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
          {"key": "selection_empty", "operator": "equal", "operand": true, "match_all": true},
          {"key": "preceding_text", "operator": "regex_contains", "operand": "\\\\includegraphics{[^}]*}$", "match_all": true}
      ]
  },
  ```
  This keybinding requires the [Chain of Command](https://packagecontrol.io/packages/Chain%20of%20Command) package to be installed and just defines macros. It will replace `\image` to `\includegraphics` so the image search is triggered. Afterwards press `}` to replace it back to `\image`. This is quite imperfect, but better than nothing.

**Comment by pierremomo** [comment]
thanks a lot for your repli...
- for the first point, my bad, I thought I checked about the subdirectories but apparently I was wrong: it is indeed scanning the subdirectories of the current one ... which is what I wanted :)

- for the second point, your proposed workaround is very interesting :) I am going to take a look in more details but I think I will have some issues with my "two arguments" macro ... will see ...

thanks again !

**Comment by ig0774** [comment]
@pierremomo: Can this be closed? Thanks...

**Comment by pierremomo** [comment]
I guess :) thanks again
