### ISSUE TITLE
Inline verbatim with underscore

### ISSUE THREAD

**Issue by dgbirm** [SublimeText/LaTeXTools#669]
Hi,

I'm running into a compiling issue with \texttt{something_somethingelse}. Would love some input to make sure I'm not just being ridiculous.

Thanks,
Daniel

**Comment by r-stein** [comment]
Change it from `\texttt{something_somethingelse}` to `\texttt{something\_somethingelse}`. Underscore is a special char and must be escaped. If you want to use it as subscript, you must be in math mode.

**Comment by dgbirm** [comment]
Thank you

**Comment by r-stein** [comment]
No problem =)
Don't forget to close the issue and for pure LaTeX related issues I would recomment http://tex.stackexchange.com/.
