### ISSUE TITLE
No PDF Generated

### ISSUE THREAD

**Issue by ormir** [SublimeText/LaTeXTools#675]
Hello everybody,
i am a new LaTeX user, and decided to use it on Sublime Text 3.
I installed BasisTex and LaTeXTools and confogured the paths.
When I buid a tex file, it doesn't show any error, and everything is generated but the PDF File.

I am using OSX 10.11.3 on Macbookair

Building the project
![screen shot 2016-04-04 at 13 57 41](https://cloud.githubusercontent.com/assets/6843504/14247263/44bcd764-fa6d-11e5-904e-2cd389366f79.png)

Created files
![screen shot 2016-04-04 at 13 57 04](https://cloud.githubusercontent.com/assets/6843504/14247283/6e6919ce-fa6d-11e5-9764-7a916f3ce9fe.png)

Thank you in advance :)

**Comment by ig0774** [comment]
You've created a TeX document with no content, hence there's no PDF (it would be entirely blank). The `\title` command just sets a variable. It doesn't, by itself, issue any typesetting commands. Try:

```latex
\documentclass{article}
\begin{document}
Hello
\end{document}
```

And, hey, welcome to LaTeX!

**Comment by ormir** [comment]
@ig0774 Thank You, for your fast responce :)
It works perfectly now
