### ISSUE TITLE
Glossary search/autocomplete in analogy to citation search/autocomplete

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#676]
The [glossaries package](https://www.ctan.org/pkg/glossaries?lang=en) gives a format for defining glossary entries that is similar to a bibTeX bibliography format (in terms of having entries indexed by key strings).

It seems that it would be possible to share some of the code for search/autocomplete popup that is used for fuzzy search through a `.bib` file with a similar utility that would search through a glossary file. 

The unfortunate thing is that unlike a bibliography, there's no easy way to detect that a glossaries file is included, and so some specific markup or other convention may need to be used to indicate that something is even a glossary file to be searched.

**Comment by lenucksi** [comment]
It would also be useful to be able to autocomplete acronyms declared using the glossaries package.

**Comment by r-stein** [comment]
This does not look complicated, just review these informations I got from the doc.

The glossary definition commands are:
- newglossaryentry
- longnewglossaryentry

Usage comands are
- gls, Gls
- glssymbol
- glspl

The acronym definition command is only
- newacronym

acronym usages:
- acrshort
- acrlong
- acrfull

In addition we need to scan files included via:
- `\loadglsentries{filename}`

**Comment by r-stein** [comment]
Added in `v3.12.0`.

**Comment by Kyslik** [comment]
Is there a way to tell LaTeXTools where is glossary file just like bibliography

```
\iffalse \bibliography{../includes/bibliography.bib} \fi
```

**Comment by ig0774** [comment]
@Kyslik: assuming you're talking about a separate `tex` file with `\newglossaryentry` and `\newacronym` commands you could just use:

```
\iffalse \input{../includes/glossary} \fi
```

LaTeXTools currently doesn't support reading the generated `glo` files.
