### ISSUE TITLE
file helper for \inputminted (code files)

### ISSUE THREAD

**Issue by JimAmuro** [SublimeText/LaTeXTools#679]
Hi,
I love the Fill Helper function very much. Now I want to use `\inputminted` to insert code file, is there any way to modify the package to make it also autofill the file name for code files? Thanks!

**Comment by r-stein** [comment]
This is currently not possible, but I think this is a nice suggestion for future releases.

Adding it to the dropdown menu, which appears when pressing `{` should not be to complicated. However using it in the autocompletion would be harder, but still possible.

**Comment by JimAmuro** [comment]
The former thing is what I mean. I just want to add it to the dropdown menu, i.e. a code file version for `\includegraphics{` . I think it is not so difficult because the treatment is the same, maybe I just need to add `\inputminted` into triggers and a filter for code files, but I don't know which file to modify...

**Comment by r-stein** [comment]
If you want to temporary modify it on your own:
(Assuming you have some basic python knowledge)
You can open the file by pasting the following in the ST console `` ctrl+` ``:

``` py
window.open_file(sublime.packages_path() + "/LaTeXTools/latex_input_completions.py")
```

Afterwards add your regex in reversed order in line `37`, add a new "filter" in line `95` afterwards add the code in the `elif` block in line `133` similar to the svg part.

However with more and more commands this requires some rework and your changes are only temporary and might be overwritten with the next update.

**Comment by JimAmuro** [comment]
Thank you very much.
I know it is just a workaround. It would be better if it could be added in the settings.

**Comment by ig0774** [comment]
If you come up with something, feel free to [open a pull request](https://help.github.com/articles/creating-a-pull-request/). We're always happy to incorporate changes.

In terms of the settings, how would you envision that working?

**Comment by r-stein** [comment]
@ig0774 I have a very promising approach [here](https://github.com/r-stein/LaTeXTools/tree/fillall_helper_setting_entries), which should also be able to solve https://github.com/SublimeText/LaTeXTools/issues/665

It builds the `TEX_INPUT_FILE_REGEX` and so on from dicts, which can also come from the user settings.

A setting entry could be:
```js
"fillall_helper_entries": [
	{
		"regex": "(?:\\][^{}\\[\\]]*\\[)?gvsedulcni\\\\",
		"extensions": ["svg"],
		"strip_extensions": [".svg"]
	},
],
```

**Comment by ig0774** [comment]
@r-stein: That looks really good!

**Comment by JimAmuro** [comment]
Thank you very much for your work on this! 
But how to use it? I substituted the old file with the new one, and added that entry into my latextools user settings, but no luck when I typed `\includesvg{` ... Should it work or not? Have I done something wrong?

**Comment by r-stein** [comment]
@JimAmuro for performance reasons this requires a reload of the module (restart ST/ open the python file and save it) for settings to have an effect

**Comment by JimAmuro** [comment]
@r-stein I restarted for several times... Still doesn't work...

**Comment by JimAmuro** [comment]
@r-stein 
Error info generated when invoking `includegraphics{` and `\includesvg{`. The first one works and the second one doesn't work, but they both invokes error info in the ST console. Hope that helps.
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_input_completions.py", line 235, in on_query_completions
    view.substr(sublime.Region(view.line(location).a, location))
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "C:\Users\Hui Sun\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_input_completions.py", line 291, in run
    view.substr(sublime.Region(view.line(point).a, point)))
TypeError: 'NoneType' object is not iterable
```

**Comment by r-stein** [comment]
@JimAmuro I pushed my newest version, please try it out and add additional issues at https://github.com/SublimeText/LaTeXTools/pull/681

**Comment by r-stein** [comment]
This has been adden in `v3.8.0`.
