### ISSUE TITLE
Command to jump to pdf but with focus on pdf not changing the toggle

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#680]
I know there is the toggle switch and I can use chain of command to toggle, then jump to pdf, and then toggle back but seeing if the LatexTools has anything built in for this.

Sometimes I want to jump and have focus on the pdf so just curious if there was a function built-in.

**Comment by r-stein** [comment]
This is currently not supported, but it might be useful and easy to add this.

@ig0774 changing line `159` to `keep_focus = args.get('keep_focus', get_setting('keep_focus', True))` would enable the user to overwrite the setting by passing args and one could e.g. use the keybinding:

``` js
    {   "keys": ["ctrl+l","J"],
        "context":  [
            {"key": "selector", "operator": "equal", "operand": "text.tex.latex"}],
        "command": "jump_to_pdf", "args": {"from_keybinding": true, "keep_focus": false}
    },
```
to let the focus at the pdf viewer and keep the focus when building

**Comment by excetara2** [comment]
Yeah I was going to keep the original `["ctrl+l", "j"]` as is and just add ["ctrl+l", "ctrl+j"] to send focus to the pdf for the times it is necessary.

**Comment by r-stein** [comment]
@excetara2 you can already test the change just open the console `` ctrl+` `` and paste `window.open_file(sublime.packages_path() + "/LaTeXTools/jumptoPDF.py:159", sublime.ENCODED_POSITION)`. Afterwards apply the change.

Aside: I would recommend to use the `ctrl+l, shift+j` keybinding, because I am looking forward to use your keybinding in a [future PR](https://github.com/r-stein/LaTeXTools/tree/jumpto_anywhere#jump-to-anywhere)

**Comment by excetara2** [comment]
Okay yeah it works great so thanks and I have set it to a different binding
as that looks like a very useful PR. Ended up setting it to `ctrl+l`, `\`
because that's used in sublime's file browser to open external file browser
or open an application with the file so used to that jumping out of Sublime.

I assume at a later PR you'll add in the above code?

**Comment by ig0774** [comment]
Closing as this is now possible.
