### ISSUE TITLE
Is it possible to use Reindent in this?

### ISSUE THREAD

**Issue by SimonRyang** [SublimeText/LaTeXTools#682]
I did use the method in https://gist.github.com/albertxing/5298255#file-indentation-rules-tmpreferences, but it does not give a nice organized code. Maybe you can tell how to use that or a little bit improvement for indenting is feasible or not? 

Thanks.

**Comment by ig0774** [comment]
You can save the file in that Gist anywhere that Sublime Text will see it. I'd recommend something like `$packages_path\User\LaTeX - Indentation Rules.tmPreferences`. You can find what I've called `$packages_path` by selecting the **Preferences: Browse Packages** option from the quick panel (c-shift-p) or via the **Preferences|Browse Packages** menu item. Note that indentation rules do not, by themselves, change already written text. They are designed to provide automatic indentation or de-dentation while you are typing.

If you want to organise an already written LaTeX file, you might try using [latexindent](http://www.ctan.org/tex-archive/support/latexindent). Somebody [created a package](https://packagecontrol.io/packages/BeautifyLatex) that appears to run this in ST, but I can't really speak to how well it works. Perhaps this is yet another feature we should consider adding.

**Comment by simonyoungfight** [comment]
Thanks!

**Comment by jaabell** [comment]
FWIW. I find that I needed to add the `text.tex.latex` scope to the previous one to get it to work. 

`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Indentation Rules</string>
        <key>scope</key>
        <string>text.tex, sources.bib, text.tex.latex</string>
        <key>settings</key>
        <dict>
            <key>decreaseIndentPattern</key>
            <string>(?x)
                ^\s*\\end\{[^\{\}]+\}.*$
            |   ^\s*\\\].*$
            |   ^\s*\}.*
            |   ^\s*\%.*\(end\).*$
            </string>
            <key>increaseIndentPattern</key>
            <string>(?x)
                ^\s*\\begin\{[^\{\}]+\}(\{.*\}|\[.*\])*$
            |   ^.*\\\[\s*$
            |   ^.*\\(.+)\{$
            |   ^\s*\\((sub)[0,2])?section(\*)?\{.*\}.*$
            </string>
        </dict>
        <key>uuid</key>
        <string>02EB44C6-9203-4F4C-BFCB-7E3360B12842</string>
    </dict>
</plist>
`
