### ISSUE TITLE
Allow building a non-active document

### ISSUE THREAD

**Issue by te-x** [SublimeText/LaTeXTools#684]
Hey, I'm writing a large document with LaTeXTools, and I've split it into several documents, one for each chapter. I can't find a way to build **main.tex** while working on **chapter9.tex**. If there was some way to specify what file to build in a given project, it would be really helpful (at least for me)

**Comment by r-stein** [comment]
In the section for [compiling latex files](https://github.com/SublimeText/LaTeXTools#compiling-latex-files) several ways are described. Just write at the top of the file `%!TEX root = relative/path/to/masterfile`, e.g. `%!TEX root = ../../master.tex`.

Aside: There is also a easy way to auto insert "magic" comment when you create the file:
If you have a command `\input{chapters/chapter9.tex}`, then you can move the cursor on the command and press `ctrl+l, ctrl+o`. If the file does not exists, then this will create a file, missing folders, and insert the root comment.
