### ISSUE TITLE
Citation search does not search later author names for citations with more than 3 names

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#687]
Currently if you have a citation that includes more than two author names, the later author names cannot be searched for using the citation search box

E.g., `spiegelhalter` in the search box will not find

@book{gilksrs96,
  editor =       {W.R. Gilks and S. Richardson and D. J. Spiegelhalter},
  title =        {Markov Chain {M}onte {C}arlo in Practice},
  publisher =    {Chapman and Hall},
  year =         {1996},
  address =      {Suffolk, UK}
}

Since this would technically be a new feature, I suppose this is more of a enhancement than a bug.

**Comment by ig0774** [comment]
This should actually be fairly easy to do as it should just require tweaking a setting. In the settings file, there's a setting called `cite_panel_format`. By default, it's set to `["{author_short} {title_short}", "{title}"]`. Change the value to `["{author_short} {title_short}", "{title}", "{author}"]` and it should be able to search by any author. A side effect will be that you should have a third line showing all the authors. I'm not really sure how this'll work with an extremely large set of authors or long author names, but at least your sample entry should be short enough to display.

More broadly, we don't have programmatic control over the quick panel. It simply displays and searches only the text provided. The `{author_short}` entry is set to display up to two authors and then just use the first authors name and "et al." so the quick panel never sees all the authors names. More generally, pretty much any field you want to search could be added in a similar fashion.

**Comment by ig0774** [comment]
See the latest comment. I screwed up the default value... I was typing from memory.
