### ISSUE TITLE
New full parse is run on every `\cite{` typed; slows writing down

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#688]
The time it takes to run the parser each time you type `\cite{` is noticeable (but not intolerable) with moderately large bib files (>12000 lines or so; maybe >1200 entires?).

This might be able to be sped up by caching the parsed bib file as it is held in memory (if it is too large to be stored in memory, maybe writing out to a binary format that can be read more rapidly than the `.bib` text?) so they can be read more quickly and then each `\cite{` hashes the bib file to see whether its changed, if not, it loads from cache.

**Comment by r-stein** [comment]
I made the suggested change to the traditional bib. Just replace bibliography_plugins/traditionalBuilder.py with 
[traditionalBibliography.py.txt](https://github.com/SublimeText/LaTeXTools/files/227284/traditionalBibliography.py.txt). This just adds the caching on top of the traditional bib as suggested.

**Comment by ig0774** [comment]
@r-stein: Thanks. I'm going to incorporate that. Btw, with the new plugin stuff you can just import `latextools_utils` directly as if the plugin were in the main folder.

**Comment by ig0774** [comment]
When you have some time, could you see if the new caching (in v3.7.3) resolves the issue?
