### ISSUE TITLE
CTRL+L,v doesn't focus evince

### ISSUE THREAD

**Issue by sdruskat** [SublimeText/LaTeXTools#689]
See title. The key binding used to open the viewer (Ubuntu 14.04, ST3), now it doesn't. Please let me know what additional info I can supply to help investigating.

**Comment by sdruskat** [comment]
Checked with different settings, and it seems that this is only broken for evince. I edited to `"viewer": "okular"` and it works fine. However, neither of the following works: `"viewer": ""`,` "viewer": "default"`, `"viewer": "evince"`.

**Comment by ig0774** [comment]
Does anything show up on the console when you're trying to use Evince? Do you have the Linux-specific `python2` setting set to a value? If not, is your system default Python a version of Python2? (You could find out the latter by typing `python --version` into the terminal).

**Comment by sdruskat** [comment]
`python2`: I have `python` mapped to python 2.7.6 64-bit, so `$ python` should (and does) start that python version. `python2` is also mapped to the same version. I've tried with the options `""`, `"python"`, `"python2"` and `"/home/full/path/to/python2/executable"`, and neither works. 

I've also tried the following "workflow" which resulted in below console output: Open ST3 with .tex file, open viewer with *CTRL+L,v* (**works!**), manually re-focus ST3, try to re-focus viewer with *CTRL+L,v* (**doesn't work!**), build, try to re-focus viewer with *CTRL+L,v* (**doesn't work!**). Same results for the following `"viewer":` settings: `""`, `"default"`, `"evince"`.

    DPI scale: 1
    startup, version: 3103 linux x64 channel: stable
    executable: /opt/sublime_text/sublime_text
    working dir: /
    packages path: /home/me/.config/sublime-text-3/Packages
    state path: /home/me/.config/sublime-text-3/Local
    zip path: /opt/sublime_text/Packages
    zip path: /home/me/.config/sublime-text-3/Installed Packages
    ignored_packages: ["Markdown", "Vintage"]
    pre session restore time: 0.160696
    startup time: 0.310921
    first paint time: 0.325697
    Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.tmLanguage
    Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.tmLanguage
    Error loading scope:source.css, source.less: Unable to find syntax file for scope source.css, source.less in Packages/MarkdownEditing/Markdown.tmLanguage
    Error loading scope:source.css, source.sass: Unable to find syntax file for scope source.css, source.sass in Packages/MarkdownEditing/Markdown.tmLanguage
    Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.tmLanguage
    Error loading scope:source.postscript: Unable to find syntax file for scope source.postscript in Packages/MarkdownEditing/Markdown.tmLanguage
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_file_settings
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.profile
    reloading plugin Default.profile_syntax_definition
    reloading plugin Default.quick_panel
    reloading plugin Default.run_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin Python.syntax_test_python
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.01-ssl-linux
    Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
    reloading plugin 0_package_control_loader.02-bz2
    reloading plugin FindResultsApplyChanges.FindExcludePatterns
    reloading plugin FindResultsApplyChanges.FindResultsApplyChanges
    reloading plugin LaTeX Word Count.WordCount
    reloading plugin MarkdownEditing.bootstrap
    reloading plugin MarkdownEditing.custom_find_under_expand
    reloading plugin MarkdownEditing.decide_title
    reloading plugin MarkdownEditing.distraction_free_mode
    reloading plugin MarkdownEditing.footnotes
    reloading plugin MarkdownEditing.indent_list_item
    reloading plugin MarkdownEditing.indent_list_multiitem
    reloading plugin MarkdownEditing.lint
    reloading plugin MarkdownEditing.mdeutils
    reloading plugin MarkdownEditing.numbered_list
    reloading plugin MarkdownEditing.quote_indenting
    reloading plugin MarkdownEditing.references
    reloading plugin MarkdownEditing.switch_list_bullet_type
    reloading plugin MarkdownEditing.underlined_headers
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin Sublimerge Pro.Sublimerge
    reloading plugin WordCount.WordCount
    reloading plugin LaTeXTools.00_reload_submodules
    reloading plugin LaTeXTools.change_environment
    reloading plugin LaTeXTools.delete_temp_files
    reloading plugin LaTeXTools.detect_spellcheck
    reloading plugin LaTeXTools.getRegion
    reloading plugin LaTeXTools.getTeXRoot
    reloading plugin LaTeXTools.jumpToPDF
    reloading plugin LaTeXTools.jumpto_tex_file
    reloading plugin LaTeXTools.kpsewhich
    reloading plugin LaTeXTools.latexCommand
    reloading plugin LaTeXTools.latexDocumentationViewer
    reloading plugin LaTeXTools.latexEnvCloser
    reloading plugin LaTeXTools.latexEnvironment
    reloading plugin LaTeXTools.latexFillAll
    reloading plugin LaTeXTools.latex_cite_completions
    reloading plugin LaTeXTools.latex_cwl_completions
    reloading plugin LaTeXTools.latex_env_completions
    reloading plugin LaTeXTools.latex_input_completions
    reloading plugin LaTeXTools.latex_installed_packages
    reloading plugin LaTeXTools.latex_ref_cite_completions
    reloading plugin LaTeXTools.latex_ref_completions
    reloading plugin LaTeXTools.latextools_default_settings
    reloading plugin LaTeXTools.latextools_plugin
    reloading plugin LaTeXTools.makePDF
    reloading plugin LaTeXTools.migrate
    reloading plugin LaTeXTools.parseTeXlog
    reloading plugin LaTeXTools.texMacro
    reloading plugin LaTeXTools.texSections
    reloading plugin LaTeXTools.texSyntaxListener
    reloading plugin LaTeXTools.toggle_auto
    reloading plugin LaTeXTools.toggle_focus
    reloading plugin LaTeXTools.toggle_fwdsync
    reloading plugin LaTeXTools.toggle_show
    plugins loaded
    Loading LaTeXTools plugins...
    Loaded LaTeXTools plugins ['pdf_builder'] from path /home/me/.config/sublime-text-3/Packages/LaTeXTools/builders/pdfBuilder.py
    Loaded LaTeXTools plugins ['script_builder', 'traditional_builder', 'simple_builder'] from path /home/me/.config/sublime-text-3/Packages/LaTeXTools/builders
    Loaded LaTeXTools plugins [] from path /home/me/.config/sublime-text-3/Packages/User
    Loaded LaTeXTools plugins [] from path /home/me/.config/sublime-text-3/Packages/User
    Loaded LaTeXTools plugins ['traditional_bibliography'] from path /home/me/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins
    Loaded LaTeXTools plugins ['base_viewer'] from path /home/me/.config/sublime-text-3/Packages/LaTeXTools/viewers/base_viewer.py
    Loaded LaTeXTools plugins ['okular_viewer', 'command_viewer', 'preview_viewer', 'sumatra_viewer', 'evince_viewer', 'skim_viewer'] from path /home/me/.config/sublime-text-3/Packages/LaTeXTools/viewers
    Loaded LaTeXTools plugins [] from path /home/me/.config/sublime-text-3/Packages/User
    Package Control: Skipping automatic upgrade, last run at 2016-04-20 10:21:54, next run at 2016-04-20 11:21:54 or after
    !TEX root =  '/home/me/Documents/papers/conference/softlink-to-git/abstract.tex'
    <class '_latextools_evince_viewer.EvinceViewer'>
    !TEX root =  '/home/me/Documents/papers/conference/softlink-to-git/abstract.tex'
    <class '_latextools_evince_viewer.EvinceViewer'>
    <class '_latextools_traditionalBuilder.TraditionalBuilder'>
    3
    Welcome to thread Thread-6
    ['latexmk', '-cd', '-e', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', 'abstract.tex']
    Finished normally
    0
    False True True
    !TEX root =  '/home/me/Documents/papers/conference/softlink-to-git/abstract.tex'
    Jump to:  24 28
    <class '_latextools_evince_viewer.EvinceViewer'>
    !TEX root =  '/home/me/Documents/papers/conference/softlink-to-git/abstract.tex'
    <class '_latextools_evince_viewer.EvinceViewer'>

**Comment by ig0774** [comment]
Oh! I see what's happening. For some reason I was thinking that it wasn't running Evince at all, but the problem is really about *focus* (which you said quite clearly; I just didn't read things properly).

I don't have a Linux box to test on right now, but you could try [this file](https://gist.github.com/ig0774/cf623365b5b000237ebfb07bb6469e2e). To use it, download the Python script, extract the zip file (if you downloaded the zip). In Sublime, from the palette, select **Browse Packages**, find the `LaTeXTools` folder and then the `viewers` subfolder and replace the current `evince_viewer.py` file with the new one. You'll need to restart Sublime, but hopefully that version will get things working. If so, I'll add it to the release queue.

**Comment by sdruskat** [comment]
Works just fine! Thanks a lot!

**Comment by ig0774** [comment]
This has been integrated into v3.7.4.
