### ISSUE TITLE
Problem with multiple selections and \begin{...} / \end{...}

### ISSUE THREAD

**Issue by tilmanbauer** [SublimeText/LaTeXTools#691]
With LatTeXTools for Sublime Text 2, build 2221, on Mac OS X 10.11.4, default user settings:

When typing into multiple selections, typing "\begin{" will only open braces at one (the "principal") cursor position instead of all of them. After that, the edited texts under the cursors are out of sync. For instance, erasing the opening brace with a backspace will erase the opening and closing braces at the principal cursor position, while erasing the "n" of "\begin" in the rest.
This seems to happen *only* with "\begin" and "\end" in conjunction with "{". Typing "\emph{" into multiple selections works just fine, as does the nonsensical "\begin[".

**Comment by r-stein** [comment]
@ig0774 I am on this
