### ISSUE TITLE
CTRL+L, backspace not working anymore ?

### ISSUE THREAD

**Issue by skilveg** [SublimeText/LaTeXTools#692]
It seems that the recent update messed with the cleaning tool that deletes auxiliary files. Any hint to correct it ?

**Comment by ig0774** [comment]
I have a vague idea. Do you have anything displayed in your console (`View | Console`) when you try it?

**Comment by skilveg** [comment]
Yes : 
`
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./delete_temp_files.py", line 49, in run
  File "./latextools_utils/cache.py", line 48, in delete_local_cache
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 43: ordinal not in range(128)
`

**Comment by r-stein** [comment]
do you have special chars in your file name/path?

**Comment by r-stein** [comment]
You use ST2?

**Comment by skilveg** [comment]
except for underscores, no. yes, I use ST2.

**Comment by ig0774** [comment]
Does the name of your main document or the path to the main document have an `é` in it? That looks like that's what that error is...

**Comment by r-stein** [comment]
It seems that only a debug message, which causes problems.

**Comment by skilveg** [comment]
Oh ! yes, there's an é in the path to the main document.

**Comment by ig0774** [comment]
Since I'm in rapid fix mode... I just released v3.7.5 which should fix this. @skilveg: can you update and verify it works now?

**Comment by skilveg** [comment]
Yes, it's fixed ! Thanks a lot !
