### ISSUE TITLE
Bibliography not parsed properly

### ISSUE THREAD

**Issue by kursjan** [SublimeText/LaTeXTools#696]
Sublime Text 3, build 3103.

The following bib entry is not parsed properly:
```
@book{bar,
	title={foo},
	url={https://books.google.ch/books?id=bar},
	foo={bar}
}
```

According to my investigation, I guess the KEY regex in `lexer.py` is too greedy. I solved this by forbidding `=` character in the key:
```
KEY                 = re.compile(r'([^\W\d][^,\s=]*)\s*=\s*', re.UNICODE)
```
instead of:
```
KEY                 = re.compile(r'([^\W\d][^,\s]*)\s*=\s*', re.UNICODE)
```

**Comment by ig0774** [comment]
Thanks for this. I've implemented the same thing in v3.7.7.
