### ISSUE TITLE
Converting EPS

### ISSUE THREAD

**Issue by chrispx** [SublimeText/LaTeXTools#7]
Hi,

iIn my case, on OS X 10.7.2 with MacTeX 2011 updated, last SL 2 beta, the compilation does not create pdf's from the eps figures.

Best
Christian

**Comment by jintiangufei** [comment]
Hi,
I am using the sublime3 text's latex. Now i want to use eps files in the pdflatex. Having tried to use your proposed method, it still doesn't work. My latex.sublime_build file is as follows:

/* Let's not preview for now. This should be OK on Win/MikTeX, too (?) */
/* Make sure latexmk is on the $PATH, AND add it to .MacOSX/environment.plist */

{
	"cmd": ["latexmk", 
	"-e", "\\$pdflatex = 'pdflatex %O -shell-escape -file-line-error --max-print-line=200 -synctex=1 %S'",
	"-e", "\\$pdf_previewer = qq{if [ -n \"`ps axww | grep Skim | grep -v grep`\" ] ; then osascript -e 'tell app \"Skim\" to revert front document' ; else open -a Skim %O %S ; fi}",
	//"-e", "\\$pdf_previewer = qq{/Applications/Skim.app/Contents/SharedSupport/displayline -g -r 0 %S}",
	"-pv", "-pdf",  "$file"],
	"working_dir": "$file_path", /* crucial or latexmk will spew stuff in /!!! */
	"file_regex": "^(...*?):([0-9]+): ([0-9]*)([^\\.]+)",
	"selector": "text.tex.latex",
	"path" : "$PATH:/usr/local/bin",

	// Windows-specific command
	// ASSUMES sumatrapdf is default viewer
	// Only problem is that it comes to the foreground
	"windows":
		{
			"cmd": ["texify", "-b", "-p",
			"--tex-option=\"--synctex=1\"", 
			"--tex-option=\"--max-print-line=200\"", 
			"--tex-option=\"-file-line-error\"",
			"--run-viewer",
			"--viewer-option=\"-reuse-instance\"",
			"$file"]
		}
}
Please help me to solve the problem, thanks very much!
