### ISSUE TITLE
v.3.7.7 broke again \cite{

### ISSUE THREAD

**Issue by vor77** [SublimeText/LaTeXTools#701]
Any ideas what's wrong with my biblio plugin. I haven't updated/touched manually to the plugin folder, and let auto-update do its stuff, after the latest update reseted settings and tried with "traditional_bibliography" and with "new_bibliography":

    Bib files found: 
    ...
    Could not find bibliography plugin named t. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named r. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named a. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named d. Please ensure your LaTeXTools.sublime-settings is configured correctly.
     ...
    Could not find bibliography plugin named l. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named _. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named b. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Could not find bibliography plugin named i. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    ...
    Could not find bibliography plugin named y. Please ensure your LaTeXTools.sublime-settings is configured correctly.
    Traceback (most recent call last):
       File ".\sublime_plugin.py", line 362, in run_
       File ".\latex_cite_completions.py", line 743, in run
       File ".\latex_cite_completions.py", line 656, in get_cite_completions
       File ".\latex_cite_completions.py", line 421, in run_plugin_command
    latex_cite_completions.BibPluginError: Could not find a plugin to handle 'get_entries'. See the console for more details

**Comment by jvrsgsty** [comment]
Same here. Opened issue #702 before reading your post.

**Comment by vor77** [comment]
Seems to be fixed in v.3.7.8.
