### ISSUE TITLE
sublime completions

### ISSUE THREAD

**Issue by ppau1** [SublimeText/LaTeXTools#709]
I have some custom completions that I have added to the LATEX.sublime-completions file. The problem is that, periodically, this files are turned into a backup file and a new file is created that does not include my custom completions.

Is there a way to permanently add custom completions?

Thanks!

**Comment by r-stein** [comment]
Just put the completions file, which contains your completions into the `Packages/User` directory.

**Comment by r-stein** [comment]
Since there are no follow up questions I will close this PR.
