### ISSUE TITLE
Can't open file 'evince_backward_search'

### ISSUE THREAD

**Issue by claire2015** [SublimeText/LaTeXTools#710]
When I run `bash ~/.config/sublime-text-3/Packages/LaTeXTools/evince/evince_sync python2 subl xxx.pdf` on my home directory, it shows that

> python2: can't open file 'evince_backward_search': [Errno 2] No such file or directory

But run it under ~/.config/sublime-text-3/Packages/LaTeXTools/evince/, the backward search does works. 
How can I fix this problem ? My system is Debian/GNU Linux.

**Comment by ig0774** [comment]
That's pretty much the expected behaviour. `evince_sync` is meant to be launched from the folder containing the two Python scripts. You could always run it as something like:

```sh
pushd ~/.config/sublime-text-3/Packages/LaTeXTools/evince && evince_sync python2 subl xxx.pdf& && popd
```

Alternatively, I suppose you could add the line `DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)` to the top and change line 23 to:

```sh
$PYTHON "$DIR/evince_backward_search" "$PDFFILE" "$EDITORCMD"&
```

But I don't generally recommend changing things in the LaTeXTools folder, since their liable to be changed on update.

**Comment by claire2015** [comment]
@ig0774 Backward search works perfectly as long as launch `evince_sync` manually. 
But if I jump to PDF from ST3 by `Ctrl+l`, `j`, it won't work at all.
I have no ideal about it >_<

**Comment by ig0774** [comment]
Do you have non-ascii characters in your tex or pdf file name / full path?

**Comment by claire2015** [comment]
Yes, my tex file contains CJK fonts

在2016-05-03 20:34:50，辜琦guqi@whu.edu.cn写道：

Do you have non-ascii characters in your tex or pdf file name / full path?

**Comment by ig0774** [comment]
But are they in the actual file name? The contents shouldn't matter...

**Comment by claire2015** [comment]
@ig0774 My tex file contains CJK fonts

**Comment by claire2015** [comment]
@ig0774 I used English filename.
My gedit + evince can do backward search

**Comment by ig0774** [comment]
I'll have to look into this a bit more.

**Comment by ig0774** [comment]
Quick thing if you wouldn't mind testing: could you open `~/.config/sublime-text-3/Packages/LaTeXTools/viewers/evince_viewer.py` and change line 46 to

```python
        st_binary = 'subl'
```

And see if that helps things...

**Comment by claire2015** [comment]
Nothing has changed

**Comment by ig0774** [comment]
Do you change the Python executable in your `.bashrc` or `.bash_profile` file or modify the path so it might change the Python version used?

**Comment by claire2015** [comment]
@ig0774 
The  Python version is 2.7(default). 
I guess Sublime may not load `jumpto_tex_file.py` correctly when it make forward search.

> DPI scale: 1
startup, version: 3103 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
......
reloading plugin LaTeXTools.00_reload_submodules
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latexFillAll
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_ref_cite_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
plugins loaded
Loading LaTeXTools plugins...
Loaded LaTeXTools plugins [] from path /home/xx/.config/sublime-text-3/Packages/User
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path /home/xx/.config/sublime-text-3/Packages/LaTeXTools/bibliography_plugins
Loaded LaTeXTools plugins ['pdf_builder'] from path /home/xx/.config/sublime-text-3/Packages/LaTeXTools/builders/pdfBuilder.py
Loaded LaTeXTools plugins ['script_builder', 'simple_builder', 'traditional_builder'] from path /home/xx/.config/sublime-text-3/Packages/LaTeXTools/builders
Loaded LaTeXTools plugins [] from path /home/xx/.config/sublime-text-3/Packages/User
Loaded LaTeXTools plugins ['base_viewer'] from path /home/xx/.config/sublime-text-3/Packages/LaTeXTools/viewers/base_viewer.py
Loaded LaTeXTools plugins ['evince_viewer', 'okular_viewer', 'preview_viewer', 'sumatra_viewer', 'skim_viewer', 'command_viewer'] from path /home/xx/.config/sublime-text-3/Packages/LaTeXTools/viewers
Loaded LaTeXTools plugins [] from path /home/xx/.config/sublime-text-3/Packages/User


> True True True
!TEX root =  '/home/xx/stretch/tmp/xxx.tex'
Jump to:  20 31
<class '_latextools_evince_viewer.EvinceViewer'>

**Comment by ig0774** [comment]
No, those are the messages it is supposed to display (`jumpto_tex_file.py` incidentally is entirely unrelated to this; the only bits involved are `jumpToPDF.py`, the `evince_viewer.py`, and the scripts in the `evince` folder).

The real problem I'm having figuring this out is that the backwards search works fine if you launch the script from the shell, which suggests a difference in the shell environment and the environment launching Sublime Text. A way to test whether that's the case would be to close all instances of ST, and launch it from the shell (i.e., open bash and run `subl`), then try the reverse sync. That way it would inherit the same environment as your shell, and that would at least narrow down what to look for.

**Comment by claire2015** [comment]
@ig0774 I have found the problem. Since I need to use fcitx in sublime, I changed  `/usr/bin/subl`  to
```bash
LD_PRELOAD=/opt/sublime_text/libsublime-imfix.so   exec /opt/sublime_text/sublime_text "$@"
```
The lib `libsublime-imfix.so` was compiled via
```bash 
gcc -shared -o libsublime-imfix.so sub-fcitx.c  `pkg-config --libs --cflags gtk+-2.0` -fPIC
```
from source code:
```c
#include <gtk/gtkimcontext.h>
void gtk_im_context_set_client_window (GtkIMContext *context,
         GdkWindow    *window)
{
 GtkIMContextClass *klass;
 g_return_if_fail (GTK_IS_IM_CONTEXT (context));
 klass = GTK_IM_CONTEXT_GET_CLASS (context);
 if (klass->set_client_window)
   klass->set_client_window (context, window);
 g_object_set_data(G_OBJECT(context),"window",window);
 if(!GDK_IS_WINDOW (window))
   return;
 int width = gdk_window_get_width(window);
 int height = gdk_window_get_height(window);
 if(width != 0 && height !=0)
   gtk_im_context_focus_in(context);
}
```
The original `subl` has no problem. Maybe, I should always launch `evince_sync` from shell when use fcitx :sob:

**Comment by ig0774** [comment]
Sorry for the long delay in addressing this. v3.8.4 now uses `subl`, if the version that `subl` reports matches the version of ST running. This should address the issue without needing any special handling on your part, but (since I don't have fcitx and am uncertain I could do more than a smoke test with it anyway) if it doesn't, please feel free to report back and re-open this issue.
