### ISSUE TITLE
Add \subref to automatically bring up references like \cref and \ref

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#718]
I think `\subref` should be added to the list that bring up references automatically. It seems currently only `\cref` and `\ref` work and not sure why `\subref` wouldn't also be added to this list.

**Comment by ig0774** [comment]
See #719. We actually support [all the `\ref` commands mentioned here](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing), but there's no reason not to include others...

**Comment by excetara2** [comment]
Ahh okay yeah `\subref` is from the `subfig` or `subcaption` packages and isn't mentioned there but thanks for adding the commit.
