### ISSUE TITLE
Possible windows 10 bug: Could not find SumatraPDF.exe

### ISSUE THREAD

**Issue by Steiniche** [SublimeText/LaTeXTools#724]
Hello,

In the setup guide it states that SumatraPDF should be on Path and then it should invoke sumatraPDF.exe
However, this is not what currently happens.
When SumatraPDF is on path I can call it through cmd.exe and e.g. setup inverse search.
But when compiling with Sublime Text 3 I get the following error: 
"Could not find SumatraPDF.exe. Please ensure the "sumatra" setting in your LaTeXTools settings is set and points to the location of Sumatra on your computer."

I have tested this with two different Windows 10 machine and I get the same issue.
Specs:
Version 10.0.10586
Sublime Text 3
LaTeXTools v3.7.10
TexLive

**workaround** 
The workaround is to set the full path, in my case: C:\\tools\\SumatraPDF\\sumatraPDF.exe, in LaTexTools.sublime-settings under Sumatra, i.e.

`"windows": {
		// Path used when invoking tex & friends; "" is fine for MiKTeX

		// For TeXlive 2011 (or other years) use

		// "texpath" : "C:\\texlive\\2011\\bin\\win32;$PATH",

		"texpath" : "",

		// TeX distro: "miktex" or "texlive"

		"distro" : "texlive",

		// Command to invoke Sumatra. If blank, "SumatraPDF.exe" is used (it has to be on your PATH)

		"sumatra": "C:\\tools\\sumtraPDF\\sumatraPDF.exe",

		// Command to invoke Sublime Text. Used if the keep_focus toggle is true.

		// If blank, "subl.exe" or "sublime_text.exe" will be used.

		"sublime_executable": "",

		// how long (in seconds) to wait after the jump_to_pdf command completes

		// before switching focus back to Sublime Text. This may need to be

		// adjusted depending on your machine and configuration.

		"keep_focus_delay": 0.5

	},`

If you need anything else don't hesitate to ask and thanks for a great plugin!

**Comment by ig0774** [comment]
So when the guide says "Path" there, it means the "PATH" environment variable. Some reasonable instructions on how to change the PATH environment variable can be found [here](http://www.computerhope.com/issues/ch000549.htm). (I'm sorry if you already did all this, I just want to be sure we are on the same page). If you've changed your environment variable, it may also be necessary to logout and log back in for the change to take effect; at the very least, you will need to restart ST. 

If you want to test something similar to what the plugin tries, do this: from cmd.exe, `cd` to the directory containing your main `.tex` file. From there type `where SumatraPDF.exe`. If you get a result, Sumatra is properly set on your PATH.

In addition, if you use the SumatraPDF installer and install Sumatra to one of the default locations (i.e., `C:\Program Files\SumatraPDF` or `C:\Program Files (x86)\SumatraPDF`), the plugin will find Sumatra automatically.

If you install Sumatra to a non-standard location and don't modify the environment variable, you will have to use the setting, as you did. That is, in fact, why the setting exists.

**Comment by ig0774** [comment]
Hope some of that information helps...

**Comment by Steiniche** [comment]
Thanks for the fast reply!

Yes when i was talking about PATH it was in fact the environment variable PATH.
So we are on the same page :)
If I cd to the location of my main .tex file and the output of  `where sumatraPDF`  is `C:\tools\SumatraPDF\SumatraPDF.exe` which is the correct path.
I have both restarted ST3 and Windows.
However, It still does not work and produce the same error.
It seems like the PATH variable is not read by the plugin?
I have also tried to install sumatraPDF in the defualt location (`C:\Program Files\SumatraPDF`), replace my PATH with this location, and I get the same error.

The only way I can get it to work is by using `"sumatra": "C:\\tools\\sumatraPDF\\sumatraPDF.exe"`

**Comment by ig0774** [comment]
Could you check the environment that's passed to ST? From the console (`View | Console`) type `import os; os.environ['PATH']`. Also, do you have any quotation marks in your `PATH` setting?

**Comment by Steiniche** [comment]
ST3:
>>> import os; os.environ['PATH']
'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;;D:\\tools\\texlive\\2015\\bin\\win32;C:\\tools\\SumatraPDF'

I do not have any quotation marks in my PATH.

**Comment by ig0774** [comment]
One other thing to try from the console: `import subprocess; subprocess.Popen(['SumatraPDF.exe'])`. Also what version of Sumatra do you have?

**Comment by ig0774** [comment]
Aha! I've discovered the source of the error. I'll get this fixed in a new release shortly.

**Comment by Steiniche** [comment]
I am glad to hear and thanks again for a great plugin!

**Comment by ig0774** [comment]
Thanks for the bug report and for sticking with me on that! This is fixed in v3.7.11.
