### ISSUE TITLE
Possible windows 10 bug: Could not find SumatraPDF.exe

### ISSUE THREAD

**Issue by Steiniche** [SublimeText/LaTeXTools#725]
Hello,

In the setup guide it states that SumatraPDF should be on Path and then it should invoke sumatraPDF.exe
However, this is not what currently happens.
When SumatraPDF is on path I can call it through cmd.exe and e.g. setup inverse search.
But when compiling with Sublime Text 3 I get the following error: 
"Could not find SumatraPDF.exe. Please ensure the "sumatra" setting in your LaTeXTools settings is set and points to the location of Sumatra on your computer."

I have tested this with two different Windows 10 machine and I get the same issue.
Specs:
Version 10.0.10586
Sublime Text 3
LaTeXTools v3.7.10
TexLive

**workaround** 
The workaround is to set the full path, in my case: C:\\tools\\SumatraPDF\\sumatraPDF.exe, in LaTexTools.sublime-settings under Sumatra, i.e.

"windows": {
		"texpath" : "", 
		"distro" : "texlive", 
		"sumatra": "C:\\\tools\\\sumtraPDF\\\sumatraPDF.exe", 
		"sublime_executable": "", 
		"keep_focus_delay": 0.5 
},

If you need anything else don't hesitate to ask and thanks for a great plugin!

**Comment by ig0774** [comment]
Closing as this seems to duplicate #724.
