### ISSUE TITLE
Okular support?

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeText/LaTeXTools#728]
Is there any way to add support for Okular? Evince is just awful.

I see there's a patch mentioned here https://github.com/SublimeText/LaTeXTools/issues/658, but it's from several months ago and I don't want to break Latextools applying it to a newer build.

A quick inspection with

    git apply --check 639.patch

shows dozens of errors, which reinforces my fears above.

**Comment by r-stein** [comment]
Okular support has been in https://github.com/SublimeText/LaTeXTools/pull/639. Just add the setting `"viewer": "okular",` to your LaTeXTools settings.

**Comment by Gabriel-p** [comment]
Where should I add that line @r-stein? I see two places where it could go. Under `// General settings`, or in the `// Platform settings: adapt as needed for your machine` block. Curretnly the latter looks like this:

```
	"open_image_command": {
		"linux": [
			{
				// open pdf documents with evince
				"extension": "pdf",
				"command": "evince"
			}
			// uncomment these lines to open all other images with the default programm
			,
			{
				"command": "viewnior"
			}
		]
	},
```

**Comment by ig0774** [comment]
`viewer` is a new setting that was added in the v3.7.x series. It can just go in `General Settings` or you could just copy it from `Preferences | Package Settings | LaTeXTools | Settings – Default (read-only)` to your settings file.

**Comment by ig0774** [comment]
Incidentally, you'll also need to configure Okular to sync with ST using something like `"subl %f:%l"`.

**Comment by Gabriel-p** [comment]
Excellent! I didn't know this had been added already.

@ig0774  I added that command to Okular under the 'Editor' settings. What does it do? Also, I see that the red polygon that encloses in the PDF the text that was under the cursor in the .tex file, is gone.

Should I do something to bring it back?

**Comment by ig0774** [comment]
The command is to pass from Okular to ST, so you can `shift+ left-click` (I think it's `shift`) to go from the PDF to the corresponding line in Sublime.

The red polygon usually disappears when you start interacting with the PDF. You could get it back by redoing the jump (from Sublime, select the appropriate line and press `ctrl+l,j`.

**Comment by Gabriel-p** [comment]
Tried but didn't work. The jump is done to the correct location, but the red polygon is definitely gone. Should I open a new issues about this?

**Comment by ig0774** [comment]
Actually, playing around with it, Okular doesn't supports the red polygon at all. There's not very much we can do about that, though it may be worth tracking [the relevant issue on the Okular bug tracker](https://bugs.kde.org/show_bug.cgi?id=240315).

**Comment by Gabriel-p** [comment]
I just added 10 votes to that issue in Okular.

I'll open another issue regarding how tabs are handled when Okular is used with Latextools, but this one can be safely closed now. Thanks again!
