### ISSUE TITLE
Ref/cite: unrecognized format for every attempted \ref

### ISSUE THREAD

**Issue by JohnPaton** [SublimeText/LaTeXTools#733]
I have recently started getting the Ref/cite: unrecognized format error every time I open a \ref{},or hit ctrl-l,x. This happens even on documents that have no fancy labeling, like the following document:

```
\documentclass{article}
\begin{document}

\begin{equation}
1+1 = 2 \label{mylabel}
\end{equation}

I'll get the error ``Ref/cite: unrecognized format'' as soon as I type 
the opening bracket of \ref{} or try ctrl-l,x.

\end{document}
```

I'm using ST2 on Windows 10, with everything up to date. No other packages other than Bracket Highlighter and Package Control. \cite{} is still working normally, this only happens with \ref{} and its variants (like \eqref{}). The dropdown menu of all my labels also no longer appears, which is quite painful as I'm working on my master's thesis right now, so this is quite painful as there are a lot of labels in the mix. It started happening while I was working on my document, so I don't think it was an update or anything that triggered it, but it is happening across all new and existing documents that I have tried. There are no errors in the console. 
![Screen Cap](https://cloud.githubusercontent.com/assets/18459252/15341918/e0d2b7ae-1c91-11e6-9132-8dc5baf52eeb.PNG)

Update: I restarted my laptop, and the issue persists, however when I opened ST2 I got the following error: "A plugin (latex_cwl_completions) may be making Sublime Test unresponsive by taking too long (11.561000s) in its on_activated callback."

**Comment by ig0774** [comment]
Sorry about that. Should be fixed in the version I just pushed.

**Comment by JohnPaton** [comment]
Wow, that was some quick response time! The new version isn't on Package Control yet, does that just update periodically?

This is an amazing project by the way, you guys have helped me so much. Thank you.

**Comment by ig0774** [comment]
Package Control updates about once an hour, but it should be available shortly. Glad you're finding it useful!

**Comment by JohnPaton** [comment]
And it's fixed. Thanks again!
