### ISSUE TITLE
Create environment with `bit` or `ben` and hitting enter after the first item then an i and [tab] leaves the environment

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#735]
I assume within an `itemize` or `enumerate` and you type an i and then `tab` you probably want an `\item` inserted and not to leave the environment. Maybe due to the snippet system this can't be done as desired and you either have to leave the snippet pressing `esc` or `cmd+enter` to get normal tab behavior or it will always jump out of the environment with tab?

**Comment by r-stein** [comment]
How do you create the `itemize` environment?

**Comment by excetara2** [comment]
By pressing `bit` then tab:

and the result is:
```
  \begin{itemize}
    \item
  \end{itemize}
```
and the cursor moves to after item and then you type
```
  \begin{itemize}
    \item balah blah
    i
  \end{itemize}
```
You hit enter and type i and normally you can tab to get `\item` but it takes you out of the `itemize` because I guess still detecting that it's in the snippet. If you hit `super enter` here instead of `enter` the snippet is ended and it works correctly. Is that clearer?

**Comment by r-stein** [comment]
Yes, that's enough information.

**Comment by r-stein** [comment]
Actually I should have reread the title =). This will be included in the next release.

**Comment by excetara2** [comment]
Okay yeah I saw your improvement for environment and commands so I thought I should mention it.
