### ISSUE TITLE
display problems of the control panel when removing packages

### ISSUE THREAD

**Issue by GeekMe93** [SublimeText/LaTeXTools#737]
System: MaxOX

Description: 

Shit + cmd + p --> remove package, then there will be a display problems, as shown in uploaded figure. This problem disappear when scroll down using down arrow.
![screenshot 2016-05-20 03 22 12](https://cloud.githubusercontent.com/assets/15790176/15406817/92018e8e-1e3a-11e6-8b32-e3e4c9ef5b95.png)

**Comment by ig0774** [comment]
This seems to be a bug for [Sublime itself](https://github.com/SublimeTextIssues/Core) or possibly [PackageControl](https://github.com/wbond/package_control) where the "remove package" command comes from. I'm not quite sure why you opened it here, unless, perhaps, it goes away when you disable LaTeXTools?
