### ISSUE TITLE
Support multiple refs in `\cref` and similar commands

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#741]
When you type a , in `\cite` it recognizes you are using multiple citations but this same behaviour isn't included for using multiple references. If you type `\cref{ch:blah,}` and then manually try to bring up the quick panel with all the refernces it throws an error saying no reference of `ch:blah,`.

**Comment by excetara2** [comment]
So I guess this was never implemented then. I thought it might be a bug in my system so wanted to check.

**Comment by ig0774** [comment]
No... It's unimplemented. `\ref` and most similar commands don't actually support multiple labels.

**Comment by excetara2** [comment]
Yeah that's true I think the others that I know are `autoref`, `varioref`, and `fancyref` that allow multiple citations.

**Comment by ig0774** [comment]
I've implemented support for this in #782. As far as I was able to confirm, there's only a limited number of commands that actually support commas in refs, `\cref`, `\Cref`, `\cpageref` and `\Cpageref`. This is an extension `cleveref` adds to references; normally `,` is actually allowable in a label name. As far as I can tell, no other reference commands get patched for this.

**Comment by ig0774** [comment]
Released in v3.10.0. Thanks for the suggestion.

**Comment by excetara2** [comment]
Awesome! Give it a try soon.
