### ISSUE TITLE
COULD NOT COMPILE

### ISSUE THREAD

**Issue by klonuo** [SublimeText/LaTeXTools#744]
I installed this plugin and when trying to build I get this error:

```
TraditionalBuilder: Engine: pdflatex. Invoking texify... 

COULD NOT COMPILE!

Attempted command:texify -b -p --engine=pdftex --tex-option="--synctex=1" UQ_Handbook_Chapter.tex
Build engine: Traditional Builder
```

Searching the issues suggests running reconfigure script, but I dont see such script. Any ideas?

I run Windows 10 with MikTex

**Comment by r-stein** [comment]
Open the ST console ``ctrl+` `` to see the internal error. If you show us this error we can provide a better error description/solution.

**Comment by klonuo** [comment]
Thanks. It turned out it can not find texify.

I added Miktex bin to PATH after I installed this plugin. Running texify in Windows console executes fine.
I thought that running Latextools build command would pick up new PATH, but it shows that I needed to restart Sublime Text, for some reason.

**Comment by r-stein** [comment]
To clearify: LaTeXTools runs inside Sublime Text and uses the environment variables of Sublime Text.
