### ISSUE TITLE
Is there any way to have self-defined math scope

### ISSUE THREAD

**Issue by Joshua1989** [SublimeText/LaTeXTools#748]
I use Latex to write concrete derivations so often I have equations which are half-page long. And I found backward search from Skim doesn't work perfectly for 'align' environment: the cursor jumps to the end of 'align' environment instead of the correct line.

So I tried some alternatives:
1. 'equation'+'aligned': backward search works perfect, but I cannot easily control equation numbering for each line.
2. 'eqnarray': backward search works perfect, can control equation numbering for each line, however it seems there are many drawbacks for this environment, many StackExchange answers recommend to avoid using it
3. 'IEEEeqnarray': similar to 'eqnarray' but with no drawbacks, seems it is a perfect solution

However, when I use 'IEEEeqnarray' environment, latextools doesn't recognize it as a math environment, and thus I cannot use all auto-complete command and snippets for math environment.
Is there any way to make latextools to recognize a self-defined environment as math environment?

**Comment by r-stein** [comment]
Do you use ST2 or ST3?

**Comment by Joshua1989** [comment]
I am using ST3 now

**Comment by Joshua1989** [comment]
Problem solved, actually we only need to modify the scope "string.other.math.block.environment.latex".
My case is on Mac for ST3:

1. Use PackageControl to install PackageResourceViewer
2. Press cmd+shift+P, PackageResourceViewer --> Extract Package --> Latex (not Latextools)
3. On menu Sublime Text --> Preference --> Browse Packages, in Packages/Latex folder open file named LaTeX.sublime-syntax
4. Find the line "| split|gather|gathered" and change it to "| split|gather|gathered|IEEEeqnarray"

Done!
For ST2 on Mac I think we can directly start from step 3

**Comment by r-stein** [comment]
Exactly. Just keep in mind, that the LaTeX syntax is currently rewritten and you might want to repeat it after the next Sublime Text Update to get the new syntax.
