### ISSUE TITLE
LaTeXtools could not parse the TeX log file (actually, we never should have gotten here)

### ISSUE THREAD

**Issue by galvaniccoffee** [SublimeText/LaTeXTools#750]
Like others, I run into this error. For me, the cause seems to be using the `gnuplottex` package. 

```
[Compiling /foo/bar.tex]

TraditionalBuilder: Engine: pdflatex. Invoking latexmk... done.


LaTeXtools could not parse the TeX log file
(actually, we never should have gotten here)

Python exception: IndexError('string index out of range',)

Please let me know on GitHub. Thanks!

[Done!]
```
[Here](http://krams.jannisbecker.de/szintillationszaehler.log) is a `.log` file causing the error.

Also, sometimes, after deleting all temporary files, I get an actual error instead:
```
/usr/share/texlive/texmf-dist/tex/latex/gnuplottex/gnuplottex.sty:79: Argument of " has an extra }. [...te\write18{rm -f "\jobname.gnuploterrors"}]
/usr/share/texlive/texmf-dist/tex/latex/gnuplottex/gnuplottex.sty:79: Paragraph ended before " was complete. [...te\write18{rm -f "\jobname.gnuploterrors"}]
```
[Apperantly, this one is caused by `gnuplottex`](http://tex.stackexchange.com/questions/305957/gnuplottex-package-not-working-anymore), but might be related to the original one.

**Comment by ig0774** [comment]
Thanks for reporting this bug. It's been addressed in the latest version.
