### ISSUE TITLE
Faster \cite list with large bibtex file? 

### ISSUE THREAD

**Issue by tlepoint** [SublimeText/LaTeXTools#752]
Hi,

When we have a really large bibliography in bibtex (eg. https://github.com/cryptobib/export), everytime we want to cite something, SublimeText freezes a few seconds, and then works perfectly. I completely understand the first freeze to cache the bibliography, but since it happens everytime, this suggests that most of the time in not spent in the caching, or that the caching is done everytime.

I don't know where to look in this plugin, and does anyone has any idea if things could be speeded up?

Thanks!

**Comment by r-stein** [comment]
Thanks for the report, this will be fixed soon.

**Comment by r-stein** [comment]
This should is fixed in `v3.8.3`, feel free to reopen if the issue persists.
