### ISSUE TITLE
Comma separated list of filenames in \bibliography command overwritten with auto-complete

### ISSUE THREAD

**Issue by gregongie** [SublimeText/LaTeXTools#753]
When I try to include multiple .bib files in the \bibliography command, the previous filename gets overwritten. For example, if I want to include both refs1.bib and refs2.bib, adding refs1 from the dropdown works fine and I get:
`\bibliography{refs1}`
But when I try and add refs2 via the drop-down list, I get
`\bibliography{rrefs2}`
rather than
`\bibliography{refs1,refs2}`

I'm using Sublime build 3083 and LaTeXTools v3.8.2 (2016-06-19).

**Comment by r-stein** [comment]
Thanks this will be fixed soon.

**Comment by r-stein** [comment]
This should is fixed in `v3.8.3`, feel free to reopen if the issue persists.

**Comment by gregongie** [comment]
Just got the update. Works great! Thanks!

Greg
