### ISSUE TITLE
Feature request: Automaticly remove temporary files after build

### ISSUE THREAD

**Issue by galvaniccoffee** [SublimeText/LaTeXTools#754]
Hey!

I really like the feature to remove all generated temporary files (`Strg` + `L`, `Backspace`).
An option to execute it automatically after every build would be pretty nice, similar to the `cleanup` option of the `gnuplottex` package.

**Comment by ig0774** [comment]
This request was already made in #323. We're aware it's a request, I'm just not convinced it's a good idea. My suggestion if you simply don't want to see the aux files, etc. I'd recommend using the `output_directory` option with the value `<<cache>>` (new feature in v3.8.x), which will keep the generated files around (faster rebuilds, etc.) but they'll be out of the way.

**Comment by galvaniccoffee** [comment]
Ah, this works for me, too. Thank you! :smile: 

Where does it save the files, by the way?

**Comment by ig0774** [comment]
In a sub-folder of the LaTeXTools folder in Sublime Text cache directory (assuming you're using ST3). The specific folder name is the MD5 hash of the full path of the main file of your document, which can make it a bit hard to find. It gets logged to the console when you run a build.

**Comment by galvaniccoffee** [comment]
Ah, interesting! Thanks again!

**Comment by zachsa** [comment]
I see this issue is closed, and i don't want to re-open it (I think). I'd like the same as the author. when i change output_directory to <<cache>> or <<temp>>, my .bib file can't be found.

**Comment by ig0774** [comment]
If you use `<>`, it will try to write to a directory called `<>` that is a sub directory of the directory containing your main file. If your OS doesn't allow `<>` as a directory name (e.g. Windows), then the output files won't be created and the build will fail. You have to either use one of the LaTeXTools-defined special strings, e.g., `<<cache>>` or the name of a valid path for your OS.

**Comment by Iorent** [comment]
Hi, I got a problem. When I use an absolute path to store the temporary files, it did not work. I mean, the compile will work, but the temp files are still in the same directory with .tex and .pdf files.

**Comment by r-stein** [comment]
@Iorent Does wit work with e.g. `<<temp>>`? If you are on windows you need to escape `\ `, i.e. use `\\` instead.

**Comment by Iorent** [comment]
@r-stein No, I tried the five options, neither of them works. The compile will work, but all the temporary files are still in the same folder with .tex and .pdf. Yeah, my OS is windows, and I use \\ instead of \ when specifying the directory. By the way, I am using MiKTeX 2.9+ST 3143.

**Comment by Iorent** [comment]
@r-stein I surely use `\\` instead `\` to specify the directory

**Comment by r-stein** [comment]
@Iorent If I am not mistaken output_directory is only supported by TeXLive and aux_directory by MikTeX. So it should not work if you are using windows and MikTeX.

**Comment by Iorent** [comment]
@r-stein Ok. Thanks for the explanation. I am wondering are there some technical difficulties that the two functions cannot be fulfilled in the same compiler? (sorry, I am not majored in CS) I think someone shares the same feeling with me, that we want the folder just shows two files: *.tex & *.pdf, the other files could exist at other place or just be hidden.

**Comment by r-stein** [comment]
I have no deep knowledge in that topic, but they are slightly different compilers. That's a valid request, but I don't think we are currently supporting that on windows with MiKTeX and I don't think we are going to work around this, because it needs a lot of work to be compatible with the included paths/files etc. .

**Comment by Iorent** [comment]
Thanks for your patience. Anyway, LaTeXTools works fun for me.

**Comment by ig0774** [comment]
If you leave `output_directory` unset and use `aux_directory` it should behave as you seem to want. If you set both of them, then PDF files will be directed to the `output_directory`.

**Comment by Iorent** [comment]
@ig0774  here is the situation. I leave `output_directory` unset and use absolute path in `aux_directory`, but nothing changed. all the files are still in the same folder after compiling. I think I did that under the construction and your suggestion. the absolute path looks like this `"aux_directory": "D:\\path",`

**Comment by ig0774** [comment]
@lorent: which builder are you using? You need to use the `basic` builder or configure the `traditional` builder to use `latexmk`.

**Comment by Iorent** [comment]
I am using MiKTeX 2.9+ST 3143. what does that mean by using `basic` or `traditional` builder? Is `latexmk`  another editor like ST?

**Comment by r-stein** [comment]
You can change the builder in the [settings](https://github.com/SublimeText/LaTeXTools/blob/st3-3.14.2/LaTeXTools.sublime-settings#L386). The differences are described there in a technical way. In general the traditional builder uses a smart compilation way provided by your tex distribution and in the basic builder we try to provide a smart compilation (which programs should be called and how often, based on the output of the previous program) by ourself. Therefore some features only work in the basic builder, because we have more control there.

**Comment by Iorent** [comment]
@r-stein That is a lot of coding. I will research and try to change the setting later on. Anyway, I appreciate your help and patience. Thanks.
