### ISSUE TITLE
Feature Request: Search in complete author field using \citet{

### ISSUE THREAD

**Issue by josndr** [SublimeText/LaTeXTools#756]
I recently noticed that it is impossible when using \cite{ to search for coauthors of a paper in the bibfile if the pop-up lists it as et al. It would be great if it was possible to let the search engine run through the author-field within the bib file rather than the abbreviation displayed. I'd appreciate if there is a way to incorporate this in a future release

**Comment by ig0774** [comment]
See [my comment on #687](https://github.com/SublimeText/LaTeXTools/issues/687#issuecomment-212105113) for a way to do this.

**Comment by josndr** [comment]
I should have been more specific. I have the ''author'' field. The quick panel also shows all authors in the second line. However the search engine is not able to find them.

To make this point clear. Suppose I have an entry with three entries in author, that is 
`Author:{John Doe, Jane Duh, Jack Dough}
Title:{Cute Title}`.

Then the quick panel shows for that entry:
First line: Doe et. al - Cute Title
Second line: John Doe, Jane Duh, Jack Dough

Searching for Duh gives no result.

**Comment by r-stein** [comment]
The match engine only uses the first line, hence you need to include it there. Since this is build into sublime we cannot do anything about it.
