### ISSUE TITLE
traditionalBibliography & multi line authors

### ISSUE THREAD

**Issue by tlepoint** [SublimeText/LaTeXTools#758]
Hi,

When using [cryptobib](https://github.com/cryptobib/export), a widely used (and large!) bib file used in cryptography, and setting {author} in the "cite_panel_format" of the setting, I get only one author.

Indeed, in the bib file, the entries have authors on several lines, which is explicitly unsupported in traditionalBibliography.py. Is there an easy way to support this?

Thanks!

**Comment by r-stein** [comment]
As you mentioned the `traditional_bibliography` operates per line. This is not perfect, but is robust and works in the most cases.
The way to support this would be using the `new_bibliography`, but as you already notices it still has to improve to support all bib files.

**Comment by tlepoint** [comment]
Fair enough. 

Thanks for the answer, I'll see if I can help improve `new_bibliography`.
