### ISSUE TITLE
autocomplete for some math env

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#767]
Hi there,

I moved to ST3 + LaTexTools + Skim platform to write my papers recently. I need to use some math environments such as  
\begin{lemma}
\end{lemma}   
\begin{theorem}, \begin{proof}...

I found there is no candidate items for these environments. Is that possible to add these environments into autocomplete list? or any other alternative solutions are welcome.

Thanks

**Comment by r-stein** [comment]
If you open the LaTeXTools settings there is a settings `cwl_list`, which contains the cwl files used to extract the completion. Since `proof` is defined by `amsthm` you can include add that to the list. You define `lemma` on your own?

**Comment by shouwei** [comment]
@r-stein 
thank you! I used the LNCS style. \documentclass{llncs}. Somehow, it is defined by myself.
One more question, do I need to download these cwl files or they are already integrated with latextools.

**Comment by r-stein** [comment]
You need to install the [LaTeX-cwl](https://github.com/LaTeXing/LaTeX-cwl) package (and restart Sublime Text).
If you want to use your own completions just open `Preferences >> Browse Packages...` and create a folder `LaTeX-cwl`. Afterwards inside the folder create a file `custom.cwl` and add your commands to it similar to the other cwl files in the package. Add it to your `cwl_list` and the commands will be parsed from it.

@ig0774 it might be useful to additonally look inside the folder `User/LaTeX-cwl` for cwl files.

**Comment by shouwei** [comment]
@r-stein 
Thank you so much! 
I will try later. :-)

**Comment by ig0774** [comment]
@r-stein: Indeed that seems very useful.

**Comment by ig0774** [comment]
#623 now supports cwl files in the `Packages/User/cwl` directory.
