### ISSUE TITLE
Sharing completions

### ISSUE THREAD

**Issue by xbelt** [SublimeText/LaTeXTools#770]
Is there a way to share the changes I made to LaTeX.sublime-completions?
Maybe a Wiki entry which could be edited or something like that?

**Comment by ig0774** [comment]
We have a [Wiki](https://github.com/SublimeText/LaTeXTools/wiki) you could use thanks to Github. Or, if you think they may be generally useful, we also take [pull requests](https://github.com/SublimeText/LaTeXTools/pulls).
