### ISSUE TITLE
latextools does not copy bib files correctly to project folderrs

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#783]
If you have multiple `\addbibresource{}`  and are using a project folder, sublime latex tools does not properly copy the bib files

Same problem when you use
`\begin{refsection}[articles.bib]
\end{refsection}
`

**Comment by ig0774** [comment]
Could you explain a bit more clearly what is happening versus what you expect to happen? I'd note (if this changes things) that new `\addbibresource{}` and similar commands are only detected once the file is saved, but that's the only thing I can think of...

**Comment by musm** [comment]
Sorry for the noise. I couldn't reproduce using a  minimal example. The trick was to restart the computer to get everything to work for my project.
