### ISSUE TITLE
Breaks alt-dragging for deselecting text

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/LaTeXTools#784]
The "jump to anywhere" addition in https://github.com/SublimeText/LaTeXTools/pull/683 breaks the ability to alt-drag on text to subtract from a selection or remove it entirely. (On Windows.)

Please revert the mouse mapping change.

**Comment by r-stein** [comment]
Do you know the difference between `alt+shift` drag and `alt` drag?

I used the same mouse bindings as [SublimeCodeIntel](https://packagecontrol.io/packages/SublimeCodeIntel), so it would be untuitive and already used by most users. However we could easily make it opt-in via the `Create mousemap in user folder` command.

**Comment by FichteFoll** [comment]
alt+shift dragging by itself works like just alt, it seems, but additionally it removes one or more selections on the initial click. I can't figure out how it works exactly though.

Anyway, you can restore the original behavior by adding `        "press_args": {"subtractive": true}
` to the mousmap entry, which is what the initial binding contains. That makes dragging work again while still allowing to capture alt+click events.

I don't use SublimeCodeIntel, but that should be affected by this as well. cc @Kronuz

**Comment by r-stein** [comment]
Okay that seems to be useful.

Now we can keep the old behavior and catch the event. Afterwards check whether we want to change the selection and to the jump. This could be opt-out/opt-in via settings.

**Comment by r-stein** [comment]
On the hindsight it might be the best to use a free mousebinding and change it if the user manually ports the mousebinding and SublimeCodeIntel is installed.

**Comment by r-stein** [comment]
Fixed in `v3.9.3`
