### ISSUE TITLE
aux/output-directory ignored

### ISSUE THREAD

**Issue by godey4me** [SublimeText/LaTeXTools#787]
Hi,
First thanks for this awesome plugin. 
 
I have been trying to get latextools to write the aux and output files in certain directory to no avail.
These are the options I have tried according to the documentation.

- edit the user settings with `"aux_directory": "./output",` and `"output_directory": "./output",`

- Add these lines to to the project  file ` "output_directory" ="./output",` and ` "aux_directory" = "./output",`

- Similarly added ` %!TEX aux_directory = ./output"` and `%!TEX output_directory = ./output` to the first line of the main file.

In all these the aux and output files are outputted into the main directory where the main file is. 
What am I doing wrong?
Thank you

**Comment by ig0774** [comment]
I'm guessing you're using MiKTeX, in which case you need to use the "basic" builder which can be set in your settings. Btw, if you want aux and output files to end up in the same place, just specify the `output_directory`.

**Comment by godey4me** [comment]
wow!! thank you very much. I have being pulling my hair all morning. 


/PS I was using the simple builder for a long time because my references were not appearing when I used the traditional builder. There wasn't a basic option then. Now when I use the basic builder I run into the same issue of references not appearing in the final pdf. How can I use the output directory with the simple builder? 


Thank you.
