### ISSUE TITLE
Autocompletion Popup Too Small

### ISSUE THREAD

**Issue by kgizdov** [SublimeText/LaTeXTools#790]
Hi,

I have the following problem - the autocompletion popup is too small for some autocompletion suggestions, mostly commands. For references (\cite{}) it seems to resize and shift the text so that all can be read, but for syntax autocompletion some of the commands do not fit inside the popup. I am seeing this issue on any size monitor and even on HiDPI laptop screen.

I've previously used LaTeXing and it seemed to work fine there, but that was a long time ago, so I can't be sure why this is the case. Can we have the box resize as for the bib entries or at least enlarge it a bit, so we notice it less.

Thanks.

**Comment by ig0774** [comment]
The autocompletion pop-up isn't programmatically resizable and, unfortunately, sometimes long commands are going to exceed it's size. There's not much we can do about that. We can probably shorten some of the completions, though, which might alleviate the problem.

**Comment by kgizdov** [comment]
OK, but I still think we are missing something. This is what I mean. I just tested LaTeXing:
![latexing2](https://cloud.githubusercontent.com/assets/3164953/17104884/c5021aee-527c-11e6-8059-890979cf077b.gif)

And LaTeXTools:
![latextools](https://cloud.githubusercontent.com/assets/3164953/17104887/c834cfc2-527c-11e6-9d25-0c22463ac271.gif)

Notice how the popup has a bigger fixed size and alignment in side for LaTeXing, whereas the LaTeXTools one looks to autoresize and is too small.

**Comment by r-stein** [comment]
It seems to be relevant in which order the items are inserted into the autocompletion menu. Based on a few tries the size seems to extracted from entries, which are visible at the start. Hence this could be solved by changing the order.

If you add this:
``` js
"cwl_list": [
	"latex-document.cwl",
	"tex.cwl",
	"latex-209.cwl",
	"latex-l2tabu.cwl",
	"latex-mathsymbols.cwl"
],
```
to your `LaTeXTools.sublime-settings` the size of the completions should increase.

**Comment by ig0774** [comment]
I redid the default order as @r-stein suggested in v3.10.0. However, I'm not entirely sure if this fixes this issue for you, so could you try it out and see if this fixes things?

**Comment by kgizdov** [comment]
I works great now. Thanks.
