### ISSUE TITLE
includegraphics filename autocompletion fuzzy matching is too insistent, won't go away with enter, swallows input on escape

### ISSUE THREAD

**Issue by michaelpacer** [SublimeText/LaTeXTools#793]
When you type `\includegraphics{` and you try to type something that it is unable to fuzzily match with anything in the directories it searches, the dialog box ceases to show any options. 

This includes if you type a file name that for some reason it does not know how to find (e.g., if its symlinked). 

as a result if you type out something that is a valid filename and hit enter, it won't select what you have written and place it in the text. Worse, even if you press enter repeatedly, the popup dialog will not go away.

You have to separately escape it and then hope that you copied and pasted what you already wrote because if you didn't its gone.

**Comment by r-stein** [comment]
The ST quickpanel can only used to select predefined entries. Hence you cannot write your own path. You could alternatively cancel the quickpanel and use the autocompletion, which also provides the file paths.

**Comment by ig0774** [comment]
I'm closing this because, as @r-stein indicated, the requested behaviour cannot be (sanely) implemented. The correct option is to either a) cancel the quick panel (using `esc`) or b) disable the quick panel altogether via the toggle `fill all auto` in the menu triggered by `C-l,t,?`
