### ISSUE TITLE
Inline previews for images, section titles, and equations

### ISSUE THREAD

**Issue by 315234** [SublimeText/LaTeXTools#794]
I have a bit of very hacky code to show inline images and section titles, and also to show rendered equations on hover. There are a couple of settings that can be configured for setting a preamble file, and `pdfcrop` binary location etc. You can see it here, with a screenshot of the results:

https://github.com/315234/LatexExtensions

It is currently very buggy, but perhaps some features like this could be included in this package. I'd be happy for my code to be used as a starting point, or even to tidy it up to meet any contribution requirements of this package.

**Comment by r-stein** [comment]
Thanks. Actually I am already working on phantom an hover-popup previews for images and math modes https://github.com/SublimeText/LaTeXTools/pull/785.

Image phantom (and also popups) would look like this:
![image](https://cloud.githubusercontent.com/assets/12573621/17191378/062d4a38-544a-11e6-8b17-b5bf92b8c78f.png)

Also I have a quite promising way to live preview math with phantoms (current state):
![lt_math_live_preview](https://cloud.githubusercontent.com/assets/12573621/17296688/c1995ec2-5802-11e6-9bee-8b38d900dbdb.gif)

In the future it might also be useful for tikz. However I don't see a reason to preview sections titles.

Thanks, I will take inspirations from your code. If you want to I will push my current status and you can participate in the pull requests.

**Comment by 315234** [comment]
Very nice! Looks like you're already a few steps ahead of my implementation.

Perhaps you could benefit from the colour extraction code, which sets appropriate the foreground and background colours for the generated png.

The rationale for previewing section headers is for readability. When working on a large latex file with many sections, the start of each section is clearly highlighted in large text, which helps to break up the document and makes skimming to the correct place much easier.

**Comment by r-stein** [comment]
Actually the [mdpopups](http://facelessuser.github.io/sublime-markdown-popups/usage/#tint_raw) library contains methods for color scope extractions and image tinting.

I agree, that it could be useful to emphasize sections via phantoms.

**Comment by r-stein** [comment]
Images and equations has been added in `v3.12.0`. I will close this issue, but you can create an issue or PR for sections.
