### ISSUE TITLE
Error on updating to v3.10.1

### ISSUE THREAD

**Issue by jrappen** [SublimeText/LaTeXTools#798]
`Package Control: Upgraded LaTeXTools to 3.10.1`

![screenshot](https://cloud.githubusercontent.com/assets/8577450/17415147/ccb6d77a-5a88-11e6-8715-514fd94f505f.png)

Gives error on loading `Default (Windows).sublime-keymap:405:1`.

**Comment by msiniscalchi** [comment]
There is a missing ']' at the very end of Default (Windows).sublime-keymap. That's what's triggering the error (I just saw that too). Emergency patch @ig0774 and @r-stein ? (I don't have a dev environment installed on my current machine at work, sorry).

**Comment by ig0774** [comment]
Sorry about that... Looks like I deleted too much in a commit. I've pushed a release with the necessary `]` which should be available on PackageControl shortly.
