### ISSUE TITLE
Log files did not report if \ref{} item is not exist

### ISSUE THREAD

**Issue by wanpengli** [SublimeText/LaTeXTools#799]
I had a figure to include in my thesis, while I was focusing on the content of my thesis, so I just use \ref{somefirge} in the code, to remind myself I will comeback to add the figure to the thesis.

But the log file now did not report a warning for this misuse of \ref{}

Hope it can be fixed.

**Comment by ig0774** [comment]
I'd love to help you out with this, but I can't reproduce the error. For example, the following document:

```latex
\documentclass{article}
\begin{document}
\ref{nothing}
\end{document}
```

Shows me the warning:

```
Reference `nothing' on page 1 undefined on input line 3.
```

Can you include a MWE that shows the issue?

**Comment by wanpengli** [comment]
Hi many thanks for you email.

I divide my thesis chapters into different .tex files. at the moment, the behaviour of Laxtextools is really strange.

I also report another issue, which redirect_uri can pass through the compile.

I attached a working example in this email.

The code is at the beginning of the introduction document.
I got this from the log:

[Compiling /Users/lamp_lee/Desktop/untitled folder/Thesis.tex]

SimpleBuilder: pdflatex run 1; done.

No errors. Warnings:

/usr/local/texlive/2015/texmf-dist/tex/latex/svn-multi/svn-multi.sty:930: Package currfile Warning: File stack underflow! on input line 930.
[no file]: Package pgfplots Warning: running in backwards compatibility mode (unsuitable tick labels; missing features). Consider writing \pgfplotsset{compat=1.12} into your preamble.
[no file]: destination with the same identifier (name{page.1}) has been already used, duplicate ignored
[no file]: destination with the same identifier (name{page.2}) has been already used, duplicate ignored
(Log parsing issues. Disregard unless something else is wrong.)


Kind regards
Wanpeng

**Comment by wanpengli** [comment]
[untitled folder 2.zip](https://github.com/SublimeText/LaTeXTools/files/404178/untitled.folder.2.zip)

**Comment by ig0774** [comment]
Ah. I think it might be the log parsing issue that's causing the messages to disappear from the log. I just caught this myself. It's been fixed in v3.10.4. With v3.10.4, I get these messages in the console:

```
[Compiling /Users/lamp_lee/Desktop/untitled folder/Thesis.tex]

SimpleBuilder:
pdflatex run 1;
bibtex run 1;
pdflatex run 2;
pdflatex run 3;
done.

Errors:

/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex:20: Missing $ inserted. [redirect_]
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex:21: Missing $ inserted. []

Warnings:

/Users/lamp_lee/Desktop/untitled folder/Thesis.tex: Package pgfplots Warning: running in backwards compatibility mode (unsuitable tick labels; missing features). Consider writing \pgfplotsset{compat=1.13} into your preamble.
/Users/lamp_lee/Desktop/untitled folder/FrontMatter/TitlePage.tex: destination with the same identifier (name{page.1}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/FrontMatter/TitlePage.tex: destination with the same identifier (name{page.2}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex:19: LaTeX Warning: Reference `fig:hello' on page 1 undefined on input line 19.
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex: destination with the same identifier (name{page.1}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex: destination with the same identifier (name{page.2}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Algorithms/Naive_Random_Graph.tex: destination with the same identifier (name{page.3}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Algorithms/Naive_Random_Graph.tex: destination with the same identifier (name{page.4}) has been already used, duplicate ignored
/Users/lamp_lee/Desktop/untitled folder/MainMatter/Introduction.tex: LaTeX Warning: There were undefined references.
(Log parsing issues. Disregard unless something else is wrong.)

Bad Boxes:

/Users/lamp_lee/Desktop/untitled folder/FrontMatter/Dedication.tex:26: Underfull \hbox (badness 10000) in paragraph at lines 26--29
/Users/lamp_lee/Desktop/untitled folder/FrontMatter/Dedication.tex:30: Underfull \hbox (badness 10000) in paragraph at lines 30--31
/Users/lamp_lee/Desktop/untitled folder/FrontMatter/Dedication.tex:32: Underfull \hbox (badness 10000) in paragraph at lines 32--33
/Users/lamp_lee/Desktop/untitled folder/FrontMatter/Dedication.tex:34: Underfull \hbox (badness 10000) in paragraph at lines 34--36

[Done!]
```

Which I assume is closer to what you were expecting?

**Comment by wanpengli** [comment]
yep, I can not really work using the current version, so I just replace it with an older version. which is the stupid but fastest fix.

**Comment by ig0774** [comment]
When you get a chance could you give it a try with 3.10.4 and see if the issue is resolved? Thanks for your patience...
