### ISSUE TITLE
The strange behaviour when compiling 

### ISSUE THREAD

**Issue by wanpengli** [SublimeText/LaTeXTools#801]
when input redirect_uri in .tex source file, this should be regarded as an error, however,

it successfully pass the compiling process and produce something like 
<img width="85" alt="screen shot 2016-08-05 at 16 30 44" src="https://cloud.githubusercontent.com/assets/20861228/17441658/023fc4aa-5b2a-11e6-9b52-881d05d84224.png">

this new update really affects my normal life, can someone give me a former version. I wanna scroll back to the previous latex tools version.

**Comment by ig0774** [comment]
It seems like you've entered that in [math mode](https://en.wikibooks.org/wiki/LaTeX/Mathematics#Mathematics_environments) rather than in letter mode. In normal mode, `_` produces an error, but it doesn't in math mode. This is a LaTeX feature and there's not much we can do to work around it...

**Comment by wanpengli** [comment]
It's not in math mode. I already sent the code templates to your email.

**Comment by ig0774** [comment]
I'm closing this in favour of #799 because they seem to be tied to the same issue rather than being two separate issues.
