### ISSUE TITLE
An error occurred while trying to run kpsewhich. TEXMF tree could not be accessed.

### ISSUE THREAD

**Issue by jcramer3** [SublimeText/LaTeXTools#806]
In all my documents, I suddenly got this error when typing \cite{. 
The autocomplete function worked before. Also, the citations are correctly listed in the biography.
What should I do to solve this issue? Thanks in advance!

**Comment by r-stein** [comment]
Can you paste the log from the ST console ``ctrl+` ``?

**Comment by jcramer3** [comment]
Yes, it gives this:

Running kpsewhich -format=mlbib Remote.bib
error: An error occurred while trying to run kpsewhich. TEXMF tree could not be accessed.
Bib files found: 
[]
error: No bib files found!

**Comment by r-stein** [comment]
The bibliography file is in the same folder as the tex root or do you get it from somewhere else?

**Comment by jcramer3** [comment]
It is in the same folder for some texts. For others I add the folder (e.g.: \bibliography{ch_2_methods/ch_2_methods}).

This all worked until yesterday. I tried it with an old version from my backup and it gave the same problems so I guess it could be an update of the package?

**Comment by r-stein** [comment]
LaTeXTools did some changes to cite completions in the last release. However this part should not have changed. In general it searches for all `\bibliography` commands and searches the file relative to the tex root and runs `kpsewhich`, if it is not present. Hence it should not run kpsewhich`, if the file is in the same folder as the tex root.

Can you open the ST console and write:
``` py
import LaTeXTools; LaTeXTools.getTeXRoot.get_tex_root(view)
```
This should give the correct tex root.

**Comment by jcramer3** [comment]
Thanks that answered the question! The root of each document is its own root so I should not add the folder (\bibliography{ch_2_methods/ch_2_methods} should be \bibliography{ch_2_methods}).
Thank you!!

**Comment by r-stein** [comment]
Everything works now?

**Comment by jcramer3** [comment]
yup :) thanks!
