### ISSUE TITLE
cannot input '{' after \input or \include

### ISSUE THREAD

**Issue by swun90** [SublimeText/LaTeXTools#809]
Quite strange, but I cannot input a left curly brace `{` after `\input` or `\include`, whether there's space or not.
And only in `.tex` file, never happen in other files.

**Comment by r-stein** [comment]
Does the ST console ``ctrl+` `` show any errors and does it work after `\ref` and `\cite`?

**Comment by ig0774** [comment]
This appears to have been fixed in the comments of #816. The underlying cause was a local keymaping defined in the keymap file in the User package. Once those bindings were removed, the problem seems to have been resolved.
