### ISSUE TITLE
Is that possible to set "aux_directory" option on OSX

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#812]
Hi there,

Is that possible to set the "aux_directory" option on OSX?

Based on the information provided in README, it seems possible. But I do not know where is the "copy_on_build" settings, and how to configure it. Does anyone have an example?

Thanks
-----------------------------------------------------------------------------------------
Output Directory and Auxiliary Directory

The --output-directory and --aux-directory flags can be set in several ways:

Using a TEX directive, such as %!TEX output_directory = <path> near the top of the file.
Using the TeX Options feature to set --output-directory and / or --aux-directory.
Using the corresponding output_directory and aux_directory settings detailed in the settings section.
There are three special values that can be used, <<temp>> <<project>> and <<cache>>. Their meaning is the same as that found in the settings section and they are described there.

Note: the --aux-directory flag is only meaningful when used with MiKTeX, but see the copy_on_build setting for an option to get some similar behaviour with TeXLive.

Note: These flags can only be set when using latexmk (default on OS X and Linux), the basic builder or the script builder (see below for documentation on using the script builder). If you are using texify (default when using MiKTeX) or the simple builder, setting these flags through any method will be ignored.

**Comment by r-stein** [comment]
Have you looked into the LaTeXTools default settings?
You can just copy the settings you want to change to your LaTeXTools user settings and change them.

You can open the settings via the menu `Prefences >> Package Settings >> LaTeXTools >> Settings - User`.

**Comment by shouwei** [comment]
@r-stein I already checked this file and there is not "copy_on_build".

**Comment by r-stein** [comment]
Check the settings from `Prefences >> Package Settings >> LaTeXTools >> Settings - Default (read only)` or reset the user settings.

**Comment by shouwei** [comment]
Actually, I used grep to search "copy_on_build" in the LatexTools folder and only found it appears in makePDF.py. But it seems no relation with the aux-directory option.
I doubt if someone really tried this option on OSX before.

**Comment by shouwei** [comment]
I already set "copy_output_on_build" value to true, but it still does not work. I think aux_directory and output_directiory are two different settings. The first one indicates the folder to store auxiliary files during compilation and the second one indicates where to put the PDF file. This is exactly what I want. I want to keep all the auxiliary files in a single folder, and just leave the PDF file and the tex files in the current folder.

**Comment by r-stein** [comment]
If you only want to keep the pdf file, set the `output_directory` setting and leave `copy_output_on_build` on `true`. The aux directory only applies on `*.aux` files, the output directory applies for the whole build output.

**Comment by ig0774** [comment]
Just a quick point, but only MiKTeX actually implements `aux_directory` on TeXLive / MacTeX, `output_directory` is the only option available. The docs could've been clearer on this point I suppose.

**Comment by shouwei** [comment]
@r-stein thank you so much! I get the expected result now.

**Comment by r-stein** [comment]
Actually @ig0774 implented that feature, so more thanks to him. However I am glad, that it works for you.
