### ISSUE TITLE
bf tab completes to textbf in math mode

### ISSUE THREAD

**Issue by dpmcsuss** [SublimeText/LaTeXTools#814]
I tried this between $$ and in equation environment and it seems that now regardless of where I am bf tab completes to \textbf{}. I know it used to complete to \mathbf{} in math mode but this is using a fresh install.  I tried removing the snippet for `Text boldface` but that didn't seem to change anything either. 
Thanks.

**Comment by r-stein** [comment]
It might be the easiest exclude the snippets from `LaTeX.sublime-completions` inside math environments. This would be done by changing the `"scope"` to `"text.tex.latex - (string.other.math, meta.environment.math)"`. You can do it manually and it will be overwritten by the next update if @ig0774 agrees with this solution.

**Comment by ig0774** [comment]
@r-stein: I agree that's a good idea!

**Comment by dpmcsuss** [comment]
That worked. Thanks for the fix.

**Comment by r-stein** [comment]
Fixed in `v3.10.8`
