### ISSUE TITLE
Cite-autocompletion no longer working

### ISSUE THREAD

**Issue by rhandersen** [SublimeText/LaTeXTools#815]
This is probably a question, rather than an issue. I have previously been using the cite-autocompletion without any issues, but it recently stopped working for me. 

I have turned auto-complete ON for citations, i have used the %!TEX root directive and the citations work fine when compiling the document. 

The bibliography is included like this:
\bibliographystyle{ieeetr}
\bibliography{bibliography/library}

The bibliography file is generated by Mendeley. 

How can I debug this issue? Nothing shows up in the console when using the \cite keyword. 

Thanks in advance.

**Comment by ig0774** [comment]
Sorry you're experiencing this issue. What `\cite` command are you using? Just`\cite{`? Something else? Does the force keybinding work for you (`C-l,alt-f,x,c` --- sorry that's a pain to type)?

**Comment by rhandersen** [comment]
Thanks for your quick reply!

I'm just using \cite{}

When trying the force keybinding it says "Cannot determine completion type for current selection", although I'm unsure if i've got the key combination right. alt-f deletes the line (on mac at least), so I tried cmd-l, cmd-alt-f, x, c as well.

**Comment by ig0774** [comment]
Whoops... It's `C-l,alt-x,c`. 1 less key than I thought. Can you try that one?

**Comment by rhandersen** [comment]
Nothing seems to happen when using that key-combination.  Neither in the console or the status-bar. 

Extra info: I have reset the user settings and is using Sublime Text 2 and LatexTools v3.10.7

**Comment by ig0774** [comment]
Have you tried just quitting (Cmd-Q) and re-opening ST2? I can simulate the issue by disabling and enabling LaTeXTools in which case, it won't work until I restart but after that it works fine. If that solves things, I'll try to get a fix in that makes restarting unnecessary.

**Comment by rhandersen** [comment]
Seems to fix the issue. I thought I did try that though, but It might be before I tried to reset my user settings. Sorry for any inconvenience and thanks for your help!

**Comment by ig0774** [comment]
No, thanks for reporting this. We are actually trying to stamp out the need to restart after upgrading, so it's good to know where these issues occur!

**Comment by ig0774** [comment]
Should be fixed in v3.10.8.
