### ISSUE TITLE
feature request: PDF generation option for latexmk

### ISSUE THREAD

**Issue by fjarri** [SublimeText/LaTeXTools#826]
Currently, `latexmk` calls default to `-pdf` (use `pdflatex`). Some relatively popular packages (e.g. [`powerdot`](https://www.ctan.org/pkg/powerdot?lang=en)) require a different PDF generation pathway, which can be achieved by passing `-pdfps` instead.

I think it might be useful to be able to turn on this option via some directive in the TeX file, similar to `!TEX engine`.

**Comment by ig0774** [comment]
This is currently achievable using the script builder, which can support pretty much any workflow you want. You'd just need something like:

```
"builder_settings": {
    "linux": {    // or whatever
        "script_commands": [
            "latexmk  -cd -pdfps -interaction=nonstopmode"
        ]
    }
}
```

**Comment by fjarri** [comment]
Thank you. I still think that the option is simple enough and useful enough to justify a directive support, but if that is the proposed way, I am going to use it.

Could you explain in more detail where this bit should go? It is not said directly in the "Script Builder" part of the docs; from the "Project-Specific Settings" part it seems that it should go into the project file, root -> `"settings"`, but that doesn't work for me — the traditional builder still gets called on cmd-B (I'm on OSX and changed the `"linux"` tag to `"osx"`, or course). Is there something else I forgot to do?

**Comment by r-stein** [comment]
You can open the settings via the menu `Preferences >> Package Settings >> LaTeXTools >> Settings - User` and should additionally add `"builder": "script",`.

**Comment by fjarri** [comment]
That would make the setting global, wouldn't it? Is there a project-local solution?

**Comment by r-stein** [comment]
Yes, you can also set the setting as a project setting and after https://github.com/SublimeText/LaTeXTools/pull/775 has been merged you can also just change the build system.

Just add 
``` js
"settings":
{
    "builder": "script",
    "builder_settings": {
        "osx": {
            "script_commands": [
                "latexmk  -cd -pdfps -interaction=nonstopmode"
            ]
        }
    }
},
```
to your sublime-project.

**Comment by fjarri** [comment]
Thanks Richard, I see now that `"builder": "script"` is the part I was missing. It works perfectly.

I guess, if introducing a directive for this is not desired, the issue can be closed.

**Comment by ig0774** [comment]
The main issue with adding a new directive is that we need to be able to respond to it sensibly in places where it doesn't make sense. `pdflatex`, `xelatex` and `lualatex` are names of executables that come included in the TeX distribution. `-pdfps` and `-pdfdvi` are actually short-cuts for little mini-scripts that `latexmk` runs, but which wouldn't make any sense in a non-`latexmk` environment (so, in particular, the `basic` builder and when using the `traditional` builder on MiKTeX).

I feel like I should've pointed out that this could've been much more simply accomplished by using the `command` option like this:

```json
"builder_settings": {
    "command": ["latexmk", "-cd", "-pdfps", "-interaction=nonstopmode", "-synctex=1"]
}
```
