### ISSUE TITLE
Citing multiple times results in "No bib files found!" error

### ISSUE THREAD

**Issue by emichael** [SublimeText/LaTeXTools#829]
The first time I use `\cite` in a file, autocomplete works fine. However, the second time I try to use it, I get an error, and autocomplete doesn't work.

**Comment by emichael** [comment]
Looks like 5ef7f665aa18a0dfc0cbc5f3298558aad21489c6 is probably the culprit. Any idea might be going on, @ig0774?

**Comment by ig0774** [comment]
What error do you get? I certainly haven't come across this before...

**Comment by emichael** [comment]
Turns out it only occurs when you are in a non-root file and the TEX root directive is below the current line. Try the following:

### paper.bib
```bibtex
@inproceedings{foo1,
  author = {Foo},
  booktitle = {Bar},
  month = nov,
  title = {Foobar},
  year = {2010}
}

@inproceedings{foo2,
  author = {Foo},
  booktitle = {Bar},
  month = nov,
  title = {Foobar},
  year = {2010}
}
```

### paper.tex
```latex
\documentclass{article}

\begin{document}
This is a test.

\input{subpaper}

\bibliography{paper}

\end{document}
```

### subpaper.tex
```latex



%!TEX root = paper.tex
```

Then, actually type in `subpaper.tex` to make it look like this:
```latex
\cite{foo1}
\cite{foo2}


%!TEX root = paper.tex
```

The console output shows that the issue is that TEX root is getting cleared out:
```
TEX root: '/tmp/sublime-test/paper.tex'
Searching file: '/tmp/sublime-test/paper.tex'
Searching file: '/tmp/sublime-test/subpaper.tex'
Bib files found: 
['/tmp/sublime-test/paper.bib']
TEX root: '/tmp/sublime-test/subpaper.tex'
Searching file: '/tmp/sublime-test/subpaper.tex'
Bib files found: 
[]
error: No bib files found!
```

So, it might not be the commit I referenced, actually. Sorry if I pinged you unnecessarily, @ig0774.

**Comment by ig0774** [comment]
No, it's ok...

The `%!TEX root` magic comment needs to be *before* any LaTeX commands in the file, otherwise it's not recognised. (The documentation says that it must be "the first line", but the implementation is actually it bit more lenient than that.)

**Comment by emichael** [comment]
Oh, didn't know that... (And citations at least used to work no matter where the comment was.)

Then, I'll add a feature request to allow it anywhere in the file. In our projects, we like to keep the top of the file clean because having newlines and other junk at the top can lead to unexpected results (e.g. `\par`s and other things being inserted where they don't belong).
