### ISSUE TITLE
"COULD NOT COMPILE" "FileNotFoundError: [Errno 2] No such file or directory: 'latexmk'"

### ISSUE THREAD

**Issue by thegreatmichael** [SublimeText/LaTeXTools#830]
I must have changed something, but i really don't know what i would have done... i have not changed any settings.

this is the output in the latextools thingy:

    [Compiling /Users/tgm/Dropbox/CV/tgm-cv.tex]

    TraditionalBuilder: Engine: pdflatex. Invoking latexmk... 

    COULD NOT COMPILE!

    Attempted command:latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 tgm-cv.tex
    Build engine: Traditional Builder

this is output in the sublime console (ctrl+`)

    Welcome to thread Thread-30
    ['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', 'tgm-cv.tex']
    Traceback (most recent call last):
      File "/Users/tgm/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 145, in run
        cwd=self.caller.tex_dir
      File "./python3.3/subprocess.py", line 819, in __init__
      File "./python3.3/subprocess.py", line 1448, in _execute_child
    FileNotFoundError: [Errno 2] No such file or directory: 'latexmk'

pretty sure i haven't changed any settings, but just in case:
LaTeXTools.sublime-settings:

    // LaTeXTools Preferences
    //
    // Keep in the User directory. Personalize as needed

    {

    // ------------------------------------------------------------------
    // General settings
    // ------------------------------------------------------------------

      // Cite/ref autocompletion by default is triggered after e.g. \ref{. If you don't like this,
      // set to false. You can also use toggles: C-l,t,a,c and C-l,t,a,r.
      "cite_auto_trigger": true,
      "ref_auto_trigger": true, 

      // Keep focus on Sublime Text after building (true) or switch to PDF viewer (false)
      "keep_focus": true,
      // Sync PDF to current editor position after building (true) or not 
      "forward_sync": true,

    // ------------------------------------------------------------------
    // Platform settings: adapt as needed for your machine
    // ------------------------------------------------------------------

      "osx":  {
        // Path used when invoking tex & friends; MUST include $PATH
        "texpath" : "$PATH:/usr/texbin:/usr/local/bin:/opt/local/bin"
        // Path to PDF viewer, if needed
        // TODO think about it. Also, maybe configure it here!
      },

      "windows": {
        // Path used when invoking tex & friends; "" is fine for MiKTeX
        // For TeXlive 2011 (or other years) use
        // "texpath" : "C:\\texlive\\2011\\bin\\win32;$PATH",
        "texpath" : "",
        // TeX distro: "miktex" or "texlive"
        "distro" : "miktex"
      },

      "linux" : {
        // Path used when invoking tex & friends; MUST include $PATH
        "texpath" : "$PATH:/usr/texbin",
        // Command to invoke Python 2. Useful if you have both Python 2 and Python 3 on your system,
        // and "python" by default is liked to Python 3. If blank, "python" is used
        // Note: ST3 uses Python 3 internally, but the evince scripts need Python 2
        "python2": "",
        // The name of the ST2 or ST3 executable. On Ubuntu, both subl and sublime-text are 
        // available for ST2; adjust as needed for other platforms, and for ST3
        "sublime": "sublime-text",
        // How long to wait after evince has launched before sending a sync message
        // in seconds, floating point; choose 2.0 or 3.0 on a slower machine, 0.5 on a fast one
        // Note: only tweak this if sync after launching the PDF viewer does not seem to work,
        // or if the PDF viewer opens instantly and you don't want to wait.
        // Default: 1.5 (works on my MBP4,1...)
        "sync_wait": 1.5
      },

    // ------------------------------------------------------------------
    // Build engine settings
    // ------------------------------------------------------------------
      
      // OPTION: "builder"
      // Specifies a build engine
      // Possible values:
      //
      // "default" or ""  the default built-in build engine; currently
      //          this is the same as "traditional"
      //
      // "simple"     invokes pdflatex 1x or 2x as needed, then
      //          bibtex and pdflatex again if needed;
      //          intended mainly as a simple example for
      //          peoeple writing their own build engines.
      //
      // "traditional"  replicates the 'old' system based on
      //          latexmk (TeXLive) / texify (MiKTeX)
      //
      // "script"     external script: just invokes the script
      //          specified in "builder_settings"
      //
      // custom name    you can also use third-party build engines;
      //          if so, set the "builder_path" option below
      //
      // NOTE: custom builders CANNOT have the same name as an existing
      // built-in build engine (including "default")

      "builder": "traditional",

      // OPTION: "builder_path"
      // If non-empty, specifies a path to a custom builder, relative to the
      // Sublime Text Packages directory.
      // For instance, "User/builders" (on Windows: "User\builders") is a good
      // choice if you roll your own. 
      // (Note: if you choose "User", you may get a Python import error in the
      // console, but things will still work). 
      // Leave empty ("") for a built-in builder.

      "builder_path": "",

      // OPTION: "builder_settings"
      // Specify builder-dependent settings and preferences
      // Possible values: see README or documentation provided with
      // third-party build engine.
      // Builder setting can be general or OS-dependent

      "builder_settings" : {
        
        // General settings:
        // See README or third-party documentation

        // (built-ins): true shows the log of each command in the output panel
        "display_log" : false,  

        // Platform-specific settings:
        "osx" : {
          // See README or third-party documentation
        },

        "windows" : {
          // See README or third-party documentation
        },

        "linux" : {
          // See README or third-party documentation
        }
      },

    // ------------------------------------------------------------------
    // Formatting of bibliographic references in quick panel
    // ------------------------------------------------------------------

      /* This preference sets the format of the quick panel to select citations using wildcards.
      The setting is a list with one or two string using wildcards for author, title, keyword etc. 
      
      Default setting: the traditional display, `["{title} ({keyword})","{author}"]` 
      Format:
      Can quantum-mechanical description of physical reality be considered complete? This is an non-existing subtitle to illustrate (einstein1935quantum)
      Albert Einstein and B Podolsky and N Rosen

      Richer alternative: ["{author_short} {year} - {title_short} ({keyword})","{title}"]
      Format:
      Einstein et al. 1935 - Can quantum-mechanical description of physical reality be considered complete (einstein1935quantum)
      Can quantum-mechanical description of physical reality be considered complete? This is an non-existing subtitle to illustrate

      Another alternative: ["({keyword}) {author_short} - {year}","{title} - {journal}"]
      Format:
      (einstein1935quantum) Einstein et al. - 1935
      Can quantum-mechanical description of physical reality be considered complete? - Physical Review

      No-title alternative: ["{author_short} {year} ({keyword})"]
      Format:
      Einstein et al. 1935 (einstein1935quantum)

      Valid wildcards: keyword, title, author, year, author_short, title_short, journal
      */

      // Uncomment or modify at will
      "cite_panel_format": ["{author_short} {year} - {title_short} ({keyword})","{title}"],
      //"cite_panel_format": ["({keyword}) {author_short} - {year}","{title} - {journal}"],
      //"cite_panel_format": ["{author_short} {year} ({keyword})"],

      // Similarly, the formatting for the autocomplete panel:
      "cite_autocomplete_format": "{keyword}: {title}"

    }

**Comment by ig0774** [comment]
At a guess you're on El Capitan or Sierra with an older settings file. If you really haven't changed any of the settings you can either 1) delete the `LaTeXTools.sublime-settings` file in the User folder of your Packages directory (which you can open by selecting **Preferences > Browse Packages...** or 2) run the **LaTeXTools: Reset user settings to default** command from the command palette.

If that doesn't fix it, can you from the terminal type `which latexmk` and ensure that the resulting path is included in the `texpath` setting.

**Comment by thegreatmichael** [comment]
Yes, it turned out to be the latex path... somehow? I needed to add `/Library/TeX/texbin` to my `texpath` in `osx` in LaTeXTools.sublime-settings
