### ISSUE TITLE
`copy_output_on_build` should copy `basename.syntex.gz` by default

### ISSUE THREAD

**Issue by fph** [SublimeText/LaTeXTools#836]
Currently, the default setting `copy_output_on_build = True` copies only the `basename.pdf` file. It would be useful if it copied `basename.synctex.gz` as well, otherwise inverse search is broken.

**Comment by ig0774** [comment]
The default setting is quite intentional. Different people have different tastes about this, as some people seem to regard even the `.synctex.gz` file as unnecessary clutter.

In any case, you can get the behaviour you're requesting by changing `copy_output_on_build` to `[".pdf", ".synctex.gz"]`,

**Comment by fph** [comment]
I understand.
