### ISSUE TITLE
Commands using `latex_ref_cite` and `insert_char` don't work anymore after updating

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#839]
I had all these bindings I had previously used and just updated to the most current LatexTools and they seemed to have stopped working. I assume this command does nothing now because logging commands shows they are still running using these keybindings but nothing happens (the command used to be inserted and it would call ref or cite. 

	{   "keys": ["super+l","super+r"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\cref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","r", "t"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\cref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","r", "r"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\ref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","r", "c"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\Cref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","r", "s"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\subref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","r", "e"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\eqref{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","p",],
	"command": "latex_ref_cite", "args": {"insert_char": "\\citet{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},
	{   "keys": ["super+l","super+p"],
	"command": "latex_ref_cite", "args": {"insert_char": "\\citep{"}, "context":
	[      { "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]},

**Comment by r-stein** [comment]
Yes there were major changes in that command to unify all completion types. You can change the keybinding to:

```py
    {
        "keys": ["super+l","super+r"],
        "command": "latex_fill_all", "args": {"completion_type": "ref", "insert_char": "\\cref{"},
        "context":
        [{ "key": "selector", "operator": "equal", "operand": "text.tex.latex" }]
    },
```
With the completion type `cite` for cites.

**Comment by excetara2** [comment]
Thanks got it working no problem! Good work on all the changes. Been really busy but most the things I'd merged into my own branch to try has been put in master and works great!!

**Comment by ig0774** [comment]
@excetara2: That's actually a really creative use of the completions. It strikes me that you could get some extra functionality by changing [`get_match_char()`](https://github.com/SublimeText/LaTeXTools/blob/05e0636b982d451c193f39e239d03f686b082bc0/latex_fill_all.py#L410) (line 410 of `latex_fill_all.py`) to:

```python
def get_match_char(self, insert_char):
        return self.MATCH_CHARS.get(insert_char[-1], '')
```

Basically, in addition to filling in `\cref{` or whatever, it should also insert the closing `}` brace.

**Comment by excetara2** [comment]
Yeah, I find it was the most typed command especially in a thesis or papers so found setting these was useful so I will give that a try because that will make it even better! Thanks!
