### ISSUE TITLE
COULD NOT COMPILE! Since today, worked yesterday just fine.

### ISSUE THREAD

**Issue by DragooNick** [SublimeText/LaTeXTools#843]
Hey,

I hope this is the right place to ask, but since I didn't change anything since yesterday, I'm out of options.

When I try to build my pdf. I get this Error:

```
TraditionalBuilder: Engine: pdflatex. Invoking texify... 

COULD NOT COMPILE!

Attempted command:texify -b -p --engine=pdftex --tex-option="--synctex=1" Thesis.tex
Build engine: Traditional Builder
```

When I look into the console:
```
Welcome to thread Thread-3
['texify', '-b', '-p', '--engine=pdftex', '--tex-option="--synctex=1"', 'Thesis.tex']
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\makePDF.py", line 147, in run
    cwd=self.caller.tex_dir
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

When had a look into the python3.3 there was a zip containing a subprocess.pyo.
I'm not sure whethere there is the problem. But I really need it to work again :(
So any help appreciated! 

Restarting my Laptop, or Sublime Text 3 doesn't change anything, sadly.

Also had this:
`Unable to open /C/Users/DragooNick/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings`

I already restored it, but why was it missing in the first place?

**Comment by r-stein** [comment]
It looks like it cannot find `texify` in the path. Can you try  to open a `cmd` and write `texify -v` this should print infomation about it and `where texify` to get the path of it.
In ST you can open the console with ``ctrl+` `` and write `import os; os.environ["PATH"]` to print the PATH, which is seen from ST. Can you check that this path contains the path to texify you have seen on the console.

**Comment by DragooNick** [comment]
Thanks for the fast answer, I believe you're right since I got no results for `textify -v` in a `cmd` and also no path in ST3:
```
>>> import os; os.environ["PATH"]
'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\nodejs\\;C:\\Users\\Username\\AppData\\Roaming\\npm;C:\\texlive\\2016\\bin\\win32'
```

**Comment by r-stein** [comment]
Looks like you have installed texlive and not miktex. Just open your `LaTeXTools-settings - User` in the platform settings change the distro from `miktex` to `texlive`.

**Comment by DragooNick** [comment]
Thanks! Sooo stupid of me :D I checked it just before I posted and thought "miktex" alright, but forgot I changed to texlive long ago...

But why or how was this changed?

**Comment by ig0774** [comment]
If you changed the `LaTeXTools.sublime-settings` file in the `LaTeXTools` package / folder, rather than the `LaTeXTools.sublime-settings` file in the `User` package / folder, then it would've worked but have been reset by the update. This is why we strongly **don't** recommend modifying that file, but using the **Settings – User** option to create a copy and modify that.

**Comment by DragooNick** [comment]
Thanks! I will do so now.
It just did it like the Guide here said:
https://github.com/SublimeText/LaTeXTools#setup-latextools-1

Maybe this should be changed then?

**Comment by r-stein** [comment]
@DragooNick I have updated the README.

**Comment by DragooNick** [comment]
Thank you very much!
