### ISSUE TITLE
no new \item on cmd+enter

### ISSUE THREAD

**Issue by tobiasgerstenberg** [SublimeText/LaTeXTools#845]
in the past, a new \item was created upon hitting cmd+enter within the itemize environment. this is not the case anymore. i use sublime build 3124 and have the most recent version of the latextools package.

**Comment by r-stein** [comment]
The keybinding would be `shift+enter` [in the keymap](https://github.com/SublimeText/LaTeXTools/blob/v3.11.1/Default%20(OSX).sublime-keymap#L373) and we missed to update the scope for the new LaTeX Syntax.

You can change/add the keybinding on your own, but the updated version will be in the next release.

``` js
 	{ "keys": ["shift+enter"], "command": "insert_snippet", "args": {"contents": "\n\\item $0"}, 
 	"context":  
	 	[
			{"key": "selector", "operator": "equal", "operand": "meta.environment.list.itemize.latex"},
			{ "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true }
		]
},
```

**Comment by tobiasgerstenberg** [comment]
great - that worked! just fyi: i had previously used this 

{ "keys": ["super+enter"], "command": "insert_snippet", "args": {"contents": "\n\\item $0"}, 
	"context":  
	    [
	        {"key": "selector", "operator": "equal", "operand": "meta.function.environment.list.latex"},
	        { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true }
	    ]
	},

so the only difference appears to be that the operand has changed (from "meta.function.environment.list.latex" to "meta.environment.list.itemize.latex")
