### ISSUE TITLE
Could not compile on macOS Sierra

### ISSUE THREAD

**Issue by aaronhossack** [SublimeText/LaTeXTools#846]
I recently upgraded to macOS Sierra and can't use LatexTools fully yet. My first error was an incorrect 'texpath' which I modified in my User specific LatexTools.sublime-settings:

`"osx": 	{
		// Path used when invoking tex & friends; MUST include $PATH
		"texpath" : "$PATH:/Library/TeXShop/bin:/usr/bin:/usr/local/bin:/opt/local/bin"
		// Path to PDF viewer, if needed
		// TODO think about it. Also, maybe configure it here!
	}`

Now it doesn't complain about the texpath but it throws the error:

`COULD NOT COMPILE!

Attempted command:latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 my_document.tex
Build engine: Traditional Builder`

But if I paste the above command into a terminal it updates the pdf correctly. So I can get my work done, it's just that command+B doesn't work.

**Comment by ig0774** [comment]
Your `texpath` is still not quite right. The default value, `$PATH:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin`, works on Sierra (assuming you've installed MacTeX).

**Comment by aaronhossack** [comment]
Thanks! I reset User settings to default and it worked this time. I have no idea why it didn't work the first time...
