### ISSUE TITLE
Allow multiple TEX roots

### ISSUE THREAD

**Issue by adamjstewart** [SublimeText/LaTeXTools#847]
I'm not sure how common my use case is, but I have a LaTeX project where I have two modular documents that share the same input files. More specifically, I have a `resume.tex` and `cv.tex` that share the same sections but can format them differently and include different sections. You can check out my repo [here](https://github.com/adamjstewart/resume).

Currently, if I update a section and want to build both my resume and cv with LaTeXTools, I have to switch the `TEXroot` back and forth in my `*.sublime-project` file. I was wondering how difficult it would be to allow LaTeXTools to accept multiple TEX roots. In terms of UI, the `*.sublime-project` file would look something like:

``` json
{
    "settings": {
        "TEXroot": ["resume.tex", "cv.tex"]
    }
}
```

On a per-file basis, it could look like:

``` tex
%!TEX root = ../resume.tex ../cv.tex
```

although I'm not sure how that would work if the filename contains spaces. I guess we could require files with spaces to be wrapped in quotes if that isn't already the case.

One complication would be which file to open with the viewer. Perhaps both? Whichever is listed first?

I imagine that this change might require substantial work since LaTeXTools is designed to build one file at a time... Could the build system be modified in the "*.sublime-project" file to support this?

**Comment by ig0774** [comment]
I'm not altogether sure that this is feasible or a good idea. Most of LaTeXTools internals are built around the assumption that there is a single root file,  a single log file, and a single final PDF and changing those assumptions would require a massive rewrite. Moreover, there's a lot of behaviour related to the root file that it's not clear how it should behave in the presence of multiple roots, e.g., the list of labels or citations (probably not a big deal for a CV, but important for many other document types).

I don't think there's a perfect fix for this, but I can think of a partial solution that would probably do the vast majority of what you need: switch over to using the `script` builder, which is configurable on a per-project basis and could be given a list of commands to run that would compile both `cv.tex` and `resume.tex` in a single build. You'll lose some error reporting doing this. To open the two resulting PDFs, you could likely use the `command` viewer, albeit at the cost that there's probably no sensible way to support `forward_sync`. There's documentation on both of those features in the README, but feel free to get in touch if you need some help setting this up.

**Comment by adamjstewart** [comment]
I no longer use LaTeXTools (switched to Overleaf), so I'll close this feature request.
