### ISSUE TITLE
Not jumping under Preview

### ISSUE THREAD

**Issue by edouardberthe** [SublimeText/LaTeXTools#849]
Hello,

I am using LatexTools under Sublime Text 3 and Preview.app as viewer (`"viewer": "preview"`) in the conf).
I have also set:

     "forward_sync": true

so that to sync the PDF to the current editor position on build. It works the first time (on first build, when it opens Preview) but after on each build it goes to the top of the PDF.
I have installed Skim and set it as viewer (without changing anything else to the conf) and the forward_sync is working (going where the cursor is in ST).

Am I the only one is this situation?

Thanks

**Comment by r-stein** [comment]
From the README (https://github.com/SublimeText/LaTeXTools#previewapp)

> The Preview.app viewer is very straight-forward. It simply launches Preview.app with the relevant PDF file. Please note that Preview.app *does not* support forward or reverse sync, so you will not have that functionality available. Nevertheless, if you want to avoid installing another PDF viewer, this may be an acceptable option.

It is recommended to use Skim on OSX, because forward and inverse are not supported by Preview. Hence we cannot support it in LaTeXTools.

**Comment by edouardberthe** [comment]
Ok, thanks for your quick answer and sorry for that!
