### ISSUE TITLE
Conflicts between my auto completion settings and the package's

### ISSUE THREAD

**Issue by JimAmuro** [SublimeText/LaTeXTools#852]
I have a auto completion setting file for LaTeX in my user folder. However, there are some conflicts with this package's settings, i.e., they share the same trigger, and the one provided by the package always comes first, which is kind of inconvenient. I am wondering if there is a way to set priority. If not, I think maybe it is better for the package to stop providing autocomplete settings by default, because even if I delete/modify the settings, they shall come back after the next update...

**Comment by r-stein** [comment]
You mean the entries in the auto complete popup? Not keybindings or something like that?

**Comment by JimAmuro** [comment]
@r-stein I mean `.sublime-completions`.

**Comment by r-stein** [comment]
I see your point, but unfortunately we cannot just opt-out that file and removing it will also result in a lot of complains.

If you want to force your completions into a higher priority you could create an EventListener, i.e. a file `completions.py` in your `User` folder with the content:

``` py
import sublime_plugin
class MyCompletions(sublime_plugin.EventListener):
    def on_query_completions(self, view, prefix, locations):
        if not view.score_selector(locations[0], "text.tex.latex"):
            return []
        return [
            ("hello\tworld", "world"),
            ("al\talign", "\\begin{align}\n$0\n\\end{align}")
        ]
```

Completions provided by an EventLIstner have a higher priority than those from a completions file. However they are handled as API completions an will also be present, when normal completions are suppressed.

**Comment by JimAmuro** [comment]
@r-stein I understand that removing them maybe a disaster for newcomers... Anyway, thank you for your suggestion. Maybe I should just bypass used triggers...
