### ISSUE TITLE
Shift-Enter no longer creates \item in enumerate or itemize environment

### ISSUE THREAD

**Issue by darsnack** [SublimeText/LaTeXTools#856]
In ST3 on macOS Sierra, the last two updates to LaTeXTools broke the "Shift-Enter" shortcut in the enumerate or itemize environment. Previously, "Shift-Enter" would create a new line and fill in "\item " automatically.

**Comment by r-stein** [comment]
This already has been mentioned in https://github.com/SublimeText/LaTeXTools/issues/845 and the fix on the master branch. I will issue a new release today to fix this.

**Comment by darsnack** [comment]
Ah, I guess I missed that issue. Thanks.

**Comment by r-stein** [comment]
Fixed in `v3.11.2`.
