### ISSUE TITLE
More selective matching of dollar sign $

### ISSUE THREAD

**Issue by MichaelChirico** [SublimeText/LaTeXTools#857]
I find it to be quite a nuisance when ST matches my escaped dollar signs. If I'm typing out a currency unit, and precede the dollar sign by `\`, it should be clear to ST/LaTeXTools that I'm escaping the `$`.

I'm not sure this is something in LaTeXTools' purview, but it would be nice to have the ability to be more selective in deploying the automatic `$` matching.

This may have already been asked; I searched for `"dollar"` among open & closed issues.

Thanks!

**Comment by r-stein** [comment]
Actually that's trivial and will be change the keymap accordingly.
