### ISSUE TITLE
Comments folding function

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#858]
Hi guys,

Does ST3 or Latextools support comment folding function now? Or any suggest solutions?

It is really boring to scroll up and down a lot when you working on a long paper.

thanks

**Comment by r-stein** [comment]
Do you want to define fold markers to specify where a fold starts and ends in the comments?

**Comment by shouwei** [comment]
no, normally, I always comment a block with the shortcut. so they will be many lines start with "%" continuously, I prefer to fold these lines, as following:

% %Editor-only macros:: begin (do not touch as author)%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \EventEditors{John Q. Open and Joan R. Acces}
% \EventNoEds{2}
% \EventLongTitle{42nd Conference on Very Important Topics (CVIT 2016)}
% \EventShortTitle{CVIT 2016}
% \EventAcronym{CVIT}
% \EventYear{2016}
% \EventDate{December 24--27, 2016}
% \EventLocation{Little Whinging, United Kingdom}
% \EventLogo{}
% \SeriesVolume{42}
% \ArticleNo{23}

**Comment by r-stein** [comment]
Folding something like this is pretty easy just open the console ``ctrl+` `` and paste:

``` py
view.fold(view.find_by_selector("comment"))
```

Also this packages seems to do that https://packagecontrol.io/packages/Fold%20Comments, although I never used it.

**Comment by shouwei** [comment]
yea, it works but not perfect.
By default, all the comments will be folded. but after expanding one comment block, it seems impossible to folded it back again. Is there any trick? I prefer a more flexible folding, such as I can decide which block to be folded, and when.

**Comment by r-stein** [comment]
I think folding is not a strength of Sublime Text, especially because packages cannot add fold marks to the gutter. Therefore we have not investigated into a nice folding system, because users would not use it anyway.

With a little python skills you can easily write your own plugins to adapt ST to your needs.
For example you can write a command to fold the comments around the selections: Open `Tools >> Developer >> New Plugin...` and paste:

``` py
import sublime_plugin


class FoldSelectedCommentCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        view = self.view
        comment_regions = view.find_by_selector("comment")
        fold_regions = [
            r for r in comment_regions
            if any(r.contains(sel.b) for sel in view.sel())
        ]
        view.fold(fold_regions)
```

afterwards create a keybinding:
``` js
    {
        "keys": ["alt+shift+c"],
        "command": "fold_selected_comment"
    },
```

Now you can click into a comment and press `alt+shift+c` to fold it.

**Comment by r-stein** [comment]
Nice, that it works for you
