### ISSUE TITLE
PDF preview problem with Skim

### ISSUE THREAD

**Issue by diegodiazd** [SublimeText/LaTeXTools#862]
Hi all,

Thanks for this tool. I installed LaTeXTools for ST3 via package control, following the setup  instructions for OSx (el capitan). I have no problem compiling tex files, but I am not able to automatically open the PDF file after build (I am using Skim as PDF reader). I configured Skim for Sync-support, as described in the README file, but in any case the application doesn't start. 

I am pretty sure I am missing something, but I can't see what it is. I would appreciate any help in this issue.

Thanks in advance!

**Comment by ig0774** [comment]
Did you change the `open_pdf_on_build` setting in your LaTeXTools settings? Unlikely, but that'd be the obvious thing to check. Does the `C-l,j` shortcut work for you? Does anything get printed in the sublime console (** View > Console**) when you run the build?

Sorry for the series of questions. Trying to narrow-down what the cause might be.

**Comment by diegodiazd** [comment]
Hi,

Sorry, always worked. I didn't realize that the focus is maintained in sublime, not in the PDF ( I come from vimtex). I didn't realized that the file is opened in Skim neither. I am very new in the OSx ecosystem. Sorry for this dummy issue.

Thanks for your help.
