### ISSUE TITLE
how to define some new autocomplete commands in "LaTeX.sublime-completions"

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#863]
hi guys,

I want to define some new autocomplete commands like those already in "LaTeX.sublime-completions" file. In the first, I appended my new commands in this file, but every time latextools update, my configuration gets lost.
Is there any other way? If possible, would you please show me one tiny example?

Thanks~

**Comment by r-stein** [comment]
Just open `Preferences >> Browse Packages...` and copy the `LaTeX.sublime-completions` file from the `LaTeXTools` to the `User` subdirectory. Open that file and replace all completions with your own completions.

**Comment by shouwei** [comment]
@r-stein thank you! :-)

**Comment by r-stein** [comment]
no problem =)
