### ISSUE TITLE
\cite autocompletion doesn't activate when next line is indented

### ISSUE THREAD

**Issue by jdumas** [SublimeText/LaTeXTools#866]
Hi,

Consider the following block of code:

```
Foo \cite{}
    Bar
```

When I type `Foo \cite{` and the next line contained an indented text `\tBar` (can be space or tabs), then the autocompletion popup doesn't show. Removed the indentation and everything works fine again.

Let me know if you can reproduce.

**Comment by r-stein** [comment]
I think I got the reason, it will be fixed soon.

**Comment by ig0774** [comment]
This has been fixed in the 3.12 series. Thanks for pointing out the issue!
