### ISSUE TITLE
No open_image_command line in default settings file

### ISSUE THREAD

**Issue by Gabriel-p** [SublimeText/LaTeXTools#868]
I'm using Latextools v3.1.2. In the `Latextools.sublime-settings` file there is no `open_image_command` line. I still have it in my user settings file.

Was this command removed at some point? If not, why is it not present in my default settings file?

**Comment by r-stein** [comment]
We have split the settings into normal settings and advanced settings and it just has moved to the [advanced settings](https://github.com/SublimeText/LaTeXTools/blob/v3.11.2/LaTeXTools%20(Advanced).sublime-settings#L58)

**Comment by Gabriel-p** [comment]
Got it. I hadn't noticed the new settings file. Thanks you!
