### ISSUE TITLE
Show build results not working (grayed out in menu) with or without enabling phantoms/coloring of build panel

### ISSUE THREAD

**Issue by excetara2** [SublimeText/LaTeXTools#869]
After I build a latex file the show build results is grayed out in the menu and the keybinding for it doesn't work either. This used to work fine for me but just upgraded to the newest version of Sublime and LatexTools. I thought it maybe was the phantoms or coloring of the build output but these do not have any effect as the build results are still grayed out. Is this a bug with my system or  the way the build results are showed is changed so this won't work anymore?

Of note, the Next Result and Previous Result for build errors still works fine just the show build results is grayed out.

**Comment by r-stein** [comment]
You can reopen the build panel with `shift+escape`. We don't use the normal panel, which disables that feature.

**Comment by excetara2** [comment]
Is there anyway to change that keybinding as system wide I have something set to shift+esc?

**Comment by r-stein** [comment]
Yes they keybinding is:

``` js
    { "keys": ["shift+escape"],
        "context": [
            {"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
            {"key": "panel_visible", "operator": "equal", "operand": false }],
        "command": "show_panel", "args": {"panel": "output.latextools"}},
```

**Comment by excetara2** [comment]
Well, I was just looking where it was in the keybindings file as you wrote that but thanks. Changed it to make it toggle as well with the below. Not sure why you wouldn't make the shift+escape also toggle with the second binding below:

```
  { "keys": ["super+ctrl+/"],
        "context": [
            {"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
            {"key": "panel_visible", "operator": "equal", "operand": false }],
        "command": "show_panel", "args": {"panel": "output.latextools"}},
  { "keys": ["super+ctrl+/"], "command": "hide_panel", "args": {"panel": "output.latextools"},
  "context":[
            {"key": "selector", "operator": "equal", "operand": "text.tex.latex"},
            {"key": "panel_visible", "operator": "equal", "operand": true },
  { "key": "panel", "operand": "output.latextools" }
  ]
  },
```

**Comment by r-stein** [comment]
We have `escape` to hide and `shift+escape` to show, but your toggle might also be useful.

**Comment by excetara2** [comment]
Yeah I know escape gets rid of the panel but just seems if you want to quickly see the panel and get rid of it just holding shift and tapping escape is a lot faster. I used to do this frequently before the phantoms were introduced for errors but maybe now I would not use the panel so frequently. I haven't used sublime much since updating to the newest version so not sure with phantoms my workflow. Thanks for the help anyways.

If you want me to submit a PR for it let me know but would seem easy to add into a PR next time you modify keybindings if desired.
