### ISSUE TITLE
autocomplete trigger problem

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#872]
hi guys,

I use a lot of this math notion in my papers, so I defined a shortcut for it, here it is:

{ "trigger": "mcl", "contents": "\\mathcal{$1}$0"},

when I type "mcl" plus tab key, it will be autocompleted. But since this item only valid in the mathematic environment and I have to add a '$' in the front and the end manually, it even more complicated than before. Is that possible to make the autocomplete contains these two '$'?
 I mean the "mcl" trigger will generate "$\mathcal{}$", instead of "\mathcal{}".

Thanks for your help.

**Comment by r-stein** [comment]
just change it to
``` js 
{ "trigger": "mcl", "contents": "\\$\\\\mathcal{$1}\\$$0"},
```

**Comment by shouwei** [comment]
@r-stein  
you are also my best trouble solver :-)
Thank you!
