### ISSUE TITLE
Inverse search not working

### ISSUE THREAD

**Issue by chalkos** [SublimeText/LaTeXTools#875]
The inverse search function stopped working after updating Skim to version 1.4.22 (96). At least I think that it was the only significant change in my system. I haven't updated to Sierra.

I followed the instructions at https://github.com/SublimeText/LaTeXTools#setup-skimapp , tried using the "custom" option (I made sure the path to subl was correct) and also reseting the settings to default.

Is anyone else having this problem on Mac OS X 10.11.6?

**Comment by ig0774** [comment]
I only have Sierra available, but the custom option still works for me with Skim 1.4.22. Make sure there are no extraneous characters in what you entered in the **Command** field. Even spaces at the beginning or end will cause it to not function. Alternatively, you can just use the preset, though that requires that you've add `subl` to `/usr/local/bin`, which you can do by running the command `ln -s /usr/local/bin/subl /Applications/Sublime Text.app/Contents/SharedSupport/bin/subl` from the terminal.

**Comment by ig0774** [comment]
I just realised this might be the same issue as #876. "Inverse search" in this context means going from Skim to ST and "forward search" means going from ST to Skim. If its "forward search" which is failing, then [see my comment on #876](https://github.com/SublimeText/LaTeXTools/issues/876#issuecomment-255078014), but basically, just revert to Skim 1.4.21.

**Comment by chalkos** [comment]
You are correct. It is forward search that is not working, i.e. going from ST to Skim.

**Comment by chalkos** [comment]
Closing, because a fix is described in #876
Thanks @ig0774
