### ISSUE TITLE
Auto-pairing inside math mode

### ISSUE THREAD

**Issue by qazip** [SublimeText/LaTeXTools#877]
Hey there,

I want to be able to auto-pair inside math mode. For example, when I type:

$\dfrac{$ I want it to automatically do $\dfrac{}$, without having to type the "}" character.

Is there a way to do this easily? Perhaps there's an option in the config file?

**Comment by r-stein** [comment]
Actually it auto-closes the brace if it is not followed by a char, which is not directly related with math mode.
Just open your keybinding and add the following entry:


``` js

    {
        "keys": ["{"], "command": "insert_snippet", "args": { "contents": "{$0}" },
        "context":
        [
            { "key": "selector", "operator": "equal", "operand": "text.tex.latex meta.environment.math" },
            { "key": "following_text", "operator": "regex_contains", "operand": "^\\$" }
        ]
    },
```

**Comment by randy3k** [comment]
Alternatively, you should consider [LaTeXZeta](https://github.com/randy3k/LaTeXZeta).

Yes! It is an advertisement 🤓

**Comment by randy3k** [comment]
But this will stop `\ref{` completions.
