### ISSUE TITLE
I don't wanna make Sumatra my default viewer

### ISSUE THREAD

**Issue by Mark-Han** [SublimeText/LaTeXTools#879]
The latest version of this package always opens my default viewer (Foxit Reader) once the tex file has been compiled successfully. 
I  wanna view the result in Sumatra, however I don't  like the viewer as much as Foxit Reader. How to evoke Sumatra to view the result PDF file automatically and keep another viewer as my default viewer.

**Comment by Mark-Han** [comment]
Attached, `LaTeX.sublime-build` can not work on my computer, and I have to replace it with `LaTeX.sublime-build.OLD`

**Comment by r-stein** [comment]
The "old" build file calls `texify` with `--run-viewer` so it will use the default viewer. The new build file is way more advanced and you should use that.
If it doesn't work you could try to reset your LaTeXTools user settings to the default ones.
You can open the ST console ``ctrl+` `` and provide us the error while building, such that we can fix that.

**Comment by Mark-Han** [comment]
@r-stein Thanks.
I remove and install the package again, then reset the user's settings, and it works!
