### ISSUE TITLE
forward_sync and keep_focus both not working with Skim on Mac

### ISSUE THREAD

**Issue by TheGraviton** [SublimeText/LaTeXTools#885]
This is my first GitHub post, so I hope I'm posting in the right place.

I've been using LaTexTools to compile my .tex files in Sublime Text 2 with Skim on my MacBook for years and have loved it. At least a few weeks ago (it may have been longer), the default forward search stopped working, so that when I compile the document, the PDF refreshes but does not jump to the spot where I have edited. Thus it always opens to the first page when it's compiled the first time. Once I scroll down to the right spot, it refreshes to that spot, but as the .tex file gets longer, I have to keep scrolling down in the PDF.

Additionally, the default behavior of keeping the focus on the Sublime Text window after compilation has stopped, so the focus keeps switching to the Skim window, which I find annoying. 

My user preferences have both forward_sync and keep_focus set to the default "true." I haven't edited them in any way. Is there a way to fix this?

**Comment by r-stein** [comment]
Have you seen https://github.com/SublimeText/LaTeXTools/issues/876?
Unrelated to that I recommend to use ST3, because due to the larger API several features are released ST3 only.

**Comment by ig0774** [comment]
As is mentioned in #876, forward sync is broken using Skim v1.4.22. The best fix is to revert to v1.4.21.

Focus shifting *shouldn't* occur unless you've somehow changed the `keep_focus` setting or toggle. In any case, I can't figure out how to reproduce the issue using either Skim 1.4.22 or 1.4.21.  You could try checking the current toggle settings (`C-l,t,?`) to see what the value for `keep_focus` currently is...

**Comment by TheGraviton** [comment]
Sorry for the delay in response. I checked the toggle settings, and both keep_focus and forward_sync are set to their default values of true. 

I don't know how to revert to an older version of Skim, and a few minutes of Googling yielded nothing. How do I do this?

**Comment by TheGraviton** [comment]
I just deleted version 1.4.22 and downloaded 1.4.21. The forward sync still seems to be a few lines off, but it's good enough for now. Focus shifting has also stopped happening. Thanks for the help.

**Comment by ig0774** [comment]
Glad that got you working. Unfortunately, the control we have over syncing is not all that fine-grained and heavily relies on the viewer doing the right thing.

**Comment by TheGraviton** [comment]
Focus shifting started happening again. I'm not sure what changed. I'm still using version 1.4.21 of Skim.

**Comment by ig0774** [comment]
Unfortunately, I can't reproduce things here... You can check what LaTeXTools thinks your current `keep_focus` setting is by running this from the console (**View | Console**):

```python
from latextools_utils import get_setting; get_setting('keep_focus')
```

**Comment by TheGraviton** [comment]
Ok. The result was "True."

**Comment by ig0774** [comment]
On the same console, when you've finished a build, you should see a line that looks like this:

```
<class '_latextools_skim_viewer.SkimViewer'>
```

After that, there will be a line that starts `Running`. Can you check what is displayed in the line starting `Running`...

**Comment by TheGraviton** [comment]
So I actually don't see that line. I have

`<class '_latextools_traditionalBuilder.TraditionalBuilder'>
Welcome to thread Thread-223
['latexmk', '-cd', '-f', '-pdf', '-interaction=nonstopmode', '-synctex=1', u'filename.tex']
Running "latexmk -cd -f -pdf -interaction=nonstopmode -synctex=1 filename.tex"`

**Comment by TheGraviton** [comment]
I suppose this means I've been using the wrong build engine?

**Comment by ig0774** [comment]
No. The build engine isn't really involved there. It does seem to indicate that LaTeXTools isn't actually calling Skim though. Do you also get the message `Finished normally` or no?

**Comment by TheGraviton** [comment]
I do get the `Finished normally`, but I also get a bunch of `debug:` lines after that.

**Comment by ig0774** [comment]
What happens when you use the jump command (`C-l,j`) inside the text document? Does Skim gain focus then?

**Comment by TheGraviton** [comment]
Yes. It switches to Skim and syncs to wherever my cursor was in the tex file.
