### ISSUE TITLE
Underscore is regarded as a word separator and cannot be changed.

### ISSUE THREAD

**Issue by jialunliu** [SublimeText/LaTeXTools#886]
First of all, I would like to thank the authors for this great package. It is really awesome.

But recently, I met a strange problem. In tex files, underscore is taken as a word separator, which I think it should not. For instance, I named files like a_nice_figure.jpg and include it in my tex files. When I click the file name, 'a', 'nice', 'figure' are regarded as separated words instead of 'a_nice_figure'. This is quite inconvenient. Furthermore, I cannot change it by modifying the 'word_seperator' in the setting file.

Thanks for helping.

**Comment by r-stein** [comment]
This is from the [default LaTeX settings](https://github.com/sublimehq/Packages/blob/master/LaTeX/LaTeX.sublime-settings) and except from that case very useful. However you can change it by editing the syntax specific settings.

**Comment by jialunliu** [comment]
Thanks a lot for your quick response. The problem is solved. Cheers.

**Comment by wentaocn** [comment]
> This is from the [default LaTeX settings](https://github.com/sublimehq/Packages/blob/master/LaTeX/LaTeX.sublime-settings) and except from that case very useful. However you can change it by editing the syntax specific settings.

@r-stein How do I edit `word_separators` for only `.tex` files?
