### ISSUE TITLE
"Check system" command doesn't recognize gswin64c.exe

### ISSUE THREAD

**Issue by Gormador** [SublimeText/LaTeXTools#891]
This oversight **doesn't prevent** previews from working if both _ImageMagick_ and _Ghostscript_ are installed correctly, but if for some other reason previews don't work then the _Check System_ report would be misleading.

I'm sorry not to pull request this but I don't have a working dev env available and, frankly, don't even know the first thing about ST package development ;-)
However, and if I'm not mistaken, this fix is as simple as adding "gswin64c" to the list of programs here
https://github.com/SublimeText/LaTeXTools/blob/master/system_check.py#L444
and to the list here
https://github.com/SublimeText/LaTeXTools/blob/master/system_check.py#L178
as well as having some kind of note in the report stating that if one of the two (gswin32c or gswin64c) is available, then everything is fine.
The proper way would be to only display one of the two if one is found, but it seems unnecessary to refactor working code for something not even used by LaTeXTools itself.

Anyway, thanks a lot for your contributions to this project!

**Comment by ig0774** [comment]
This is addressed in v3.12.3. Thanks for the bug report!

**Comment by Theolean** [comment]
I think this is still a bug. 
I updated to the latest version of LatexTools and "System Check" tells me thas gswin32c is missing. 
I have installed gswin64c and all works fine
