### ISSUE TITLE
`copy_output_on_build` not honored

### ISSUE THREAD

**Issue by c8441106** [SublimeText/LaTeXTools#893]
It seems that the `copy_output_on_build` setting is not honored (neither as TeX directive nor as project-specific setting).
```latex
%!TEX output_directory = build
%!TEX copy_output_on_build = false
\documentclass{article}
\begin{document}
foo
\end{document}
```
I took a quick look into `makePDF.py` and wondered at the trailing `or True` in line 864, but removing it only proved to fix the issue for project files.
````python
if self.output_directory is not None:
    copy_on_build = get_setting('copy_output_on_build', True)# or True
````

**Comment by ig0774** [comment]
Thanks for the bug report. That `or True` bit shouldn't be there. `copy_on_build` currently isn't intended to be used as a TeX directive.

**Comment by c8441106** [comment]
Ah, that makes sense. I just scanned the readme and obviously misread the relevant part:
> copy_output_on_build (true): if true and you are using an output_directory, either set via the setting or the %!TEX directive, this instructs LaTeXTools to copy to resulting pdf to the same folder as the main tex file.
