### ISSUE TITLE
Previewing math with custom macros

### ISSUE THREAD

**Issue by doksa** [SublimeText/LaTeXTools#896]
Hello,

First of all thanks for this really incredible latexing environment.

I hope this issue hasn't been raised before: is it possible to preview math that uses custom macros (i.e. newcommand, renewcommand, providecommand, DeclareMathOperator), possibly included from another file? 

Thanks,
Ivan

**Comment by Joshua1989** [comment]
Yes, I just figure it out, in your Latextools user settings, add
"preview_math_template_preamble": "\\input{your-preamble-filename}",

For my case, it is
"preview_math_template_preamble": "\\input{/Users/JoshuaLian/Dropbox/LaTex_Folder/Sublime-Latex/tex_macros}",

**Comment by r-stein** [comment]
You can either use [`preview_math_template_preamble`](https://github.com/SublimeText/LaTeXTools/blob/v3.12.3/LaTeXTools.sublime-settings#L132) or provide a file with [`preview_math_latex_template_file`](https://github.com/SublimeText/LaTeXTools/blob/v3.12.3/LaTeXTools%20(Advanced).sublime-settings#L113). This can also set per project.
E.g. 
``` js
"preview_math_template_preamble": [
    "\\newcommand{\\foo}{bar}",
    "\\newcommand{\\foobar}{foobar}"
],
```

However you should not use the `\input{...}` command inside that, for technical reasons. A hash of the preview file is used to identify it unique. Changes in the `\input{...}` file won't propagate into that hash, hence you might get images based on older versions of that file.

**Comment by doksa** [comment]
Thanks a million!

**Comment by Crazy-Ape** [comment]
Thanks!
Could you please add an option to support relative paths for the preamble file inclusion? It would make my life a lot easier...

**Comment by r-stein** [comment]
@Crazy-Ape supporting paths relative to tex root in `preview_math_latex_template_file` should be possible.
Aside: for consistency reasons it will be renamed to `preview_math_template_file`

**Comment by Crazy-Ape** [comment]
Thanks, sorry for not being clear before. I meant to ask if it is possible for the path to be relative to the current working folder?

**Comment by r-stein** [comment]
We could change it to something like `"preview_math_template_file": "$tex_root/template.tex"` and only load the file if it is present. The tex root usually equals the working directory, but is better to detect.

**Comment by Crazy-Ape** [comment]
That sounds excellent, thanks a lot in advance

**Comment by r-stein** [comment]
I close this issue, because it is solved.
@Crazy-Ape you can create a separate issue for the relative path.

**Comment by BenjaminDbb** [comment]
@r-stein I am used to adding the newcommand to a file named command.tex 
like this:(command.tex)
```
% !TeX root = ./main.tex
\newcommand{\vecbf}[1]{\ensuremath{\boldsymbol{#1}}}
\newcommand{\feynnorm}[1]{\ensuremath{\lvert #1 \rvert^2}}
```

when I try to set ```"preview_math_template_preamble": "./command.tex",``` in the setting, it doesnot work.
how to fix it in the configuration?
BTW, I also try to add ``` "preview_math_template_file": "./command.tex",```, without help

thank you
