### ISSUE TITLE
magick definitely in path yet check systems says in unavailable

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#899]
magick definitely in path yet check systems says   unavailable

Windows 10 and texlive

**Comment by r-stein** [comment]
If you open a cmd and write `where convert` does it provide the path to ImageMagick? Have you checked the *Install legacy utilities* checkbox while installing ImageMagick?

**Comment by musm** [comment]
Ahh I needed to add them to 		"texpath" 

sorry for the noise and thank you for this awesome package
