### ISSUE TITLE
SumatraPDF no longer launches

### ISSUE THREAD

**Issue by stephenlevitt** [SublimeText/LaTeXTools#900]
I am running ST3 and the latest version of LaTeXTools ( v3.12.3 ) on Windows 10. Since it updated earlier today I have noticed that building a LaTeX file no longer launches SumatraPDF as the viewer. If SumatraPDF is **already open** the PDF appears and updates as expected.

I am using the `basic` builder. Viewer settings are as follows:
```
// ------------------------------------------------------------------
// Viewer settings
// ------------------------------------------------------------------
	"viewer": "",
	"viewer_settings": {
		// Platform-specific settings:
		"osx" : {
			// See README or third-party documentation
		},

		"windows" : {
			// See README or third-party documentation
		},

		"linux" : {
			// See README or third-party documentation
		}
	},

	"open_pdf_on_build": true,

	"disable_focus_hack": false,
```

**Comment by xrayn** [comment]
same issue here!

**Comment by guoguo12** [comment]
Same issue. Works fine after I manually open SumatraPDF.

**Comment by stephenlevitt** [comment]
Thanks for the speedy fix!
