### ISSUE TITLE
Math preview equations look  rough/ quality issues

### ISSUE THREAD

**Issue by musm** [SublimeText/LaTeXTools#901]
![image](https://cloud.githubusercontent.com/assets/4319522/19907838/e8923d54-a056-11e6-9849-8d86a2c6f356.png)

I tried playing around with the density and factors to get a smoother looking equation, but none seem to help.

Any tips?

Not sure how the color are set up but it might be good to set the equation color and background color by injecting them in the tex generation code instead of changing color after vectorization (if its not already done like that)

**Comment by r-stein** [comment]
The colors are injected while converting the pdf to png. I agree, that it would be better to inject that into the pdf template. However this would also be less error resistant.
My current idea would be to optionally disable the color conversion and give a small discription for the user to set the color [in the preamble](https://github.com/SublimeText/LaTeXTools/blob/master/LaTeXTools.sublime-settings#L132). I am open to suggestions =)

**Comment by ig0774** [comment]
At least for colours specified as hex values, it would be possible to continue the same auto-selection and use [xcolor's](https://www.ctan.org/tex-archive/macros/latex/contrib/xcolor) capabilities by adding something like this to the preamble:

```latex
\IfFileExists{xcolor.sty}{\usepackage{xcolor}}{}
```

And prepending the document body with something like:

```latex
\IfFileExists{xcolor.sty}{%
    \pagecolor[HTML]{<<background_color>>}%
    \color[HTML]{<<foreground_color>>}%
}%
```

Where `<<background_color>>` and `<<foreground_color>>` are the hex codes without the preceding `#`. Not exactly sure what to do about named HTML colours, though.

**Comment by r-stein** [comment]
That looks good. Small remark: we only set the foreground color in the pdf. The background is transparent is set in the css of the phantom.

**Comment by r-stein** [comment]
The quality should improve in `v3.12.5`

**Comment by musm** [comment]
fantastic looks great now.

**Comment by JimAmuro** [comment]
![image](https://cloud.githubusercontent.com/assets/11274691/20026788/d4dee798-a2d7-11e6-8db3-36f77967880b.png)
for 4x default density and scale.
![image](https://cloud.githubusercontent.com/assets/11274691/20026803/33a31394-a2d8-11e6-833c-86c3ecee58d5.png)
for default.
I find it still rough... Is there anything wrong? Thanks.
I am on Windows 10, system check all OK.

**Comment by JimAmuro** [comment]
OK... I changed density to 800 and find it much better...
![image](https://cloud.githubusercontent.com/assets/11274691/20124295/5ed7b6aa-a5f3-11e6-88bd-ab572185923b.png)
So the problem is that it looks bad when the font is scaled down to a small picture. Is there any way to render vector directly?

**Comment by ig0774** [comment]
@JimAmuro: No. We're limited by the image types [ST's minihtml supports](https://www.sublimetext.com/docs/3/minihtml.html) (PNG, JPG and GIF).

**Comment by r-stein** [comment]
@JimAmuro as @ig0774  said we cannot use a vector format, but if you want to you can play arount with the [ImageMagick options](https://github.com/SublimeText/LaTeXTools/blob/v3.12.6/st_preview/preview_math.py#L138) and try to the improve the png in some way.

**Comment by JimAmuro** [comment]
@r-stein Thanks! I shall try it out.
