### ISSUE TITLE
Only image can be previewed, but not for math equation ?

### ISSUE THREAD

**Issue by zzf-technion** [SublimeText/LaTeXTools#902]
![_2016-11-01_23-34-56](https://cloud.githubusercontent.com/assets/16667938/19908450/13d7e52e-a08c-11e6-980e-34275a308db3.png)
![_2016-11-01_23-37-01](https://cloud.githubusercontent.com/assets/16667938/19908485/3a1e266c-a08c-11e6-830b-5989f5f1b0cd.png)

Hello, 

First of all, Thank you for creating such cool and useful function, really like LatexTool !

I am a green hand to try the preview, not very familiar with the settings, after I installed ImageMagick-7.0.3 and Gs9.20, I added their dir to $path, checked the system, everything was available. Under \includegraphics  the preview of graph is fine, But for the math equation, it can not be show normally.

Can someone explain how to fix the problem ?

Thanks,
Jack

**Comment by r-stein** [comment]
Is it possible to convert pdf to png via `convert test.pdf test.png` in the console (`test.pdf` must be present)? Previewing png images is relativly trivial and does not rely on other programs.

**Comment by zzf-technion** [comment]
Thanks for your reply. When I used the test file, it showed as below:

convert test.pdf test.png
  File "<string>", line 1
    convert test.pdf test.png
               ^
SyntaxError: invalid syntax


when I put the cursor in the equation environment, the console shows
Running "pdflatex -interaction=nonstopmode 9e6bbca2418b9edd0af1e14832a9c880.tex".

is the problem with the path setting ?
Thanks you

**Comment by ig0774** [comment]
You should run the `convert` command from the command-line, not the Sublime Console. Also, it might be helpful if you could show the value you get for your PATH in the system check.

**Comment by zzf-technion** [comment]
T tried in cmd command window,  when I type "help convert", it shows: CONVERT volume /FS:NTFS  [/v] [/CvtArea:filename] [/NoSecurity] [/X], I think this command doesn't work. It only converts FAT to NTFS.

PATH       E:\ImageMagick-7.0.3-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windows System Resource Manager\bin;F:\Python\Python 27\Scripts;F:\NEMA\JRE\bin\client;E:\MiKTex\miktex\bin\x64\;F:\Matlab2016a\bin;F:\Matlab2016a\polyspace\bin;E:\gs9.20\bin;E:\MiKTex\miktex\bin\x64\TeXcount_3_0_0_24;E:\perl\c\bin;E:\perl\perl\site\bin;E:\perl\perl\bin;E:\perl\perl\bin

**Comment by ig0774** [comment]
@zzf-technion: I'm closing this as it appears you got things working.
