### ISSUE TITLE
Math environment highlight

### ISSUE THREAD

**Issue by Joshua1989** [SublimeText/LaTeXTools#903]
After ST3119 the highlight of math environment is removed.
In the wiki page of this repo, the [tutorial](https://github.com/SublimeText/LaTeXTools/wiki/Tips-and-Tricks#highlight-inside-math-environments) gives highlight of alphabet letters, however I found the round/square/curly braces are still not highlighted, so I add more scopes to be highlighted:
`variable.other.math.tex, constant.character.parenthesis.tex, constant.character.bracket.tex, constant.character.brace.escape.tex, meta.group.brace.tex, punctuation.definition.group.brace.begin.latex, punctuation.definition.group.brace.end.latex`.

But it is not perfect for the curly braces: many command outside math environment are highlighted e.g. `enumerate, textbf, figure`, so is there are neat solution for this issue?
<img width="591" alt="screenshot 2016-11-01 18 32 21" src="https://cloud.githubusercontent.com/assets/1357342/19910355/c6b70ca8-a062-11e6-9cbe-81249a02eb2d.png">

**Comment by r-stein** [comment]
You can use `meta.environment.math` and it should be fine.

**Comment by Joshua1989** [comment]
`meta.environment.math` is used to change the background color, but now I just want to change the foreground color of curly braces in math environment

**Comment by r-stein** [comment]
You can also use `meta.environment.math` for the foreground to highlight everything inside. This ist just a recommendation. If you want to limit the highlighting to add curly braces  you can use `text.tex.latex variable.other.math.tex, text.tex.latex meta.environment.math punctuation.definition.group.brace`

**Comment by Joshua1989** [comment]
OK, it works now, I didn't realize `text.tex.latex meta.environment.math punctuation.definition.group.brace` is one scope, at first I mistakenly add comma among them.
So is the sub-scope given from space?

**Comment by r-stein** [comment]
Yes, space is somewhat an order-preserving `and` and comma is an `or`.

**Comment by keith-hall** [comment]
I've never really found any good documentation on scope selectors, but an answer I wrote on SO may be helpful: http://stackoverflow.com/questions/37406338/sublime-text-modifying-tmtheme-file/37407588#37407588
