### ISSUE TITLE
Strange character popping up since update

### ISSUE THREAD

**Issue by mfariacastro** [SublimeText/LaTeXTools#909]
Hi everyone. First of all I would like to thank the developers for putting in the time to create and maintain this amazing tool.
Ever since the most recent update, I have been having an issue where a strange character (a small question mark inside a box) pops up  in a new line, and then disappears. This seems to happen more or less at random (I'm sure it is not random, but I haven't found any noticeable pattern).
![latextools](https://cloud.githubusercontent.com/assets/17793102/19934384/d76dae8c-a0ec-11e6-852e-178e6335dd44.PNG)

**Comment by r-stein** [comment]
This is a new feature to live preview math equations and this should be an [hour glass (⌛)](http://www.fileformat.info/info/unicode/char/231b/index.htm), which seems to be missing:

![demo](https://cloud.githubusercontent.com/assets/12573621/19117757/7048fdf2-8b1a-11e6-940b-2626e161df5f.gif)

You can disable the feature by setting [`preview_math_mode`](https://github.com/SublimeText/LaTeXTools/blob/v3.12.4/LaTeXTools.sublime-settings#L100) to `"none"` or try to make it work for which #883 might be helpful. We are still improving the feature and especially the error handling/feedback.

**Comment by ig0774** [comment]
Unfortunately, rendering the hour glass is only going to work if the font in use has the hour glass symbol, which they apparently don't. There are two possibilities that could be used to enhance this:

1. Use a bit of CSS to try and force the selection of a font known to contain the hour glass symbol and likely to be installed only for the phantom.
1. Just use a png and render that instead.

**Comment by r-stein** [comment]
Actually the character must not necessary be available in the font (it is not in my main font). As far I know Sublime Text uses DirectWrite on Windows 7, but has problems with showing special characters (not in font) with Windows 10.
I think using a png would be the best option, but we would need to tint it to fit to the foreground color.

**Comment by mfariacastro** [comment]
Thank you for your replies. I installed ImageMagick and the preview works great now!
