### ISSUE TITLE
newcolumntype syntax/math preview problems

### ISSUE THREAD

**Issue by RomanKarwacik** [SublimeText/LaTeXTools#921]
LaTeXTools v3.12.5 (2016-11-03)

If I use the command \newcolumntype like this:
`\newcolumntype{L}{>{$}l<{$}}`
from the package array, the math preview doesn't work properly, it shows "ERROR: Failed to run 'pdftex' to create pdf to preview.".
Also the syntax highlighting is a bit off:
![newcolumntype](https://cloud.githubusercontent.com/assets/8593000/20014166/29d335a0-a2b6-11e6-9248-cd7f257937ae.PNG)
Without these commands it works fine.
![newcolumntype1](https://cloud.githubusercontent.com/assets/8593000/20014400/1e07359a-a2b7-11e6-8168-edadbfec1d37.PNG)
![newcolumntype2](https://cloud.githubusercontent.com/assets/8593000/20014401/1fee7292-a2b7-11e6-8c3b-6ff694cd427e.PNG)

**Comment by ig0774** [comment]
To get this running, you'd have to modify the `preview_math_template_packages` setting to add `\usepackage{array}`. LaTeXTools currently doesn't try to do anything with the packages in the current document (though this may change).

In terms of syntax highlighting, you me have to open an issue with the [Sublime Packages](https://github.com/sublimehq/Packages) repo which handles the LaTeX syntax file.

**Comment by RomanKarwacik** [comment]
Adding it to `preview_math_template_packages` doesnt help, I'll open the issue on the Sublime repo.

**Comment by ig0774** [comment]
What does your `preview_math_template_packages` setting look like right now?

**Comment by r-stein** [comment]
The preview document content is extracted via the scope content, which is in this case everything behind $. Unsurprisingly this build fails, so the syntax is the only issue.

**Comment by r-stein** [comment]
Since this is an syntax issue I will close it. A work around would be to move all `\newcolumntype{L}{>{$}l<{$}}` into an other file an just `\input` that instead.
