### ISSUE TITLE
Math context completion doesn't work

### ISSUE THREAD

**Issue by flyseeksky** [SublimeText/LaTeXTools#927]
Thank you for your amazing work. I really enjoy using LaTeXTools a lot.

I just noticed the issue since last update that when in math context, like between `$ $` or `\[ \]`, many useful tab completion do not work anymore. For example, `a -> \alpha`, `b-> \beta`, etc. used to work pretty well, but not now.

It seems that, I guess, there is something not working perfect with context thing. Could you please look into this issue? Thank you.

**Comment by r-stein** [comment]
I cannot reproduce the issue, because they work on my ST2 and ST3.

- Are you using Sublime Text 2 oder 3?
- Have you edited your syntax and/or completions file?
- Have you lately installed new packages like [AllAutocomplete](https://github.com/alienhard/SublimeAllAutocomplete)

**Comment by flyseeksky** [comment]
Thanks for quick response.

I'm using ST3, and I followed your recommendations in README file, so I didn't change anything in latextools package folder. I put everything, personal preferences, customized snippets, all into `User` foler.

I just tried to remove latextools and reinstall it, but this issue persists. 

Now, when I type `d` and press Tab, it competes to `\date{text}`, which is exactly the behavior for ordinary text. The same for `a`, which turns to be `\abstractname{name}'.

**Comment by r-stein** [comment]
If I understand you correclty you made your own latex snippets and when you open the auto completion via `ctrl+space` these are above the math snippets?

**Comment by flyseeksky** [comment]
It's not that case.

I made only 3 snippets, mainly for template, but not includes `\date{text}` and `\abstractname{name}`. So it cannot be that these snippets above math completions.

**Comment by r-stein** [comment]
Ah okay, these completions comes from the cwl completion list. I assume you have set the [cwl completions](https://github.com/SublimeText/LaTeXTools/blob/v3.12.6/LaTeXTools.sublime-settings#L64) to `"always"`. You could set it back to `"prefixed"` to solve this issue, because it interfers with the snippet selections. I don't know what we could do about this.

**Comment by flyseeksky** [comment]
You're right. This solves my problem. 

Thank you for your help and your great work. 👍

**Comment by r-stein** [comment]
You're welcome =)
