### ISSUE TITLE
Windows path to ghostscript

### ISSUE THREAD

**Issue by loofel** [SublimeText/LaTeXTools#928]
Hi, 

I just re-visited the README after a couple of years using your tool. First, I'd like to thank you for your efforts. 

Then, I'd like to correct the path to ghostscript inside the texlive installation. How is the process for this?

The path in my installation is `path\to\texlive\<year>\tlpkg\tlgs\bin` instead of `path\to\texlive\<year>\tlgs\bin`.

With regards

**Comment by r-stein** [comment]
The path may differ for different years. The process to change the readme is to either create a pull request or an issue.

**Comment by loofel** [comment]
Ah good to know that there is a difference among the versions.

Do you consider this minor patch worth changing? Otherwise, I consider this issue as being resolved.

**Comment by r-stein** [comment]
Yes, I will add it to the readme.
