### ISSUE TITLE
Equation Preview issue related to UnicodeDecodeError

### ISSUE THREAD

**Issue by heungson** [SublimeText/LaTeXTools#934]
I thank all contributors to this great tool.

Anyway, the image preview just work ok for me. However, I got this error and when equation preview tried to pop up.

![image](https://cloud.githubusercontent.com/assets/12857095/20208573/4bdbdfe0-a832-11e6-98f3-0ab6d6600822.png)

The above error is from the following simple latex code from another post.

% import xcolor if available and not already present
\IfFileExists{xcolor.sty}{\usepackage{xcolor}}{}%

% The four packages below are specified in LatexTools.sublime-settings
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{latexsym}
\usepackage{mathtools}
%<<preamble>>
\begin{document}
% set the foreground color
%\IfFileExists{xcolor.sty}{<<set_color>>}{}%
$$
a = b
$$

\end{document}

It seems that no one reported the same problem. Is there any solution?

**Comment by r-stein** [comment]
I think we just need to change [this](https://github.com/SublimeText/LaTeXTools/blob/v3.12.7/latextools_utils/external_command.py#L243) to 

``` py
re.split(r'\r?\n', stream.decode('utf-8', 'ignore').rstrip())
```

**Comment by heungson** [comment]
@r-stein Thank you for the reply. Unfortunately, when I tried that code,
almost same messages show up.

  File "C:\Users\LHS1012\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 243, in convert_stream
    re.split(r'\r?\n', stream.decode('utf-8', 'ignore').rstrip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

**Comment by r-stein** [comment]
You need to restart ST after that change.

**Comment by heungson** [comment]
@r-stein Thank you, now it works perfectly fine.

**Comment by r-stein** [comment]
Ok I the fix will be included in the next release.
