### ISSUE TITLE
makeglossaries from texify? [W10, MiKTeX]

### ISSUE THREAD

**Issue by Gormador** [SublimeText/LaTeXTools#935]
Hi,

Currently working on a memoir document (detail apparently not relevant ; took a long time to figure that out...), I wanted to skip the use of the horrendous windows command prompt to build the glossary of my document, as well as avoid rebuilding to take the changes into account.
So I went on looking and found this on TexSE: http://tex.stackexchange.com/a/329384 (by the way: @ig0774 is everywhere!)

Doing everything just as instructed and after double checking that the .latexmkrc file was supposed to be were it was, it still failed to make the glossary.

Turns out, and you have probably already guessed it: LaTeXTools doesn't use `latexmk` on windows... Derp.

**So, my question is as follows:**

> Is it in any way possible to have a file that would work as a `.latexmkrc` file, recognized by `texify` and LaTeXTools to make the use of `makeglossaries` ubiquitous?

Thanks in advance for your answers :-)

**Comment by r-stein** [comment]
You could avoid using the command prompt by creating a build system to build the glossaries. Don't know how to integrate it into texify either.

**Comment by ig0774** [comment]
As far as I know, there's no way to coerce`texify` to run `makeglossaries`. Unfortunately, `texify` isn't terribly flexible. Probably the easiest solution is just to install `latexmk` and convince LaTeXTools to use it, which is pretty easy to do. `latexmk` is available on MiKTeX as a package. You can install it using the Package Manager in the usual way. Then, in your LaTeXTools settings (or project settings if you're using them, change the `command` setting in the `builder_settings` block to look like this:

```json
"builder_settings" : {
    "command": ["latexmk", "-cd", "-f", "-%E", "-interactionmode=nonstopmode", "-synctex=1"]
}
```

This will cause the builder to run `latexmk` even though you're using MiKTeX and the modified `.latexmkrc` file should work as usual.

If, for some reason, you don't want to install `latexmk`, you could always use the `script` builder to coerce LaTeXTools to run whatever sequence of commands you want.

**Comment by Gormador** [comment]
Thank you for your replies. Tried that out for a bit, can't get it to work either; I suspect something else is wrong with my setup (the `makeglossaries` command line gives me a strange "PARSE NAMESTRING syntax error" with that particular document).

Will use another machine (either on MacOS or linux) to get the glossary sorted out and come back to this issue if I'm brave enough. I will keep you posted if I do.
In the mean time, thanks again for your replies and this awesome package, good Sirs :-)
