### ISSUE TITLE
texify + biber still doesn't work after env var set

### ISSUE THREAD

**Issue by JimAmuro** [SublimeText/LaTeXTools#938]
I am using MikTeX on Windows 10. I cannot run biber, hence I checked the doc https://github.com/SublimeText/LaTeXTools/wiki/BIber-Support, which says setting the env var `%BIBTEX%` to `biber` should work. I did that:
![image](https://cloud.githubusercontent.com/assets/11274691/20243465/32288cd4-a926-11e6-9d7f-392e3e34242f.png)
But it still doesn't work...
I decide to use basic builder instead, but I am still wondering why it doesn't work. Is that my problem? Thanks.

**Comment by ig0774** [comment]
@JimAmuro: You're right that doesn't appear to work. I'm going to pull that from the documentation. Thanks for pointing that out!

**Comment by JimAmuro** [comment]
@ig0774 Thanks for the response! Is it a bug of `texify`? In fact I tried command line but it still didn't work.

**Comment by ig0774** [comment]
@JimAmuro: I'm not sure if its so much a bug as a limitation, but, yes, it doesn't appear that `texify` works with `biber` at all.
