### ISSUE TITLE
Sumatra did not start after building or forward search

### ISSUE THREAD

**Issue by Theolean** [SublimeText/LaTeXTools#941]
After the last update the following problem occurred:
sumatra did not start after building
sumatra did not start after forward search

If I open the .pdf in sumatra, i could jump with a double click to my .tex-file

Sublime console shows this message: 
`True True True`
`Jump to:  158 442`
`<class '_latextools_sumatra_viewer.SumatraViewer'>`
`Running "'' -reuse-instance -forward-search  
'C:\Users\aaa\Dropbox\Uni\Masterarbeit\Ausarbeitung\31einkopplung.tex' 159 'C:\Users\aaa\Dropbox\Uni\Masterarbeit\Ausarbeitung\0ausarbeitung.pdf'"`
`Traceback (most recent call last):`
  ```
File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
```
  ```
File "C:\Users\aaa\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\jumpToPDF.py", line 159, in run
    viewer.forward_sync(pdffile, srcfile, line, col, keep_focus=keep_focus)
```
  ```
File "C:\Users\aaa\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers\sumatra_viewer.py", line 132, in forward_sync
    pdf_file
```
  ```
File "C:\Users\aaa\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers\sumatra_viewer.py", line 103, in _run_with_sumatra_exe
    use_texpath=False, show_window=True
```
  ```
File "C:\Users\aaa\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 215, in external_command
    cwd=cwd
```
`  File "./python3.3/subprocess.py", line 819, in __init__`
`  File "./python3.3/subprocess.py", line 1063, in _execute_child`
`  File "./python3.3/subprocess.py", line 632, in list2cmdline`
`TypeError: argument of type 'NoneType' is not iterable`

Any idea how to fix the problem?

**Comment by r-stein** [comment]
have you tried to restart ST?

**Comment by Theolean** [comment]
I have this issue with two different systems. I restarted both systems several times and this error remains.

**Comment by r-stein** [comment]
Can you try to set the path to SumatraPDF in the settings? This somehow seems to be wrong.

**Comment by Theolean** [comment]
ok... this is really strange... 

1. I checked Latextools System Check -> sumatra available
2. sumatra did not show up after building
3. I manually added the sumatra directory to the PATH setting in windows
4. I restart the system
5. I tried forward search and building and both showed sumatra

So... thank you very much for your fast response!

**Comment by r-stein** [comment]
There should be a more informative popup, which states that sumatra is missing. We will have a look at that.
It would helpful if you could press `windows+r` and write `regedit` and check the content of the path
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SumatraPDF.exe` and whether it is available.

**Comment by Theolean** [comment]
The path ist available with the following content: 
Name: Standard
Typ: REG_SZ
Daten: C:\Program Files\SumatraPDF\SumatraPDF.exe

**Comment by r-stein** [comment]
Then it should work out of the box, we will have a look at that.

**Comment by Theolean** [comment]
Ok. 

It worked till saturday. After the update ist stopped working (on both systems)

Tomorrow I will check my second system.

**Comment by ig0774** [comment]
@Theolean: Thanks for pointing this out. It will be fixed in the next release. For now, you can just manually set the `sublime` setting.
