### ISSUE TITLE
build doesn't start

### ISSUE THREAD

**Issue by bqwer** [SublimeText/LaTeXTools#943]
Every time I try to build have this message:
![message](https://cloud.githubusercontent.com/assets/434668/20312907/2129b448-ab66-11e6-8ded-ef94572c52f4.png)
I've checked "command" setting and PATH, tried to run latexmk from command shell and everything seems ok to me. It worked earlier (about month ago).
Couldn't figure out what to do.

Windows 10
Sublime 3 build 3126
LaTeXTolls 3.12.8
Here are check report and my user settings:
[system check.txt](https://github.com/SublimeText/LaTeXTools/files/592493/system.check.txt)
[user settings.txt](https://github.com/SublimeText/LaTeXTools/files/592494/user.settings.txt)

**Comment by r-stein** [comment]
Does this error appear from the same file, where you startet the system check? Because you have set the builder to `traditional` and the system check says the same, but thats an error from the `script` builder.

**Comment by bqwer** [comment]
Yes, this error appears in the same file.
I've tired to reinstall package several times and had no success.

**Comment by r-stein** [comment]
Can you press `ctrl+shift+b` and select the entry `LaTeX`?

**Comment by bqwer** [comment]
I've tried that too and also without success.

I can't access my work pc till tomorrow but will try to recreate this error at home in an hour or so, as my home setup almost identical to work setup.

**Comment by bqwer** [comment]
Can't reproduce bug with exact same user config (copied from first message) and same Sublime build and LaTeXTools build. I will try to completely reinstall Sublime at work tomorrow.

**Comment by r-stein** [comment]
Reinstalling Sublime Text or LaTeXTools won't reset your settings and hence not help you. It seems to open the wrong build, therefore you should just open the build selection menu `ctrl+shift+b` and select the entry **LaTeX - Traditional**. This will force it to use the correct builder and solve the problem.

**Comment by bqwer** [comment]
Thank you! I will try this tomorrow.

**Comment by ig0774** [comment]
To clarify a bit: that message comes from the `script` builder when it is run without any corresponding `script_command` setting (the `script_command` setting goes in the platform-specific block of the `builder_settings` block). You can get rid of the message simply by changing your `builder` setting to pretty much any other value.

**Comment by bqwer** [comment]
Invoking `ctrl+shift+b` and choosing **LaTeX-traditional** helped with this issue.
Earlier I mistook command and actually tried to choose "build system", not "build with".
Still don't know what caused this behavior.
Thank you very much for help!

**Comment by r-stein** [comment]
This behavior was most likely caused by pressing `ctrl+shift+b` and selecting **LaTeX - Script**. This overwrites the default/traditional builder and you run into that error.
