### ISSUE TITLE
Option to disable math preview for inlined math

### ISSUE THREAD

**Issue by fredrikekre** [SublimeText/LaTeXTools#944]
It would be nice with an option to disable math preview for inlined math. It looks quite awkward with previewed math inside a text section like this:

![screenshot from 2016-11-16 09-02-40](https://cloud.githubusercontent.com/assets/11698744/20339257/95646360-abdb-11e6-8495-cabd9709f360.png)

Would it be possible to have different settings for `\begin{equation} \end{equation}` blocks and inline math?

**Comment by xmlu** [comment]
In the latest version, you can disable the math preview by added `"preview_math_mode": "none"` in the user setting file.

**Comment by r-stein** [comment]
I am not sure, which would be the best way to do this w/o creating a setting for every special case.

**Comment by fredrikekre** [comment]
> In the latest version, you can disable the math preview fucntion by adding `"preview_math_mode": "none"` in the user setting file.

I know, maybe I wasn't clear enough, but I just want to be able to not preview math in text sections, i.e. the `x` and `f` in my example.

@r-stein Yea okay, how many special cases would that be? It could  default to the current setting, but the option to differentiate between math environments would be neat.

**Comment by r-stein** [comment]
> @r-stein Yea okay, how many special cases would that be? It could default to the current setting, but the option to differentiate between math environments would be neat.

I don't know =). Of user (as you) come up with very reasonable ideas I never thought about. For this problem my first two ideas would be

1. Option to disable the preview in single line equations. E.g. disabled in

    ``` tex
    $x^2$
    ```
    but enabled in 

    ``` tex
    $
    x^2
    $
    ```
2. (I tend to this) Option to set the math scope selectors. So one could only enable it in begin/end environments. Using this users could also "hack" the preview for other environments as long as they have a special scope (e.g. lists).

**Comment by ig0774** [comment]
@r-stein I agree that option 2 sounds like the best possible solution. Especially since, with #923, this could allow people to use a custom syntax to render equations in environments not currently recognised, etc.

**Comment by diego898** [comment]
This is related to #997
