### ISSUE TITLE
Comments do not work for .sty and .cls file?

### ISSUE THREAD

**Issue by xlong88** [SublimeText/LaTeXTools#949]

**Comment by r-stein** [comment]
Could you please be a little bit more specific of what you are trying to archive with comments. What are you doing and what would you expect?

**Comment by xlong88** [comment]
Sorry! My problem is I want to use "super + /" to comment the selected lines in a .sty or .cls file, but it does not work!

**Comment by r-stein** [comment]
Ah okay that does not seem to work on pure tex files. You can

- set the syntax to LaTeX
- install [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer), open the file `LaTeX/Comments.tmPreferences` and change the from `text.tex.latex` to `text.tex` [here](https://github.com/sublimehq/Packages/blob/v3123/LaTeX/Comments.tmPreferences#L7)

**Comment by xlong88** [comment]
It worked! Thanks so much!
