### ISSUE TITLE
Is it possible to add auto-completion for \begin ?

### ISSUE THREAD

**Issue by xlong88** [SublimeText/LaTeXTools#950]
Currently when I typed in "\begin{", it will automatically close the bracket. Is it possible to make 
the auto-completion for "\begin" work just like for "\cite" and "\ref". That is when you type in 
"\begin{" all possible environments (e.g., equation, align, figure, etc) pop up, waiting for user's selection.

**Comment by r-stein** [comment]
Yes, you can open the settings and set [`"env_auto_trigger"`](https://github.com/SublimeText/LaTeXTools/blob/v3.12.8/LaTeXTools.sublime-settings#L31) to `true`.

**Comment by xlong88** [comment]
Thanks!
