### ISSUE TITLE
Question about popup window

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#957]
Hi guys,  

I have a problem which has bothered me for quite a long time. I use ST3 + LatexTools to write papers. Whenever I type "{" for a math environment, a window will popup and FORCE me to choose some candidate items. But actually, I don't want to use any of them! So I have to press esc key to cancel this window.  Would you please tell me how to get rid of this popup window?  

Thank you so much!

PS: I asked this question on the ST3 official forum, but did not get a solution. So I have to ask for help here again.

![screenshot 2016-11-23 11 07 32](https://cloud.githubusercontent.com/assets/4194670/20567023/7ea98378-b197-11e6-82dc-229a341adbc9.png)

**Comment by ig0774** [comment]
Two options:

1. Disable the completions by setting `env_auto_trigger` to `false` in your LaTeXTools settings.
1. You can always exit the quickpanel by pressing escape, which won't select anything.

**Comment by shouwei** [comment]
@ig0774 
The first one is exactly the solution I am looking for.
Thank you so much!
