### ISSUE TITLE
Check system only looks for 32-bit Ghostscript, not 64-bit

### ISSUE THREAD

**Issue by fredrikpaues** [SublimeText/LaTeXTools#959]
At least on a Windows installation, the "Check system" command only checks for the 32-bit version of Ghostscript (`gswin32c.exe`) and not the 64-bit version (`gswin64c.exe`), even though the image and equation preview features works just fine with the 64-bit version.

Also, the Windows/MikTeX instructions in `README.markdown` should mention that the Ghostscript directory should be added to `$PATH`.

**Comment by r-stein** [comment]
Actually it should also check for the 64-Bit version #892, although this may not work perfect. Does it find the 32 Bit version and reports that or does it find nothing?

We are moving to only use ghostscript w/o ImageMagik #947, so this may not be necessary in the future.

**Comment by fredrikpaues** [comment]
The line I get is

    Program    Location                                          Status     Version
    -------    --------                                          ------     -------
    gswin32c   None                                              missing    unavailable

So, it finds nothing, not the 32-bit version (which I haven't installed) nor the 64-bit version (which I have installed).

**Comment by r-stein** [comment]
Have you added it to the system path?

**Comment by ig0774** [comment]
ImageMagick scans the registry even if Ghostscript isn't in the `PATH`, so strictly speaking, it's not necessary to add it to the `PATH`, as long as you installed a version of Ghostscript other than that bundled with your TeX distro. The current version of system check doesn't look anywhere other than the `PATH` and I believe just reports `gswin32c` if it can't find any version. With #947, the system check will move to be able to find Ghostscript either via the `PATH` or the registry.

**Comment by fredrikpaues** [comment]
Sounds like a good development. For what it's worth, I did add `gswin64c` to `PATH` but System check didn't find it anyway.

**Comment by FichteFoll** [comment]
When I added the 64-bit gs version to my PATH, System check reported it correctly. However, when neither is found, it just shows that `gswin32c` is missing.

I can also confirm that ImageMagick does its work even when gs is not on your path.

**Comment by fredrikpaues** [comment]
Strange. I probably did something wrong. The path I added to path was `C:\Program Files\gs\gs9.20\bin`. Maybe it should just have been `C:\Program Files\gs\gs9.20`. Sorry for taking everybody's time :-/

**Comment by ig0774** [comment]
This should be fixed in v3.12.9, which is more intelligent about finding Ghostscript on Windows.
