### ISSUE TITLE
Math Preview only works if after an empty line

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/LaTeXTools#960]
While going through https://github.com/SublimeText/LaTeXTools/issues/920#issuecomment-263133780 I noticed that the preview creates an empty phantom for me:

![2016-11-27_18-06-05_sublime_text](https://cloud.githubusercontent.com/assets/931051/20650058/e5d7ff32-b4cd-11e6-9e1d-8499071a42bd.png)

When I then added an empty line later (by accident) I found out that the preview works now:

![2016-11-27_18-10-00_sublime_text](https://cloud.githubusercontent.com/assets/931051/20650059/f0f8d9cc-b4cd-11e6-8b08-5ba9415a9f56.png)

But this obviously won't compile, since empty lines are invalid in align environments.

I also noticed that the first few pixel columns look extremely bad once I start adding more lines:

![2016-11-27_18-19-49_sublime_text](https://cloud.githubusercontent.com/assets/931051/20650068/1b7053a6-b4ce-11e6-925d-5d47d569d980.png)

I'm on Windows7 64-bit. System check:

```
Variable   Value
--------   -----
PATH       C:\Program Files\ImageMagick-7.0.3-Q16;<redacted>;C:\Perl\c\bin;C:\Perl\perl\site\bin;C:\Perl\perl\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;<redacted>;c:\Program Files\gs9.20\bin\
TEXINPUTS  C:\Program Files\Sublime Text 3;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\tex\latex;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\tex\latex;E:\Dropbox\localtexmf\tex\latex;C:\Program Files\MiKTeX 2.9\tex\latex;C:\ProgramData\MiKTeX\2.9\tex\latex;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\tex\generic;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\tex\generic;E:\Dropbox\localtexmf\tex\generic;C:\Program Files\MiKTeX 2.9\tex\generic;C:\ProgramData\MiKTeX\2.9\tex\generic;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\tex;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\tex;E:\Dropbox\localtexmf\tex;C:\Program Files\MiKTeX 2.9\tex;C:\ProgramData\MiKTeX\2.9\tex
BIBINPUTS  C:\Program Files\Sublime Text 3;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\bibtex\bib;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\bibtex\bib;E:\Dropbox\localtexmf\bibtex\bib;C:\Program Files\MiKTeX 2.9\bibtex\bib;C:\ProgramData\MiKTeX\2.9\bibtex\bib
BSTINPUTS  C:\Program Files\Sublime Text 3;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\bibtex\bst;C:\Users\Fichte\AppData\Roaming\MiKTeX\2.9\bibtex\csf;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\bibtex\bst;C:\Users\Fichte\AppData\Local\MiKTeX\2.9\bibtex\csf;E:\Dropbox\localtexmf\bibtex\bst;E:\Dropbox\localtexmf\bibtex\csf;C:\Program Files\MiKTeX 2.9\bibtex\bst;C:\Program Files\MiKTeX 2.9\bibtex\csf;C:\ProgramData\MiKTeX\2.9\bibtex\bst;C:\ProgramData\MiKTeX\2.9\bibtex\csf

Program    Location                                                  Status     Version
-------    --------                                                  ------     -------
sublime    .\sublime_text.exe                                        available  Sublime Text Build 3125
texify     C:\Program Files\MiKTeX 2.9\miktex\bin\x64\texify.exe     available  MiKTeX Compiler Driver 2.9.4203 (MiKTeX 2.9 64-bit)
pdflatex   C:\Program Files\MiKTeX 2.9\miktex\bin\x64\pdflatex.exe   available  MiKTeX-pdfTeX 2.9.4902 (1.40.14) (MiKTeX 2.9 64-bit)
xelatex    C:\Program Files\MiKTeX 2.9\miktex\bin\x64\xelatex.exe    available  MiKTeX-XeTeX 2.9.4987 (0.9999.3) (MiKTeX 2.9 64-bit)
lualatex   C:\Program Files\MiKTeX 2.9\miktex\bin\x64\lualatex.exe   available  This is LuaTeX, Version beta-0.76.0-2013062821  (MiKTeX 2.9 64-bit) (rev 4627)
biber      None                                                      missing    unavailable
bibtex     C:\Program Files\MiKTeX 2.9\miktex\bin\x64\bibtex.exe     available  MiKTeX-BibTeX 2.9.4360 (0.99d) (MiKTeX 2.9 64-bit)
bibtex8    C:\Program Files\MiKTeX 2.9\miktex\bin\x64\bibtex8.exe    available  This is 8-bit Big BibTeX version 0.99d
kpsewhich  C:\Program Files\MiKTeX 2.9\miktex\bin\x64\kpsewhich.exe  available  MiKTeX 2.9 64-bit
gswin64c   c:\Program Files\gs9.20\bin\gswin64c.exe                  available  GPL Ghostscript 9.20 (2016-09-26)
magick     C:\Program Files\ImageMagick-7.0.3-Q16\magick.exe         available  ImageMagick 7.0.3-8 Q16 x64 2016-11-24 http://www.imagemagick.org

Packages for equation preview  Status
-----------------------------  ------
standalone                     available
preview                        available
xcolor                         available
amsmath                        available
amssymb                        available
latexsym                       available
mathtools                      available

Builder      Status
-------      ------
traditional  available

Builder Setting  Value
---------------  -----
options          ['--shell-escape']

TeX Root
--------
<redacted>

LaTeX Engine
------------
pdflatex    

LaTeX Options
-------------
--shell-escape

Viewer   Status     Location
------   ------     --------
sumatra  available  c:\Program Files (x86)\SumatraPDF\SumatraPDF.exe

**Comment by r-stein** [comment]
I am wondering why the phantom is under the enumerate and not under the align. You did not tweak something to treat it as math environment?

![align](https://cloud.githubusercontent.com/assets/12573621/20650467/5eea8268-b4cf-11e6-91e1-c5093acf8dab.png)

For the empty phantom: It might be the case, that a previous image is still cached, where the build failed but created an empty pdf. I assumed, that the same tex file would create the same pdf, so the image name is the hash of the document content.
Can you try to open the cache
``` py
import os; sublime.active_window().run_command("open_dir", {"dir": os.path.join(sublime.cache_path(), "LaTeXTools", "preview_math")})
```
and delete all images and try it again.

**Comment by FichteFoll** [comment]
Removing the contents of the cache dir did not help, however I found out that I had some older copy of the LaTeX package in my packages folder. Removing (or rather renaming that) makes the phantom appear below the align environment and makes the problem go away too. When I restore just the old `LaTeX.sublime-syntax` file, the problem is back. I still have that syntax file, if you're interested in investigating further, but I consider this problem solved.

Thanks for the quick response (the note that the phantom should appear blow the align environment is what made me suspicious).

**Comment by r-stein** [comment]
Can you just check, that the old syntax file also spans the `meta.environment.math` over the `\end{align}` command?

I.e. old:
```tex
>|\begin{align}
   xx
   \end{align}|<
```

new:
```tex
  \begin{align}>|
   xx
   |<\end{align}
```

where >| is the start of the scope and |< the end of the scope.

**Comment by FichteFoll** [comment]
It does.

![2016-11-27_19-26-02_sublime_text](https://cloud.githubusercontent.com/assets/931051/20650788/5fa000c2-b4d7-11e6-9cb4-cf1917b5c550.png)


Here's the entire file: [LaTeX.zip](https://github.com/SublimeText/LaTeXTools/files/614891/LaTeX.zip)
