### ISSUE TITLE
The readme is too long

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/LaTeXTools#961]
There is way too much information in the readme without there being any sort of ToC. This makes it incredibly hard to locate the information you are looking for, assuming it even exists.

It should definitely either receive a ToC or more ideally be split up into several files/documents. Migrating the content to the [wiki](https://github.com/SublimeText/LaTeXTools/wiki) would also be a good idea, along with some good references to frequently used pages from the readme, like "installation" or "troubleshooting" or "general usage".

**Comment by r-stein** [comment]
Agreed @ig0774 has already created a PR #952 to improve that.

**Comment by ig0774** [comment]
Alright, the README has been greatly shortened and most of the documentation split up and made available at https://latextools.readthedocs.io. This probably isn't perfect yet, but hopefully its a basis on which we can develop better documentation.
