### ISSUE TITLE
References dont work

### ISSUE THREAD

**Issue by dnusman** [SublimeText/LaTeXTools#964]
Suddenly all my references, acronyms and citation dont work.
Get the following warnings:

Reference '....' on page x undefined on input line x

Did not move the folders or something

**Comment by r-stein** [comment]
The compilation does not work correctly? You could have switched the build engine, try to press ctrl+shift+b and select LaTeX.

**Comment by dnusman** [comment]
I was an idiot, sorry

**Comment by sublimator** [comment]
Lol. It happ3ns
