### ISSUE TITLE
Glossaries Jump To for /gls when entry defined as acronym

### ISSUE THREAD

**Issue by truemoid** [SublimeText/LaTeXTools#965]
When using the Glossaries package it is acceptable to define an acronym using the `\newacronym` command but to refer to that acronym using the gls-type commands (e.g., `\gls`, `\glspl`). As currently coded, `latex_glossary_completions.py` will only Jump To a `\newglossaryentry` or a `\longnewglossaryentry` if the command in the selection is a gls-type. It would be useful if the Jump To would go to a `\newacronym` entry if there is no `\newglossaryentry` corresponding to the current selection.

**Comment by r-stein** [comment]
This will be in the next release together with completions, which were suggested in #945.
