### ISSUE TITLE
LaTeXTools not sorted alphabetically in Preferences/Package Settings menu

### ISSUE THREAD

**Issue by fredrikpaues** [SublimeText/LaTeXTools#966]
To me at least, the LaTeXTools package settings submenu that appears under Preferences/Package Settings is not placed in its alphabetical order, that is under L. Instead it appears among packages starting with S and seems to be sorted as "SublimeLaTeXTools". Is this just me? If so, do you have any idea of why?

**Comment by r-stein** [comment]
Based on my experience the extracted packages are put behind the zipped packages in the settings. Since this package installs as an extracted one it will be put behind. There is nothing we can do about.
