### ISSUE TITLE
Change environment not working with optional argument

### ISSUE THREAD

**Issue by PaulPichaureau** [SublimeText/LaTeXTools#967]
Hi!

Unfortunately I have found a case where the change environment command cannot detect the current env :

\begin{test}[option = { some options }] 

\end{test}

The regex in change_environment.py detect for the beginning tag : "test}[option = { some options" (up to the last right brace).

**Comment by r-stein** [comment]
This will be fixed in the next release.

**Comment by PaulPichaureau** [comment]
Great! Thank you!
