### ISSUE TITLE
sync problem between tex and PDF

### ISSUE THREAD

**Issue by shouwei** [SublimeText/LaTeXTools#969]
Hi,

My environment is OSX 10.11.12, ST3 + LaTeXTools + Skim. I already configure PDF-TeX Sync support in Skim as follows:
Preset: Custom
Command: /Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl
Arguments: "%file":%line

But I found the sync function has an unsatisfied performance, most of the time, it's hard to jump to the precise position in PDF, only close to the perfect place. This problem becomes even worse when you have an external monitor. For example, the tex file opened on the laptop monitor and the pdf file located on the external monitor.

I don't know whether this issue is responsible for LatexTools, or we should ask help from Skim. 

Thanks a lot.

**Comment by r-stein** [comment]
The problem is in both directions tex -> pdf and pdf -> tex?

**Comment by shouwei** [comment]
@r-stein  I only know and use one direction, whose shortcut is command+l,j, from tex to pdf.

What is the other shortcut from pdf to tex? I can test it and let you know the result.

**Comment by ig0774** [comment]
With recent versions of Skim, it's best to use the Sublime preset, but that won't change syncing accuracy.

The accuracy of syncing to a location in a PDF is a function of how closely a line in the `tex` file can be matched to a position in the PDF file. The only thing Skim knows (and the only information LaTeXTools can provide it) is that you want to go to line x of the document.

The best way to improve accuracy of syncing is to break up long blocks of text into several lines. This could be accomplished manually, e.g. by adding a newline for each sentence, or somewhat automatically by using either Sublime's built-in hard wrap functionality or something like [this plugin](https://github.com/randy3k/AutoWrap) which tries to do hard wrapping as you type.

**Comment by ig0774** [comment]
To go from PDF -> ST, hold down `cmd+shift` and click on a point in the document.

**Comment by shouwei** [comment]
@ig0774 Actually, my wiring style is exactly as you said, each sentence in a single line. Surely, this is not an intention to get a more accurate syncing, but to locate some mathematical symbol errors easier.

The reverse direction, from PDF -> ST doesn't work for me, do I need to configure this manually or it is a default option of latextools?

**Comment by ig0774** [comment]
PDF -> ST is controlled by Skim. Your `command` setting looks like it's probably wrong. ST3 is usually "Sublime Text.app" not "Sublime Text 3.app", but as I said earlier, I'd just try the Sublime preset.

**Comment by ig0774** [comment]
If you're already writing a sentence per line, it's going to be hard to get things more accurate than they are.

**Comment by shouwei** [comment]
Thank you so much! It works and seems not bad.
I think we can close this ticket now.
