### ISSUE TITLE
cite and ref completions not working; ST3 B3126

### ISSUE THREAD

**Issue by ric-cioffi** [SublimeText/LaTeXTools#972]
Hi,
first post here but this is really bothering me.
Whenever I try using any of the cite or ref commands sublime won't let me open the curly braces and the autocomplete functionalities don't work. I always have to resort to unattractive workarounds.
This seems to be related to #615 . However, I tried all the solutions posted there and they do not work.
I believe it may be related to the latex_ref_cite_completions.py file which was apparently missing (I created a new one copying the code from the latextools repository but still does not work.)
If I open the console and try using, say, \cite{ this is what happens:

```
command: latex_ref_cite {"insert_char": "{"}
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'insert_char'
```

I really don't know what else to try. For the time being I have created shortcuts for the commands I use the most but besides being still a little inconvenient the dropdown list still does not work.

Thanks in advance,
Riccardo

**Comment by ig0774** [comment]
Most likely you have a keybinding in your local settings that's still referencing `latex_ref_cite`. In recent versions of LaTeXTools (starting from v.3.10.0), its been superceded by `latex_fill_all`. If you remove the keybinding, things should go back to working.

**Comment by ric-cioffi** [comment]
How can I check for it?
I have looked at my user settings but could not find anything that seemed to be referencing to `latex_ref_cite`. Maybe I just missed it though.
Thanks

**Comment by ig0774** [comment]
It's on the right-hand side of the file opened by selecting **Preferences > Key Bindings** (on a recent version of ST3) or the file opened by selecting **Preferences > Key Bindings – User** (on ST2 and earlier versions of ST3).

**Comment by ric-cioffi** [comment]
Great, this solved the problem, thanks.
