### ISSUE TITLE
Traditional Builder Problem

### ISSUE THREAD

**Issue by pravin-endeavour** [SublimeText/LaTeXTools#973]
Upon updating to the latest version of latextools, I get the following error when trying to build,

> Cannot find builder traditional. Check your LaTeXTools Preferences

Using XeLaTeX.

**Comment by r-stein** [comment]
Can you try to restart sublime text?

**Comment by marri5317** [comment]
I'm having the same issue. Probably a bug in the latest release?

**Comment by shouwei** [comment]
Me too! The problem will be solved after a restart.
