### ISSUE TITLE
Folder for output and auxiliary files

### ISSUE THREAD

**Issue by nilgoyyou** [SublimeText/LaTeXTools#98]
I want to change the output directory and the aux directory (for exemple -output-directory=C:/temp -aux-directory=C:/temp) in my project for two reasons : 
1) I want my work folder to be as clean as possible. Only tex files and figures.
2) I work on Google Drive (or Dropbox) and each time I build (I build often), all is updated on the server for no reason.

I tried to change it myself in the LaTeX.sublime-build file using « --tex-option=--output-directory="..." » but the build fails because your code suppose the output files are at the usual place,  which is normal.

So, is it possible to change the ouptput/aux folder? Sorry if this is already done but I couldn't find it. Thanks for your time.

**Comment by roeebar** [comment]
I just copy only the minimum (two) files to the main dir (the PDF and the synctex file).  It's not ideal but better than having all the aux files.

This is my project settings:
```
		"builder_settings": 
		{
			"osx": {
				"script_commands": [
					"latexmk -cd -pdf -synctex=1 -bibtex -interaction=nonstopmode -auxdir=./Output -outdir=./Output $file_name",
					"cp ./Output/$file_base_name.pdf ./",
					"ln -s -f ./Output/$file_base_name.synctex.gz ./"
				]
			}
		}
```

**Comment by ig0774** [comment]
We've added support for `--output-directory` and `--aux-directory` in v3.8.0. There's also a `copy_on_build` option which enables something not dissimilar to @roeebar's suggestion (if you want to keep the PDF file, and optionally, any other files.

**Comment by aadityadar** [comment]
Does this solution work when using MiKTeX on Windows?

**Comment by r-stein** [comment]
@aadityadar This suggestion is kinda outdated. You can change the builder to `basic`, which supports output and aux directory.

**Comment by aadityadar** [comment]
Ah okay, thanks!

**Comment by viditvia** [comment]
I changed the output directory. I use OSX. Sublime Text -> Preferences -> Package Settings -> LaTeXTools -> Settings-User -> Change output directory.
