### ISSUE TITLE
LaTeX-cwl cannot trigger \cite or \ref

### ISSUE THREAD

**Issue by J6rry** [SublimeText/LaTeXTools#981]
I work with LaTeX-cwl for autocompletation, it works well with latextools.
However, if I use latex-cwl to complete the \cite or \ref command, latextools won't trigger the cite command for selection. Same as the \ref command.
Does it can be fixed?
or am I too stupid to understand the Readme?

**Comment by ig0774** [comment]
Use the Fill All command (`C-l,C-f`) or the ref / cite specific version (`C-l,x`) with the cursor inside the brackets.

Unfortunately, AFAIK there's no straight-forward way to know when an autocomplete snippet has been inserted, so there's no way we could respond to it and launch the completion helper.

**Comment by J6rry** [comment]
Maybe that's the best solution, thanks.
