### ISSUE TITLE
Forward search broken in Okular 1.0

### ISSUE THREAD

**Issue by JackGin** [SublimeText/LaTeXTools#989]
Hi, I recently upgraded to Okular 1.0 (kde apps 16.12)  to find that the forward search does not work anymore when called as usual from LaTeXTools. The problem is discussed here: 
https://bugs.kde.org/show_bug.cgi?id=373855
It seems that a simple syntax fix like in Comment 4 could solve the problem.
Regards,
JG

**Comment by r-stein** [comment]
You can change the command [here](https://github.com/SublimeText/LaTeXTools/blob/master/viewers/okular_viewer.py#L42), but need to restart Sublime Text.
I am a little worried, that it might break backward compatibility.

**Comment by JackGin** [comment]
Can't check the backward compatibility right now, but for Okular 1.0 this indeed resolves the problem. Thank you!

**Comment by 5chdn** [comment]
I am having the same issue. Could you explain _how_ you fixed it? Did you prepend `file:` or did you remove everything after `#src:` and disable forward search functionality?

**Comment by r-stein** [comment]
It would be nice if one of you would create a PR to fix this.

**Comment by JackGin** [comment]
Sorry for late reply. Indeed, mere prepending file: solves the problem. This solution is backward compatible with Okular 0.26.1, according to my test on openSUSE Leap 42.2.
