### ISSUE TITLE
Previewing math that use symbols and commands from other packages

### ISSUE THREAD

**Issue by Poetastrophe** [SublimeText/LaTeXTools#993]
When I use the package "siunitx", I get some previews that are quite hard to read. 
<img width="251" alt="screen shot 2017-01-06 at 17 04 54" src="https://cloud.githubusercontent.com/assets/17691932/21723917/8ceca150-d432-11e6-9794-2331ee7b17d6.png">

How do I get the preview that makes use of the functions provided by 'siunitx'?

**Comment by r-stein** [comment]
You need to add the package to the used packages in the settings [here](https://github.com/SublimeText/LaTeXTools/blob/v3.12.11/LaTeXTools.sublime-settings#L125).
