### ISSUE TITLE
Unable to build on Fedora 25

### ISSUE THREAD

**Issue by darthoctopus** [SublimeText/LaTeXTools#994]
I'm not sure exactly what happened, because this was working two days ago, but when I try compiling anything now I get a COULD NOT COMPILE error, with the following output to the console:

```
<class '_latextools_traditionalBuilder.TraditionalBuilder'>
4
Welcome to thread Thread-6
['latexmk', '-cd', '-f', '-xelatex', '-interaction=nonstopmode', '-synctex=1', 'yaleprop.tex']
Running "latexmk -cd -f -xelatex -interaction=nonstopmode -synctex=1 yaleprop.tex"
Could not import subprocess32 module, falling back to subprocess module
Traceback (most recent call last):
  File "/home/joel/.config/sublime-text-3/Packages/LaTeXTools/makePDF.py", line 316, in run
    self.caller.builder.set_output(out.decode(self.caller.encoding,"ignore"))
AttributeError: 'NoneType' object has no attribute 'decode'
<class '_latextools_basicBuilder.BasicBuilder'>
```

**Comment by shoetten** [comment]
Same for me on OS X 10.11.6 El Capitan. I think the bug got introduced in the latest version 3.12.12, because everything was working fine before the update.

**Comment by r-stein** [comment]
Try to restart Sublime Text.

**Comment by shateiely** [comment]
Same for me on windows 10 X64 and Sublime Text Build 3126. I think the bug got introduced in the latest version 3.12.12, because everything was working fine before the update.

**Comment by r-stein** [comment]
Sorry, new version is out and should fix this.
